### ISSUE TITLE
sql-queries: 23.2 release checklist

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#101875]
This issue captures a series of tests and steps that we need to run when 23.2 is getting close to being finalized.
 - [x] check and update private opt tests repository
   - Done: https://github.com/cockroachlabs/opt-private-tests/pull/32
 - [x] check regressions in microbenchmarks
 - [x] run all tests with `fast_int_set_small` tag: `./dev test -- --define gotags=bazel,gss,fast_int_set_small`
 - [x] run all tests with `fast_int_set_large` tag: `./dev test -- --define gotags=bazel,gss,fast_int_set_large`
 - [x] check TODOs in opt code (especially those added since the last release)
 - [x] clone an instance of this issue for the next release
 - [x] check the SQL Queries "Active" and "Release XX.X" buckets for issues that we'd really like to get into the release
 - [x] upgrade https://github.com/sqlancer/sqlancer to the latest version of CRDB
   - https://github.com/sqlancer/sqlancer/pull/902

Jira issue: CRDB-27169

**Comment by rharding6373** [comment]
Generated a spreadsheet of all TODOS in pkg/sql using `./scripts/todo_diff.sh v23.1.1 release-23.2 pkg/sql`, and manually found owners using blame for TODOs without names.

https://docs.google.com/spreadsheets/d/1DzC47lq_L4bcNozv6x4rnGYoOVHYioFnkxevZJaXYEo/edit#gid=0

**Comment by mgartner** [comment]
> and manually found owners using blame for TODOs without names

Yikes, that sound tedious. Thanks! Is this a reason to prefer names in TODOs instead of issue numbers?

**Comment by rharding6373** [comment]
There were ~10 TODOs without names or issue numbers which I manually added names for in the spreadsheet. Sorry for the confusion, it wasn't that tedious. Issue numbers are definitely preferable to names or nothing at all!

**Comment by mgartner** [comment]
The SQLancer PR has not yet been merged, but it found no major issues, so I think it's safe to check-off and close the issue.
