### ISSUE TITLE
kv: load-based splitter permits splits between SQL rows backport tracker

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#104353]
This issue tracks backporting the fix for https://github.com/cockroachdb/cockroach/issues/103483 to earlier CRDB versions.

- [x] Master https://github.com/cockroachdb/cockroach/pull/103690
- [x] 23.1 https://github.com/cockroachdb/cockroach/pull/103876
- [x] 22.2 https://github.com/cockroachdb/cockroach/pull/104563

Jira issue: CRDB-28487

**Comment by kvoli** [comment]
23.1 merged above.

I took a quick stab at resolving the conflicts to 22.2 - there were a lot.

**Comment by kvoli** [comment]
Tried again at 22.2 backport - not success on resolving conflicts. I'll set aside some time to do this later today.

**Comment by kvoli** [comment]
23.1 merged.
22.2 opened https://github.com/cockroachdb/cockroach/pull/104563

**Comment by kvoli** [comment]
https://github.com/cockroachdb/cockroach/pull/104563 merged. Closing as complete.
