### ISSUE TITLE
pglogical: SQL "frontend" related changes meta issue

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#105130]
* [ ] Implement the PG [streaming replication protocol](https://www.postgresql.org/docs/current/protocol-replication.html)
  * [x] Implement the parser #104938
  * [ ] Allow `replication={database,0,1,on,off}` as an argument into the connection string
  * [ ] Disable extended protocol when `replication` mode enabled
  * [ ] Implement & use the streaming replication protocol commands
      * [ ] IDENTIFY_SYSTEM
      * [ ] START_REPLICATION
      * [ ] CREATE_REPLICATION_SLOT (not-AWS DMS blocking)
      * [ ] READ_REPLICATION_SLOT (not-AWS DMS blocking)
      * [ ] DROP_REPLICATION_SLOT (not-AWS DMS blocking)
* [ ] Add the system `replication_slots` table + migration
* [ ] Implement the pg_catalog metadata + functions
   * [ ] pg_replication_slots
   * [ ] pg_create_logical_replication_slot
   * [ ] pg_drop_replication_slot
   * [ ] pg_logical_slot_get_changes
   * [ ] pg_logical_slot_peek_changes
   * [ ] pg_logical_slot_get_binary_changes	
   * [ ] pg_logical_slot_peek_binary_changes
   * [ ] pg_get_replication_slots
   * [ ] pg_replication_slot_advance
* [ ] Add requisite version gating
* [ ] Add `max_replication_slots`, `max_wal_senders`, `wal_level`, `wal_sender_timeout` session variables

----

x-ref #93404 for prototype PR
Epic: https://cockroachlabs.atlassian.net/browse/CRDB-26486

**Comment by shermanCRL** [comment]
We might consider contributing to or forking https://github.com/jackc/pglogrepl for things that are “only about the protocol”, and are not CRDB-specific.
