### ISSUE TITLE
plpgsql: tracking issue for 23.2 PLpgSQL features

### ISSUE THREAD

**Issue by DrewKimball** [cockroachdb/cockroach#105254]
This is a tracking issue for PLpgSQL features that are planned for 23.2.

- [x] Basic support for `IF/ELSE`, `LOOP`, variable declarations, variable assignments, parameters, `EXIT`, `CONTINUE`, and `RETURN` #104755
- [x] Support `CONSTANT` variable declarations #105241
- [ ] Support `FOR` and `WHILE` loop statements #105246
- [x] Support for raising errors and messages #105251
- [x] Support `SELECT INTO` syntax #105252
- [x] Support exception blocks #105253
- [ ] Support PLpgSQL in randomized testing #106368
- [x] Implement tail-call optimization for nested PLpgSQL sub-routines
- [x] Support for cursors #109709

Epic: CRDB-799

Jira issue: CRDB-28943

**Comment by DrewKimball** [comment]
Note: FOR loops and OTHERS branch were dropped for 23.2.
