### ISSUE TITLE
Product Roadmap Q4 2016

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#10528]
**Note: This is a working copy of our product roadmap featured here: https://github.com/cockroachdb/cockroach/wiki

CockroachDB is currently in beta. We track issues using 3 milestones:

- 1.0 is for work to be completed by the 1.0 release.
- Later is for work to be completed after the 1.0 release.
- Issues without a milestone have either not been scheduled or are cleanup work that can be done whenever someone finds the time or inclination.

**2016 Roadmap**

**Goals:**
- Developer adoption
- Ready for production deployment

**Themes (near term):**
- Core DB
    - Scalability
    - Stability
    - Performance
- Varied cluster deployments & tools
- Fully-featured RDBMS
- Functional UI for cluster management

**Q4 2016 Roadmap Details**

**Core & Stability**
- [ ] Stability
    - [ ] Advanced chaos testing
    - [ ] Jepsen
- [ ] Test clusters with increasingly large range counts (1M ranges, ~37TB)
- [x] Linear scaling (up to 64 nodes, 3, 10 node clusters with p99 latency with 2.5x p50)
- [ ] Cross datacenter deployments (intra-region, inter-region, inter-continental) https://github.com/cockroachdb/cockroach/issues/10275
- [ ] Functionality
    - [ ] Infrastructure for data migrations
    - [x] Epoch based range leases https://github.com/cockroachdb/cockroach/pull/10305
    - [x] Rebalancing of leaseholders https://github.com/cockroachdb/cockroach/pull/10464
    - [ ] Raft pre-vote RPC
    - [x] Parallelized dist sender
    - [ ] Quiescence improvements (in presence of down replicas) https://github.com/cockroachdb/cockroach/issues/9446
    - [ ] Zone config expressiveness https://github.com/cockroachdb/cockroach/issues/4868, https://github.com/cockroachdb/cockroach/issues/10692
    - [x] Measure clock skew faster than max clock-offset (high/low max-offset)
    - [ ] Queues for high contention
    - [ ] Leader lease optimizations

**SQL Functionality**
- [ ] Support top 5 ORMs https://github.com/cockroachdb/cockroach/issues/10079
- [ ] Improve performance and isolation for online schema changes https://github.com/cockroachdb/cockroach/issues/9149
- [x] Online upgrades https://github.com/cockroachdb/cockroach/pull/11658
- [x] Views https://github.com/cockroachdb/cockroach/issues/2971
- [ ] Parallelized driver https://github.com/cockroachdb/cockroach/issues/10057
- [ ] Collations https://github.com/cockroachdb/cockroach/issues/2473
- [ ] Fuzz testing
- [ ] Enterprise backup / restore
- [ ] Bulk ingest
- [x] Password-based PGWire https://github.com/cockroachdb/cockroach/issues/10863
- [ ] Robustness
    - [x] Minimize resource usage blowups
    - [ ] Draining on node shutdown https://github.com/cockroachdb/cockroach/pull/10765
- [ ] Distributed SQL
    - [ ] Read-only queries (filtering, sorting, aggregations, joins)
    - [ ] Push-down filtering to ranges

**UI**
- [ ] UI/UX revamp (explore a new information architecture, reskin UI)
- [x] Improve graphing facility (readability, performance, time scales, UX)
- [x] Snappy performance
- [x] Auto-pruning of time series data

**Comment by dianasaur323** [comment]
Closing this issue in favor of releasing a new issue with items needed for 1.0.
