### ISSUE TITLE
sql: provide alternative syntax for the UX surface of cluster virtualization operations

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#106068]
We want to introduce the term "virtual cluster" or "cluster virtualization" in those features that are exposed to end-users.
This part of the change would need to be backported to 23.1.

for a smooth transition, this change should *alias* the syntax and merely hide the variant that uses "tenant" in the name.

The following surface should be adapted:

- [x] `BACKUP TENANT` -> `BACKUP VIRTUAL CLUSTER` #106110
- [x] `BACKUP/RESTORE ... include_all_secondary_tenants` -> `include_all_virtual_clusters` #106110
- [x] `CREATE TENANT` -> `CREATE VIRTUAL CLUSTER` #106110
- [x] `DROP TENANT` - ditto #106110
- [x] `SHOW TENANT(s)` - ditto #106110
- [x] `ALTER TENANT` (all variants) - ditto #106110
- [x] `cockroach debug zip` - generated `tenants` sub-directory #106117
- [x] config profile names `multitenant+XXX` #106116
- [x] session var `disable_drop_tenant` #106121
- [x] DB Console drop-down title "tenant" #106118
- [x] HTTP parameter `tenant_name` #106122
- [ ] `tenant=` in status vars
- [ ] (maybe,unsure) HTTP cookie name "tenant" and "X-Cockroach-Tenant"
- [ ] cluster settings:
  - `sql.create_tenant.default_template` -> `sql.create_virtual_cluster.default_template`
  - `server.controller.default_tenant` -> `server.controller.default_virtual_cluster`
  - `server.controller.default_tenant.check_service.enabled` -> ditto
  - `server.secondary_tenants.authorization.mode`
  - `server.secondary_tenants.redact_trace.enabled`
  - `spanconfig.tenant_coalesce_adjacent.enabled`
  - `spanconfig.tenant_limit`
  - `sql.multi_region.allow_abstractions_for_secondary_tenants.enabled`
  - `sql.scatter.allow_for_secondary_tenant.enabled`
  - `sql.split_at.allow_for_secondary_tenant.enabled`
  - `sql.zone_configs.allow_for_secondary_tenant.enabled`
  - other settings on a best-effort basis
- [ ] `cockroach demo --multitenant=XXX`

Epic: CRDB-29380

Jira issue: CRDB-29381

**Comment by knz** [comment]
backport list:

- [x]  #106229
- [ ] #106110  #106116  #106121
- [ ] #106117
- [ ] rest tbd
