### ISSUE TITLE
sql: ensure that common implicit cross joins don't explode

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10633]
Found by @jordanlewis while investigating Hibernate:
https://gist.github.com/jordanlewis/850fb3aac4ba79541b0e47f580f68723

This performs a cross-join between:
```
         pg_catalog.pg_namespace pkn, 
         pg_catalog.pg_class pkc, 
         pg_catalog.pg_attribute pka, 
         pg_catalog.pg_namespace fkn, 
         pg_catalog.pg_class fkc, 
         pg_catalog.pg_attribute fka, 
         pg_catalog.pg_constraint con, 
         pg_catalog.generate_series(1, 32) pos(n), 
         pg_catalog.pg_depend dep, 
         pg_catalog.pg_class pkic 
```

Even assuming conservative numbers for each of these tables (5 namespaces, 10 classes, 10 attributes, 10 constraints, 10 dependencies) the cross product is 5^2 x 10^3 x 10^2 x 10 x 32 x 10, in other words 8 million rows, each of them quite long, *that must be computed loaded into memory even before evaluating the remainder of the query.*  Then even if it might fit in memory it's going to take forever.

So in order to support this query we must start doing some serious filter optimization. I have split this up in sub-tasks:

- [x] extend USING for arbitrary equalities #10630 
- [x] optimize JOIN .. ON that uses only equalities #10631 
- [ ] add a new equality predicate to an existing join #11192
- [ ] push simple filters down #10632 and  #11723
