### ISSUE TITLE
Make SHOW statements timezone aware 

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#107644]
**Is your feature request related to a problem? Please describe.**
Several SHOW statements (`SHOW JOBS`, `SHOW BACKUPS`, `SHOW STATISTICS`, `SHOW SESSIONS`, `SHOW QUERIES`) output timestamp fields, but those fields are not time zone aware today. 

If you were to set a time zone for your session in the database, like  ```ALTER ROLE max SET timezone = 'America/New_York';```  certain SHOW statements like `SHOW JOBS` will still continue to show timestamp fields as UTC, not EST/EDT. 

The reason for this is that some of the tables underlying the SHOW statements use TIMESTAMP, not TIMESTAMPTZ.  

**Describe the solution you'd like**
Note that statements like `SHOW SCHEDULES` do utilize TIMESTAMPTZ so timestamp fields will show up in EST/EDT (or whatever timezone the database is set to) instead of UTC, which is the desired behavior. 

That's the desired behavior for the rest of the SHOW statements that output timestamp fields:
- [x] SHOW JOBS https://github.com/cockroachdb/cockroach/issues/107647
- [x] SHOW BACKUPS https://github.com/cockroachdb/cockroach/issues/107648
- [x] SHOW STATISTICS https://github.com/cockroachdb/cockroach/issues/107651
- [x] SHOW SESSIONS https://github.com/cockroachdb/cockroach/issues/107649
- [x] SHOW QUERIES https://github.com/cockroachdb/cockroach/issues/107650

As long as the timezone is set to a particular value (e.g. ‘America/New_York’) in a session for a role/user, that role/user will see that time zone for timestamp fields. 

Jira issue: CRDB-30142

Epic CRDB-24406

**Comment by thtruo** [comment]
cc @dikshant @livlobo for awareness

**Comment by thtruo** [comment]
Hi @michae2 - I think the risk is mitigated by:
* the fact that the customer would have to explicitly set the timezone in their session in order to change the output, and that once they do that
* we should add language to docs flagging impact to any application relying the timestamp output of those commands when the user sets their session timezone (tracking DOC ticket https://cockroachlabs.atlassian.net/browse/DOC-8046)

Let me know where you think this might fall short and what else we should call out

**Comment by michae2** [comment]
Ah, never mind, I didn't realize that `SHOW` statements are explicitly called out as unstable in our [docs](https://www.cockroachlabs.com/docs/stable/api-support-policy#apis). Never mind, ignore me.

**Comment by dt** [comment]
> the fact that the customer would have to explicitly set the timezone in their session in order to change the output, and that once they do that

Is this true? Doesn't the output go from `2023-08-07 16:03:06.908441` to `2023-08-07 16:03:06.908441 +0000` or something when you switch to TZ, to indicate the zero offset?

**Comment by michae2** [comment]
Looks like all tasks are done!
