### ISSUE TITLE
roachtest: port remaining `mixed-version` roachtests to the new framework

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#110528]
The original roachtest mixed-version framework [1] was born sometime in `2017`. While it has gone through many iterations and improvements since then, its limitations have inspired a new, declarative approach [2], which attempts to _increase_ coverage of the mixed-version states while _reducing_ boilerplate, thereby allowing the author to focus on the salient bits, namely workloads and invariants. The new mixed-version framework has already proven its worth by finding 12+ new bugs, having ported only two pre-existing roachtests,

- [`acceptance/version-upgrade`](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/versionupgrade.go#L102)
- [`backup-restore/mixed-version`](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/mixed_version_backup.go#L2145)

Most recently, an _initial_ port of [`cdc/mixed-versions`](https://github.com/cockroachdb/cockroach/pull/108802) was merged. This leaves the following roachtests which remain to be ported,

- [x] [`import/mixed-versions`](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/import.go#L366) (#113546)
- [x] [`decommission/mixed-versions`](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/mixed_version_decommission.go#L34) (#131252)
- [x] [`change-replicas/mixed-version`](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/mixed_version_change_replicas.go#L51) (#113222)
- [x] [`schemachange/mixed-versions`](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L83) (#113890)
- [x] [`schemachange/secondary-index-multi-version`](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/secondary_indexes.go#L27) (#113696)
- [x] [`systemschema/validate-after-version-upgrade`](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go#L37) (#113643)
- [x] [`declarative_schema_changer/job-compatibility-mixed-version-V222-V231`](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go#L134)(#114043)
- [x] [`tpcc/mixed-headroom/n5cpu16`](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/tpcc.go#L410) (#113706)
- [x] [`version/mixed/nodes=%d`](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/version.go#L33) (#113323)
- [x] [`follower-reads/mixed-version/single-region`](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/follower_reads.go#L103) (#115317)
- [x] [`rebalance/by-load/leases/mixed-version`](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/rebalance_load.go#L232) (#115559)
- [x] [`rebalance/by-load/replicas/mixed-version`](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/rebalance_load.go#L267) (#115559)
- [x] [`generate-fixtures`](https://github.com/cockroachdb/cockroach/blob/72ad9e17825ba5adf3160c4ddfdbcebc690846ba/pkg/cmd/roachtest/tests/fixtures.go#L25) (#131467)

In virtue of the new framework, even a mechanical approach to porting the above is likely to yield a higher coverage of the mixed-version states. However, we ask that the authors take a deliberate approach by studying the limitations of the current implementation and correcting them, when feasible, with the help of the new framework. 

In addition to the above, TestEng is planning to add a _long-running_ workload utilizing `sqlancer` in the near term. (Unlike existing workloads, `sqlancer` is more antagonistic and randomized, albeit synthetic.) Mid-to-longer term, automated failure injection and other features will be added to the framework, thereby increasing overall coverage of error-handling (e.g., verifying that migration steps are indeed idempotent).

[1] https://github.com/cockroachdb/cockroach/pull/18057
[2] https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/roachtestutil/mixedversion/README.md

Jira issue: CRDB-31478

**Comment by srosenberg** [comment]
Linking follow-up CDC issue to add more randomization: https://github.com/cockroachdb/cockroach/issues/108943

**Comment by nvanbenschoten** [comment]
> TestEng is planning to add a long-running workload utilizing sqlancer in the near term. (Unlike existing workloads, sqlancer is more antagonistic and randomized, albeit synthetic.)

Does sqlancer run transactions or mutations? If not, it will be limited in the coverage that it provides, especially of KV, Replication, and Storage. We would benefit from some workload that also performs mutations, so we should consider also adding a long-running workload like TPC-C into the mix.

**Comment by srosenberg** [comment]
> Does sqlancer run transactions or mutations? If not, it will be limited in the coverage that it provides, especially of KV, Replication, and Storage. We would benefit from some workload that also performs mutations, so we should consider also adding a long-running workload like TPC-C into the mix.

Its transactions are fairly basic; it does run mutations [1]. However, it's relatively easy to extend it. E.g., I'd like to add more concurrent (schema) mutations.

> we should consider also adding a long-running workload like TPC-C into the mix

Agreed, we already have it in the mix.

[1] https://github.com/sqlancer/sqlancer/blob/cddff69308e9bcdbf0ed9abc5b77b57590431ff7/src/sqlancer/cockroachdb/CockroachDBProvider.java#L52

**Comment by srosenberg** [comment]
Last remaining test to be ported is [decommission/mixed-versions](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/mixed_version_decommission.go#L34), thus moving the parent issue to KV.

**Comment by renatolabs** [comment]
> Last remaining test to be ported is [decommission/mixed-versions](https://github.com/cockroachdb/cockroach/blob/ac3c2bec120c79d595a8d335f473b8fe2487e794/pkg/cmd/roachtest/tests/mixed_version_decommission.go#L34), thus moving the parent issue to KV.

We ported `decommissions/mixed-versions` in #131252. I'll keep this issue open until we remove the `newUpgradeTest` dependency from the automation that generates fixtures each release (`generate-fixtures`), then we'll be able to delete the old upgrade API and that would be a nice way to close this issue.
