### ISSUE TITLE
tracking issue for removal of deprecated 23.1 version gates

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#112501]
#112449 renamed all gates that need removal to start with `TODO_Delete`.

Below is a list of packages that contain a reference to these gates. Please check off when they are cleaned up.

- [ ] pkg/ccl/backupccl
- [ ] pkg/ccl/changefeedccl
- [ ] pkg/cli
- [ ] pkg/clusterversion
- [ ] pkg/jobs
- [ ] pkg/kv
- [ ] pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer
- [ ] pkg/server
- [ ] pkg/server/authserver
- [ ] pkg/server/settingswatcher
- [x] pkg/sql (#114307)
- [X] pkg/storage (#112269)
- [ ] pkg/upgrade/upgrademanager
- [ ] pkg/upgrade/upgrades
- [ ] pkg/workload/schemachange

Jira issue: CRDB-32451
