### ISSUE TITLE
clusterversion: tracking issue for improvements and cleanup

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#112629]
- [x] Use an array for the versions table (`[numKeys]roachpb.Version`) for cleaner definitions (and fast lookup)
- [x] Deprecate `ByKey()` in favor of a `Key.Version()` method (to avoid the annoying `clusterversion.ByKey(clusterversion.VFoo)`
- [x] Separate the `DevOffset` code to a different file, improve documentation
- [x] Rename `BinaryVersion` to `Latest`, `MinBinarySupportedVersion` to `MinSupported`
- [x] In `VersionHandle` rename `binaryVersion` to `maxVersion` and `binaryMinSupportedVersion` to `minVersion`
- [x] Remove `TestingBinaryVersion` etc
- [ ] ~Rework scheme for intermediary versions: https://github.com/cockroachdb/cockroach/issues/112708~ [too disruptive]
- [x] Make tests around upgrade that check an expected version only look at the release series part (so they don't need fixing when we mint a final version)
- [x] Adjust cockroach cli initialization use the previous release instead of `MinSupported` unless skipping is enabled via env var; update upgrade roachtests
- [ ] ~Add a special nightly build that runs unit tests with `MinSupported` bumped up (using a build tag)~ [not worth triaging test failures from flaky tests]
- [x] Make a command that can dump new "initial values" files (for `pkg/sql/catalog/bootstrap/data/`)
- [x] Avoid unmarshaling in the `IsActive` hot path (#113385)

And, after a good chunk of these are done:
- [ ] Update/rewrite the release runbooks as an `md` file in the repo.

Jira issue: CRDB-32524

**Comment by pavelkalinnikov** [comment]
Would #113385 be in scope for this work?

**Comment by RaduBerinde** [comment]
Sure, I added it to the list.
