### ISSUE TITLE
sql-queries: 24.1 release checklist

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#113089]
This issue captures a series of tests and steps that we need to run when 24.1 is getting close to being finalized.

 - [x] check and update private opt tests repository
 - [x] check regressions in microbenchmarks
 - [x] run all tests with `fast_int_set_small` tag: `./dev test -- --define gotags=bazel,gss,fast_int_set_small`
 - [x] run all tests with `fast_int_set_large` tag: `./dev test -- --define gotags=bazel,gss,fast_int_set_large`
 - [x] clone an instance of this issue for the next release
 - [x] check the SQL Queries "Active" and "Release XX.X" buckets for issues that we'd really like to get into the release
 - [x] upgrade https://github.com/sqlancer/sqlancer to the latest version of CRDB
   * https://github.com/sqlancer/sqlancer/pull/947

Jira issue: CRDB-32744
