### ISSUE TITLE
cdc: meta issue for 23.2 benchmark regressions

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#113678]
Below is a list of benchmark regressions we should triage.

Timing regressions:

- [ ] `pkg/ccl/changefeedccl→Encoders`
- [ ] `pkg/ccl/changefeedccl→EncodeCollatedString-32`
- [ ] `pkg/ccl/changefeedccl→EncodeGeometry-32`
- [ ] `pkg/ccl/changefeedccl→EncodeVarbit-32`
- [ ] `pkg/ccl/changefeedccl→EncodeBool-32`
- [ ] `pkg/ccl/changefeedccl→EncodeBytes-32`
- [ ] `pkg/ccl/changefeedccl→EncodeGeography-32`
- [ ] `pkg/ccl/changefeedccl→EncodeINet-32`
- [ ] `pkg/ccl/changefeedccl→EncodeUUID-32`
- [ ] `pkg/ccl/changefeedccl→EncodeBox2D-32`
- [ ] `pkg/ccl/changefeedccl→EncodeBitLarge-32`

Allocation regressions (allocs/op):

- [ ] `pkg/ccl/changefeedccl→EncodeBytes-32`
- [ ] `pkg/ccl/changefeedccl→Encoders`

Allocation regressions (alloc/op):

- [ ] `pkg/ccl/changefeedccl→Encoders`
- [ ] `pkg/ccl/changefeedccl→EncodeVarbit-32`
- [ ] `pkg/ccl/changefeedccl→EncodeBytes-32`

Data comes from [this spreadsheet](https://docs.google.com/spreadsheets/d/1KgE67kvpzDZmEnJvYlUvSkhMiY5MFcSeajzb-wU3Iuc/edit#gid=7). I did some basic grouping to collapse down the variants.

Jira issue: CRDB-33106

**Comment by nicktrav** [comment]
I did some bisecting, and I've narrowed some of the regressions down to d1d75c451c1131cac632b786580bc5996e6bd0ec.

I'm running the following:

```
$ ./dev bench ./pkg/ccl/changefeedccl --filter 'BenchmarkEncoders/csv/encodeValue/1cols/envelope=row/diff=false' --count 10 --verbose --show-logs --ignore-cache
```

Before the commit:

```
nickt@gceworker-nickt:~/go/src/github.com/cockroachdb/cockroach$ benchstat master 23.1
name                                                       old time/op    new time/op    delta
Encoders/csv/encodeValue/1cols/envelope=row/diff=false-24    2.69µs ± 1%    2.66µs ± 1%  -1.13%  (p=0.001 n=10+10)

name                                                       old alloc/op   new alloc/op   delta
Encoders/csv/encodeValue/1cols/envelope=row/diff=false-24      212B ± 0%      212B ± 0%    ~     (all equal)

name                                                       old allocs/op  new allocs/op  delta
Encoders/csv/encodeValue/1cols/envelope=row/diff=false-24      7.00 ± 0%      7.00 ± 0%    ~     (all equal)
```

At that commit:

```
nickt@gceworker-nickt:~/go/src/github.com/cockroachdb/cockroach$ benchstat master 23.1
name                                                       old time/op    new time/op    delta
Encoders/csv/encodeValue/1cols/envelope=row/diff=false-24    4.42µs ± 1%    2.66µs ± 1%  -39.89%  (p=0.000 n=10+10)

name                                                       old alloc/op   new alloc/op   delta
Encoders/csv/encodeValue/1cols/envelope=row/diff=false-24      485B ± 0%      212B ± 0%  -56.29%  (p=0.000 n=10+10)

name                                                       old allocs/op  new allocs/op  delta
Encoders/csv/encodeValue/1cols/envelope=row/diff=false-24      21.0 ± 0%       7.0 ± 0%  -66.67%  (p=0.000 n=10+10)
```

@miretskiy - does this ring any bells to you, in terms of slowing things down in the encoder benchmarks?
