### ISSUE TITLE
plpgsql: tracking issue for unimplemented statements

### ISSUE THREAD

**Issue by DrewKimball** [cockroachdb/cockroach#117744]
This issue tracks adding support for unimplemented PL/pgSQL statements. 
NOTE: limitations for partially implemented statements are not included, and are tracked elsewhere.

**Basic statements**
- [ ] [PERFORM](https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-GENERAL-SQL) #108416
- [ ] [EXECUTE](https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-GENERAL-SQL) #115300
- [ ] [GET DIAGNOSTICS](https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-GENERAL-SQL) #117410
- [ ] [NULL](https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-GENERAL-SQL)

**Control Structures**
- [ ] [RETURN NEXT/QUERY](https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-STATEMENTS-RETURNING-RETURN-NEXT)
- [ ] [CALL](https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-STATEMENTS-CALLING-PROCEDURE)
- [ ] [CASE](https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-CONDITIONALS-SIMPLE-CASE)
- [ ] [FOR (integer variant)](https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-INTEGER-FOR) #105246
- [ ] [FOR (query variant)](https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-RECORDS-ITERATING)
- [ ] [FOREACH](https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-FOREACH-ARRAY)
- [ ] [DECLARE/BEGIN (nested)](https://www.postgresql.org/docs/current/plpgsql-structure.html#PLPGSQL-STRUCTURE) #114775

**Cursors**
- [ ] [OPEN <cursor> FOR EXECUTE](https://www.postgresql.org/docs/current/plpgsql-cursors.html#PLPGSQL-CURSOR-OPENING-OPEN-FOR-EXECUTE)
- [ ] [FOR IN](https://www.postgresql.org/docs/current/plpgsql-cursors.html#PLPGSQL-CURSOR-OPENING-OPEN-FOR-EXECUTE) #115296

**Transaction Management**
- [ ] [COMMIT and ROLLBACK](https://www.postgresql.org/docs/current/plpgsql-transactions.html#PLPGSQL-TRANSACTIONS) #115294

**Errors and Messages**
- [ ] [ASSERT](https://www.postgresql.org/docs/current/plpgsql-errors-and-messages.html#PLPGSQL-STATEMENTS-ASSERT)
