### ISSUE TITLE
sql: support Sequelize ORM

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#12292]
These are needed to support basic CRUD operations for Sequelize ORM for Node.js:
- [x] #9990: fully support Postgres OIDs
- [x] #12109: support `client_min_messages` variable
- [x] #12110: support `SET TIMEZONE INTERVAL` syntax
- [x] #12113: support `STANDARD_CONFORMING_STRINGS`
- [x] #12115: support `array_agg`
- [x] #12117: support `pg_get_indexdef`
- [x] #12122: support `SERVER_VERSION`
- [x] #12188: can't use ARRAY-type columns in `GROUP BY`
- [x] #12207: pgwire behavior for string arrays is partially incorrect
- [x] #13434 pgwire behavior for vector types is partially incorrect
- [x] #12971: implement `pg_enum`
- [x] #13645: lowercase column name for `SHOW SERVER_VERSION`

`upsert` requires a bit more:
- [x] #12120: sequelize needs stored procedures
- [x] #6637: support `RETURNING` for `UPSERT` and `INSERT INTO... ON CONFLICT` (no longer needed because of Sequelize dialect)

This list should be updated as we progress in our support for Sequelize.

cc @knz @nvanbenschoten @jordanlewis

**Comment by pierpaolobettoni** [comment]
Is there an ETA?

**Comment by cuongdo** [comment]
We're aiming to have basic support for Sequelize in Q1 2017.

**Comment by cuongdo** [comment]
Released. Docs are here: https://www.cockroachlabs.com/docs/build-a-nodejs-app-with-cockroachdb-sequelize.html

**Comment by edwardsmarkf** [comment]
This is absolutely fantastic.   thank you so much.

NOTE:  to run this on another server, you will need to add **host:**

```
var sequelize = new Sequelize('bank', 'maxroach', '', {
  dialect: 'postgres',
  host: '35.184.109.43',   // added 'host'
  port: 26258,
  logging: false
});

```
