### ISSUE TITLE
sql: tracking issue, proposed optimizations

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12418]
This issue is meant to track proposals for SQL-level optimizations before they are implemented.

- the list below can include ideas for which the technical problem is not yet fully understood and thus for which no individual issue can yet be created.
- the person proposing the optimization or interested in the conversation around it should be mentioned in the list too.

- [ ] expression and query compilation #16686 @knz
- [ ] take into account that fwd scans are faster #14228 @RaduBerinde 
- [ ] replace a filter using OR with a UNION of two index-based small-range lookups  #2142 @petermattis 
- [ ] map sub-queries to joins #7042 @petermattis @knz
- [ ] use roaring bitmaps for all cases where a bitmap is needed (e.g. outer joins etc) #11687
- [ ] reduce the number of intermediate result columns with joins and USING #12250  @RaduBerinde 
- [ ] rewrite correlated subqueries as joins #3288 @mjibson @arjunravinarayan
- [ ] use an array of sub-plans for UNION instead of a binary tree
- [x] sql: Substitute TRUNCATE for DELETE without WHERE clause #17713 @knz
- [x] implement constant-space aggregation when input ordered on group key #17086 @RaduBerinde @knz
- [ ] simplify `(a, b) IN ((1, 2)) AND a = 1` to `(a, b) IN ((1,2))` or even `a = 1 AND b = 2` #3472 @andreimatei 
- [x] `SELECT * FROM a,b WHERE f(a)` -> `SELECT * FROM (SELECT * FROM a WHERE f(a)), b` (push down filters across inner joins) #8566 #10633 @knz @RaduBerinde 
- [x] optimize filters across outer joins: filter propagates on the left for right outer joins, on the right for left outer joins (question: what of full outer joins?) @RaduBerinde 
- [x] move lossless expr transforms from "simplification" to "normalization" #2791 @petermattis

**Comment by knz** [comment]
cc @arjunravinarayan

**Comment by andy-kimball** [comment]
@knz, propose we close this down, since it's outdated, and info is captured in other places.

**Comment by knz** [comment]
yes go ahead
