### ISSUE TITLE
cdc: 24.2 release checklist

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#125138]
This issue captures a series of tests and steps that we need to run when 24.2 is getting close to being finalized.

- [x] clone an instance of this issue for the next release
- [ ] check regressions in benchmarks
- [x] check the CDC "24.2 Holding" and monthly milestone buckets for issues that we'd really like to get into the release
- [ ] organize a bug bash (see https://docs.google.com/document/d/1Je52baIv3HKeXFwlP427ehEQNyMF3N0BSulr-YZNa0g)

Jira issue: CRDB-39271

**Comment by rharding6373** [comment]
Closing since 24.2 is close to release.
