### ISSUE TITLE
backup/restore/ingest 2017Q1

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#12555]
O: Robust SQL interface to Backup/Restore

- [x] KR: Finalized SQL dialect
- [ ] KR: Read-only queries over backups by hooking up our SQL onto a read only kv store (stretch)
- [ ] KR: Point in time restore (stretch)
- General Robustness
  - [x] Remove TestDisableTableLeases from the tests (@dt)
    - [x] Error if the table or database exists (@dt)
  - [x] Figure out permissions (@dt)
  - [ ] Audit restored `TableDescriptor`s (e.g. FKs need to be marked invalid) (@dt)
    - [ ] Don't need to revalidate an fk if both tables involved were restored in the same command
  - [x] Cloud storage credentials (@dt)
  - [x] `BACKUP DATABASE foo; DROP DATABASE foo; CREATE DATABASE foo; RESTORE DATABASE foo` is broken (`no database with ID 50 found`). our current tests don't catch this because they restore into new clusters (@dt)
  - [x] Test for tables with secondary indexes
  - [x] Test the MVCCStats behavior of the WriteBatch impl
  - [x] Fix the flaky tests
  - [x] Implement `ValidatePreviousBackups` by calling `restoreTablesRequests`
  - [x] Checksumming (#13482)
  - [x] Verify kv checksums in WriteBatch
  - [x] Support placeholders in BACKUP's TO and RESTORE's FROM (#13624)
  - [x] Finalize protos
  - [x] Make the logs down the backup/restore calls all use rewritten start/end keys
  - [ ] Is TestMVCCIterateIncremental/intents3 correct?
  - [ ] [blocked] Test context cancellation
  - [ ] [blocked] During restore, wait for the newly created ranges (and leaseholders) to rebalance
- Known-bugs:
  - [x] backup: network errors should be retried (#14044)
  - [x] restore: TableDescriptors: unexpected value (#14045)
  - [ ] specifying bogus descriptors to BACKUP doesn't fail (#14118)
  - [x] backup: correctness issues in Import's construction of WriteBatches (#14152)
  - [ ] empty SSTs https://github.com/cockroachdb/cockroach/issues/14178
  - [ ] RESTORE should return useful info #14296 
  - [x] `SELECT * FROM system.jobs` during a backup on lapis is slowwwww (also system.descriptor)

# O: Admin UI for Backup/Restore

- [x] KR: Backup restore state in jobs table (@benesch)

# O: Stability and Performance

- [ ] KR: Restore 10-node cluster, 2T in 1 hour (@mjibson)
- [x] KR: Integrate with production clusters and run regular backups (@mjibson)
- [x] KR: Regularly (nightly) backup and then restore a production cluster (@mjibson)
- [ ] KR: Validate the restored data using a dump (@mjibson)
- [ ] KR: Validate restore using SQL fsck tool
- [x] KR: Incremental backups on 10-node cluster of 2T to S3/GS sink (@mjibson)
- [ ] KR: Checkpoint restore and recover from a checkpoint (stretch)
- [x] Benchmark incremental backup of a small time window over a large cluster
- [ ] Investigate poor restore performance in a geographically distributed cluster (one of the beta customers saw this when using arjun's benchmark data)

# O: Enterprise Trailblazing

- [x] KR: Move off of enterprise repo (@danhhz)
- [x] KR: CCL + Apache2 binaries, testing infra (@dt)
- [x] KR: Auditing enterprise feature use  (@danhhz)

**Comment by danhhz** [comment]
Q1 is over. Closing in favor of https://github.com/cockroachdb/cockroach/projects/3 for Q2
