### ISSUE TITLE
sql: meta issue for enabling partial statistics collection "at extremes"

### ISSUE THREAD

**Issue by Uzair5162** [cockroachdb/cockroach#125950]
This issue will serve as the meta-issue for making partial statistics collection "at extremes" production ready and enabling it by default.

- [x] https://github.com/cockroachdb/cockroach/issues/93094
- [x] https://github.com/cockroachdb/cockroach/issues/126730
- [x] https://github.com/cockroachdb/cockroach/issues/126822
- [x] https://github.com/cockroachdb/cockroach/issues/95233
- [x] https://github.com/cockroachdb/cockroach/issues/126856
- [x] https://github.com/cockroachdb/cockroach/issues/94101
- [x] https://github.com/cockroachdb/cockroach/issues/126401

PR to enable partial stats at extremes: https://github.com/cockroachdb/cockroach/pull/127850

Jira issue: CRDB-39681
