### ISSUE TITLE
sql: clean-ups after the filter propagation refactoring

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12618]
A couple of issues have been uncovered or are remaining after the work on #12617, #12616, #12605, #12575, #12553 and #12319:

- [x] rename selectNode to renderNode #12720
- [x] incomplete planNode walker #12599
- [x] add query plan tests once #12637 lands
- [x] propagated filters are not used for span generation #12893
- [x] stray starDatumInstances #12615 
- [x] no-op selectNodes created from a view descriptor are not fully optimized away (noticed in #12616) - this needs refactoring the view dependency tracking code
- [x] if the plan simplification reveals new filterNode/scanNode combinations which were not visible before, these are not yet taken into account for index selection / span generation (noticed in #12616, perhaps related to #12893, not sure)
- [x] ~there's a (separate) regression lingering from earlier where the index constraints generated during spanNode filter optimization are not fully propagated back to the filter expression, i.e. `select * from kv where k < 10` properly determines the span `-/10` for the `kv` scanNode, but the scanNode also retains the expression `k < 10` on top of that (which is redundant) (perhaps related to #12893, not sure).~ That was already so -- the predicate propagation only propagates equalities, not inequalities. Fixed by #13373 
- [ ] `addFilter()` on an emptyNode should evaluate the filter expression immediately (assuming it's non-row-dependent like `random()`) and set/reset `emptyNode.results` accordingly.
- [ ] implement filter propagation for GROUP BY columns #12762
- [ ] implement renderNode combination #12763
- [ ] propagate equalities in join filters #12892

**Comment by knz** [comment]
This has been obsoleted by the work on the optimizer.
