### ISSUE TITLE
kvserver/rangefeed: meta issue for reducing registration goroutines

### ISSUE THREAD

**Issue by wenyihu6** [cockroachdb/cockroach#126560]
**Is your feature request related to a problem? Please describe.**

This issue tracks meta-issues needed to land https://github.com/cockroachdb/cockroach/issues/110432.
- [x] Remove non-mux rangefeed code
- [x] Remove future package 
- [x] Move clean up function to stream muxer 
- [ ] Get rid of registration goroutine and per-range per-registration buffer 
- [ ] Introduce a queue buffer to StreamMuxer 

Jira issue: CRDB-39978

Epic CRDB-37519

**Comment by wenyihu6** [comment]
Closing - we will track child issues one by one in https://cockroachlabs.atlassian.net/browse/CRDB-37519.
