### ISSUE TITLE
roachtest: update mixedversion tests to work in shared-process deployments

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#127378]
The mixedversion framework recently introduced support for multi-tenant deployments (shared-process only, for now). However, a number of tests need to be adjusted (often in minor ways) in order to support this mode.

The following tests currently disabled multi-tenant deployments in upgrade tests. We should update them and enable the shared-process deployment mode:

* [x] `cdc/mixed-versions` (#128473)
* [x] `follower-reads/mixed-version/single-region` (#128596)
* [x] `follower-reads/mixed-version/survival=region/locality=global/reads=strong` (#128596)
* [x] `change-replicas/mixed-version` (#128119)
* [x] `backup-restore/mixed-version` (#128696)
* [x] `rebalance/by-load/leases/mixed-version` (#129117)
* [x] `rebalance/by-load/replicas/mixed-version` (#129117)
* [x] `tpcc/mixed-headroom/n5cpu16` (#129343)
* [x] `acceptance/validate-system-schema-after-version-upgrade` (#129485)
* [x] `multi-region/mixed-version` (#129085)

Jira issue: CRDB-40417

**Comment by renatolabs** [comment]
All tests have been updated, closing.
