### ISSUE TITLE
sql-queries: 24.3 release checklist

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#127468]
This issue captures a series of tests and steps that we need to run when 24.3 is getting close to being finalized.

 - [ ] check and update private opt tests repository
 - [ ] check regressions in microbenchmarks
 - [ ] run all tests with `fast_int_set_small` tag: `./dev test -- --define gotags=bazel,gss,fast_int_set_small`
 - [ ] run all tests with `fast_int_set_large` tag: `./dev test -- --define gotags=bazel,gss,fast_int_set_large`
 - [ ] clone an instance of this issue for the next release
 - [ ] check the SQL Queries "Active" and "Release XX.X" buckets for issues that we'd really like to get into the release
 - [ ] upgrade https://github.com/sqlancer/sqlancer to the latest version of CRDB

Jira issue: CRDB-38478

**Comment by michae2** [comment]
Using the tip of release-24.3 (c63ecd9c88af9e571519a3056723e718363a712d) I ran the following on a gceworker:

`./dev test --ignore-cache -- --define gotags=bazel,gss,fast_int_set_small` resulted in:

```
Executed 784 out of 784 tests: 784 tests pass.
```

`./dev test --ignore-cache -- --define gotags=bazel,gss,fast_int_set_large` resulted in:

```
Executed 784 out of 784 tests: 784 tests pass.
```

(each run used 114 GiB of disk space, which I cleaned up with `bazel clean --expunge`)

**Comment by mgartner** [comment]
Thanks @michae2!!!
