### ISSUE TITLE
1.0 Product Roadmap

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#12854]
CockroachDB is currently in beta. As we get closer to releasing our 1.0 version, we will be sharing our 1.0 roadmap instead of our quarterly roadmap, as we had done previously.

**1.0 Roadmap**

- Stability
     - [ ] Stable 64 node cluster
- Performance
     - [ ] Stable cluster performance after node recovery
     - [X] Improved performance under high contention workloads https://github.com/cockroachdb/cockroach/pull/13501
- Support zero downtime rolling upgrades
     - [ ] Draining on node shutdown 
     - [ ] Proposer evaluated KV https://github.com/cockroachdb/cockroach/issues/10431
- SQL Functionality
     - Distributed SQL
          - [ ] Filtering, sorting, aggregations
          - [ ] JOINs, diverse queries, schema changes 
          - [ ] Enabled for appropriate queries
- Developer Usability
     - [ ] Basic ORM support: Hibernate, Sequelize, ActiveRecord, GORM, SQLAlchemy

Check out our longer-term roadmap https://github.com/cockroachdb/cockroach/issues/13517

**Comment by dianasaur323** [comment]
Closing out as we approach our 1.0. Cheers!
