### ISSUE TITLE
ui: showcase value props in the admin ui

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/cockroach#13184]
Different approaches were discussed at various meetings, put them down here to keep track of progress and decisions. 

## Prescriptive improvement ideas:
- [ ] Click and drag to zoom into time range selector #13752
- [ ] Surface node down as a warning notification - WIP
- [x] Introduce main dashboard, issue logged #13163 #13348 - Done
- [ ] Add applicable durations to be displayed in the event list itself; something like "Node Rejoined (downtime: 5m)" #13378
- [ ] Show event on graph #13378
- [ ] Provide every graph (or important graphs) with a hover that shows you a histogram with a per node value. The idea is to provide a visualization of a node's contribution towards a point in the graph. #13389

## To prototype and explore: 
**1. Show 10 node cluster graphically** #13557
2. Explore histograms, bar chart (one bar for each node), scatter plot (for comparing two variables eg CPU vs QPS), bullet chart (for a more compressed view), heatmap (for comparing outliers over time) to show outliers
3. Generate video/film of changes to the entire cluster's lifetime
4. Onboarding checklist upon first use
5. Range visualization to see ranges split and rebalance, especially for new clusters.

**Comment by mrtracy** [comment]
A few suggestions we discussed:

+ Some of the events should display over graphs as a range, not an instant.  This applies to many events; nodes are down for a period of time, schema changes take time to apply, etc.  Other events, like a node joining for the first time, are actual events.
+ Additionally, it might be nice for these durations to be displayed in the event list itself; something like "Node Rejoined (downtime: 5m)"

**Comment by vivekmenezes** [comment]
Drawing from this paper: https://research.google.com/pubs/pub44686.html

the value props that cockroachdb brings that we should attempt to highlight:
1. High availability: This can mean showing cluster availability in the event of machine failures. This can mean showing machine down periods on the graphs and the minimal effect on them.  A major plus will be the ability to show case multi-homed clusters that provide availability in the light of datacenter failure. I'd suggest pushing the multi-homed use case to the latter part of the year.
2. Horizontal scale: This can mean showing the ability to run on many machines and adding capacity linearly. (harder to show on a cluster where the cluster size doesn't change)
3. Efficient resource utilization: This is shown by keeping clusters hotter than previous architectures like master/backup ones thereby using few resources for the same impact. (this is going to be much harder to showcase in my opinion) but we can show rebalancing as a means to show that even when a machine dies it's original load gets evenly balanced across all the machines, and on a suitably large cluster (10 machines) this can mean a small increase in machine utilization per machine. (easy)

**Comment by vivekmenezes** [comment]
And drawing from https://honeycomb.io/blog/2017/01/instrumentation-the-first-four-things-you-measure/

not value props specific to cockroachdb, but our UI would be more valuable to our customers if these metrics were bang in the middle of the front page, and the metrics we used to show the above value props.

**Comment by maxlang** [comment]
The couple things that come to mind in the "to prototype and explore section":

1. While we mentioned a histogram it might be useful to explore a few other visualizations to see which show outliers more clearly. Ideas might include:
 - bar chart (one bar for each node)
 - scatter plot (for comparing two variables eg CPU vs QPS)
 - bullet chart (for a more compressed view)
 - heatmap (for comparing outliers over time)

2. I really want to double down on the add a node/remove a node scenario. I think we need a good range visualization to see ranges split and rebalance, especially for new clusters.

Also while at first just an onboarding checklist will be a good start, the more we can integrate into the UI the easier it will be.

**Comment by vivekmenezes** [comment]
Here is some data we can show on the cluster visualization:

- node fullness: which can express rebalancing and resource utilization
- node SQL qps/error rates/outstanding queries, histogram of query latency : which can express cpu 
- node bandwidth and latency: What is the bandwidth utilization on a node in Mbps? and what is the latency between a node and all other nodes in the cluster. 
- grouping nodes in terms of zone config, group nodes within region together.

The challenge is going to be to show all this without crowding up the page.

**Comment by vivekmenezes** [comment]
Another idea is to provide every graph (or important graphs) with a hover that shows you a histogram with a per node value. The idea is to provide a visualization of a node's contribution towards a point in the graph

**Comment by petermattis** [comment]
Here is a beautiful drawing of the idea:

![photo on 1-31-17 at 3 36 pm](https://cloud.githubusercontent.com/assets/6201335/22483438/4149b4de-e7cb-11e6-9b83-419e97ccd275.jpg)

The histogram on the right is intended to show the point in time of the vertical line of the graph. If the user is not hovering over the graph, the histogram would show the rightmost time of the graph.

**Comment by kuanluo** [comment]
@petermattis @vivekmenezes I captured the idea in the issue.

**Comment by dianasaur323** [comment]
Moving to 1.1

**Comment by dianasaur323** [comment]
@kuanluo should we close this issue out in favor of new issues that we will be creating post @josueeee's additional work?

**Comment by kuanluo** [comment]
Yes, that sounds good to me. @dianasaur323

**Comment by dianasaur323** [comment]
Great, thanks! Closing out 👍
