### ISSUE TITLE
cdc: 25.1 release checklist

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#132850]
This issue captures a series of tests and steps that we need to run when 25.2 is getting close to being finalized.

- [ ]  clone an instance of this issue for the next release
- [ ]  check regressions in benchmarks
- [ ]  check the CDC "25.2 Holding" and monthly milestone buckets for issues that we'd really like to get into the release
- [ ]  organize a bug bash (see https://docs.google.com/document/d/1Je52baIv3HKeXFwlP427ehEQNyMF3N0BSulr-YZNa0g)

Jira issue: CRDB-43308
