### ISSUE TITLE
[Observability] Upgrade compatibility checklist for 24.3

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#132889]
Part of https://github.com/cockroachdb/cockroach/issues/132884 for DB teams to go through the upgrade compatibility checklist for 24.3.

## Upgrade compatibility requirements for 24.3
24.3 must be upgradeable **from both 24.1 and 24.2**

## Checklist
_[from doc: [Upgrade compatibility checklist for 24.3](https://docs.google.com/document/d/1qLKK0vfAtNWyZQQ7hunWBvhMj5P_U12vjKw2Vr4s7M8/edit). Tip: one way to review the checklist could be to integrate it into the team pre-mortem, with EMs and TLs signing-off that this has been reviewed with the team.]_

### New Functionality:

- [x] Has upgrade compatibility from both 24.1 and 24.2 been considered in your team pre-mortem?
- [x] Has the team introduced any migrations or version gates?
- [x] Have you tested all your migrations in upgrades from 24.1 and 24.2?
- [x] Have you tested all your version gates and related logic?
- [x] Has upgrade and mixed-version functionality (mixed versions including 24.1, 24.2 and 24.3) been tested against new functionality [1]?

### Existing Functionality:

- [x] Have you pulled out any 24.2 code (since April 2024) that could potentially impact upgrades or mixed-version functionality?
- [x] (if so, has this been resolved to support upgrade compatibility?)
- [x] Have you made any changes to existing functionality that could misbehave on a cluster created at an arbitrarily old version (either after upgrade to 24.3, or in a mixed cluster with some 24.1 or 24.2 nodes)?

[1] Note that there are a ton of other ways to break upgrades, ways that may not even use any migrations or version gates. e.g. Storage team recently we made a fix to the Pebble comparator (related to a now obsolete flag) which lead to inconsistent replica crashes on a 24.2 cluster

Jira issue: CRDB-43325

Epic CRDB-43331

**Comment by dhartunian** [comment]
Summary from team discussion: the biggest changes are the migrations + job we added for the databases page. The issue we uncovered as part of this checklist was ensuring that 24.3 shows the **legacy DB Page in DB Console prior to finalization**. Otherwise, the new tables aren't present when the new page is loaded and the page stops working during upgrades.

This was completed here: https://github.com/cockroachdb/cockroach/pull/133895
