### ISSUE TITLE
distsql: make TestLogicDistSQL run on a 3-node cluster w/fake span resolver

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#13377]
List of issues blocking this:
- [x] #13376 TxnCoordSender doesn't allow distribution if transaction changed data **[workaround in place]**
- [x] #13371 parallel streams may lose ordering
- [ ] #13646 alter_table logic test failure with fake span resolver
- [ ] #13384 inconsistent printing of decimals
- [ ] #13689 inconsistent aggregation results

**Comment by RaduBerinde** [comment]
#13371 also causing some failures.

**Comment by RaduBerinde** [comment]
Depends on #13646, #13371.

**Comment by RaduBerinde** [comment]
This has been enabled with workarounds for the outstanding issues (which are tracked separately).
