### ISSUE TITLE
sql-queries: 25.1 release checklist

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#134462]
This issue captures a series of tests and steps that we need to run when 25.1 is getting close to being finalized.

 - [x] check and update private opt tests repository
 - [x] check regressions in microbenchmarks
 - [x] run all tests with `fast_int_set_small` tag: `./dev test -- --define gotags=bazel,gss,fast_int_set_small`
 - [x] run all tests with `fast_int_set_large` tag: `./dev test -- --define gotags=bazel,gss,fast_int_set_large`
 - [x] clone an instance of this issue for the next release
 - [x] check the SQL Queries "Active" and "Release XX.X" buckets for issues that we'd really like to get into the release
 - [ ] upgrade https://github.com/sqlancer/sqlancer to the latest version of CRDB

Jira issue: CRDB-44093
