### ISSUE TITLE
distsql: tracking issue for enabling DistSQL by default

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#13666]
TODO list for getting all our ducks in a row for enabling DistSQL in "auto" mode. Feel free to add as needed. CC @andreimatei @cuongdo 

Correctness:
- [x] logic tests on multi-node cluster with fake span resolver #13377
- [x] nightly bigtests on distsql (@andreimatei)
- [x] tests for auto mode determination (probably via a special EXPLAIN mode - #13674)
- [x] versioning #13801
- [x] retryable errors should be marshalled correctly and tested #14504 @andreimatei
- [ ] DistSQL reads can't be run in txns that performed writes #13376 @andreimatei

Stability:
- [x] enable on all production clusters in auto mode @asubiotto 
    - currently running photos load on `navy` with `DISTSQL=ON`
- [x] run continuous TPC-H load against at least one production cluster @cuongdo 
- [x] check that index backfill works fine when nodes crash (#13655) @RaduBerinde 

Performance:
 - [x] update caches for span resolver (@andreimatei)
 - [x] sanity check execution plans for various queries (@asubiotto)

Features:
- [x] marshall `evalCtx` data - particularly timezone info required for date operations #13821

After initial "auto" release:
- [ ] marshall `ObservedTimestamps` #15013
- [x] memory accounting #15304
- [ ] distributed query cancellation #15671
- [x] better test infrastructure #13665
- [x] have some basic benchmarks in place for running periodically (@asubiotto)
- [x] gather some distsql on vs off data from the benchmarks @arjunravinarayan is working on.

**Comment by jseldess** [comment]
Wonder if we should add external docs to this checklist, @RaduBerinde?

**Comment by RaduBerinde** [comment]
@jseldess Yes, I think we should have some docs mentioning this. I don't know if going in depth about how distsql works is useful, but what we should convey is that we have a new distributed framework for running a subclass of (read-only) queries, and it can be disabled per-session using `SET DISTSQL = OFF` (this might be useful if a user is having some kind of problem with a query and wants to try it without distsql). The docs can also mention `EXPLAIN (DISTSQL)` can be used to see if a query will be run via distsql.

**Comment by petermattis** [comment]
@RaduBerinde Is there anything left to do here? There are still some unfinished items, but we've already enable DistSQL by default.

**Comment by arjunravinarayan** [comment]
The only agenda item (that's not in the "after auto release" section) that has not been closed is " DistSQL reads can't be run in txns that performed writes", which we've chosen not to do. 

So this issue should be closed, although we should first probably add/document a separate tracking issue for "distributed query cancellation" which does not have a linked issue (the other open agenda item is marshalling `ObservedTimestamps` which does have a linked issue).

**Comment by andreimatei** [comment]
Created #15671 for the cancellation.
