### ISSUE TITLE
sql: support for Liquibase

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#13991]
We should test out whether we work with Liquibase, which is a schema management tool along the same lines as Flyway, and determine how much work it would be to support if it doesn't work already.

Known issues:

- [x] #24714
- [x] #24713
- [ ] #31463
- [ ] https://github.com/cockroachdb/appdev-issues/issues/34 
- [ ] https://github.com/cockroachdb/appdev-issues/issues/32
- [ ] https://github.com/cockroachdb/appdev-issues/issues/33

**Comment by wdroste** [comment]
+1

**Comment by jjzazuet** [comment]
If it helps, I just gave it a quick shot with a development instance via `brew instal cockroach`, and the running the quick start change log example provided here: http://www.liquibase.org/quickstart.html

```
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
    <changeSet id="1" author="bob">
        <createTable tableName="department">
            <column name="id" type="int">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="name" type="varchar(50)">
                <constraints nullable="false"/>
            </column>
            <column name="active" type="boolean" defaultValueBoolean="true"/>
        </createTable>
    </changeSet>
</databaseChangeLog>
```
With the following command line, the change set appears to be working with cockroach 1.0.1.

```
$ liquibase --driver=org.postgresql.Driver --classpath=/opt/sqldeveloper/jdbc/lib/postgresql-42.1.1.jar --changeLogFile=changelog.xml --url="jdbc:postgresql://192.168.1.114:26257/bank" --username="root" --password="" --logLevel=debug migrate
DEBUG 5/28/17 3:59 AM: liquibase: Connected to root@jdbc:postgresql://192.168.1.114:26257/bank
DEBUG 5/28/17 3:59 AM: liquibase: Setting auto commit to false from true
DEBUG 5/28/17 3:59 AM: liquibase: Executing QUERY database command: select count(*) from bank.databasechangeloglock
DEBUG 5/28/17 3:59 AM: liquibase: Create Database Lock Table
DEBUG 5/28/17 3:59 AM: liquibase: Executing EXECUTE database command: CREATE TABLE bank.databasechangeloglock (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))
DEBUG 5/28/17 3:59 AM: liquibase: Created database lock table with name: bank.databasechangeloglock
DEBUG 5/28/17 3:59 AM: liquibase: Executing QUERY database command: select count(*) from bank.databasechangeloglock
DEBUG 5/28/17 3:59 AM: liquibase: Initialize Database Lock Table
DEBUG 5/28/17 3:59 AM: liquibase: Executing EXECUTE database command: DELETE FROM bank.databasechangeloglock
DEBUG 5/28/17 3:59 AM: liquibase: Executing EXECUTE database command: INSERT INTO bank.databasechangeloglock (ID, LOCKED) VALUES (1, FALSE)
DEBUG 5/28/17 3:59 AM: liquibase: Executing QUERY database command: SELECT LOCKED FROM bank.databasechangeloglock WHERE ID=1
DEBUG 5/28/17 3:59 AM: liquibase: Lock Database
DEBUG 5/28/17 3:59 AM: liquibase: Executing UPDATE database command: UPDATE bank.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = '192.168.81.1 (192.168.81.1)', LOCKGRANTED = '2017-05-28 03:59:18.366' WHERE ID = 1 AND LOCKED = FALSE
INFO 5/28/17 3:59 AM: liquibase: Successfully acquired change log lock
DEBUG 5/28/17 3:59 AM: liquibase: Resolving XML entity name='null', publicId='null', baseURI='null', systemId='http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd'
DEBUG 5/28/17 3:59 AM: liquibase: Opening jar:file:/opt/liquibase/liquibase.jar!/liquibase/parser/core/xml/dbchangelog-3.1.xsd as liquibase/parser/core/xml/dbchangelog-3.1.xsd
DEBUG 5/28/17 3:59 AM: liquibase: Computed checksum for 1495958358896 as aba2491e358538f531e523e92e9fc6ee
DEBUG 5/28/17 3:59 AM: liquibase: Create Database Change Log Table
INFO 5/28/17 3:59 AM: liquibase: Creating database history table with name: bank.databasechangelog
DEBUG 5/28/17 3:59 AM: liquibase: Executing EXECUTE database command: CREATE TABLE bank.databasechangelog (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP WITHOUT TIME ZONE NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))
DEBUG 5/28/17 3:59 AM: liquibase: Executing QUERY database command: select count(*) from bank.databasechangelog
INFO 5/28/17 3:59 AM: liquibase: Reading from bank.databasechangelog
DEBUG 5/28/17 3:59 AM: liquibase: Executing QUERY database command: SELECT * FROM bank.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
DEBUG 5/28/17 3:59 AM: liquibase: Executing QUERY database command: select count(*) from bank.databasechangeloglock
DEBUG 5/28/17 3:59 AM: liquibase: changelog.xml: changelog.xml::1::bob: Computed checksum for createTable:[
    columns=[
        [
            [
                nullable="false"
                primaryKey="true"
            ]
            name="id"
            type="int"
        ],
        [
            [
                nullable="false"
            ]
            name="name"
            type="varchar(50)"
        ],
        [
            defaultValueBoolean="true"
            name="active"
            type="boolean"
        ]
    ]
    tableName="department"
] as ffa8508dc9cdd8bd88f8063efa23645a
DEBUG 5/28/17 3:59 AM: liquibase: changelog.xml: changelog.xml::1::bob: Computed checksum for 7:ffa8508dc9cdd8bd88f8063efa23645a: as 17a94fcdd73aa8852c1f53e4d06ee651
DEBUG 5/28/17 3:59 AM: liquibase: changelog.xml: changelog.xml::1::bob: Running Changeset:changelog.xml::1::bob
DEBUG 5/28/17 3:59 AM: liquibase: changelog.xml: changelog.xml::1::bob: Changeset changelog.xml::1::bob
DEBUG 5/28/17 3:59 AM: liquibase: changelog.xml: changelog.xml::1::bob: Reading ChangeSet: changelog.xml::1::bob
DEBUG 5/28/17 3:59 AM: liquibase: changelog.xml: changelog.xml::1::bob: Executing Statement: liquibase.statement.core.CreateTableStatement@5b03b9fe
DEBUG 5/28/17 3:59 AM: liquibase: changelog.xml: changelog.xml::1::bob: Executing EXECUTE database command: CREATE TABLE bank.department (id INT NOT NULL, name VARCHAR(50) NOT NULL, active BOOLEAN DEFAULT TRUE, CONSTRAINT PK_DEPARTMENT PRIMARY KEY (id))
INFO 5/28/17 3:59 AM: liquibase: changelog.xml: changelog.xml::1::bob: Table department created
INFO 5/28/17 3:59 AM: liquibase: changelog.xml: changelog.xml::1::bob: ChangeSet changelog.xml::1::bob ran successfully in 7ms
DEBUG 5/28/17 3:59 AM: liquibase: changelog.xml: changelog.xml::1::bob: Executing QUERY database command: SELECT MAX(ORDEREXECUTED) FROM bank.databasechangelog
DEBUG 5/28/17 3:59 AM: liquibase: changelog.xml: changelog.xml::1::bob: Executing EXECUTE database command: INSERT INTO bank.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'bob', 'changelog.xml', NOW(), 1, '7:17a94fcdd73aa8852c1f53e4d06ee651', 'createTable tableName=department', '', 'EXECUTED', NULL, NULL, '3.5.3', '5958358917')
DEBUG 5/28/17 3:59 AM: liquibase: Release Database Lock
DEBUG 5/28/17 3:59 AM: liquibase: Executing UPDATE database command: UPDATE bank.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
INFO 5/28/17 3:59 AM: liquibase: Successfully released change log lock
Liquibase Update Successful
```

How cool is that??

Cheers!

**Comment by jjzazuet** [comment]
I'm sure there might some complications down the road creating indexes or other kinds of commands specific to PostgreSQL. I'll ping back if I run into issues. Thanks!

**Comment by ReidE96** [comment]
Currently using liquibase and investigating cockroach - thus far there's been two main issues presenting:
1) Cockroach 1.1 not supporting non-restrict constraints (which I'm aware is implemented for 2.0, so just noting for others' reference before that releases)
2) Failure on dropping a primary key. This is caused by the postgresql driver using the DO command for these, so given that's psql specific it's an understandable failure, but it's something we should address if we plan to support liquibase officially.

In case it's helpful, here's a sanitised version of the full query generated:
```DO $$ DECLARE constraint_name varchar;
BEGIN
  SELECT tc.CONSTRAINT_NAME into strict constraint_name
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'
      AND TABLE_NAME = 'myTable' AND TABLE_SCHEMA = 'mySchema';
    EXECUTE 'alter table mySchema.myTable drop constraint ' || constraint_name;
END $$;]

**Comment by ruzkant** [comment]
So the reserved words query is halfway there. Cockroachdb 2.0 supports pg_get_keywords(), but string_agg is not yet supported but referenced in https://github.com/cockroachdb/cockroach/issues/10495

**Comment by ruzkant** [comment]
Related issues: 

https://github.com/cockroachdb/cockroach/issues/24714
https://github.com/cockroachdb/cockroach/issues/24713

**Comment by patelh** [comment]
Any updates on this?

**Comment by jordanlewis** [comment]
@patelh, @timveil has done some investigation on this and discovered that Liquibase support has drastically improved since the last time we commented on this issue. However, we still haven't figured out how to run comprehensive tests on our compatibility.

I would recommend trying out CockroachDB with Liquibase on your application and reporting back. We'll be able to help more if you do that.

Thanks!

**Comment by awoods187** [comment]
Also worth noting that Liquibase doesn't respect the order of primary keys on Postgres databases. Instead, it uses the order of columns in the table, so keep an eye out for that.

**Comment by patelh** [comment]
@jordanlewis @awoods187 will do thanks!

**Comment by jordanlewis** [comment]
@rafiss, do you have a tracking issue for this one? I'm going to move it to the AppDev board, but feel free to close!

**Comment by rafiss** [comment]
Thanks Jordan.

@vy-ton: we can use this to track any further issues as they come up.
