### ISSUE TITLE
distsql: tracking issue for queries we expect to run through DistSQL

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#14288]
This is a TODO list for listing queries that we expect to run using DistSQL (in auto mode) by 1.0. Feel free to add as needed, cc @andreimatei @RaduBerinde @cuongdo @asubiotto.

- [x] `SELECT COUNT(*)` should always run through DistSQL for speed reasons. It is a common operation just after loading a bunch of data. It is currently exceedingly slow on large tables (without DistSQL). @arjunravinarayan
- [x] `SELECT COUNT (DISTINCT) column_name` @arjunravinarayan
- [x] Distributed sorting over large datasets: might be implicitly tested by a TPC-H query. Identify which one and document. @asubiotto 
- [x] Distributed Aggregations over large datasets: might be implicitly tested by a TPC-H query. Identify which one and document. @asubiotto 
- [x] Large scans with a very sparse `WHERE` clause. @arjunravinarayan
- [x] TPC-H queries that we support (see #14295) @asubiotto 
    - Queries 9 and 15 don't run through DistSQL, see issue for more info.
- [x] Basic join queries. For some helpful query ideas, the [join order benchmark](https://github.com/gregrahn/join-order-benchmark) provides plenty of samples to try with DistSQL, even if we won't be optimally efficient on these for a while. @arjunravinarayan
- [x] `LIMIT` queries, particularly limits after `JOIN`s that would cause large amounts of state to stream across machines. @arjunravinarayan
- [x] queries using MIN @asubiotto 
- [x] queries using MAX @asubiotto 
- [x] queries using AVG (see #14351) @asubiotto

If there are any queries that we want turned on by 1.0, please add them to the list above.

Do not check off an item as done without adding a comment/issue tracking the queries actually attempted on a cluster. Try and report running times and `EXPLAIN(query)` output to show the DistSQL plan.

**Comment by asubiotto** [comment]
Ran
```
SELECT MIN(l_extendedprice) FROM lineitem
```
On a 3 node local cluster. `lineitem` has 6million rows (~2.5GiB).
The query runs correctly, [the execution plan looks good](https://raduberinde.github.io/decode.html?eJy8kjFr8zAQhvfvV3y8UwsaKidNwZM7emhSQreiQbUOI7AlI8nQEvzfiy1Ka1OUlISM0ul9njtxBxiraCtb8shfwcGQgWEFwdA5W5H31o2l-LBU78jvGLTp-jBeC4bKOkJ-QNChIeR4kW8N7UkqcmBQFKRuJnjndCvdR9FoQzpQC4ZdH_L_xQZiYLB9-IIO7HTdY107qmWwC9tTub0p-O3J6G9ib6xT5EjNgGK4sJxf9xuP6M6ZJLvuJEd0l1qIX9B78p01nhaLMecJBlI1xZ3ytncVPTtbTfB43E2vpwtFPsQqj4fSxNLY1s8wT4azWZgvw1ky_JA2r5LhdTq8Pqft-2R4kzZv_mQWw7_PAAAA__-abK3j), and the times for one run are below:

| Without DistSQL | With DistSQL |
| --- | --- |
| 22.028s | 9.520s |

**Comment by asubiotto** [comment]
Ran
```
SELECT MAX(l_extendedprice) FROM lineitem
```
On a 3 node local cluster, using the TPC-H scalefactor=1 dataset. `lineitem` has 6million rows (~2.5GiB).
The query runs correctly, [the execution plan looks good](https://raduberinde.github.io/decode.html?eJy8kkFLwzAUx-9-CvmfFHIw3ZzQU3fcQSfDgyA5xOZRAm1SkhSU0e8ubRBtkWyysWPy8v_93gtvD2MVPcmGPPI3cDBkYFhAMLTOluS9dUMpPtyoD-R3DNq0XRiuBUNpHSHfI-hQE3K8yPeadiQVOTAoClLXI7x1upHus6i1IR2oAcO2C_l1sYLoGWwXvqE9O163ripHlQx2Zntcv94U_PZo9A-xM9YpcqQmQNGfWc4v-40HdKdMkl12kgO6cy3EH-gd-dYaT7PFmPIEA6mK4k5527mSnp0tR3g8bsfX44UiH2KVx8PGxNLQ1u8wT4azSZjPw1ky_JA2L5LhZTq8PKXt-2R4lTav_mUW_dVXAAAA__-0Gq3r), and the times for one run are below:

| Without DistSQL | With DistSQL |
| --- | --- |
| 22.821s | 9.481s |

**Comment by tamird** [comment]
Hm, that's much slower than I'd have expected. Isn't DistSQL able to reduce network traffic on these queries to O(1)?

**Comment by RaduBerinde** [comment]
Yes, the network traffic is O(1) in these plans. Note that these are *local* clusters (all nodes on the same machine) so network traffic is not really network traffic.

**Comment by tamird** [comment]
Ah, understood.

**Comment by RaduBerinde** [comment]
@danhhz mentioned a `SELECT COUNT(*)` experiment on a real 3 node cluster (I think it was ~200M rows, `SELECT COUNT(*)`  took 7m33s compared to over an hour).

**Comment by tamird** [comment]
Makes much more sense, thanks.

**Comment by danhhz** [comment]
Indeed, it was the production lapis cluster

**Comment by asubiotto** [comment]
Ran
```
SELECT COUNT(*) FROM lineitem
```
on 6-node `navy` ([Standard_D3_v2](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#dv2-series)), using the TPC-H scalefactor=1 dataset. `lineitem` has 6million rows (~2.5GiB).
The query runs correctly, [the execution plan looks good](https://raduberinde.github.io/decode.html?eJy8k89K80AUxfffU3yclcIsmjStNauKqy5spbYrCRIzlxBIZ8KdCSgl7y5NEG2QSWUky_lzzu-emXuPUFrSOj2QQfyMAAIhBKYQiCAwQyJQsc7IGM2nK51gJd8QTwQKVdX2tJ0IZJoJ8RG2sCUhxi59LWlLqSSGgCSbFmULqbg4pPy-LAtFhaUDBLakJHH8f4KkEdC1_bRtxOXAuzxnylOre7z7zX69u1oG1xebf3nWSrMkJnlmmTS_wD_tH15WFxQQjP2cA0C_5wzHTjMA9EszHTvNANAvTTR2mgHg3w3uD-ZbMpVWhnoDfO6XCJDMqZt9o2vO6JF11pp3y017u92QZGx3GnSLleqOTmV9FwdOcXgmDvri0E0eQE-d6sgtjnzqnjnFczd57kO-cYoXbvLCh3zr_qvJQJu4m6zPTpp_HwEAAP__quGRIA==), and the times for one run are below:

| Without DistSQL | With DistSQL |
| --- | --- |
| 36.707s | 12.350s |

**Comment by asubiotto** [comment]
Ran
```
SELECT AVG(l_extendedprice) FROM lineitem
```

on 6-node `navy` ([Standard_D3_v2](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#dv2-series)), using the TPC-H scalefactor=1 dataset. `lineitem` has 6million rows (~2.5GiB).
The query runs correctly, [the execution plan looks good](https://raduberinde.github.io/decode.html?eJy8lEFLwzAUx-9-ivI_bRBw7bo6e6p42sFN5naSILV5lEKXlCQFRfrdpYvgNiRFNnbry3u__N7_0HxBKkHLfEcG6StCMEzBEINhBoYEnKHRqiBjlO5HHLAQH0gnDJVsWuuObWVrQopWKi1IkwCDIJtXdd_nHWcolCakv6MPZampzK3SR7N42T6NsnAM1n-9LZabURb11ZqkIJ0GWRjcBlkE3jGo1v6swDt2sFx4sNwf6k3-XtOackEn7kZXu1x_ZnUlqbK0A8OqtWmQJefohpM-rrZ9znDs1UTXTTWgu1Sq6XVTDegulSq-bqoB3aVSTfyaNZlGSUMnP__xfZyBREnu3TCq1QU9a1XsL3flaj-9PxBkrOveu2IhXatf6xAOvXDkhyMvPDmCw1N46oVjvzk-xzzzwonfnJxjvvPCc795_i8z726-AwAA__8o_C6k), and the times for one run are below:

| Without DistSQL | With DistSQL |
| --- | --- |
| 46.255s | 18.560s |

**Comment by arjunravinarayan** [comment]
Can you report the cockroach sha you used for future reference?

**Comment by petermattis** [comment]
@asubiotto The ranges for the `lineitem` table are only spread across 4 nodes? Or is there another reason the query plan only has 4 TableReaders?

**Comment by arjunravinarayan** [comment]
Is there a quick way to find this information out? Last time I asked, there wasn't a clean way to figure out, given a table, what ranges the table was spread across.

**Comment by arjunravinarayan** [comment]
Admin UI says there are 74 ranges for table lineitem (but I can't figure out how to find range IDs or node information for those ranges), so it being spread across just 4 nodes seems strange (but possible).

**Comment by petermattis** [comment]
`SHOW TESTING_RANGES FROM TABLE <table-name>`

**Comment by arjunravinarayan** [comment]
Thank you @petermattis. It appears there are replicas and lease holders on every node, so let me investigate.
Also, there are 24 ranges, for 72 replicas, so clearly the Admin UI is buggy when it says there are 74 ranges. I will file an issue.

**Comment by asubiotto** [comment]
I updated the execution plan. I think the gateway node probably had a cache that hadn't been updated. The query plan now shows only 5 TableReaders which is still weird.

**Comment by asubiotto** [comment]
Actaully, 1 doesn't seem to be a lease holder for any range so it makes sense.

**Comment by arjunravinarayan** [comment]
Sure, but it was showing 4 before, and that was certainly incorrect. cc @andreimatei.

**Comment by andreimatei** [comment]
> Sure, but it was showing 4 before, and that was certainly incorrect.

The range-descriptor and leaseholder caches can be empty or stale. This explains it, right?

The state of the caches is supposed to be seen in the `ranges_cached` internal table, but I think this hasn't been implemented yet.

**Comment by asubiotto** [comment]
All these queries were run using 4129fe0 on 6-node `navy` ([Standard_D3_v2](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#dv2-series)), using the TPC-H scalefactor=1 dataset.

I started by trying to run
```
SELECT * FROM lineitem ORDER BY l_extendedprice
```
On 6million ~2.5GiB `lineitem` but this failed (see #15332 but note that this query doesn't cause an OOM crash with 4129fe0 any more)

I then moved down to `orders`, a 1.5million ~600MiB table. Ran
```
SELECT * FROM orders ORDER BY o_totalprice
```
The query runs correctly, [the execution plan looks good](https://cockroachdb.github.io/distsqlplan/decode.html?eJzMlDFv8jAQhvfvV3x6114lEkKATF5ZoKLdKg9pfKoiQS6yHalVlf9eEVcqoNaosGS0fc897zskH2jE8Lrcs0PxjASEFIQMhBkIOTShtVKxc2IPIwFYmTcUE0LdtJ0P1772O0YBsYYtGxAM-7LeDXtVdgfda0IlllF8T6_lXtqTWd0TpPNfe3VPR8bkyPjDsqfyZcdbLg3bU31r631p39WQzYGw6XzxXyWkUlJTUhmpGamc1JzUgtQSN4R4FOvP_aH-7yvTMfS6EOKaXtMx9LoQ4ppe2Rh6XQhxTa9JfOWWXSuN4-j3qglsXjn8FJx0tuIHK9WwPBw3w_RwYdj58LoMh1UTng6xjuEkCqdxOI3CkxM4OYenUTiLm7NbzLMonMfN-S3meRRexM2LP5l1_-8zAAD__wr6HiA=) (note that nodes `1` and `3` aren't leaseholders for any of `orders`' ranges), and the times for one run are below:

| Without DistSQL | With DistSQL |
| --- | --- |
| 3m51s | 3m34s |

I also ran:
```
SELECT * FROM lineitem ORDER BY l_extendedprice LIMIT 10
```
To avoid running out of memory on the gateway node ([execution plan here](https://cockroachdb.github.io/distsqlplan/decode.html?eJzMlE-rnEAQxO_5FI--pgO2_94-T31dCLthk1vwYJwmDKgj4wgJi989rBKSNcvMgjl4dKar6kfZzBU6o-RUtTJA8RUIEGJASAAhBYQMEHIoEXprahkGY29ji-iofkARIeiuH93tuESojRUoruC0awQK-FJ9a-QilRILCEpcpZs5qLe6rexPbnQn2kkLCOfRFS9MyDFygpwiZ8g58ivyAfkNmSJkImSKkSlBphSZMmTKoZwQzOh-g0z4POJnY92ajvP3gPBRt9q9UPS0-x9TY5VYUf-6ltMDhJP5YPr72aeyaf_lBxA3lh_vv4AA4sYCkv0XEEDcWEC6_wICiBsLyPZfQADxPz7AD9wvMvSmG-TOf-1XIoj6LssbPpjR1vLJmno2Xz7P8_R8oGRwyy0tH8duubph_S0mrzi-E9NaHPuTE3904lWnfnG6hTvzinN_cr4l-dUrPviTD1uS3_z_KgqsiX_JAtnk3zKKA-H-PVuHl9O7XwEAAP__7Zg25w==)). The times for one run are as follows:

| Without DistSQL | With DistSQL |
| --- | --- |
| 1m45s | 15.389s |

**Comment by arjunravinarayan** [comment]
Queries run with `630757cbc0` on a 6-nodeo `navy` (Standard_D3_v2) using the TPC-H scalefactor=1 dataset.

```
cockroach@cockroach-navy-0006:~$ time ./cockroach sql --certs-dir=certs -e "set distsql = off; select count(DISTINCT l_suppkey) FROM tpch.lineitem LIMIT 1;"
+---------------------------+
| count(DISTINCT l_suppkey) |
+---------------------------+
|                     10000 |
+---------------------------+
(1 row)

real	0m29.891s
user	0m0.028s
sys	0m0.012s
cockroach@cockroach-navy-0006:~$ time ./cockroach sql --certs-dir=certs -e "set distsql = on; select count(DISTINCT l_suppkey) FROM tpch.lineitem LIMIT 1;"
+---------------------------+
| count(DISTINCT l_suppkey) |
+---------------------------+
|                     10000 |
+---------------------------+
(1 row)

real	0m9.481s
user	0m0.044s
sys	0m0.008s
```

**Comment by arjunravinarayan** [comment]
I forgot to include the [execution plan](https://cockroachdb.github.io/distsqlplan/decode.html?eJy8lE1rq0AYhff3V4SzuhdmkYn5uHHlJdkIl6SkdlVcWOdFBtSRmRFagv-9RCmtUsYSweV8nPPMIy9eUSpBp6QgA_8ZHAwrMKzBsAHDFjFDpVVKxih9u9IFQvEKf8kgy6q2t-2YIVWa4F9hpc0JPqLkJacLJYI0GATZROYtpNKySPRbkMuSpKUCDOfa-ovAQ9wwqNp-lDbs57ijNFaWqe2zAu7s5PMqjODuUljNqzCCu0vBm1dhBHeXwnpehRHcZIXPqrpUWpAm0euKm2-o_7JMU5ZYNXA8nJ9O0e9j-BiFp0O0CPgfMPyXhbSLSR_1QqZSpaHBy_p9MQOJjDopo2qd0oNWafs76Zbn9na7IcjY7pR3i7Dsjm7P-hrm7vCyl-bD9MqZ9txobxJ67Uxv3OjNJPTWmd650btJ6L_O9N6N3k9C85E5Gw5a3Px6DwAA__8fn4T3), which looks good.

**Comment by arjunravinarayan** [comment]
Queries run with `630757cbc0` on a 6-node `navy` (Standard_D3_v2) using the TPC-H scalefactor=1 dataset.

This query was constructed to have a sparse where clause, and really nothing else. The 
```
cockroach@cockroach-navy-0006:~$ time ./cockroach sql --certs-dir=certs -e "set distsql = on; SELECT * FROM tpch.lineitem WHERE l_extendedprice < 1000;" > foo_on

real	0m12.068s
user	0m0.072s
sys	0m0.012s
cockroach@cockroach-navy-0006:~$ time ./cockroach sql --certs-dir=certs -e "set distsql = off; SELECT * FROM tpch.lineitem WHERE l_extendedprice < 1000;" > foo_off

real	0m49.482s
user	0m0.076s
sys	0m0.008s


```

The execution plan [looks good](https://cockroachdb.github.io/distsqlplan/decode.html?eJzclMtq4zAUhvfzFOZfnwHJt5nR6gxzgcBMUkJ3rReudSgGxzKyDC3B715iU5qUkkW98_JcPun_tNARrbOyLQ_Sw9xBgxCDkIKQgZCjIHTeVdL3zp9WZmBjn2AUoW67IZzaBaFyXmCOCHVoBAa35UMjeymteBCshLJupks6Xx9K_8xN3Uod5ADC37oJ4k3EeXQ_KJVUkVZKGWN-__m1-f_zHwi7IZiINXFMnBCnxBlxTvyN-DvxD2KtiLUm1jGxToh1SqwzYp2jGAluCK9ZRzqz0KuwiFdhkazCIl2dxVv4oXXeihd7Eb0YP_Dcuq-ue7f26UfbS9-5tper5xUEsY8yJ-7d4Cu58a6afqq53E3bU8NKH-ZpNhebdhrpU6xzWC-B4yVwsgROl8DZVTi_gNVYjF9eAgAA__-3j-r3)

The results are correct:
```
cockroach@cockroach-navy-0006:~$ sort foo_on > foo_on_sorted
cockroach@cockroach-navy-0006:~$ sort foo_off > foo_off_sorted
cockroach@cockroach-navy-0006:~$ diff foo_off_sorted foo_on_sorted
cockroach@cockroach-navy-0006:~$ wc -l foo_off
3082 foo_off
cockroach@cockroach-navy-0006:~$ wc -l foo_on
3082 foo_on```

I did not add an `ORDER BY` or a `COUNT` operation just to confuse things, but when added the runtimes are similar.

**Comment by arjunravinarayan** [comment]
Queries run with `630757cbc0` on a 6-node `navy` (Standard_D3_v2) using the TPC-H scalefactor=1 dataset.

The query is `SELECT * FROM tpch.lineitem JOIN tpch.supplier ON tpch.lineitem.l_suppkey = tpch.supplier.s_suppkey`. This query was constructed to have a JOIN that could have a lot of rows in it, followed by a limit. It is extremely artificial and otherwise useless in any real analytics scenario.

The DistSQL [execution plan](https://cockroachdb.github.io/distsqlplan/decode.html?eJzsls9q3DAQh-99ijCnBKbgke39YyjMsSklKaG34oOzVrMCr2VkGRrCvntZuxC8TTRd1NOyR1v6rPl9MyC_QGtrfVftdA_FDyBAUICQAUIOCAsoETpnN7rvrTtsmYDb-hcUCYJpu8EfXpcIG-s0FC_gjW80FPC9emz0g65q7QCh1r4yzXhI58yucs_cmFYbr3eAcD_44ooJWSGnyBlyjrxAXiKvkNfIlCATIZNCphSZMmTKkWkB5R7BDv5PIa_nPz5fbat-Oz-bUyj35R7fifFKD611tXa6nvEjKW15w8Xnqt9-saY9VtHon_6a05tPzjxt_TXTTZwMZFoi0wqZ1sgqQVaH7yhklQLCV7Mz_oqSI2dzH3QebaVLW2c-1Hm0VV3aOvORnkdbY2P0Q9c1Zlx9N8aJRVKwyMvsQZGdx-xll7ZG-Hgj7J39aLt5zv8xTw-672zb6-OGzL5XIuj6SU-193ZwG_3N2c34mzc93o-7xx-EWvd-WqVkerptp7VDXf9OpzHwKgbOY2AKw3QMJzNYoFWU7zAt-A7Dgu8wLPgWQofhNMp3FuU7TAu-w7DgOwwLvoXQYTiP8r2I8h2mBd9hWPAdhgXfQugwvDzFmDqNTmPgVQycx8AUhldRE7qOmtAwLUxoGBYmNAwLEyqEFm68v-7Lk4STcGOqGZ7sy_2H3wEAAP__5Joqug==) is intimidating, but ultimately correct.

```
cockroach@cockroach-navy-0006:~$ time ./cockroach sql --certs-dir=certs -e "set distsql = on; SELECT * FROM tpch.lineitem JOIN tpch.supplier ON tpch.lineitem.l_suppkey = tpch.supplier.s_suppkey limit 10" > foo_on

real	0m0.124s
user	0m0.028s
sys	0m0.028s
cockroach@cockroach-navy-0006:~$ time ./cockroach sql --certs-dir=certs -e "set distsql = off; SELECT * FROM tpch.lineitem JOIN tpch.supplier ON tpch.lineitem.l_suppkey = tpch.supplier.s_suppkey limit 10" > foo_off

real	0m0.186s
user	0m0.036s
sys	0m0.016s
```

When run without the limit, both versions OOM:
```
cockroach@cockroach-navy-0006:~$ time ./cockroach sql --certs-dir=certs -e "set distsql = off; SELECT * FROM tpch.lineitem JOIN tpch.supplier ON tpch.lineitem.l_suppkey = tpch.supplier.s_suppkey" > foo_off
Error: pq: root: memory budget exceeded: 10240 bytes requested, 3676112896 bytes in budget
Failed running "sql"

real	0m16.898s
user	0m0.036s
sys	0m0.012s

cockroach@cockroach-navy-0006:~$ time ./cockroach sql --certs-dir=certs -e "set distsql = on; SELECT * FROM tpch.lineitem JOIN tpch.supplier ON tpch.lineitem.l_suppkey = tpch.supplier.s_suppkey" > foo_off
Error: pq: root: memory budget exceeded: 136007680 bytes requested, 3676112896 bytes in budget
Failed running "sql"

real	0m35.439s
user	0m0.028s
sys	0m0.028s
```

While that is unsatisfactory and needs work, the point of this query demonstrates that in both time and memory usage, `LIMIT` queries in DistSQL (and regular SQL) do the right thing, and match expected behavior.

**Comment by asubiotto** [comment]
Query run using 630757c on 6-node `navy` ([Standard_D3_v2](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#dv2-series)), using the TPC-H scalefactor=1 dataset.
```
SELECT l_shipmode, AVG(l_extendedprice) FROM lineitem GROUP BY l_shipmode;
```
The query runs correctly, [the execution plan looks good](https://cockroachdb.github.io/distsqlplan/decode.html?eJzUlsFq20AQhu99CjOnBLa0K1mO7ZNK24MPsYsTn4ooijU4AltrVjI0BL17kUVJbZH5426Q0M1a6dt_tN_g0TNlJuF5vOOcpj9JkyKPFPmkaEiKAlI0okjR3po157mx1WM1NEt-0_SzojTbH4pqOVK0NpZp-kxFWmyZpnQfP2x5yXHClhQlXMTp9hi0t-kutk_hNs04LXhHihaHYjoIdaDCEUWlInMo_m5cqrdHftlsLG_iwpwlhtW7zb59n99fhfqaFN2tbq9Cr_r1dbGqVr3rs9yXTR-eBo9x_tjYMSpfr-2FPmTGJmw5OeGj8n2qv1vd_ppV6351teQsYVsd5CD0Bp8Gof_mw_yvgufmo9mfPfZ6nG6_XUBkp-2i-9YuXvv-QGSn_ry--fPb9wciO_Xn983fsH1_ILJTf8O--Qva9wciO_UX9M0f-PZccr43Wc7i91CkiJMN1--cm4Nd8w9r1sfN68vF8enjQsJ5Ud_V9cUsq29VZf0L63NYn8DjE1pfRk9c4JELrD0nOnChQbQn2vJl2JdVT2TXQ5EOZDhwahSZBo0iw6BRQN3AFqBBo8g0iB65NMqNCI9l1WMn1TINVMswUA3qBucNaKBapkH0xEW1Bv__aAA4TgC3EeA2AxyHgOMUcBoD2mkOaDAIhsB5YxJc5lzGkXOZRs5B6ejYAY6cyzgKb8yDi5zLA0HfAOeNkXCZcxlHzmUaOQelo2MHOHIu4yi8MRhE51H54U8AAAD__zi8lFQ=), and the times for one run are below:

| Without DistSQL | With DistSQL |
| --- | --- |
| 44.103s | 7.799s |

**Comment by petermattis** [comment]
@asubiotto Almost linear speedup. Nice!

**Comment by arjunravinarayan** [comment]
Queries run using 630757c on 6-node `navy` ([Standard_D3_v2](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#dv2-series)), using the TPC-H scalefactor=1 dataset.

I ran a variety of join queries, but not documenting all of them, since they all have the same story: we always plan HashJoins with full bisection flows on all nodes that have a TableReader for that query. Sadly, this means we are very susceptible to running out of memory, which we still do on large datasets (and sometimes kill nodes as well since the memory accounting guardrails are not in 630757c).

Here is one sample [execution plan](https://cockroachdb.github.io/distsqlplan/decode.html?eJzUls9r2zAUx-_7K8o7baCDZTv9YRhk7LIM1oysPQ0z3PgtMTiWkWVYKfnfR-xBZ6fRd9nrIbnVlT76Pukj8vRElcn5NttwQ8l30qQoJEURKYpJ0YQUXVKqqLZmyU1j7G5aD83yX5QEioqqbt3u36mipbFMyRO5wpVMCd1lDyUvOMvZkqKcXVaUXVBti01mH6dlUXHheEOK5q1LLqYRpVtFpnV_Fn1e6-HxYp016-E6U03pNt2qAyU9021lbM6W8wHfkWjKC_v6lDXrz6aoxtsq-ad7O9Xv3ttite7-IkULrnK2yUUw2trhsl9I_LBaWV5lzowSP87vb--6IN_i-vQ06fPUBE5Spik8PU3heWoCJynTFJ2epug8NYGTlGmKT09TfJ6awEnKNE1OT5O0pKat67LoRvuS9KuWdEY3B5zk692c_9rwofhv919-zORXd8FNbaqGx3IG66WKOF9xv4fGtHbJX61Zdg_C_nPeze6eHjk3rh_VV_3XrOrHdnX9Oy2CtQgOJHQsio78tB7Twd90OICDMRx6YX3jj45Erv20CAauAQxc-2ngGkQD17FX18TveiJyfSly7adFMHANYODaTwPXIBq4vvLquva7vha5vhG59tMiGLgGMHDtp4FrEI1-w_dawNCX9tvW_h6AdOu9LnCUb4DLaGAc0UA5wIFzFI6k7_WCobUYSPc3Ayh9rx0cJ92Py2gkHdBIuh9H0kE4kn5UHw2PxGW0ltGBCI9l4RHA_d1Ug3aqZf1U73WH4Rs9GKWn2ze_AwAA__-Zukx-): as you can see, the planner is planning HashJoins and doing full bisection flows between all the nodes.

```
cockroach@cockroach-navy-0006:~$ time ./cockroach sql --certs-dir=certs -e "set distsql = off; SELECT count(*) FROM tpch.lineitem, tpch.supplier where lineitem.l_suppkey = supplier.s_suppkey;"
+----------+
| count(*) |
+----------+
|  6001215 |
+----------+
(1 row)

real	0m52.902s
user	0m0.032s
sys	0m0.016s
cockroach@cockroach-navy-0006:~$ time ./cockroach sql --certs-dir=certs -e "set distsql = on; SELECT count(*) FROM tpch.lineitem, tpch.supplier where lineitem.l_suppkey = supplier.s_suppkey;"
+----------+
| count(*) |
+----------+
|  6001215 |
+----------+
(1 row)

real	0m13.531s
user	0m0.028s
sys	0m0.020s
```
There is speedup, so the HashJoin, while not the best possible plan for this query, is still a hefty speedup over local execution.

**Comment by arjunravinarayan** [comment]
Closing this issue as we have now empirically evaluated and learned the breadth and limits of our DistSQL processors and the planning. All the credit to @asubiotto, who shepherded this through all those OOMs! 

🎉

**Comment by asubiotto** [comment]
Spun up an azworker with the same specs as navy and ran all of these queries against postgres (TPC-H scalefactor 1). These numbers are from one run only.

| Query | Postgres | CockroachDB (single-node SQL) | CockroachDB (distributed SQL) |
| --- | --- | --- | --- |
| `SELECT MIN(l_extendedprice) FROM lineitem` | 1.582s | 22.028s | 9.520s |
| `SELECT COUNT(*) FROM lineitem` | 0.925s | 36.707s | 12.350s |
| `SELECT AVG(l_extendedprice) FROM lineitem` | 1.839s | 46.255s | 18.560s |
| `SELECT * FROM orders ORDER BY o_totalprice` | 6.063s | 3m51s | 3m34s |
| `SELECT * FROM lineitem ORDER BY l_extendedprice LIMIT 10` | 1.476s | 1m45s | 15.389s |
| `SELECT COUNT(DISTINCT l_suppkey) FROM lineitem LIMIT 1` | 5.234s | 29.891s | 9.481s |
| `SELECT * FROM lineitem WHERE l_extendedprice < 1000` | 1.343s | 49.482s | 12.068s |
| `SELECT * FROM lineitem JOIN supplier ON lineitem.l_suppkey = supplier.s_suppkey LIMIT 10` | 1.247ms | 1860ms | 1240ms |
| `SELECT l_shipmode, AVG(l_extendedprice) FROM lineitem GROUP BY l_shipmode` | 3.548s | 44.103s | 7.799s |
| `SELECT COUNT(*) FROM lineitem, supplier where lineitem.l_suppkey = supplier.s_suppkey` | 2.409s | 52.902s | 13.531s |

cc @petermattis @arjunravinarayan

**Comment by petermattis** [comment]
Thanks, @asubiotto. This will definitely motivate work in 1.1.
