### ISSUE TITLE
distsql: tracking issue for TPC-H queries

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#14295]
This is a list of TPC-H queries that we expect to run using DistSQL. All queries are run with a scale factor of 1 on 6-node navy.

Note: Performance numbers are of a single run. More robust performance numbers will be worked on in the future since the current focus is for the queries to run in the first place.
- [x] [Query 1](https://github.com/cockroachdb/loadgen/blob/65da3bca3a7dde0fbc64a68591f11897c92378aa/tpch/query1.go)
    - [Plan](https://raduberinde.github.io/decode.html?eJzsVm-L2k4Qfv_7FMu8Of25cplNYpKFwsqdpYGqh38otA0lNYsENJFNhJbD716S9GKUdnOHfacQ5NmZfWZ2H5-BfYYkjeQk3MoM-BdAoMCAggkULKBgQ0Bhp9KVzLJUFVsqgh_9AG5QiJPdPi_CAYVVqiTwZ8jjfCOBwyL8vpEzGUZSAYVI5mG8KZvsVLwN1U-xiRMZ53ILFN7Hm1wqTgQi-bo3DHP1jtyh57l9w-0zlxgGL79e-XvHOV_449F8MRw_kU_-4gMpluTzdDICCjOZRGUxjwg0iLCJGBTf_6SDnPPH0YM_Hn4kfSKcLun8JdE9j_aIcLsvxRxi_C4PwYFCus9fdDjQ1ys0XK-VXId5eiaQQKQCi__BfxxNFh2B3SNmBZ4vxx1h1siqkV2jQY2cAj1MlwXbqaNuI-rWUa8RbWI0GkfA5nmQdV-twfHq-yRVkVQyOrl5cHiTShYVaP9TlebL8Tf_D4rU8UqHMlGpcMyw02XZt7YiEsGIMImwjha6J8ItXHRf2RSxRIwINC9x1TxV-fnICexRwXrasngb55ZxblHoKsaZ3VzS4pIWha7CJebNJS0uaVHoKlxi3VzS4pIWha7CJS3PnZnMdmmSybOH5Gm9gIKM1rJ6g2bpXq3kk0pXZfFqOS13l4FIZnmVxWrhJ1WqOFaTjFoyOyHjOZlpyaa-s6k_NtOzLS3b1pPtSy490JIdfWfnks6uluzpO3uXdMYWj7WZ7G0uCw7__QoAAP__RehpoQ==)

| Without DistSQL | With DistSQL |
| --- | --- |
| 1m20s | 50s |

- [x] [Query 3](https://github.com/cockroachdb/loadgen/blob/65da3bca3a7dde0fbc64a68591f11897c92378aa/tpch/query3.go)
    - ~~#14360~~ 
    - [Plan](https://raduberinde.github.io/decode.html?eJzcVF1rGk0Uvn9_xXBuEt9OwNldPzoQGElss6VqUXtRyhI27qkurDsyMwsNwf9eHJu4buxYNYHQuzMfz3Oe8_kAuUywH89RA_8ODCj4QCGAiMJCyQlqLdXqaf0xTH4Cr1NI80VhVtcRhYlUCPwBTGoyBA6fZJoPMU5QAYUETZxmlnuh0nms7oVUCSoNFAaF4UQwKjwqGlS0IVpSkIV5pF7SPzjd-Cpyy4bJlqtoeYSsLM0xNTgvC2tS0XpBVfQo4Texnq3EV4UP-iTDH-ZcsNqlSqczaz2p96jwqQhsZneEsaG_uyezWM-2uQWDaPn2Qx1inqDiRDSJaJH_yTnjnF93r8Je5zO5IKJdIyIgomE_rIy_LuYOcZ3pVOE0NrIi7inDFMLrbn_8W9voa-9ceLXNrV-yg5LdKNnNkt2qve5AvHA8J2R2JJWpllx4F1T475y0zE07ju8y3DXy2a1Odsy7e9S9I5097pdJoY2c29cPaWZs27bIJTnrda5uwn53-O2Mcz4aD8P-x_IOOn1yj1Uub2XybFvXXyVJJ1fk39xIe9L5hjfSDrVD1AuZa6zWZYsvooDJFNcl1bJQE_yi5MSSr48D-9teJKjN-tVbH8LcPrGVrDKYHQD2qmCvCmZlMGOnoH032HfqDrbA9So4cIIb7ow1nOCm23PTCWa-G91yo92624cU60C07wa_d-quu4Nm7v7eo5u5G5x5e5w_a1Jnq0TL_34FAAD__6Tu5tY=)

| Without DistSQL | With DistSQL |
| --- | --- |
| 4m27s | 4m15s |

- [x] [Query 7](https://github.com/cockroachdb/loadgen/blob/65da3bca3a7dde0fbc64a68591f11897c92378aa/tpch/query7.go)
    - ~~#13989~~
    - [Plan](https://raduberinde.github.io/decode.html?eJzcmE9vq0YUxff9FGg2sZup5BnAdpAqjfuStq4ap03yNq2simemDpIDFoylF1X57pVxomBI78mEOJpmh4HDvWf-_A74H5bliZ7Ft7pk0Z9MMM4k48xnnAWMs5DNOVsX-UKXZV5sb9kJpslXFg04S7P1xuxOm9SsNIvYJsuLRBc6YZwl2sTpant9fj_nbJEXmkVPt_6Sp9mljhNd7N3L1kV6Gxd3apVmOjX6lnF2sTGRpwRXPldDrkZcCcHm95zlG9Nq4cuddxOXN_sPVdv75_f81Qb4qzz-HJc3W59Njxczb6X_Nr3-90W6vDG9ft2krHwGlgZ9Jw0q-WhR-f3GTAZcDT_ELNZMij2TAVfhhzEpnjMpH2cyrLblmKsTW7dchY4a5vWJ5Src2r7UWaKLyFNjT514-qsp4oXpHd3puDiKoujq-nI6-4l7atj3VOB96_VEFEWnZ5-m55Nfve88FfZfIG0M4X-PzTO2JstloZexyRu2qpXI1YhxNj09m10_TOPDsawdVxv16vN5TwW1s2HteFg7Hr2821dN0xv76TCyV3lhmotFiWOu5DFX_jH5aEE_-jr-stLPheHqrzJ5JglHZDH5fyj2GPPVQij38s-SILKFj649LTalyW-rq08sf9OuHIiqw-SxYyYPk8dOmHzPPHbDsJt5DGDjWB77HdFYbtbrVdoNjQ-Mf9vGDpEjvgvL_tAwc8Lke8LMDcNuwgzsQsdgFrzni-5rix0SUF17ymKT5hnj7Md0ZaqVJ73pzOsdfZrMJqeT-so5Or_4Y3L-w_T3z2dPp_uUnQ_R6ofFvhMm3xP7bhh2E_tgczqGffA_zaUu13lW6uaM7j1vzplOlnq3GMp8Uyz0b0W-qB6--3lR3V39dZPo0uyuBrsf02x3advWy8XypItahJ1qC1ot6Nr-nlraqSUtlrR43EUtgk61B13UYMx8i4VmKW4sNEt1Y6HZ1ha0OqDVYK3QatA4LfbBZNNqMaTVYVM9qKv3xYOmeEiKR_TOHpHiMV15TIp9SatPSPUAEKkFNCs1QNK4k1yAHEDVuzXvAzVAYje5BGpAB0BzIEc4R9XBFgdyFII0IVDrAIwA6UCOmI6qA6iLFt6sqA7kqHdajbgO5AjsgoazGNGIFDSeAdtFi8_UuNvKwQsnUPsIcrS8Me5teStc7ABPyyHgQXXknZYDQkubb5T2S6vVR4qtHIEGVQegkSBY0acGLUe9g1hGXwvgnQKARrZyeY8U0qdBI1vZZgMa2coHm5cxCeIB7FUgR3sVVe_WPNqrIB6Amk4HtFlowiJOgGxBnAB4R3sNVEfWAZ8RJ2g56h3QHXECRBPghE9_N_mC5oTfohTJifn9N_8GAAD__5nfUK4=)

| Without DistSQL | With DistSQL |
| --- | --- |
| 2m16s | 2m00s |

- [x] [Query 8](https://github.com/cockroachdb/loadgen/blob/65da3bca3a7dde0fbc64a68591f11897c92378aa/tpch/query8.go)
    - Single-node SQL execution time could not be collected due to #14933
    - [Plan](https://raduberinde.github.io/decode.html?eJzcmVFr20gXhu-_XyHmpsm3UzYajZ3UUJBJtFsviVPiLMuymEWNZxODYxlJhpaS_75YTrFlhXmiTqyoe9fGfqz3zEjve87oq5gnEzOM700men8JX0ihhBSBkEILKTpiLMUiTW5MliXp6itrYDD5LHpHUkzni2W--vNYipskNaL3VeTTfGZET1zHn2bmysQTkwopJiaPp7PiIot0eh-nX8LZdG6mubkXUlwu854X-jJUMgxk2JXhsRg_SJEs88cLbH730xfvLs7uyr8Z-mL8MH6Qz5f3WzKd29Ql6cSk2Y62Tk1VyqpqQy_nxeXMpMQXJH3lidI-xNndqrzd0i6H3sz8kx8cvk-nt3f5weHuytesLmhldaH6Vl8YlCoMZKhf9K5qQYV-qUJd_w79wSoMZNiRYfe_UaT_VJFrB9RFnccyPJHhu7qms16gNhYstzZ2JXNT9uPGFjXXLfjH2N4rM5-YtOeZz3ka3-QHb76YOH3T6_VG11eD4a_SC7uHXqi9_3sHfq_XO4tOBxf9c--tF3YOvUoe1sq6YfI2WZRVflMT-t5pfxR5f3yIhl4YeO-9N6f9Yf-sv1HmXRefKS86H0Xe0Za2aHi2-nuxAd8trn97m5rbOE921jFcNSCDs2h4_biAo98vVsbw7V-FuT9-rg-freC79tpJ49ZSh8r72avkbK3lGiVpvnvLhf5P1p_0292p-S18Wvdqxu0ouCkzbke1zZkxPG2va8YgrgEzVu02I1d5N8ssT-6LTzd9ufPYqNrwDO117Gh1hS81drSiyCaTrh0FN5V07ai2uaQDr3zdpANxDSRd4BglizjNhRS_TGd5sWad1TJFp5fDy4s_vY-X54PRh-jMG11H0flm2bZty92VXUvIlovFbOqWhqvH98WF7bmLcJWXmttpMt_efLXa_P5FdDU47T-92-rZN2NbvGmv0dOOgpuKnnZU21z0wAP2utED4hqIHt1ue_xeecnfyaTyZu5orysxj_O1E2-GAedp7uU12b1ft8Ec9vparmUV7mE-bnWFLzUft6LIJpuUdhTcVJPSjmqba1LA51-3SQFxDb-We0LBlckWyTwzu7dF6ffGUpjJrVnfUVmyTG_MxzS5KX58_d_L4tvFyffEZPn600Ct_zeYrz9b6Xo-7WsXWgUudNcF1iDct9IdF1jBittpDWum7LRfolU9OrDDgb1suLSd1sqJtsO6xmbXhBXottMaVrxT59GuSfuwaHZaOSnvusAahHftiwbC7bQPN4udVk7Kj11gDcKP7YsGwu20D9ttp5WT8hMXWIPwk136aJt-V4KPduF3Vtg_stN-Jf7KuA8ZVAmhMq7g6pUcKeEaSvftbk4tC-DUswBOTQvg0LUAjW2LPU_I3AAndwOc7A1w8DegyeB8yFLSDmEKTgE4eRzgYHJAk8v5lWQpe8UxPOwVjy3jJ4DbTRaNrmKz9azGjqPV2HG0GjtOVmOnyWoUzHaw8IBrWHjCga4z3lWHpFrzXV2cen4FMxpd3Y5T1w84tf2Ag9MATY2_graCtENbQXcNtBVu4iEcgaZwVNBWkHZoK2jboa1wEw_hCDSFo6pkaymeVNeebsqerQqyVUG2kkdXstW27XVxH_IJcAWHcICfONGatENbQYd40FZQ6dBW0L7Z8WMnWoP2wO24GnBqyACnhgxwuGmApoYssM_sdIAKbQWd_UJbAR4NOIUj4BCOQFM4BtBWkHZoKyBgAKdwBBzCEWgKx6CSraU7NujY0y2wZ2sA2RrA3ArhGMCRKBkVnInSww6HomRUdpyMCo5FSTuM7LBtkC-0bZDMdlrbj1VhzzUMjvCGDHB6RUY40HaTpJdk4O8kHRwawknXOk-ui9PIDDiNzICDxQJNI7N2O08GnLoCwKkrABy6AqCpK9Bu58mAU1cAOHUFgENXADR1BdqeyxpmXm2feTWcJ-ua58njh__9GwAA__8YBIIC)

| Without DistSQL | With DistSQL |
| --- | --- |
| - | 52s |

- [x] [Query 19](https://github.com/cockroachdb/loadgen/blob/65da3bca3a7dde0fbc64a68591f11897c92378aa/tpch/query19.go)
    - [Plan](https://raduberinde.github.io/decode.html?eJzsl11vmzAUhu_3K6yzi5LJkzAf6WYpkmnDMtaEVKSbJm25YOEsRUohMo60qep_n4A2HyRl61ByRe44xy88dh5b8j0kaYR-eIcZ8G_AgIIBFEygYAEFGyh0YUphKdMZZlkq82FlyIt-AdcpxMlypfLylMIslQj8HlSsFggcbsIfCwwwjFAChQhVGC-KDy1lfBfK32IRJxgrvAMKH-KFQsmJlv-ETb6vdN3EHrE553330hs5ww5x_D5ZN2c9wra7T21mE88n2pnjBWec88lN4PkDSvJnEriDTa2ziVikR8767tD74gZ5-toNJmN_eygZB6SCxow6NsM4GdshOFOvg7P0k8EBhfFKcSIMKmwqulScU8EsKpgN0wcK6Uo9GfRAn3Fro9QqSWWEEqMdoYrk34YcEPRjmN1-SuOk6ufYJwv8qbROT8bzW6XlkwgwiXJBhUneEI1t1o-8JcLq_PNcDmA487nEeajSCsbk80gTrP7VrN2C7RY80hZs6tYylKrilShoL2SYRK9NawvycTbn5fwnI3Ix_rqzBJMRuXQmbrV27Vxe7dWuDq2UJrobbzjnnn_z9NXu-l-xHxvrP3Qb2GbPAo_cPrlwBjskRa0yi7y2h1wU_5-Z6WvoQ9Sm_Sz1cLAHOBzsL_NwsM-c1xogb9Z5LSejwirlrJXSaA-89sA70oFntm61bh3JLat1q3XrSG7ZrVutWye4hx9wK8BsmSYZVu_jO--bUsBojuVVPktXcobXMp0VLy8fx8XoohBhpsouKx-8pGixHGs7zGrDxk5Yr4aN2vD7-rDZBNt6Qdiohu0mX-42CZ83Cb97UXj68OpPAAAA__8HB4oT)

| Without DistSQL | With DistSQL |
| --- | --- |
| 2m10s | 2m15s |

Queries with memory issues:
- [Query 9](https://github.com/cockroachdb/loadgen/blob/65da3bca3a7dde0fbc64a68591f11897c92378aa/tpch/query9.go)
    - Single-node SQL execution time could not be collected due to #14933
    - Running with DistSQL results in OOM (see #15206)

Queries supported by single-node SQL but not DistSQL:
- [Query 15](https://github.com/cockroachdb/loadgen/blob/65da3bca3a7dde0fbc64a68591f11897c92378aa/tpch/query15.go)
    - Cannot be run with DistSQL because this query requires support of `CREATE VIEW` (see #15037)
 
The other queries are not supported by single-node SQL.

**Comment by asubiotto** [comment]
cc @andreimatei @RaduBerinde @arjunravinarayan @knz @vivekmenezes @cuongdo
