### ISSUE TITLE
server/status: debug pages tracking

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#14671]
This is a tracking issue for debug page work.  Note that not all of this will be ready for 1.0 and this list is not exhaustive.

Ranges
- [x] Lease History
- [x] #15932 Range History (splits)
- [x] #15932 Rebalance History
- [x] #15722 MVCC Stats 
- [x] Clean up histories (split the json)
- [x] ~~maybe join lease and log into one~~
- [x] #17433 move to admin ui
- [x] #16583 cleanup top line to combine node, store and replica id
- [x] #9797 Command Queue Details
- [x] #9025 More visibility into rebalance decisions 
- [ ] 1.2 Improve Styling 

Troubled Ranges
- [x] #15291 Unavailable ranges  
- [x] #15291 Leader no leaseholder ranges 
- [x] No Raft Leader
- [x] No Lease
- [x] Under-replicated
- [x] #16414 move to admin ui
- [x] #15342 Better performance when loading 
- [ ] 1.2 Improve Styling

Networking #13984
- [x] Latencies #16174
- [x] Allow specifying only a small subset of nodes #16243
- [x] Allow specifying a locality. #16243
- [x] #16728 move to admin ui
- [ ] 1.2 More stats per node
- [ ] 1.2 A page dedicated to finding nodes without any connections.  
- [ ] 1.2 Save the last error we logged for that connection, etc.

Nodes (#13943)
- [x] #16300 Command line arguments
- [x] #16300 Environment variables
- [x] #16331 IP address
- [x] #16300 Build info
- [x] #16475 move to admin ui
- [ ] 1.2 More stats:
 - CPU count 
 - CPU type
 - RAM capacity and usage
 - Disk capacity and usage

Certificates
- [x] Move to admin ui

Debug Root Page
- [x] Move to admin ui

Queues 
- [ ] 1.2 TBD 

Operations
- [ ] 1.2 TBD 

Gossip/Liveness (#9817)
- [ ] 1.2 TBD

**Comment by BramGruneir** [comment]
All remaining items on this are being moved to 1.1

**Comment by BramGruneir** [comment]
This is old.  Closing.
