### ISSUE TITLE
distsql: document then investigate known limitations in 1.0

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15633]
The following issues have emerged during the lead to 1.0 and need to be documented as known limitations upfront, then later analyzed to determine whether we want to fix them or make them official product features:

- [ ] the new values generated by DEFAULT expressions during `ALTER TABLE ADD COLUMN` use the UTC time zone (e.g. in timestamp-string conversion), regardless of the time zone configured in the session that issued ALTER #15628 
- [ ] the new values generated by DEFAULT expressions during `ALTER TABLE ADD COLUMN` have an empty current database (used e.g. if the DEFAULT expression uses `current_schemas()` and `current_schema()`), regardless of the current database configured in the session that issued ALTER #15628 
- [ ] the new values generated by DEFAULT expressions during `ALTER TABLE ADD COLUMN` use the default search path (used e.g. if `current_schemas()` is used), regardless of the search path configured in the session that issued ALTER #15628 
- [ ] the new values generated by DEFAULT expressions during `ALTER TABLE ADD COLUMN` use the transaction timestamp for `statement_timestamp()`, if that function is used, regardless of the time at which the ALTER statement was issued #15628
- [ ]  the new values generated by DEFAULT expressions during `ALTER TABLE ADD COLUMN` will have `now()`, `current_timestamp()` `current_date()` `transaction_timestamp()`, `cluster_logical_timestamp()`  based on the time of the txn that issued ALTER (this is arguably the expected + correct behavior, and can be mentioned just to clarify instead of as a known limitation) #15628 
- [x] [this is a general limitation, not only when distsql is enabled, but is exacerbated when distsql is used] When mixing CockroachDB nodes in the same cluster that have been compiled with different versions of the `golang.org/x/text` package, and this package contains conflicting collation information, the result of queries that touch/use/modify COLLATEDSTRING columns or string values are undefined. @eisenstatdavid  @tamird - arguably this is a matter of process, we need to absolutely thoroughly scrutinize the changelog of its sub-package `collate` whenever we bump that dependency

(additions to this list are welcome)

**Comment by petermattis** [comment]
The `collate` issue doesn't seem like a known-limitation at this point, but something to pay attention to in the future. @eisenstatdavid we should pin the `golang.org/x/text` dep in `glide.yaml`.

**Comment by cuongdo** [comment]
These all seem to be in https://www.cockroachlabs.com/docs/stable/known-limitations.html
