### ISSUE TITLE
distsql: tracking issue for continuous load tests

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#15775]
This is a tracking issue for the next phase of DistSQL continuous load testing. The goal is to test DistSQL more thoroughly, and eagerly raise any stability issues in DistSQL execution if there are any lurking under the hood.

#14288 was a success in identifying queries to empirically test in DistSQL, and #14295 was a success in identifying which TPC-H queries we could even run. We closed those issues as we got over the finish line for each query, getting them running in individual tests. It's time to step that up and run those queries under continuous, repetitive load on a production cluster, to see if we reveal any additional issues under stress.

The goal is to track two things:
1. That queries that we support do run repeatedly for weeks.
2. That queries that we don't support (e.g. data sets too big to be computed in-memory) fail gracefully without crashing cockroach nodes.

The cluster to be used for continuous load testing is Navy. Load will be monitored by me and @asubiotto. The load generator used will be `loadgen/tpch`.

The queries we will run are those TPC-H that were seen to work previously, namely:
* Query 1
* Query 3
* Query 7
* Query 8
* Query 9
* Query 15
* Query 19

We will initially run it on `scalefactor=5`, expecting success. We will then up the scalefactor until we abort every query due to OOM, to check the abort path works correctly. This issue will track progress on that. The success criterion for closing this issue is a full week of successfully running all these queries in a loop under moderate parallelization (current plan: 5 queries in flight at a time) at some scalefactor X (current plan: 5), and aborting every query (where feasible; some queries simply do not use much memory) gracefully at some higher scalefactor (current plan: 10 or at most 20).

Please pitch in if you think there is something else we should be testing, or if this plan is missing something. cc @petermattis, @cockroachdb/distsql.

**Comment by cuongdo** [comment]
How is the cluster looking?

**Comment by arjunravinarayan** [comment]
The load generator is in a strange state. It was started on navy as follows:

`(./tpch -queries "1,3,7,8,9,15,19" -max-errors=0 -loops 0 -concurrency=5 'postgresql://root@localhost:27183/tpch?sslcert=%2Fhome%2Fcockroach%2Fcerts%2Fnode.crt&sslkey=%2Fhome%2Fcockroach%2Fcerts%2Fnode.key&sslmode=verify-full&sslrootcert=%2Fhome%2Fcockroach%2Fcerts%2Fca.crt' > tpch.log 2>&1 &)`

It finished 5 runs of query 1, and then gracefully OOMed on all 5 runs of query 3:

```
$ cat tpch.log
2017/05/08 19:25:05 [3] finished query 1: 4 rows returned after 155.34 seconds
2017/05/08 19:25:07 [2] finished query 1: 4 rows returned after 156.75 seconds
2017/05/08 19:25:08 [4] finished query 1: 4 rows returned after 157.81 seconds
2017/05/08 19:25:08 [0] finished query 1: 4 rows returned after 157.85 seconds
2017/05/08 19:25:12 [1] finished query 1: 4 rows returned after 161.69 seconds
2017/05/08 19:34:18 [2] error running query 3: pq: root: memory budget exceeded: 10240 bytes requested, 3676091392 bytes in budget
2017/05/08 19:34:39 [1] error running query 3: pq: root: memory budget exceeded: 10240 bytes requested, 3676091392 bytes in budget
2017/05/08 19:34:39 [3] error running query 3: pq: root: memory budget exceeded: 10240 bytes requested, 3676091392 bytes in budget
2017/05/08 19:34:39 [4] error running query 3: pq: root: memory budget exceeded: 10240 bytes requested, 3676091392 bytes in budget
2017/05/08 19:35:30 [0] error running query 3: pq: root: memory budget exceeded: 10240 bytes requested, 3676091392 bytes in budget
```

And then, nothing. The load generator is still running:
```
cockroach@cockroach-navy-0006:~$ ps ax | grep tpch
 9282 pts/0    S+     0:00 grep --color=auto tpch
43526 ?        Sl     0:00 ./tpch -queries 1,3,7,8,9,15,19 -max-errors=0 -loops 0 -concurrency=5 postgresql://root@localhost:27183/tpch?sslcert=%2Fhome%2Fcockroach%2Fcerts%2Fnode.crt&sslkey=%2Fhome%2Fcockroach%2Fcerts%2Fnode.key&sslmode=verify-full&sslrootcert=%2Fhome%2Fcockroach%2Fcerts%2Fca.crt
```

Investigating now. My hypothesis is that this is a bug in the load generator in proceeding after queries error.

**Comment by arjunravinarayan** [comment]
So I got distracted by other issues for a while, but I triaged this to [a bug](https://github.com/cockroachdb/loadgen/pull/51) in the load generator. I've redeployed `tpch` on Navy with the fix.

**Comment by cuongdo** [comment]
As a reminder, let's get continuous DistSQL load as part of 1.1. As we've discussed, one simple way of doing this is to add reads to an existing load generator (I think `photos` makes sense). 

The problem with `tpch` as a load generator is that even with scale factor 1, the fastest query takes ~100 seconds. While this tests reading from tables, it doesn't test flow setup / teardown and all the stuff that goes into a DistSQL query frequently enough. Also, `tpch` uses a static data set. Good for reproducible benchmarks, bad for representative load tests.

**Comment by cuongdo** [comment]
@RaduBerinde do you have additional thoughts?

**Comment by RaduBerinde** [comment]
Yes I think we should add more read queries to `photos` as soon as possible. Longer term, we should also use a mixed-workload benchmark (like the one that combines TPC-C and TPC-H).

**Comment by arjunravinarayan** [comment]
@RaduBerinde do note that mixed-workload benchmark that combines TPCC and TPCH requires that we have TPCC first! There are also complications with mixing those workloads correctly, naively doing it does not work as well (you need to make sure the TPCH query durations overlap with the TPCC updates, which, for instance, the OLTPBench chBenchmark does not do correctly).

I've added a PR (cockroachdb/examples-go#109) to add some analytics queries to `photos`. We can deploy them on a production cluster when that PR is merged, which will improve our DistSQL continuous load test coverage.

**Comment by RaduBerinde** [comment]
Is the `chBenchmark` implemented according to [this](https://research.tableau.com/sites/default/files/a8-cole.pdf) paper?

**Comment by arjunravinarayan** [comment]
I do not know how faithfully the OLTPBench code follows that paper, but the raw code is [here](https://github.com/oltpbenchmark/oltpbench/tree/master/src/com/oltpbenchmark/benchmarks/chbenchmark)

**Comment by arjunravinarayan** [comment]
This is an update comment for testing DistSQL to uncover any issues that may have been introduced by 1.1 features. The biggest surface area to test is external storage, but also buffering of rows, planning of merge joins, and scheduling of DistSQL queries in the presence of downed or version mismatched rows.

The following list tracks various test configurations, along with the feature they are intended to test.

- Test DistSQL under TPC-H at scalefactor 10.
- [ ] Query 1
- [ ] Query 3
- [ ] Query 7
- [ ] Query 8
- [ ] Query 19
- [ ] Test disk space usage with TPC-H query 9, which creates very large working sets. Ensure it gracefully errors out.
- [ ] Test TPC-H under artificially low memory limits to aggressively spill to disk.
- [ ] Test TPC-H under the presence of downed nodes (downed at query start).
- [ ] Test TPC-H under cluster chaos (nodes going down mid-query).
- [ ] Quantify merge join vs hash join speedup, and ensure correctness of output. Get to the point where we can flip the default feature switch to on (not sure we will).

**Comment by arjunravinarayan** [comment]
Attempting to run query 9 uncovered an interesting failure - query 9 on a single node errors gracefully (albeit after creating a gigantic amount of intermediate state, see #17663), but results in a node OOM-kill on a 6 node run on cluster `navy`, due to inadequate memory accounting (see #17594). This memory accounting is only triggered via an invocation of `hashRouter`, which does not occur on a single node.

Nevertheless, the 1 node run is an interesting case to highlight, since on a single node it did successfully create 62 gigabytes of intermediate state without falling over. Apparently external storage works.

**Comment by asubiotto** [comment]
Is this issue still relevant @arjunravinarayan?

**Comment by arjunravinarayan** [comment]
No, this is completed. Thanks for triaging.
