### ISSUE TITLE
distsql: tracking issue for unsupported query subexpressions

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#15793]
This is a checklist for query types and subexpressions that are currently not supported by distsql. We should try to close the gap on some of these in 1.1.
- [x] subqueries #26149
- [x] tuples #15938
- [x] arrays (and ARRAY_AGG) #15939
- [x] outer joins
- [x] HAVING (with aggregation) PR #15796
- [x] FILTER (with aggregation)

**Comment by cuongdo** [comment]
changing to 1.2, as we're not adding new features to 1.1 any more

**Comment by vivekmenezes** [comment]
This is necessary for the merge of the two execution engines.

**Comment by vivekmenezes** [comment]
possible intern project

**Comment by vivekmenezes** [comment]
assigning to abhishek to complete some of this work.
