### ISSUE TITLE
ui: Code Refactoring for improved development experience

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#16112]
This is a tracking issue for an ongoing effort to refactor the Admin UI codebase (located in `/pkg/ui`) in order to provide a better development experience going forward.  There are several motivations; it will pay down organizational debt acquired from rapid UI development over the previous year, it will apply some lessons we have learned during that period that should make future development easier, and it will take advantage of new toolchain features which have recently become available.

A list of planned improvements is below, roughly in order of planned completion.  This list may expand or shrink as my work continues.

In progress:
- [x] Organize '/src' directory structure to be more approachable and predictable.
The current structure of files in the '/src' directory is difficult to follow; this is a result of limited guidance early in the project, combined with many rapid design changes which were not reflected in the file structure. #16250

We will be converting the directory structure based on the principles of BEM's suggested directory structure (one directory per "block") along with the suggested structure Redux (separation of blocks components/containers).

Planned project-wide organizational refactorings: 
- [ ] Update code base to follow the AirBnB React/JSX Style Guide https://github.com/airbnb/javascript/tree/master/react
- [ ] Use available linters to enforce appropriate styles on JSX code
- [ ] Move Stylus code into the `/src/` tree alongside the components to which each style applies.
- [ ] Convert common styling motifs, currently copy/pasted, to Stylus mixins
- [ ] Convert comments to documentation comments (`/** */`) where appropriate

Planned refactorings to specific components:
- [ ] Move "l-columns" layout classes into proper react components.
   Currently, this CSS layout classes are applied directly on DOM elements emitted by container classes. Instead, this should be moved to a set of stateless React components.
- [ ] Rename UIData reducer to "PersistentSettings"
- [ ] Created a type-safe accessor for PersistentSettings, similar to the one used for LocalSettings
- [ ] Refactor file names (and contents of files) in Cluster-related pages, which do not align well with current responsibility.
- [x] Refactor dependencies related to metrics components - there is a dependency chain running from the metrics reducer all the way up through line graphs, and it is exceptionally convoluted. Fix will involve moving components between files, and likely creating at least one new component.

Completed:
- [x] Eliminate warnings / reduce log spew when running UI tests #16039
- [x] Add "test-watch" target to help run tests more rapidly during development sessions #16039
- [x] Remove cross-folder relative imports using Typescript's baseURL #16074

**Comment by jordanlewis** [comment]
Closing due to age (cc @dhartunian)
