### ISSUE TITLE
sql: support features used by Hibernate

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#16491]
There's a number of queries issued by the Hibernate test suite that we don't execute properly or cannot parse (for various different reasons), this issue tracks them as they're found and fixed. This list is incomplete and growing as we find more:

Most important:
* [x] `information_schema._pg_expandarray` - #16971

Mildly more important:
* [x] `time` datatype - #16490
* [x] `CREATE TEMPORARY TABLE ...` - #5807
* [x] Hibernate tries to load `SERIAL` types into an int, which fails if they are too large - `testDirectIdPropertyAccess` -#22607
  * [x]  sql: 32 bit SERIAL type #24062 
* [ ] int/float operations (like `1::int + float::int`) - `testQuotientConversion` -#24063
* [ ] Adding a foreign key without having an index
  * This often doesn't actually result in the tests failing
* [x]  sql: Support ALTER TABLE __ ADD CONSTRAINT __ FOREIGN KEY __ statements #8855 

Mildly less important:
* [x] `ALL` operator with subqueries (rather than just arrays) - `testEqualAll` - #17662
* [x] Sequences - #16445
  * We can disable sequences in a dialect
* [x] Correlated subqueries - `testCollectionIsEmptyCriteria`
* [x] Types besides int8 - `testConstructorResultNativeQuery` - #14493
  * We can remap the names to `int` in a dialect, but just doing this seems to break Hibernate's type inference.
* [x] `current_time` - `testDateTimeFunctions` - #20944
* [x] `SELECT ... FOR UPDATE` - can be worked around via a dialect - #6583
* [x] sql: Implement "ESCAPE" #23538 

Other:
* [x] sql: statement with parameters much slower than with string concatenation #21463
* [x] Run the Hibernate test suite and capture examples of failed queries #24741 
* [x]  sql: use Hibernate's test suite #15821 

Some of them would probably be better to fix in CockroachDB itself (like temporary tables) and some would be better fixed by a custom Hibernate dialect, and some might be infeasible to fix at all at present.

**Comment by cuongdo** [comment]
Can you bucket these by how many tests are failing because of these issues? Perhaps two categories, such as "frequent failure" and "infrequent failure", would be sufficient. I believe this would help the prioritization of these issues.

**Comment by justinj** [comment]
Yeah, sounds good. At the moment I have them roughly sorted by how many failures I estimate they cause (top causing the most), but it's very rough.

**Comment by awoods187** [comment]
Do we need savepoint support for Hibernate?

**Comment by tschottdorf** [comment]
User @Linitha on Gitter ran into the int4/int problem: https://gitter.im/cockroachdb/cockroach?at=5b2a9a626ceffe4eba1d2e24

> Hi everyone
We are planning to move from mysql to cockroachDB. Our app uses Hibernate so I ran first time with hibernate.api.hbm2ddl.auto= create and next time when I run with hibernate.api.hbm2ddl.auto= validate I get the following exception:
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [cancellationReason] in table [api_apple_store_receipt_log]; found [int8 (Types#BIGINT)], but expecting [int4 (Types#INTEGER)]
My entity class have:
private Integer cancellationReason;

**Comment by awoods187** [comment]
cc @knz

**Comment by knz** [comment]
@Linitha @tschottdorf we plan to work on that as #26925.

**Comment by tim-o** [comment]
Zendesk ticket #[2504](https://cockroachdb.zendesk.com/agent/tickets/2504) has been linked to this issue.

**Comment by tim-o** [comment]
*Comment made from Zendesk by Ricardo Rocha on 2019-07-08 at 14:23:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Closing older ZenDesk forum incidents as per Support meeting on 7/2</p></div></blockquote>

**Comment by jordanlewis** [comment]
This feels like it's outlived its usefulness - cc @rafiss @solongordon maybe want to close this one?

**Comment by rafiss** [comment]
Yes we don't need this now. For anyone else looking here, please try out the CockroachDBDialect in Hibernate, and let us know if you have issues.
