### ISSUE TITLE
distsql: use mergejoins

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#16580]
- [x] Detection of existing ordering and using mergejoiner during planning
 Plan mergejonis if provided orderings happen to match on all equality columns. The logic to keep only required orederings needs to be adjusted.

 - [ ] Use of a partial ordering
If we have a matching ordering on a subset of equality columns, we would benefit from a hybrid merge-hash join (use hashjoin across all rows with the same value on the ordered columns). In lieu of this, we could use a sorter to provide the full ordering (the sorter can take advantage of partial orderings).

 - [ ] Take desired ordering into account during index selection
We would want index selection to prefer indexes that give us matching orderings. This is complicated because local SQL doesn't have a merge-join `planNode`, and because we don't support desiring that two plans have the same ordering (we only support desiring of a specific ordering).

 - [ ] Devise a mechanism for merge joiner to bubble upstream information about the next row (e.g. to skip part of a scan)
Longer-term, we want to have feedback from the merge joiner to potentially skip a lot of unnecessary rows from one source. This kind of mechanism can be implemented by table readers and sorters.

CC @arjunravinarayan

**Comment by vivekmenezes** [comment]
assigning richard, he might be able to help out here. Will discuss later

**Comment by RaduBerinde** [comment]
We also need better ordering propagation through merge joins. Currently if we do `t1(k1) JOIN t2(k1,k2) USING k1`, the output ordering is just `k1` (instead of `k1,k2`). This is because the ordering applies to the `joinNode` and local SQL doesn't do merge joins; `k1` is the only ordering we can guarantee if we might do a hash join. CC @richardwu

**Comment by andy-kimball** [comment]
This doesn't sound like a SQL planning issue. Or if it is, it's too broadly defined, since it reads more like distsql planning (which is currently part of SQL execution).

**Comment by RaduBerinde** [comment]
Indeed this is very broadly defined. The optimizer covers some of these points already. Closing.
