### ISSUE TITLE
External storage implementation tracking issue

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#16718]
Original issue outlining the problem: #15206

- [ ] RFC: #16069 
- [ ] implement on-disk storage: #16716 
- [ ] implement using on-disk storage in sorting: #16717 
- [ ] test on-disk storage on sorting queries using TPC-H scalefactor-10 data
- [ ] implement using on-disk storage for hash joins
- [ ] test on-disk storage on TPC-H scalefactor-10 JOIN queries
- [ ] test on-disk storage under chaos
- [ ] consider implementing on-disk storage for other processors/sorters as well.
- [ ] Optimize RocksDB flags for the local RocksDB instance.

**Comment by arjunravinarayan** [comment]
I tested it the current candidate head of #16717 (88f44bd) on Navy (6x Azure D3_v2), with a somewhat contrived query designed to force sorting of all rows (but not rendering the complete result, since we want to isolate the OOM on the query processing, but not the final rendering):
`SELECT count(*) FROM (SELECT * FROM tpch.lineitem ORDER BY l_orderkey, l_partkey, l_suppkey, l_linenumber, l_quantity, l_extendedprice, l_discount, l_tax, l_returnflag, l_linestatus, l_shipdate, l_commitdate, l_receiptdate, l_shipinstruct, l_shipmode, l_comment LIMIT 1000)`. I used TPCH Scale-Factor 10 data.

The generated query plan is [here](https://cockroachdb.github.io/distsqlplan/decode.html?eJzUlk-L2zAQxe_9FMucWjQFj_8l8WlKTwslKdktPZRQ3HgwhsQysgItS757kX3YJjTyLmbBvhgkzfP7-ekd_AS1LmSdH6WF7AcQIISAEAFCDAgJIKSwQ2iM3kvbauPGetF98RuyAKGqm5N12zuEvTYC2RPYyh4EMnjMfx1kK3khBhAKsXl16IwaUx1z84cPVS2VlSMgbE42u2NCDpEj5Bg5QU6RF8hL5BUyBchEyBQiU4RMMTIlyJTC7oygT_YZpLV5KZDRGV8O-6CNveZkUsihQo4UcqyQE4WcKuSFQl4q5JVyYO7hJsmNkpslN0xumlIFCF-qY2XvKAiCm7DhBSzNKdkB2GklG84p2QHYaSUbzSnZAdhpJRvPKdkB2Gklm8wp2QHY6Sb7zKhNIUaKN4Hcnf8Tylp_1M2lXXdRL_uk6DX5fypLI2Vu9dUdfN58Wz_-3G6-P7z_cNMpfo3TVtpG161c-Nx6c-BikaKU_iZafTJ7-Wr0vvsl6pebTtdtFNLa_pT6xX3dHznAf8XkF4cXarpWh1515LeORlnHXnXit05GWade9cJvvRhlvfSqV37r1ShrGujZUNHGNY38VaOBrtFA2eIr-e787m8AAAD__3go-b8=).

Running this with external storage disabled (using the cluster setting in that SHA) resulted in an OOM after ~45 seconds:
```
Error: pq: root: memory budget exceeded: 10240 bytes requested, 3676091392 bytes in budget
Failed running "sql"

real	0m45.893s
user	0m0.032s
sys	0m0.024s
```

Running this with external storage enabled resulted in the query completing after ~6 minutes:
```
+----------+
| count(*) |
+----------+
| 59986046 |
+----------+
(1 row)

real	5m47.287s
user	0m0.044s
sys	0m0.140s
```

**Comment by petermattis** [comment]
@arjunravinarayan Given the `LIMIT 1000` on the inner select, why is the `count(*)` returning `59986046` instead of `1000`?

**Comment by arjunravinarayan** [comment]
That's a typo (I also ran the limit version to check something else - that the topK sorter wasn't OOMing). There isn't a limit. The query run was
`SELECT count(*) FROM (SELECT * FROM tpch.lineitem ORDER BY l_orderkey, l_partkey, l_suppkey, l_linenumber, l_quantity, l_extendedprice, l_discount, l_tax, l_returnflag, l_linestatus, l_shipdate, l_commitdate, l_receiptdate, l_shipinstruct, l_shipmode, l_comment);`

**Comment by arjunravinarayan** [comment]
This is a (frequently updated) tracking comment for all the RocksDB tuning parameters/optimizations to consider for the local RocksDB engine once the basic features are built:
1) Tweak `MaxOpenFiles`.

**Comment by asubiotto** [comment]
1.1 testing is tracked in this issue: #15775
