### ISSUE TITLE
sql: support Hibernate's use of _pg_expandarray

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#16971]
Adding an index to a table in Hibernate issues a query which makes use of this. Note that supporting this also means that we would need to support record types. The query below should work, if this is implemented:

```sql
SELECT (i.keys).n FROM (SELECT information_schema._pg_expandarray(indkey) AS keys FROM pg_index) AS i;
```

This function takes an array `a` and returns a set of records that looks like the following:
```
 x   |  n
----------
a[1] |  1
a[2] |  2
a[3] |  3
a[4] |  4
...
```

The work is to be decomposed as follows:

- [x] support the set-generating function `information_schema._pg_expandarray` #24422
- [x] support simple labeled tuple access
  - [x] add tuple labels #25283
  - [x] access different columns in SRF #24832 
- [ ] support in-flight composite types #24866.
  - [x] propagate labels during typing, including subqueries #26621
  - [ ] labeled tuple serialization bug #26624.
  - [ ] labeled tuples in distsql #26627.
- [ ] verify that all the complex queries listed here and in the `srfs` logic test file work properly
  - [ ]  add pg_get_indexdef with 3 arguments #26629
  - [ ] fix the column pg_index.indclass #26504

**Comment by petermattis** [comment]
@justinj Supporting record types looks to be a sizable project. Is that accurate? Or can this somehow fallout of the existing system easily?

Cc @knz

**Comment by justinj** [comment]
I haven't investigated too deeply, but if we only support the result-value type then I suspect it's not *too* bad. My guess would be that the most difficult part would probably be handling the `.` operator in a way that was insulated from name resolution.

**Comment by knz** [comment]
It's definitely a mid-size project, and somewhat larger than implementing arrays as result-value type.

**Comment by jordanlewis** [comment]
I just realized that this is more difficult than we thought. Not only do we need to support (or at least pretend to support) record types, we also need to support generator functions in render positions, which we currently don't support at all.

See #13156 for more context.

**Comment by jordanlewis** [comment]
To be more clear, this is in all reality blocked on correlated subquery support as well!

**Comment by knz** [comment]
Looking at this briefly on @awoods187's request. Resolution here requires support for record types in in-memory values (datums or whatever will replace them), not db encoding for them (i.e. we don't need to store them). Analogous to the same distinction we used when array support was first implemented.

**Comment by petermattis** [comment]
@jordanlewis Is the query that hibernate issues identical to the use of `_pg_expandarray` on other ORMs? Or are there minor syntactic differences. I'm wondering if we can do something even simpler (re: more hacky) than in-memory support for the record type.

**Comment by jordanlewis** [comment]
They're not all identical. Sometimes they occur in the context of larger queries. Here's another example:

```
        SELECT
            indexrelid,
            (information_schema._pg_expandarray(indclass)).x AS operator_argument_type_oid,
            (information_schema._pg_expandarray(indclass)).n AS operator_argument_position
        FROM
            pg_index
```

The only thing we really need to support for this "indexing into" the `_pg_expandarray` function with the `.x` syntax, for the `x` and `n` fields.

**Comment by knz** [comment]
Bram and I had an offline discussion and Bram discovered this item has two aspects to it: 

- implementing `_pg_expandarray`. Surprisingly (to me) this is merely a SRF, like the others we already support.
- implementing the notation `E.x` when `E` is a SRF call; this is surprisingly simply a notation to access the column `x` in the table produced by migrating `E` to the FROM position. This is a natural extension of the `x.y` column notation and has nothing to do with record types. (I had a "mind blown" moment when I realized the consequences of Bram discovery)

**Comment by knz** [comment]
@awoods187 this does mean this item is _much_ easier to implement than what we initially thought, it downgrades it from M-L to S.

**Comment by awoods187** [comment]
I'll update to a S and am excited to see the results.

**Comment by BramGruneir** [comment]
I just wanted to add a bit here, there are 3 parts that are required to support the statement above and 
be able to close this issue.

[ ] Implement the `information_schema._pg_expandarray` as a Set Returning Function (SRF). 
[ ] Add the ability to use the `.` notation to access a table produced from the migration of a SRF to the FROM position.  See @knz comment above for more details.
[ ] Mock the `pg_index.indkey`.

**Comment by jordanlewis** [comment]
`pg_index.indkey` is already implemented - was there something else you needed from it?

**Comment by BramGruneir** [comment]
Hmm...

This works:
```sql
+---------+
| indkey  |
+---------+
| 1 2     |
|       1 |
|       1 |
|       1 |
|       1 |
| 1 2 4 3 |
| 1 6     |
| 1 7     |
|       1 |
|       1 |
| 2 3     |
|       1 |
|       5 |
|       4 |
| 1 2     |
| 1 2     |
| 1 2     |
|       1 |
|       2 |
+---------+
(19 rows)
```

But this doesn't (in my branch with _pg_expandarray working):
```sql
SELECT information_schema._pg_expandarray(indkey) FROM pg_index;
pq: column name "indkey" not found
```

And even this doesn't work:
```sql
root@:26257/system> SELECT unnest(indkey) FROM pg_index;
pq: column name "indkey" not found
```

**Comment by jordanlewis** [comment]
Yeah, our name resolution can't handle this case at the moment.

**Comment by BramGruneir** [comment]
Ok, I'll update that checklist for this case.

**Comment by knz** [comment]
From #24713 - this will need to be tested

```sql
SELECT NULL AS table_cat,
       n.nspname AS table_schem,
       ct.relname AS TABLE_NAME,
       NOT i.indisunique AS non_unique,
       NULL AS index_qualifier,
       ci.relname AS index_name,
       CASE i.indisclustered
         WHEN TRUE THEN 1
         ELSE CASE am.amname
           WHEN 'hash' THEN 2
           ELSE 3
         END
       END AS TYPE, 
       (i.KEYS).n AS ordinal_position,
       trim(BOTH '"' FROM pg_catalog.pg_get_indexdef(ci.oid, (i.KEYS).n, FALSE)) AS COLUMN_NAME,
       CASE am.amcanorder
         WHEN TRUE THEN CASE i.indoption[(i.keys).n - 1] & 1
           WHEN 1 THEN 'D'
           ELSE 'A'
         END
         ELSE NULL
       END AS asc_or_desc,
       ci.reltuples AS CARDINALITY,
       ci.relpages AS pages,
       pg_catalog.pg_get_expr(i.indpred, i.indrelid) AS filter_condition
FROM pg_catalog.pg_class ct
JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid)
JOIN (
  SELECT i.indexrelid,
         i.indrelid,
         i.indoption,
         i.indisunique,
         i.indisclustered,
         i.indpred,
         i.indexprs,
         information_schema._pg_expandarray(i.indkey) AS KEYS
  FROM pg_catalog.pg_index i
) i 
  ON (ct.oid = i.indrelid)
JOIN pg_catalog.pg_class ci ON (ci.oid = i.indexrelid)
JOIN pg_catalog.pg_am am ON (ci.relam = am.oid)
WHERE TRUE
  AND n.nspname = 'public'
  AND ct.relname = 'act_de_databasechangelog'
ORDER BY non_unique,
         TYPE,
         index_name,
         ordinal_position
```

**Comment by knz** [comment]
Another test query from https://github.com/metabase/metabase/issues/5050

```sql
SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM, ct.relname AS TABLE_NAME, a.attname AS COLUMN_NAME, (i.keys).n AS KEY_SEQ, ci.relname AS PK_NAME FROM pg_catalog.pg_class ct JOIN pg_catalog.pg_attribute a ON (ct.oid = a.attrelid) JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid) JOIN (SELECT i.indexrelid, i.indrelid, i.indisprimary, information_schema._pg_expandarray(i.indkey) AS keys FROM pg_catalog.pg_index i) i ON (a.attnum = (i.keys).x AND a.attrelid = i.indrelid) JOIN pg_catalog.pg_class ci ON (ci.oid = i.indexrelid) WHERE true AND ct.relname = 'sometablename' AND i.indisprimary ORDER BY table_name, pk_name, key_seq
```

**Comment by knz** [comment]
Oops, no this is not done yet
