### ISSUE TITLE
distsql: analytics queries performance tracking issue

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#17382]
This is a tracking issue for Analytics query performance, including but not limited to TPC-H.

So far we've been using the TPC-H queries that run on CockroachDB to benchmark our ability to run large queries. However, we only successfully run (at all) queries 1,3,7,8,9,19, and that's what we've been using so far in testing performance, on larger and larger datasets. 

It is time to break this down into more concrete subtasks, and write more queries that test CockroachDB in smaller incremental chunks, and with wider feature coverage. The TPC-H queries that we do run are big chunks. We want additional queries that test more query plans (e.g. Joins with and without convenient secondary indices so that we test both merge and hash joins).

In the longer run, we also want to build up the features that are required for all the queries. Here is an initial probe on what the TPC queries do 

- [ ]  Q1 - Table scan, arithmetic expression, and aggregation performance.
- [ ]  Q2 - Correlated subquery performance. Unsupported (#3288)
- [ ]  Q3 - Latency to produce initial results
- [ ]  Q4 - Rewriting sub-query away
- [ ]  Q5 - Join order
- [ ]  Q6 - Low selectivity
- [ ]  Q7 - Complex join filter pushdown
- [ ]  Q8 - CASE expression performance
- [ ]  Q9 - Performance of joins with large result sets
- [ ]  Q10 - Dependent group-by keys
- [ ]  Q11 - Complex having predicate performance
- [ ]  Q12 - Detecting column correlation
- [ ]  Q13 - Rewriting LIKE into a range and outer join performance
- [ ]  Q14 - Special case of rewriting LIKE
- [ ]  Q15 - View or common table expression performance
- [ ]  Q16 - String matching performance
- [ ]  Q17 - Correlated subquery performance
- [ ]  Q18 - Join and semi-join performance
- [ ]  Q19 - Complex predicate performance
- [ ]  Q20 - Multiple levels of nested subqueries
- [ ]  Q21 - Join, semi-join, and anti-join performance
- [ ]  Q22 - Large in clause performance

As you can see, Query 5 (Join Ordering) is already a big step - we want incremental queries (5.1: merge joins, 5.2: hash joins?) that just test a single large JOINs performance.

I propose we augment our current TPC-H load generator with some non-standard queries (clearly marking them as such) and add those to our regular testing cycle.

We should also concretely test our query plans versus the plans produced by Postgres, to see what optimizations we are not yet considering.

cc @petermattis @albler.

**Comment by albler** [comment]
Arjun,

Thanks for setting this up. If I may make a suggestion, I wouldn't extend this set of queries.

What I'd do instead is treat this is as... a query set, the first one. But there may be others. The reason I'd so this is that you guys may wish to collect and maintain important sets like this along the way, be it from strategic clients, from other benchmarks or, as you mention, for specific features testing. 

It is very convenient to keep these sets as units.

Now, there is a bit of tooling to build around this. To extract useful information from a unit we need to do 
+ Data generation
+ Database setup (creating the proper schema, loading the data, and updating the stats)
+ Instrumented run (to the very least an 'explain')
+ Comparison to expected results

About this latter, there could be qualitative results (the plan we use after a modification is better than the one before) or quantitative (the query runs faster) -- hopefully both. And, as you mention, running agains another database is very, very useful.

I will mention that, besides Postgres, SQL Server now also has a Linux version, too. And so does IBM DB2. They will smoke Postgres without breaking a sweat -- every single time. So you might as well look beyond Postgres... I am very comfortable setting up any -- or both -- of these with you and walking you through the ropes of how to operate them, including programmatically. 

cc @arjunravinarayan @petermattis

**Comment by arjunravinarayan** [comment]
Cc @andy-kimball

**Comment by jordanlewis** [comment]
This is pretty covered by sql-20 and recent work to track TPCH perf by @asubiotto.
