### ISSUE TITLE
umbrella issue for cluster version migrations

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17659]
- [x] Acceptance testing.
- [x] Update the RFC.
- [x] Pave the way for future use of `UseVersion < MinVersion`, if still required.
- [x] Migration that makes sure there's always a cluster version settings able
entry #17389, disallow version bump if settings table has no value entry?
- [ ] Consider removing the reliance on gossip callback ordering. Gossip does
      not *guarantee* that version updates arrive in-order, and we currently
      persist the cluster version blindly. `*ExposedClusterVersion` would
      have to do its own synthesis to refuse illegal changes backwards. This
      may be a non-issue but needs some consideration (all of the cluster
      settings would be vulnerable to it).
- [ ] gossip more. We currently gossip `ServerVersion` but really you care more about the version the server is operating at (i.e. `ServerVersion` will be 1.1 even if the binary is still running in compat mode for 1.0).

RFC: https://github.com/cockroachdb/cockroach/pull/16977

**Comment by tschottdorf** [comment]
I'll call this done, but we could do more.
Filed https://github.com/cockroachdb/cockroach/issues/18058 which covers the last item.
Also filed https://github.com/cockroachdb/cockroach/issues/18060 about ui warnings.

I have not been able to confuse the gossip callback ordering, so I think that's more of a theoretical concern. The worry here is

1. node receives bump to 1.0-2
1. fires goroutine with callback
1. node receives bump to 1.0-3
1. fires goroutine with callback
1. second callback executes
1. first callback executes

in this case, the version statemachine would see two bumps that are each illegal. I can't promise it, but I definitely suspect that it would panic the server. If it doesn't, that's almost as bad because the server likely won't operate at the desired version (`1.0-3`).
