### ISSUE TITLE
storage: re-enable stats-based rebalancing

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#17979]
#17968 disabled stats-based rebalancing because of unresolved issues under certain situations.

Re-enabling it wil involve:
- [x] Fix behavior under splits without load (found while testing `sky`)
- [x] Fixing storage: stats-based rebalancing can't handle large numbers of splits and scatters #17671
- [x] Fixing storage: Delayed update of per-store write stats can cause rebalance thrashing #17970 
- [x] Fixing storage: Consider which replica will be removed when adding a replica to improve balance #17971
- [x] Fix the success criteria for the nightly allocator tests. Stats-based rebalancing means that we're no longer balancing just range counts, so the nightly allocator tests need a different set of metrics to measure. #17685
- [x] Ideally, introducing an allocator acceptance test (a CI acceptance test rather than a nightly) that tests the allocator's behavior in various situations.

**Comment by a6802739** [comment]
@cuongdo  I wonder if I could offer some help here for this part? :)

**Comment by nvanbenschoten** [comment]
@a6802739 I personally haven't gotten involved in the work that needs to be done here, so any help you could provide would be appreciated 😃 @a-robinson can speak more towards this, but I think addressing #17671 might be a good place to start.

**Comment by a6802739** [comment]
@nvanbenschoten , Great, Thank you very much.

**Comment by a-robinson** [comment]
@a6802739 help in this department would be very much appreciated. All of the numbered issues from the original post (#17671, #17970, or #17971) would be good tasks to try out, with #17671 being the most open-ended of the bunch.

**Comment by a-robinson** [comment]
Note for future me: running `./kv --sequential` with a reasonable `block-size` setting (e.g. `--min-block-bytes=256 --max-block-bytes=257`) would make for a good test -- it does a great job of imbalancing the amount of bytes and qps on each node.

<img width="1313" alt="screen shot 2018-01-31 at 5 20 49 pm" src="https://user-images.githubusercontent.com/7085343/35650741-24b210b4-06ab-11e8-9f85-e3efbf0e3e59.png">
<img width="981" alt="screen shot 2018-01-31 at 5 21 02 pm" src="https://user-images.githubusercontent.com/7085343/35650749-2e429b94-06ab-11e8-8690-99863b8f1441.png">

**Comment by a-robinson** [comment]
Fully implemented as of https://github.com/cockroachdb/cockroach/pull/28852 and all known issues from the previous version of stats-based rebalancing have been taken care of. This just needs some adversarial testing from someone other than me, ideally to improve `RelocateRange` (https://github.com/cockroachdb/cockroach/issues/29130 / https://github.com/cockroachdb/cockroach/pull/29684), and to flip the setting to default on.

**Comment by a-robinson** [comment]
The new feature is controlled by the `kv.allocator.load_based_rebalancing` cluster setting, which defaults to "leases" but would have to be switched to default to "leases and replicas" to enable load-based rebalancing of replicas by default.

**Comment by nvanbenschoten** [comment]
All of the work has been done here, but stats-based rebalancing is still disabled by default. Moving the remaining item of switching it to enabled by default to 2.2.

**Comment by a-robinson** [comment]
Done by https://github.com/cockroachdb/cockroach/pull/30589 / https://github.com/cockroachdb/cockroach/pull/30649
