### ISSUE TITLE
core: refactoring projects

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#18779]
This is a master list for core refactoring work. The theme is breaking up the massive `storage` package. Separate GitHub issues should be created as work or discussion begins on an item.

Ideas:

- [ ] Break apart the larger types, like Replica.
  - [ ] Remove unrelated stuff from Replica.
- [ ] Simplify Pre-Raft / Raft flow.
- [ ] Add explicit instructions, such as bumping the transaction timestamp, that KV layer can send to `TxnCoordSender`. This would add grepability and understandablity.
- [ ] Pull queues and caches into their own package.
- [ ] Pull node liveness out of storage.
- [ ] Centralize split code.
- [ ] Add file-level comments that describe the general purpose and scope of that file.
- [ ] Move `RaftTransport` out of `storage`
- [ ] Move `raftScheduler` out of `storage`
- [x] #18784: Move evaluation of `BatchRequest`s to a separate package
- [ ] Enforce lock ordering, preferably programmatically

As you start to work on items, please put your name or GitHub id next to the task to claim it.

**Comment by a6802739** [comment]
@cuongdo, could I have a try for this part?

**Comment by petermattis** [comment]
@a6802739 The above checklist is a grab bag of refactoring ideas, not all of which may pan out. Give us some time to make a bit of progress on the margins and get a better feel for what the refactoring will look like. I'm sure there will be some tasks that emerge for you to tackle.

**Comment by a6802739** [comment]
@petermattis, Thank you very much.

**Comment by a-robinson** [comment]
Also, as suggested in https://github.com/cockroachdb/cockroach/issues/18657#issuecomment-334758036: remove the locking of `Replica.raftMu` in `Replica.propose`

**Comment by tschottdorf** [comment]
https://github.com/cockroachdb/cockroach/pull/19133 has some more abstract refactoring ideas on how to make the "non-raft" portion of Replica clearer.

**Comment by tschottdorf** [comment]
Closing as there isn't anything very specific left here.
