### ISSUE TITLE
distsql: tracking issue for performance improvements

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#19134]
Starting a task list for distsql performance. Please add stuff you think of.

### Infrastructure improvements ###
- [ ] remove type information from `EncDatum`
- [ ] design a more efficient way to pass around datums (#8792)
- [x] change the infrastructure to allow sending and processing groups of rows instead of one row at a time
- [x] investigate a better interface for processors to allow running "synchronously" or fusing multiple processors in a single goroutine

### Evaluation ###
- [x] benchmarks for infrastructure:
  - [x] local streams
  - [x] inter-node streams
  - [x] post-processing
  - [x] processors
- [x] gather peformance data for a group of simple queries on TPC-H dataset for 1.1

**Comment by asubiotto** [comment]
Closing because this seems like a stale issue. We've:
- added benchmarks for all infrastructure pieces as well as devised a group of queries in `pkg/workload/querybench` for evaluation.
- `RowSource`ified all important processors: https://github.com/cockroachdb/cockroach/issues/21220
- Investigated batching: https://github.com/cockroachdb/cockroach/issues/20555
- Discussed alternative representations to EncDatum/EncDatumRow https://github.com/cockroachdb/cockroach/issues/21523

The last bullet is the pending item of work but will be addressed in the 2.2 timeframe and the linked issue captures more information.
