### ISSUE TITLE
distsql: tracking issue for feature parity gaps

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#19320]
There are certain queries which either can't run at all in distsql, or which we never run in distsql because they can be much less efficient. Closing on these gaps is a pre-requisite to unifying the two SQL execution paths.

- [x] support tuples in streams (#15938)
- [x] support ordinality node
- [ ] support internal tables (e.g. TRACE)
- [x] support SHOW TRACE FOR (#16562)
- [x] support ARRAY_AGG (#15939)
- [x] support set operations (#10432)
- [ ] more efficient limits ([RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170602_distsql_limit.md))
- [x] support subqueries
- [x] support distsql operations in a write txn (#13376)
- [x] support writing to tables (from the gateway node) using results from a distsql query
- [x] support window functions (#24425)
- [ ] support `spool`
- [ ] support batching (at least for mutations)

We also have a bunch of planNodes which implement various internal statements: split, scatter, set cluster settings, cancel query, show ranges, alter table, copy from, etc.  These are all written in the local SQL framework and would need some kind of refactoring.

I'm likely missing a few so please add more if you think of anything. CC @andreimatei @knz @petermattis @vivekmenezes

**Comment by petermattis** [comment]
Cc @awoods187

**Comment by jordanlewis** [comment]
Closing this. I don't think it's useful anymore.
