### ISSUE TITLE
sql: Support 'COMMENT ON ...' for tables, columns and other objects

### ISSUE THREAD

**Issue by flokli** [cockroachdb/cockroach#19472]
Postgres docs on `COMMENT ON`: https://www.postgresql.org/docs/current/static/sql-comment.html

- [x] ~`COMMENT ON TABLE` #32442~
- [x] `COMMENT ON ` for table columns #32965
- [x] `COMMENT ON DATABASE` #33057
- [ ] `COMMENT ON ` schemas

**Comment by dt** [comment]
Huh, interesting. Thanks for isolating the issue and including an example of it used in the wild!

Indeed, cockroach doesn't currently support that syntax, or indeed store any sort of table or column comments or plain-text descriptions.
Full postgres docs: https://www.postgresql.org/docs/current/static/sql-comment.html

@knz it seems like it this shouldn't be too hard to add and may improve some off-the-shelf ORM/app compatibility (based on that example). Seems like a decent SQL starter project?

**Comment by knz** [comment]
Yep!

**Comment by ZacharyThomas** [comment]
Going to try and look at this if nobody else is. PG lets you comment on nearly everything. Would we want to adopt that approach here, or should I focus only on tables? 

It also looks like PG stores this in two new tables by oid. It seems a little more complicated than I initially would have thought but I'll give it my best shot. Do ya'll see any obvious gotchas with that approach?

**Comment by knz** [comment]
Hi @ZacharyThomas !
Thank you for wanting to help here.
In the initial implementation we recommend that you modify CockroachDB to recognize the comment syntax but just ignore it and not store the comments anywhere. 
Storing the comments and providing an interface to retrieve them would be a much significant undertaking and I wouldn't recommend it as a starter project.

**Comment by knz** [comment]
So thanks to #21063 CockroachDB 2.0 will have minimal support for this syntax. @flokli it would be great if you could indicate whether this is sufficient to enable compatibility with Drupal. Otherwise, please create new issue(s) as appropriate and link them to #22211.
Thank you!

**Comment by awoods187** [comment]
It looks like this is actually not supported yet so I'm reopening it

**Comment by BramGruneir** [comment]
Let's not forget that there are a ton of objects that can have comments on them:
https://www.postgresql.org/docs/9.1/sql-comment.html

Let's make sure that any work towards this is extensible.

Also, we should populate this and any other internal tables: https://www.postgresql.org/docs/9.6/catalog-pg-description.html

**Comment by bithavoc** [comment]
@hueypark are you going to work on the `system.comments` approach?

**Comment by knz** [comment]
@bithavoc yes it is being done in a new update to #32442.

**Comment by jordanlewis** [comment]
This is done but for schemas which we don't support anyway - closing. Thanks again @hueypark.
