### ISSUE TITLE
clusterviz: milestone tracking

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19513]
Tracking issues for the different components we want to ship, by monthly milestone (have dates by request from @cuongdo)

**Milestone 1 - ~11/22 pre Thanksgiving** 
- [ ] Adding system table to track lat / long (or however we want to do this) https://github.com/cockroachdb/cockroach/issues/19532
- [ ] Placing nodes and aggregated localities on points in a canvas or map
- [ ] CCL implementation
- [ ] Cluster overview tab
- [ ] Cluster overview view for OSS

**Bucket for next milestone**
- [ ] More stats (bubbles) - CPU%, replicas, Mem%, QPS, Uptime per node
- [ ] Warning messages as users hit too many nodes
- [ ] Check boxes to display more metrics on the node canvas
- [ ] Node join event
- [ ] Node decommissioning event
- [ ] Node dead event
- [ ] Clean loading states
- [ ] Notifications by locality
- [ ] Hover over network view
- [ ] Network bandwidth in / out
Design needs (post-some prototyping):
- [ ] Aggregated view with groupings (different from what we have now)

**Comment by dianasaur323** [comment]
Hopefully this feels less prescriptive to everyone. Feel free to comment and adjust to make it more helpful to you.

cc @mrtracy @kuanluo @cuongdo @spencerkimball @couchand @vilterp

**Comment by dianasaur323** [comment]
ah, definitely closing this. not relevant anymore.
