### ISSUE TITLE
sql: sequences (tracking issue)

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#19723]
DEPRECATED TRACKING ISSUE IN FAVOR OF PROJECT: https://github.com/cockroachdb/cockroach/projects/13

Original issue: #5811 
RFC: #19196 
Docs issue: https://github.com/cockroachdb/docs/issues/2014

The implementation will be split into multiple PRs; this issue tracks them.

- [x] Implement `CREATE SEQUENCE` and `nextval` (biggest; others depend on this) (#19664)
- [ ] implement `setval(seqname, val, iscalled)`
- [x] Don't evaluate `DEFAULT` expressions on table create (#20031)
- [ ] Respect the `MINVALUE`, `MAXVALUE`, and `CYCLE` settings (#20574)
- [x] `pg_class` fixes (#20282)
- [x] `information_schema.sequences` entries and `pg_sequence` (#20111)
- [x] Implement `DROP SEQUENCE` and `ALTER SEQUENCE` (#20089)
- [x] Implement additional builtin functions (`currval`, `setval`, `lastval`) (#20306)
- [ ] enforce permissions in builtins (e.g. can't call `nextval` without write permissions)
- [ ] implement `ALTER SEQUENCE ... RESTART WITH x`
- [ ] Add dependency relationship between sequences and the columns that use them (protecting a sequence from being dropped if it's in use); implement `OWNED BY`
  - [ ] `DROP TABLE CASCADE`, `DROP SEQUENCE CASCADE` (what does PG do here?)
- [ ] Make sequences work in load/dump and backup/restore (#20725)
- [ ] Ensure that sequences work with zone configs (so an operator can control locality of a sequence)
- [ ] teach UI about sequence event types
- [ ] use regclass instead of string as argument to sequence functions
- [ ] update the RFC to say "complete"
- [ ] add Hibernate test to https://github.com/cockroachdb/examples-orms

**Comment by lego** [comment]
Found usage of `setval(string, int, bool)` that isn't postgres backups :'(.

It is called in ActiveRecord's [PostgreSQL adapter](https://github.com/rails/rails/blob/9f33a8f06e5bba343b0d108a41246ab8368d71d3/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L275-L301).

It does seem to be special case thing that I only encountered it because of running the ActiveRecord test suite against CockroachDB. So no need to take this as a reason to implement it.

(The specific error was `PG::UndefinedFunction: ERROR:  unknown signature: setval(string, int, bool)`, in case anyone searches and finds this issue -- please comment or upvote this comment if you did run into this!)

**Comment by vilterp** [comment]
Filed as https://github.com/cockroachdb/cockroach/issues/20410
