### ISSUE TITLE
security: encryption at rest

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#19783]
This issue tracks the status of encryption-at-rest. Comments and reviews should be done on the individual PRs or in separate issues.

Approximate breakdown of work to be done (not complete, order may change):
- [x] finalize RFC #19785
- [x] add crypto++ dependency #19827
- [x] upgrade rocksdb to 5.9 #20070
- [x] add CCL-only encryption flags #20225
- [x] add support for switching env (plaintext only) #20225
- [x] pass CCL encryption options through to libroachccl #20570 
- [x] add store key manager #20670 
- [x] add data key manager #21150
- [x] add file registry #21580
- [x] add encrypted env #21580
- [x] perform actual encryption #21580
- [x] use encryption for all local disk usage (non-logs) #25281 #25591 #25806 #27075
- [x] calculate/report encryption status (debug/status page/monitoring) #25850 #26040 
- [x] calculate/report encryption progress (number and size of files) #26802 #27388 #26890
- [x] live key rotation (not just at startup) #28148
- [x] tooling support (debug commands) #26477, #35234
- [ ] metrics #35506
- [ ] benchmarks
- [x] draft docs https://github.com/cockroachdb/docs/pull/3193
- [x] QA: #21880
  
Tracking of misc improvements:
- [x] test non-rocksdb file paths in file registry
- [x] respect read-only flag (don't write file/key registries) #26468
- [x] cli command to generate keys #26167
- [x] better logging of encryption status #27880
- [x] prevent key leakage on swap and core dump #27426
- [x] ensure runtime AES-NI detection is available #26649
- [ ] enterprise gating for report pages
- [x] debug tools for better visibility #28582 
- [x] ensure encryption settings are specified if previously used #28710

**Comment by mberhault** [comment]
CC: @dianasaur323. This is the tracking issue for encryption-at-rest.

**Comment by tbg** [comment]
The Raft log size computations are going to be incorrect when encryption at rest is turned on and IMPORT/RESTORE or the AddSSTable index backfill (currently being introduced) is used. This may not cause any problems, but it's a wart. The fix is to update this code here to use the RocksDB env. Currently listing files isn't even exposed through the Engine, so there's work to do for plumbing. And at the end of it, using the true Size of files may require decrypting them, so it's going to harm performance. All this may lead to accepting the inconsistency in the end regardless, and making sure our log truncations don't require specifics. (I think this is the direction we're moving towards in general). See https://github.com/cockroachdb/cockroach/issues/31913.

**Comment by mberhault** [comment]
Why would it be? Encryption at rest does not change the sizes of files, just the contents.

**Comment by tbg** [comment]
Oh, that's good, thanks for the heads up. Then the only problem is that there's some messy code.
