### ISSUE TITLE
sql: role-based access control.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#20371]
This issue tracks the status of role-based access control. Comments and reviews should be done on the individual PRs or in separate issues.

Approximate breakdown of work to be done (not complete, order may change):
* [x] finalize [RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171220_sql_role_based_access_control.md) #20149 
* [x] add `root` to `system.users` table #20369 
* [x] add `isRole` column and default `admin` role #20397 
* [x] give `admin` role same privileges as `root` on all dbs/tables #20397
* [x] roles membership table(s) #20397
* [x] add `root` as member of `admin` #20397
* [x] SQL statements
  * [x] `SHOW ROLES` #20980 
  * [x] `CREATE ROLE` #21020
  * [x] `DROP ROLE` #21020 
  * [x] `GRANT role ...` #21341
  * [x] `REVOKE role ...` #21341
  * [x] `SHOW GRANTS ON ROLE` #22205
  * [x] fill in `%SeeAlso%` for related ROLES statements in `parser/sql.y`  #21341
  * [x] expand role memberships for privilege/superuser checks #21820
* [x] expanded roles cache per node #22678
* [x] `pg_catalog` virtual tables #21780
* [x] `information_schema` virtual tables #22242
* [x] fix issues discovered during QA, see #21872
  * [x] `SHOW ROLES` column name is `username` #22680
  * [x] `admin` role privileges can be dropped #23876
* [x] draft documentation and add `%SeeAlso%` links [docs/#2433](https://github.com/cockroachdb/docs/pull/2433)

**Comment by mberhault** [comment]
CC: @awoods187: this is the tracking issue for role-based access control.

**Comment by mberhault** [comment]
CC: @jordanlewis: this provides an approximate breakdown of the planned work. That way you won't be surprised by stuff missing at certain steps (I hope).

**Comment by mberhault** [comment]
This is pretty much done. Just docs remaining.
