### ISSUE TITLE
sql, opt: tracking issue for the new index constraints code.

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#20775]
Tracking progress of the new index constraints generaton code in `opt`:

- [x] build expr from TypedExpr
- [x] basic comparison ops
- [x] conjunction
- [x] single variable IN
- [x] tuple equality
- [x] tuple inequality
- [x] tuple IN
- [x] column directions (support for descending columns)
- [x] top-level disjunctions
- [x] IS/IS NOT NULL constraints
- [x] simplification of filters after calculating index constraints
- [x] convert from expr back to TypedExpr
- [x] allow unsupported subtrees like subqueries (store them opaquely in a special op)
- [x] go through opt_index_selection testcases and make sure they are all represented in opttest
- [x] JSONB indexes
- [x] verify all problems reported in #6346 and associated issues are addressed

**Comment by RaduBerinde** [comment]
CC @petermattis @knz @rytaft
