### ISSUE TITLE
sql: ActiveRecord / Rails ORM support

### ISSUE THREAD

**Issue by lgo** [cockroachdb/cockroach#20932]
This is an issue tracking support for ActiveRecord and its features. Many of the extra features (partial indexes, ranges, comments) can be gated if the adapter so chooses to support them, making it easy to keep them disabled until we support them. If you have arrived here from one of the referenced issues, please comment on this issue to make others aware the change can be made to ActiveRecord.

- [ ] `ALTER TABLE ... ALTER COLUMN ... TYPE <type>` #9851. This is required for `connection.change_column(...)` statements. This is frequently used for migrations. To mitigate the problem, we can modify the adapter to generate an alternative (new col, backfill, drop col, rename col).
- [ ] Partial indexes #9683. Standard feature support, gated by the adapter.
- [ ] Certain generated queries with GROUP BY are unsupported. #20729. The impact of this needs to be investigated, but it may be any use of `Model.group`. This may be able to be resolved by modifying the adapter.
- [ ] Ranges #17022. Standard feature support, gated by the adapter.
- [x] SQL comments. #19472. Standard feature support, gated by the adapter.
- [ ] `FOR UPDATE`. #6583. This is used for `Model.lock!` statements.
- [ ] Savepoints. #10735. This prevents explicit savepoints and many uses of transactions.
- [ ] Computed indexes. #9682. Standard feature support, gated by the adapter.
- [x] Correlated sub-queries. #3288. Required for some generated queries made when retrieving associations. It may be possible to modify the adapter to work around this. See [this ActiveRecord test](https://github.com/rails/rails/blob/5232ddad654aad7fc48fb1458c4d776246789409/activerecord/test/cases/associations/eager_test.rb#L1402-L1404) for code that generates a correlated sub-query. 
- [x] Virtual columns (aka computed columns). #20882. Standard feature support, gated by the adapter. 

There are more issues, but they have not been tracked down to CockroachDB issues or just adapter issues. See [lego/activerecord-cockroachdb-adapter/CONTRIBUTING.md](https://github.com/lego/activerecord-cockroachdb-adapter/blob/master/CONTRIBUTING.md#tracked-test-failures) for the full list.

**Comment by knz** [comment]
cc @awoods187 for tracking

**Comment by bobvawter** [comment]
RFC for changing column type in #24703.
