### ISSUE TITLE
opt: high level tracking issue

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#21061]
Tracking goals and progress for optimizer-related tasks

2.0
 - [ ] stats generation (via explicit statement)  **95%**
 - [x] introduce the expression tree for scalar expression; convert to and from TypedExpr **90%**
 - [x] new index constraints generation (addressing issues in #6346) **80%**

2.0 (stretch goals)
 - [ ] support relational expressions
 - [ ] perform name resolution and type checking on the expression tree
-  [ ] convert `opt.Expr` to {local,dist}sql execution plans
 - [ ] predicate inference and push down

2.1
 - [ ] automatically gather stats
 - [ ] introduce the memo structure
 - [ ] transform correlated queries into apply variants; transform common apply variants into joins
 - [ ] nested loop join, semi-join, anti-join, apply processors
 - [ ] basic cost model powered by stats
 - [ ] task-based single stage search (no pruning)
 - [ ] join elimination, distinct/group-by elimination, join commutativity, join associativity, index selection, and scalar normalization
 - [ ] testing infrastructure (random data generation based on schema; random sampling and execution of alternate query plans to verify equivalence; stats injection).
