### ISSUE TITLE
Product Roadmap

### ISSUE THREAD

**Issue by jess-edwards** [cockroachdb/cockroach#2132]
*Please note that this roadmap is only a look at features in development or still to come. It does not reflect the many features already completed by the CockroachDB community.*

Beta roadmap

* [ ] Rebalancing
    * [x] Basic rebalancing support #620
    * [ ] Improved rebalancing heuristics #2600, #2747 
* [x] Recovery #2149
* [x] Disable public KV access #2089
* [x] SQL
    * [x] Single table queries
    * [x] Support for indexes #1625, #2140, #2142 
    * [x] Transactions #1890, #2094
    * [x] Builtin functions #2042
    * [x] Aggregation functions (e.g. COUNT()) #2043
    * [x] Order By #2096, #2169
    * [x] Permissions / privileges #2005
    * [x] Schema change #2035, #2036
    * [x] Schema distribution #1743
    * [x] Support DATE and TIMESTAMP columns #1995, #2327, #2328, #2329
    * [x] Update grammar with modern amenities
    * [x] Postgres-compatible server endpoint #2720 
* [x] Stable on-disk format, wire protocols
    * [x] RPC version #2719 
    * [x] RocksDB storage version #2718
* [x] Batches
    * [x] Store-side #2340 
    * [x] Dist sender #2406 #2130
    * [x] 1PC txns #2716, #2717
* [x] Transaction cleanup #2062
* [x] Gob cleanup #629
* [x] Config prefix maps -> database / table descriptors #2090
* [x] Multiraft
    * [x] Stability / correctness ~~#1911~~ ~~#1878~~ ~~#1488~~ ~~#1644~~ ~~#1650~~ ~~#1972~~ 
    * [x] Tombstones #768 
    * [x] Optimization #1384 ~~#1573~~ 
* [ ] Documentation
    * [x] Table of contents
    * [x] Quick start guide
    * [ ] Privileges #2134 
    * [ ] Wire protocol
    * [x] SQL grammar #2134 
    * [x] Deployment
    * [ ] Configuration
    * [ ] Troubleshooting
    * [x] FAQ
* [x] Admin UI
    * [x] Sufficient transient stats #2721
    * [x] Aggregated graphs #2722
    * [x] Aggregate error/warning log #2724
    * [x] Application of design skin #2723 
* [ ] Prod / Deployment
    * [x] Security #1675
    * [x] Additional testing use cases #2432 
    * [x] Cloud-hosted cluster with load
    * [ ] Integrations #28
        * [ ] Digital Ocean

V 1.0
* [x] Response cache cleanup
* [x] Gossip cleanup / optimization
* [ ] Backup / restore
* [ ] Monitoring / alerting
* [ ] Map reduce
* [ ] Prod / Deployment
    * [ ] Integrations #28
        * [ ] Microsoft Azure
        * [ ] Openstack / Internap
* [ ] SQL
    * [ ] Protobuf / JSON columns? #2969 
    * [ ] Array type #2115
    * [x] Decimal type #1618
    * [x] Group by #2174 
    * [x] Having #2175 
    * [ ] Joins #2970
    * [ ] Interleaved tables #2972
    * [ ] Foreign key constraints #2968 
    * [ ] Performance
        * [ ] KV where clause support
    * [ ] Rich indexes
        * [ ] Geo spatial
        * [ ] Full text
* [ ] Password-based authentication
* [ ] Jepsen testing #4036

**Comment by joeblew99** [comment]
Feature request: push queries.
I use these in rethinkdb because I have a streaming architecture with the compute and data in a large DAG.
It would be great if the concept of push queries was part of the features

**Comment by vivekmenezes** [comment]
Joe,

We know that push queries are useful and they will hit the roadmap one day.
We are focusing a lot of our energy at the moment on performance and
stability. Thank you for your input, it is much appreciated.

Vivek

**Comment by somecallmemike** [comment]
I was wondering if there were any tentative timelines around the beta and V1 of CockroachDB?  Looks like an amazing project and we want to start using it as soon as possible!

**Comment by vivekmenezes** [comment]
Mike,

Thanks for your interest. We are working towards beta and are focused on
improving the performance and stability of the system. Unfortunately we
still do not have a confirmed beta date.

Thanks

**Comment by mbdas** [comment]
Do you have any update on the beta date?

**Comment by spencerkimball** [comment]
@mbdas we expect to announce the beta very soon. In a small number of weeks. That will be the turning point for stability in the underlying data structures with an assured upgrade path.

**Comment by boreys** [comment]
I hope to hear the good news soon. I have been watching this project for a long time now.

**Comment by spencerkimball** [comment]
@petermattis need to close this issue and start a new one...

**Comment by petermattis** [comment]
Yep. Closing this for now. I'm going to work on a revamped 1.0 roadmap in the next week or so.
