### ISSUE TITLE
cli/tables: the default formatter for tabular results is problematic

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#21660]
Currently commands default to table format `pretty` which are based off the `tablewriter` package.
We have a couple of issues, ranging from pet peeve to major UX problem:

- [x] ~some commands have natural wide rows to report, and the table writer doesn't render them well (= seriously unreadable). Already tracked as #16926.~ #28465
- [x] ~the thing buffers all the results before they are printed. If the result is large, the client explodes #18329.~ #28490
- [x] ~the thing buffers all the results before they are printed. If the result is large, the user has to wait a *noticeable* amount of time before they see the first row.~ #28490
- [x] ~our handling of newline characters confuses k8s on windows. #18507~  #22324
- [x] ~the handling of line wrapping is confusing #22628~ #28465

Really we should have a table formatter which:
- operates in streaming fashion, doesn't wait for last row to print first row
- renders wide lines in a format more pleasant to the user
- (optionally) extend the client to paginate the results and wait for confirmation before scrolling to the next page

Note that rendering a pretty-formatted table and rendering in a streaming fashion may seem at first irreconcilable (how does one determine the column width until we've seen all the rows?) but there are solutions:
- buffer one page at a time; recompute a column width per page if the previous known widths are inadequate
- increase the width as wider results are seen, as in e.g. https://github.com/knz/align

**Comment by knz** [comment]
All the issues have been addressed by various PRs. Closing this.
