### ISSUE TITLE
sql: sanitize mutation statements  with RETURNING

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#23156]
After a discussion with @andreimatei and @jordanlewis  we can address the following :

- [x] ~sql: bracket subquery results in wrong transaction status #22208~ dup #20732.
  - scheduled for 2.0
- [x] ~sql: DMLs in statement sources don't work properly with limits #20732~ fixed #23824
  - scheduled for 2.0
- [x] ~sql: DMLs with RETURNING stream results that violate constraints #22304~ fixed #23373
  - scheduled for 2.0.1
- [x] ~sql: ON DELETE SET DEFAULT violates constraints #23361/~ fixed #23373
  - scheduled for 2.0.1

Make this happen:

- ~row container for the results if the results are consumed in a surrounding query~ done #20732
- ~ensure that no results to be streamed out before constraint validation occurs~ done #23373
