### ISSUE TITLE
build: add checklist for Go version bumps

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#23481]
See #23441.

**Comment by bobvawter** [comment]
I was able to just refer to `build/README.md` and had no problems revving the go runtime.

**Comment by benesch** [comment]
But there's one final gotcha, which is bumping the Go version in bootstrap-debian.sh, and which is why I think it'd be useful to have a checklist that gets copied and pasted into any Go version bump PR. Here's what it should look like off the top of my head:

* [ ] Adjust version in Docker image ([source](https://github.com/cockroachdb/cockroach/blob/53e1686b19e95a4c9b79884e348720b05b434244/build/builder/Dockerfile#L199-L200)).
* [ ] Rebuild the Docker image and bump the version in builder.sh accordingly ([source](https://github.com/cockroachdb/cockroach/blob/53e1686b19e95a4c9b79884e348720b05b434244/build/builder.sh#L6)).
* [ ] Bump the version in go-version-check.sh ([source](https://github.com/cockroachdb/cockroach/blob/master/build/go-version-check.sh)), unless bumping to a new patch release.
* [ ] Bump the default installed version of Go in bootstrap-debian.sh ([source](https://github.com/cockroachdb/cockroach/blob/master/build/bootstrap/bootstrap-debian.sh)).
