### ISSUE TITLE
sql: provide more visibility into long-latency queries

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#24109]
CockroachDB should make it easy(easier) for users to discover which queries are taking the most times and identify their origin, frequency, etc.

The result of this work comprises:
- [x] one or more interfaces to discover "high latency" queries (e.g. SQL-evel + web UI)
- [x] enough data to identify where and when these queries originate, and their frequency. Covered in the statements page as well as via [explain](https://www.cockroachlabs.com/docs/v19.1/query-behavior-troubleshooting.html#query-is-always-slow).
- [x] contextual links to docs and/or suggestions for follow-up actions when a user discovers a slow query. Docs [here](https://www.cockroachlabs.com/docs/v19.1/query-behavior-troubleshooting.html#query-is-always-slow).

The work may actually comprise, as a sub-unit of work, resolution of:
- [ ] sql: provide visibility into total transaction time #21241
- [ ] sql: raise the visibility of full table scan queries to users #20060

Here are example issues which would be aided by the work described here:
~- Observing very high latency on queries #19199~
~- Queries take >10s when updating same row concurrently #17883~
~- [Performance] Is Update slower than Upsert? #17621~
~- perf: poor performance on small table without index, likely due to contention #16252~
- sql: allow rejecting a query if a full table scan is involved #13969

**Comment by knz** [comment]
cc @dianasaur323 @piyush-singh this is the github issue reflecting the item "Enable users to discover slow queries" in the roadmap.

**Comment by dianasaur323** [comment]
thank you! Let's use this as a springboard / resource during our query analysis meeting next week. this is so excellent!

**Comment by knz** [comment]
@piyush-singh I think you're the new person in charge of this one (is the issue still applicable? ISTM this has been taken over by some other project)

**Comment by awoods187** [comment]
We are adding https://github.com/cockroachdb/cockroach/issues/21241 in 19.2

**Comment by ericharmeling** [comment]
> We are adding #21241 in 19.2
@awoods187 
Is this still on for 19.2?

**Comment by awoods187** [comment]
I updated the issue to state:
>We landed [this PR](https://github.com/cockroachdb/cockroach/pulls?page=2&q=is%3Apr+is%3Aclosed+author%3Ayuzefovich) in 19.2 but it doesn't cover the full scope of this whole issue
