### ISSUE TITLE
sql: enhance SQL errors + make them reportable

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#24108]
This is a sub-issue of #15854 and re-phrases actionable items for 2.1:

- [ ] audit the SQL package for errors constructed by other means than using the `pgerror` constructors; convert any remaining errors accordingly.
- [ ] audit the SQL package for "leaf" uses of 3rd-party packages that can generate non-pgerror errors, and add suitable pgerror wrapper. This can be automated with a linter.
- [ ] modify the pgerror error constructors so that sensitive and non-sensitive information can be distinguished from each other (defined so that non-annotated info is considered sensitive by default)
- [ ] make the data collection by app_stats.go + reporting able to report non-sensitive data
- [ ] (main item from #15854): in pgwire detect any remaining non-pgerror errors and convert them to "internal server error" so that users become less surprised.

**Comment by knz** [comment]
@vivekmenezes this is a work item that is driven by a user story but requires cross-team work at multiple levels (across the entire SQL layer of CockroachDB). So I added it to at least two projects that I think are relevant.

I probably would like to be involved; I think @dt was interested to look into this, and perhaps Bram will be as well.

**Comment by knz** [comment]
Assigning according to airtable; this assignment may change as the roadmap gets further refined.

**Comment by knz** [comment]
(still working on this, see #36987)

**Comment by knz** [comment]
This work has been completed.
