### ISSUE TITLE
sql: name resolution woes post-2.0

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#24598]
This is a meta-issue that describes remaining name resolution problems discovered around the 2.0 release.

### Issues due to invalid/missing default db

These issues can be solved by either introducing a pseudo-descriptor for the current database when no valid current db is set, or ensuring the current db exists when a session is opened.

- [x] sql: confusing error when creating table with no active db #24056
- [x] sql: errors in client due to use of pg_catalog with non-existent db as current #23893
- [x] sql: make `pg_catalog` error out cleanly when no cur db set #23958
- (only indirectly)  sql: current_schema should skip over invalid schemas #24472 

### Outright pg compat bugs

- [x]  sql: current_schema should skip over invalid schemas #24472 
- [ ] Support pg_catalog.regclass when casting #18856

### Unfortunate bugs due to the special CRDB 1.x compatibility "feature"

- [x] v2.0-beta.20180319: Regression in star queries #24169
- (only indirectly) sql: not-searched index name found already qualified #24475

### Other bugs due to CockroachDB idiosyncrasies

- [x] sql: not-searched index name found already qualified #24475

### UX improvements

- [ ] sql: Error messages should be improved in case of no matching data source #22966

**Comment by knz** [comment]
cc @vivekmenezes I'll be working on this soon/next (after closing my current UPSERT PR), as this corresponds to one "unit of work" conceptually and contains fixes to known 2.0 regressions

**Comment by knz** [comment]
cc @jordanlewis

**Comment by knz** [comment]
All 2.0-critical issues now have PRs. The relevant PRs will be cherry-picked to 2.0.x. The remaining items can be addressed for 2.1.

**Comment by knz** [comment]
The two remaining issues are not directly related to name resolution. We'll catch them in separate sub-projects. Closing this now.
