### ISSUE TITLE
sql: support DBeaver

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#25135]
- [x] Support pg_catalog.pg_stat_activity #24745
- [ ] Support pg_catalog.pg_conversion #24744 
- [ ] Support pg_catalog.pg_opfamily #24743 
- [ ] Support pg_catalog.pg_opclas #24742 
- [ ] Missing oid column from pg_extension #24620
- [ ] List of DBeaver metadata queries #28309

**Comment by awoods187** [comment]
@knz should we close this now?

**Comment by knz** [comment]
I suppose we can yes!

the compatibility has been solved via a specialized dbeaver backend for cockroachdb.

**Comment by awoods187** [comment]
https://dbeaver.com/release-notes/#5.2/
