### ISSUE TITLE
changefeed: prototype in v2.1-alpha.20180604

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#25192]
Starting my notes to keep track of what needs to make the prototype. Don't worry about this making sense until the RFC is out, then I'll make sure the jargon here stays in sync with it.

- [x] merge rfc
- [x] pause/resume
- [x] initial catchup (or not)
- [x] support for DELETE
- [x] switch kafka address to sql option
- [ ] setting for how far behind to read
- [x] envelope=none,key_only
- [ ] format=json,avro
- [ ] confluent schema registry
- [x] timestamps in messages
- [x] correct table leasing
- [ ] truncate
- [ ] end-to-end testing (elasticsearch)
- [ ] end-to-end testing (something that wants to be transactionally consistent)
- [x] tpcc roachtest
- [ ] docs

haven't decided yet
- [ ] schema change topic?
- [ ] distsql
  - [ ] periodically rebalancing the flow
- [ ] enterprise license check
- [ ] column_whitelist
- [x] timestamp close notifications
- [ ] envelope=diff

no
- [ ] alter changefeed
- [ ] new storage primitive
- [ ] rock solid failure resilience
- [ ] permissions
- [ ] non-kafka sinks
- [ ] tables with more than one column family
