### ISSUE TITLE
Database Visualizers List

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#25467]
This is meta issue to serve as a list of known DB visualization tools that we would like to support.  I'll be keeping this top description updated, so if there are any tools out there that are not on this list, please comment and I'll add them. Note that these are ordered alphabetically and not by priority.  If there is a tracking issue for a tool, it will be linked to from here.

Note that these tools do not have to be open source, but that open source tools will probably get a higher priority. As will cross platform tools.

- [ ] #20641 [DataGrip](https://www.jetbrains.com/datagrip/)
- [ ] #25135 [DBeaver](https://dbeaver.io/)
- [ ] [dbglass](http://dbglass.web-pal.com/)
- [ ] #18022 [DbVisualizer](https://www.dbvis.com/)
- [ ] #25213 [pgAdmin](https://www.pgadmin.org/)
- [ ] [PGWeb](https://github.com/sosedoff/pgweb)
- [ ] #19054 [IntelliJ IDEA](https://www.jetbrains.com/idea/) - the same as DataGrip?
- [ ] [Postico](https://github.com/jakob/Postico)
- [ ] [PSequel](http://www.psequel.com/)
- [ ] [TablePlus](https://tableplus.io/)
- [ ] [Valentina studio](https://www.valentina-db.com/en/valentina-studio-overview)
- [ ] [Visual Studio Server Explorer](https://msdn.microsoft.com/en-us/library/x603htbk.aspx) with #25462 [npgsql](http://www.npgsql.org/)

**Comment by andrew-bickerton** [comment]
Azure Data Studio (open source) with postgres extension.
Uses psycopg2 to query the db.
Works with:
- connect
- create db
- create table
- insert table

Fails on:
- select from table

But it can display a fair bit of info:
- list of DBs
- table list (but not columns under tables)
- roles

**Comment by BramGruneir** [comment]
Thanks @andrew-bickerton!

I bet the select is using a cursor.  Which we don't support yet.

Added it to the list.

**Comment by gnat** [comment]
Consider this: Even a page in the core admin gui that sends simple queries for:
* field editing
* column rename/add/remove

Would allow all of these tickets to be closed because these 3rd party solutions are all such awful experiences compared to the core product.

GUI tooling is sooo important for getting new people in. It is a weakpoint for CockroachDB adoption right now, which is a shame since the core itself is wonderfully engineered and it does so many things right :100: 

PGWeb, gets half way there, but it has zero functionality beyond browsing-- but it is tiny, and dockerizable, portable, just like CockroachDB. pgAdmin is overrated since half the features aren't even applicable to Cockroach DB, but it would be my second choice as its a simple `docker-compose up` away. The rest are very poor experiences that are a poor representation of the rest of CockroachDB. @ericharmeling @jordanlewis
