### ISSUE TITLE
sql: npgsql  support

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#25462]
- [x] sql: dotNET server explorer fails silently with npgsql #18026 
- [x]  sql: int4 type mapping error in npgsql #24172 
- [x]  sql: pgwire OID error during EF Core / Npgsql migration #24173 

Jira issue: CRDB-5712

**Comment by awoods187** [comment]
Added a need to run the test suite in https://github.com/cockroachdb/cockroach/issues/38188

**Comment by dgadelha** [comment]
If you generate migrations through Entity Framework, when adding a column that references another entity, Npgsql will use an unimplemented feature: #32917

**Comment by rafiss** [comment]
A few EntityFramework-related issues:
- [ ] https://github.com/cockroachdb/cockroach/issues/48050 EntityFramework Core Scaffolding tool can't load pg_catalog data
- [ ] https://github.com/cockroachdb/cockroach/issues/32917 ALTER TABLE ADD COLUMN colname REFERENCES tablename(colname)
- [ ] https://github.com/cockroachdb/cockroach/issues/48532 GENERATED syntax

cc @roji

**Comment by rafiss** [comment]
npgsql is now supported, as per the docs: https://www.cockroachlabs.com/docs/stable/third-party-database-tools
