### ISSUE TITLE
Misc Database Tools

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#25470]
This is meta issue to serve as a list of miscellaneous tools that we would like to support. These tools should not fit into #25467, #25468 or #25469.

I'll be keeping this top description updated, so if there are any other tools that are not on this list, please comment and I'll add them. Note that these are ordered alphabetically and not by priority. If there is a tracking issue for any of them, it will be linked to from here.

This list is not exhaustive, but I would like to keep this as up to date as possible, so it can be somewhat of a source of truth.

The check marks just mean that there are no known current issues with that particular tool and it has been tested.

- [ ] #19369 [Mattermost](https://about.mattermost.com/)
- [ ] #5583 [Navicat](https://www.navicat.com/en/)
- [ ] #20296 [pg-dump](https://github.com/postgres/postgres/blob/master/src/bin/pg_dump/pg_dump.c#L1061)
- [ ] #20419 [Presto](https://prestodb.io/)
- [ ] #22937 [Zabbix](https://www.zabbix.com)

**Comment by sokoow** [comment]
so after a couple of months, I ran mattermost again, and now i'm getting:
```
{"timestamp":"2021-12-10 14:39:09.371 +01:00","level":"info","msg":"Pinging SQL","caller":"sqlstore/store.go:261","database":"master"}
{"timestamp":"2021-12-10 14:39:09.376 +01:00","level":"info","msg":"Pinging SQL","caller":"sqlstore/store.go:261","database":"migrations"}
{"timestamp":"2021-12-10 14:39:09.381 +01:00","level":"fatal","msg":"Failed to apply database migrations.","caller":"sqlstore/store.go:162","error":"try lock failed in line 0: SELECT pg_advisory_lock($1) (details: pq: unknown function: pg_advisory_lock())"}
```

**Comment by sokoow** [comment]
this is re: https://github.com/cockroachdb/cockroach/issues/19369
