### ISSUE TITLE
sql: Django compatibility

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#25608]
Does CockroachDB work with Django?

@bdarnell proposes: 

> if you use the django tooling to create a new app, that new app will contain some default migrations that need alter column type
> if you bypass that step there are other issues

(This needs to be double-checked against newer Django versions)

Ben also started work on a django adapter here: https://github.com/cockroachdb/cockroachdb-python/pull/14

Known django-related issues:

- [x] sql: support "DEFERRABLE INITIALLY DEFERRED" for constraints #9897
- [ ] sql: support ALTER TABLE ... ALTER COLUMN ... SET DATA TYPE ... #9851
  - [x]  sql: Support (some) column type changes #5950 
- [ ] sql: support creating a database as duplicate of another ("create database ... with template ...") #10151

**Comment by knz** [comment]
@BramGruneir can you link this issue from one of the new meta-issues.

**Comment by bdarnell** [comment]
From https://github.com/cockroachdb/cockroachdb-python/issues/25#issuecomment-394605584 the django migration tools expect savepoints to be available when using the postgres dialect.

**Comment by timgraham** [comment]
Use https://github.com/cockroachdb/django-cockroachdb. I think this can be closed as more specific issues have been created.

**Comment by awoods187** [comment]
We are closing this now that we have beta support for Django. https://github.com/cockroachdb/django-cockroachdb
