### ISSUE TITLE
sql: Hibernate Test Failures

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#26657]
While working towards #15821, I've been trying to catalog the hibernate test failures here.

The following issues still need investigation to understand what's going on:

- [x] #26799 transaction issues
- [x] #26803 Can't execute a native query in hibernate 
- [x] #26804 Timestamp strangeness
- [x] #26809 Optimistic Lock Exception
- [x] #26812 jdbcBatchSize 
- [x] #26735 Resultset is not scrollable (perhaps cursors?)

The following we will probably address:

- [x] #26658 correlated subqueries
- [x] #26737 implement string_agg()
- [x] #26709 group by does not conform with prostgres
- [x] #26260 implement ESCAPE
- [x] #26730 Auto-addition of a sequence for serial types
- [x] #5807 Temporary Tables
- [x] #26738 automatically add the needed index during alter table add fk constraint on empty tables 

Perhaps in the future, but not anytime soon:

- [ ] #26725 blob storage + pg's API for blob storage

The following we will probably not address (fundamental feature set mismatch or different design philosophy)

- #6583  SELECT FOR SHARE/UPDATE (NOWAIT), etc. See discussion in #19577
- #26732 support `<int> / <float>` operator
- #26710 some rando hibernate test thinks it's smart requiring an implicit cast

**Comment by awoods187** [comment]
@rafiss have these all been addressed now?

**Comment by vy-ton** [comment]
@rafiss Can this issue be closed?

**Comment by rafiss** [comment]
@vy-ton @awoods187: Thanks for the pings. I will close this. The tests tracked in the description are either passing now, or are intentionally getting skipped for a different reason. I closed out the linked issues too.
