### ISSUE TITLE
perf: avoid common allocations in TPC-C to reduce impact of GC

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#30512]
This is a tracking issue that's inspired by the GC troubles observed in https://github.com/cockroachdb/cockroach/issues/30213. The goal are twofold:
1. reduce `alloc_space`: We'd like to reduce the total memory size of garbage that we allocate to reduce the frequency of GCs. This should also reduce the amount that goroutines get in "debt" and are forced to assist the GC while it's running concurrently.
2. reduce `alloc_objects`: We'd like to reduce the total object count of garbage that we allocate to speed up the GC mark and sweep phases. This should also reduce the impact that the GC has while running concurrently (i.e. decrease GC assist pauses, both while marking and sweeping) because it should make it less common that a goroutine allocates during this period.

For the sake of the issue, we'll look at a three-node cluster running TPC-C 1k. I've gone through a few heap profiles and picked out some of the worst offenders in these two areas.
- [x] (#30523/@nvanbenschoten) `RocksDBBatchBuilder.maybeInit`: 5.89% of allocated space
- [x] (#30523/@nvanbenschoten) `RocksDBBatchBuilder.grow`: 4.13% of allocated space
- [x] (#30523/@nvanbenschoten) `newRocksDBBatch`: 3.57% of allocated space
- [ ] `RaftMessageRequestBatch.Unmarshal`: 4.55% of allocated space
- [ ] `handleSimpleQuery -> sql/parser/Parse`: 1,296 bytes allocations, 2.29% of allocated space, 4.6% of allocated objects
- [x] (#30464/@jordanlewis) `processExpression -> sql/parser/Parse`: 1,296 bytes allocations, 2.53% of allocated space, 3.81% of allocated objects
- [x] `raft.getStatus`: 3.46% of allocated space, 3.71% of allocated objects
- [x] (#30510/@nvanbenschoten) `StatsHandler.HandleRPC`: 0.51% of allcoated space, 3.25% of allocated objects
- [ ] `storage.collectSpans` (mostly in `DefaultDeclareKeys`): 1.44% of allocated space, 1.96% of allocated objects

When picking one of these allocations to tackle, it helps to get familiar with why we're allocating and what the object is being used for. Sometimes we can avoid the allocation by embedding it in another object with a longer lifetime (e.g. `sql/parser/Parse`), sometimes we'll be able to reduce it's cost with a `sync.Pool` (e.g. `newRocksDBBatch`), sometimes the allocation is completely avoidable (e.g. `StatsHandler. HandleRPC` and probably `raft.getStatus`).

Please assign an issue to yourself in the list above when investigating.

A separate but similar issue will be to reduce the number of pointers in objects with long lifetimes (e.g. `Replica`, `connExecutor`, etc.). This should speed up te sweep phase of each GC because it will need to chase fewer pointers.

**Comment by nvanbenschoten** [comment]
These might each individually look small, but I think they're all fixable and they add up to 29% of all allocated space for this workload. If we can fix them, we'll have significantly fewer GCs, the GC runs will be faster, and the GC should be less disruptive to other concurrently running goroutines.

**Comment by nvanbenschoten** [comment]
@jordanlewis could you triage the `processExpression -> sql/parser/Parse` allocation?

**Comment by jordanlewis** [comment]
@nvanbenschoten I've got a PR out for that #30464

**Comment by petermattis** [comment]
If it is possible, it would be good to prototype having these all "fixed" (perhaps with hacks) to see what the performance gain is. For example, you can fix `raft.getStatus` in a branch.

**Comment by nvanbenschoten** [comment]
> If it is possible, it would be good to prototype having these all "fixed" (perhaps with hacks) to see what the performance gain is. For example, you can fix raft.getStatus in a branch.

Yes, I completely agree. It's hard to run micro-benchmarks and measure the effect these changes have on the GC though. We'll want to take these prototypes and run them against a full end-to-end test like we've been doing in #30213.

**Comment by nvanbenschoten** [comment]
Moving this to 2.2 because none of these changes will be backported.

**Comment by irfansharif** [comment]
I ran TPCC-1k to see some of the worst offenders now, and the list above is stale. Going to draft a new issue with some added context for Madeline to possibly take a stab at.
