### ISSUE TITLE
sql: increase support / decrease warnings for users of IntelliJ IDEA

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#31737]
Pursuant of #19054 we want to check waht the current state is.

Found the following while investigating:

- SQL query errors are conveniently reported in an "event log" at the bottom - no need for complex tracing server-side
  Also it's possible to produce a "detailed SQL trace" with an option in the db config settings. This provides also all the pgwire messages. Handy for debugging.

- [x] the embedded default pg JDBC driver is outdated; user should manually download/obtain 42.2.5 or later
  If we ever advertise IntelliJ this must be clearly documented.
- [x] the default connection settings cause an error "column N.xmin does not exist" while inspecting the schema
  This is because of issue #33296.
  Workaround is to go to "options" screen in db connection settings and click "Introspect using JDBC metadata" - thanks pete V for the tip!
- [x] warning about decorrelation errors, one per database upon listing dbs #33298
- [ ] warning about missing built-in function `pg_function_is_visible()` #33297
  This repeats often and may thus be worth fixing earlier

**Comment by vilterp** [comment]
I've been using this daily. Everything I've tried works (sidebar, SQL console window, table editor, even schema diagram) as long as you check this box: 
![image](https://user-images.githubusercontent.com/7341/50228630-71190480-0376-11e9-8fac-91a87affd56e.png)

There are a couple of errors during schema introspection, but they don't seem to cause any problems:
![image](https://user-images.githubusercontent.com/7341/50228731-a9204780-0376-11e9-9467-d3566f4a13a3.png)

If you don't check the box, it uses a different introspection pathway, which doesn't seem to work at all:
![image](https://user-images.githubusercontent.com/7341/50228830-e7b60200-0376-11e9-9092-9c1fff60fd9e.png)

**Comment by knz** [comment]
The "JDBC introspection" uses pg_catalog; without it it tries to use information_schema which, as the error suggests, is not sufficient/complete.

I'd like to track down all the various errors (both with and without the option checked) so see what needs to be done to have no error whatsoever.

**Comment by jordanlewis** [comment]
We'd need to add the various hidden columns on all tables, like`xmin` `xmax` and so on, even though I don't think they make any sense in our model.

**Comment by knz** [comment]
I don't know about "all tables" but we can certainly find out what intellij specifically needs.

**Comment by knz** [comment]
Ok I dug into this and found some items for work (see list in issue description at top). 

The following seem to work:
- creating new table
- adding table comments
- adding FK relations
- inspecting the schema
- obtaining a schema diagram
- editing the rows of a table
- deleting rows from a table
- dumping the contents of a table to a file (TSV)
- dropping a table
- dumping the content of crdb_internal tables to a file

The following seem to not-work:
- running pg_dump/pg_restore via intellij
- using the table editor on crdb_internal tables (error on missing CTID, related to #33296)

**Comment by sploiselle** [comment]
@knz Are there specific features that do not work with versions < 42.2.5 of the JDBC PostgreSQL driver? I've been tinkering around with 41.1.x in IntelliJ without the level of support differing from 42.2.5, though I haven't gone through as extensive testing as you might have.

**Comment by knz** [comment]
When I tried last time with an older pgJDBC version, the thing was outright failing with errors.

If it doesn't any more that's great news! But I don't know how to explain that, other than perhaps an unrelated change in CockroachDB that introduced compatibility with older pgJDBC versions.

**Comment by knz** [comment]
Also you'll get different results between 2.2-alpha and 2.1.x (and 2.0.x). We'll want to recommend configs that work in both 2.2/19.1 and 2.1, if there's any.

**Comment by jordanlewis** [comment]
This is looking groovy - after #40902 I don't see any warnings or errors when clicking around in the IDEA database plugin.

**Comment by awoods187** [comment]
Should we close this after #40902 lands?
