### ISSUE TITLE
cli: add I/O benchmarking to cockroach

### ISSUE THREAD

**Issue by m-schneider** [cockroachdb/cockroach#31833]
This is a tracking issue/discussion for adding I/O benchmarking to CockroachDB. We're planning on measuring op/s per second, MB per second and latency for the following operations:

- [ ] 128MB block append writes with and without contention
- [ ] Smaller appends with periodic calls to fsync every 512KB
- [ ] Random reads of some block size in a file with contention
- [ ] Sequential reads of a file
- [ ] RocksDB reads and write

This isn't meant to be a final list, but a starting point for a discussion.

**Comment by m-schneider** [comment]
> FYI, RocksDB sstables are ~128MB in size, but they are written in smaller chunks (I'm not sure what the actual value here is) and we've configured RocksDB to call fsync every 512KB.

We can do random sized chunks up to 512KB? 

> What does it mean to have contention during file reads?

I was thinking of something along the lines of multiple readers using a flock in shared mode.

**Comment by petermattis** [comment]
> We can do random sized chunks up to 512KB?

For sequential write performance, I think we can do something like: write 32KB blocks and call fsync (or fdatasync) every 512KB.

> I was thinking of something along the lines of multiple readers using a flock in shared mode.

We definitely want to test multiple concurrent readers. I suspect there is some confusion here over the usage of `flock`.  RocksDB only uses `flock` on the `LOCK` file which is neither read or written.

**Comment by knz** [comment]
this has been addressed since
