### ISSUE TITLE
release: v2.1.0

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#31900]
Candidate SHA: f0dd1dc2d2500155c8b36330ae3d6932c13c1027 (same as [`v2.1.0-rc.2`](https://github.com/cockroachdb/cockroach/issues/31767))
Deployment status: Deployed to adriatic and omega
Nightly Suite: https://teamcity.cockroachdb.com/viewLog.html?buildId=987129

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: Thursday 2018-10-25
- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters and start nightly suite](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] fill in `Deployment status` above with clusters and `Nightly Suite` with the link to Nightly TeamCity Job
- [x] [Verify node crash reports](https://github.com/cockroachdb/cockroach/wiki/Release-Process#verify-crash-reports)
- Keep an eye on clusters until release date. Do not proceed below until the release date.

Release date: Tuesday 2018-10-30
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)

- For production or stable releases in the latest major release series
  - [x] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [x] Update the image tag in our [Orchestrator configurations](https://github.com/cockroachdb/cockroach/wiki/Release-Process#orchestrator-configurations)
  - [x] Update the version label in our [Red Hat Atomic Docker image](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/Dockerfile). For major/minor releases, also update the documentation link in the [image's help file](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/help.1)
  - [x] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - [x] Upgrade the registration cluster (reg runs latest stable version)

- [x] Update docs
- [ ] External communications for release
- [x] File issue for next release and assign to release coordinator

---

Sorry I won't be able to handle this since I'll be offline next week. Unless we find a non-risky fix to https://github.com/cockroachdb/cockroach/issues/31823 within the next day, the release should be the same build as [`v2.1.0-rc.2`](https://github.com/cockroachdb/cockroach/issues/31767).

**Comment by tschottdorf** [comment]
Clusters look good.

> Adriatic looks as usual. Omega looks good. There’s a small downtrend in qps (visible on the a week scale. I assume this is expected since we’re pumping more and more data into it. Big drop at the beginning from the 8k range into the 6k range when ranges split.

> What’s interesting is that there seems to have been a pretty large RocksDB compaction event (at the same time as GC queue event) on 10/27 at noon. Throughput took a dip (~12k to ~11k if I read that right), 784GB to 303GB drop in cluster used capacity (15k ssts to 6.8k ssts). Nothing to worry about, but was interesting to see. Not sure what happened there.

Proceeding to tag the release.

**Comment by tschottdorf** [comment]
Release is tagged. TC build is running: https://teamcity.cockroachdb.com/viewQueued.html?itemId=994144&tab=queuedBuildOverviewTab

**Comment by tschottdorf** [comment]
TC build succeeded, bincheck running at https://github.com/cockroachdb/bincheck/pull/74.

**Comment by tschottdorf** [comment]
Bincheck succeeded.

**Comment by tschottdorf** [comment]
Homebrew: https://github.com/Homebrew/homebrew-core/pull/33508
Orchestration: https://github.com/cockroachdb/cockroach/pull/32003
DCOS: https://github.com/cockroachdb/dcos-cockroachdb-service/pull/67

**Comment by tschottdorf** [comment]
Reg cluster done:

> root@:26257/defaultdb> INSERT INTO registration.versions (version, details) VALUES ('2.1.0', 'https://www.cockroachlabs.com/docs/releases/v2.1.0.html');
INSERT 1

> Time: 9.743008ms

**Comment by tschottdorf** [comment]
I redeployed `register`. This was a little awkward since supervisor didn't know the processes were running. I assumed someone restarted them manually. I verified (on register:1) that the command line flags are identical.

**Comment by tschottdorf** [comment]
cc @jseldess and @jess-edwards for docs/external comms.

Filed and assigned https://github.com/cockroachdb/cockroach/issues/32004 for the first 2.2.0 alpha.

**Comment by tschottdorf** [comment]
`register` seems to be running fine, but I am noticing a marked increase in CPU usage. I think this is related to the consistency queue doing a full run, so nothing to be worried about. I'll check back in in a few hours.

**Comment by tschottdorf** [comment]
The release is long out, but we're having some problems with Homebrew/homebrew-core#33508. @benesch is looking, so assigning him.
