### ISSUE TITLE
sql: fix unimplemented github tracking error number

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31989]
**Describe the problem**

The following unimplemented features are tagged to the wrong github issue:

- [x] unimplemented.#8318 | https://github.com/cockroachdb/cockroach/issues/8318 -> #27792
- [x] unimplemented.#2115 | https://github.com/cockroachdb/cockroach/issues/2115 -> #32551, #32552
- [x] unimplemented.#20991 | https://github.com/cockroachdb/cockroach/issues/20991 -> solved in v2.2
- [x] unimplemented.#19472 | https://github.com/cockroachdb/cockroach/issues/19472

**Desired Action**
Update with either the correct github issue or create a new one if it doesn't exist yet.

**Comment by knz** [comment]
Please can you clarify - what do you mean they are "tagged with the wrong issue"? What do you expect instead?

**Comment by knz** [comment]
Clarification: the issue number needs to be updated (issue was superseded)

**Comment by knz** [comment]
Done:

- unimplemented.#8318 -> #27792
- unimplemented.#2115 -> #32551, #32552
- unimplemented.#20991 -> solved in v2.2
- unimplemented.#19472 -> issue re-opened (feature was not provided)
