### ISSUE TITLE
sql: add github issue number to the following unimplemented features 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31990]
**Describe the problem**

Add github issue tracking number to the following unimplemented features:

- [x] unimplemented.alter set type | #9851 with details
- [x] unimplemented.alter set non null | #28751
- [x] unimplemented.alter using |  #9851 with details
- [x] unimplemented.create sequence OWNED BY option | #26382
- [x] unimplemented.at tz |  #32005
- [x] unimplemented.on conflict on constraint | #28161
- [x] unimplemented.match simple | #20305 
- [x] unimplemented.frame_bound |  Implemented in v2.1 via window function improvements
- [x] unimplemented.func_application |  Implemented in v2.1 via window function improvements
- [x] unimplemented.alter add fk | #8855
- [x] unimplemented.with recursive | #21085
- [x] unimplemented.alter add computed | Implemented in v2.1
- [x] unimplemented.set local | #32562
- [x] unimplemented.index_elem a_expr | #9682
- [x] unimplemented.func_expr_common_subexpr | #32563 
- [x] unimplemented.func const | #32556 
- [x] unimplemented.create sequence AS option | #25110 with details
- [x] unimplemented.alter add check | #29639
- [x] unimplemented.alter column type | #9851 with details
- [x] unimplemented.pg_catalog.pg_matviews | N/A
- [x] unimplemented.pg_catalog.pg_statio_user_tables | N/A
- [x] unimplemented.import.mysqlcoltype.GEOMETRY |  #32560, #32559 and #32561

**Comment by knz** [comment]
- some of these are already done in 2.1 but maybe should be backported to 2.0
- some of these may not be clearly reproducible or maybe context is missing, in which case we may still want to invite users to submit an issue.
