### ISSUE TITLE
release: v2.1.1

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#32227]
Candidate SHA: 4523f9819d2dde9b054fc8faf1568e107f130986.
Deployment status: Adriatic, Omega.
Nightly Suite: [Nightly](https://teamcity.cockroachdb.com/viewLog.html?buildId=1010533&).

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: 
  ~~`Monday, November 12th, 2018`~~
  ~~restarted with a new SHA `Tuesday, November 13th, 2018`~~
  restarted again with a new SHA `Wednesday, November 14th, 2018`
- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters and start nightly suite](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] fill in `Deployment status` above with clusters and `Nightly Suite` with the link to Nightly TeamCity Job
- [x] [Verify node crash reports](https://github.com/cockroachdb/cockroach/wiki/Release-Process#verify-crash-reports)
- Keep an eye on clusters until release date. Do not proceed below until the release date.

Release date: `Monday, November 19th, 2018`
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)

- For production or stable releases in the latest major release series
  - [x] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [x] Update the image tag in our [Orchestrator configurations](https://github.com/cockroachdb/cockroach/wiki/Release-Process#orchestrator-configurations)
  - [x] Update the version label in our [Red Hat Atomic Docker image](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/Dockerfile). For major/minor releases, also update the documentation link in the [image's help file](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/help.1)
  - [x] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - [x] Upgrade the registration cluster (reg runs latest stable version)

- [x] Update docs
- [ ] External communications for release
- [ ] File issue for next release and assign to release coordinator

**Comment by BramGruneir** [comment]
Updating to a new SHA 5e5083d94ed4060471c88217d745f7266dd86fee

**Comment by BramGruneir** [comment]
Updating again to a new SHA 4523f9819d2dde9b054fc8faf1568e107f130986

**Comment by BramGruneir** [comment]
Adriatic has been suck for a while, while omega has been fine.  Proceeding with the release regardless.
