### ISSUE TITLE
sql: increase the sqllogic test coverage

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#3292]
The following bugs need to be fixed before the sqllogic select tests can be enabled:

- [x] support tables without a primary key? #2081
- [x] comparison of float and int #3266
- [ ] integer division returns float, sqllogic test expects int #3271
- [x] add failing test for aliased subquery #3291
- [x] hide rowid column from select and inserts #3293
- [x] support JOIN #2970
- [x] convert NULL to false #3544

**Comment by knz** [comment]
Closing as this is superseded by #7733 and #7734.
