### ISSUE TITLE
exec: meta issue for remaining work on experimental_vectorize

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#32935]
This issue tracks the laundry list of major remaining work on the experimental_vectorize project.

*Features*:
- [ ] memory monitoring
- [x] serialization - format for writing batches to bytes and reading back out. should be 0-copy on the read side - operators must be able to read directly from the serialized structure
- [ ] distribution - distributed flows must be plannable.
  - [x] merging input synchronizer
  - [x] hash router
  - [ ] range router
- [ ] disk spilling - computation that hits a memory limit must fall back to disk containers.
- [x] improved logic test capability - experimental_vectorize=always, to let logic tests ensure that things actually get planned with the columnar ops.
- [x] tracing / stats
- [ ] explain (shows flow of exec operators)

*Relational operators*:

- [x] index / lookup join (can these be the same?)
- [x] offset
- [ ] top k sort
- [x] merge join
- [x] sort chunks
- [ ] unordered / partially ordered distinct
- [ ] window functions
- [x] outer joins
- [ ] finished support for nulls
- [x] planning for projections which use comparison operators (`SELECT x > 5 FROM ...`)

*Scalar operators*:

- [x] LIKE, ILIKE, etc. (needed for several TPCH queries)

**Comment by jordanlewis** [comment]
Dupe of #36507
