### ISSUE TITLE
changefeedccl: Rangefeed Correctness and Resilience

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#32944]
In 2.2 we are looking to convert Changefeeds to gather data using Rangefeeds, as opposed to the current method of polling data using the Export statement.  A current rangefeed-based implementation does exist and can be used with an experimental cluster setting, but there are a few architectural shortcomings that will need to be addressed. This issue outlines those changes.

## Current System

Below is a visual outline of the current rangefeed-based system, using an EIP Diagram to focus on the asynchronous architecture of the system:

![rangefeed organization-current system](https://user-images.githubusercontent.com/6969858/49675470-b8280100-fa2a-11e8-857f-1621b16f023a.png)

The system has three primary components:
+ The ChangeAggregatorProcessor, which outputs changes to the target Sink. (Note that a single Changefeed will have multiple ChangeAggregatorProcessors, but the behavior of that system is not directly impacted by the rangefeed switchover).
+ A singleton Processor on each replica serving a rangefeed, which pushes live changes to all rangefeeds connected to that replica.
+ Several Rangefeeds, which pull change data from remote replicas to the CA.
    + Each rangefeed receives events from its replica processor, and optionally from an initial "catch-up" iterator which is specific to a rangefeed. The catch-up iterator is eventually exhausted and the rangefeed reaches a steady state.

Notably, each CA uses multiple rangefeeds, and each processor serves multiple rangefeeds.

### Problem #1: Processor Blocking.

As highlighted here, the major problem of the current architecture is that a slow output sink on a CA can block the processor thread of its component rangefeeds:

![rangefeed organization-processor block](https://user-images.githubusercontent.com/6969858/49675646-6df34f80-fa2b-11e8-96b2-a678d702344b.png)

Blocking this thread also blocks progress on all other rangefeeds being served by that processor; its also the case that this will block *all* processors serving a CA at nearly the same time (modulo the small internal buffer of the GRPC stream.)

Since the processor is not allowed to miss a message from raft, but also is forbidden from blocking raft, this means that the entire processor and all served rangefeeds must be destroyed when the live event buffer from raft fills up after the processor is blocked for too long. This is not ideal behavior.

The proposed fix, which I believe is uncontroversial, is to add a per-rangefeed buffer as so:

![rangefeed organization-per-rangefeed buffer](https://user-images.githubusercontent.com/6969858/49675867-3933c800-fa2c-11e8-83af-4fdf8f535df4.png)

In this way the processor itself is never blocked on writing to a rangefeed, and thus a slow rangefeed won't block its peers. A rangefeed is still destroyed in this scenario if its individual live buffer overflows, but that only affects that single rangefeed, not the processor.

### Problem #2: Bad Ordering.

An additional problem is that the ordering of events from a rangefeed may violate the ordering variants that a Changefeed is supposed to guarantee, as illustrated here:

![rangefeed organization-incorrect ordering](https://user-images.githubusercontent.com/6969858/49675913-739d6500-fa2c-11e8-81ac-8c4df03709f8.png)

The first issue is that live events are arbitrarily interleaved with events from the catch-up iterator, meaning that a new live update for a row may precede an older update for a row retrieved from the scan. 
The second issue is that output from the iterator is not ordered correctly; in fact, it is strictly reversed, as data is stored in descending timestamp order.

The fix, which should be uncontroversial, is two-fold: add a small "re-order" buffer to the output of the iterator, and secondly only begin pulling from live events after the catch-up scan is completed.

![rangefeed organization-correct ordering](https://user-images.githubusercontent.com/6969858/49676079-24a3ff80-fa2d-11e8-9979-87cc1e824552.png)

Note that the re-ordering buffer does not have to contain the entire output of the scan, as the only ordering guarantee is per-key; therefore, it can use a buffer much smaller than the expected output.

This solution also leverages the per-rangefeed buffer; we start accumulating live events in the buffer as soon as the catch-up scan begins, but they won't be output until the catch-up is complete.  This way there is no gap in values between ending the catch-up and starting live events (although there may be some correctly-ordered duplicates).

### Problem #3: Changefeed Resilience

After these fixes are applied, the major remaining problem is that the changefeed is *still* insufficiently resilient in the case of a slow (or unavailable) sink.  This can be illustrated by considering the new backpressure in our modified scheme:

![rangefeed organization-slow sink backup](https://user-images.githubusercontent.com/6969858/49676166-87959680-fa2d-11e8-8496-07b98208e0b7.png)

This means that the per-rangefeed live buffer might overflow; we can't simply allow it to grow unbounded.  In that case, while the processor is safe, we still end up destroying the entire ChangeAggregator in the case of a slow sink; this will either cause the Changefeed to fail, or cause it to thrash attempting to re-establish connection to the sink. This represents a lot of wasted work.

I have two proposed fixes:

#### _(rejected)_ Proposal #1: Resilient Rangefeeds

In this solution, we make the Rangefeed more resilient so that it never has to fail due to backpressure from a slow sink:

![rangefeed organization-resilient rangefeed fix](https://user-images.githubusercontent.com/6969858/49676273-e22ef280-fa2d-11e8-8216-b4b95d48637f.png)

This is essentially what was proposed in #32655.  In this system, when the per-rangefeed live events buffer overflows, instead of cancelling the rangefeed it sets an "overflowed" flag, which stops the processor from writing new events to the buffer.  When sink recovers and the buffer is finally emptied, the rangefeed then instantiates a new catch-up iterator, as if it had just been started.

This allows the rangefeed to function essentially indefinitely; if the sink is not reading, then it will wait with a full buffer (and possibly an open iterator) until the Sink catches up.

However, there is one anticipated problem with this, and that is the notion that open iterators are *very expensive*; it is thought that opening too many catch-up iterators across the cluster could cause a real danger of thrashing from contention.

#### Proposal #2: CA Buffer

In this solution, we add two components: A central buffer in the CA with its own reader, and a "feed manager" which is able to restart feeds which have closed due to backpressure.

![rangefeed organization-central buffer fix](https://user-images.githubusercontent.com/6969858/49676444-9cbef500-fa2e-11e8-84e8-df06d37c1d24.png)

The central buffer means that sink backpressure no longer goes directly to the rangefeed processors; instead there is a buffer which the sink output reads from, and backpressure only goes back to component processors if the buffer is filled.

The feed manager, meanwhile, is able to note when rangefeeds have collapsed due to backpressure and re-start them later.  If the sink is slow and the buffer fills up, rangefeeds will close; once the buffer is empty (or just low), the feed manager will restart the feeds.

Importantly, the feed manager has the ability to *limit the rate at which feeds are started*; this is the method used to limit the number of catch-up iterators in progress across the cluster.  This is similar to how the current polling solution limits the number of active polling requests at a time using a worker pool; if all export requests are executed in parallel, it can cause the cluster to thrash.

The major drawback in this proposal occurs when the sink is routinely slow and we are "flagging",  i.e. feeds are repeatedly shutting down and we're essentially shipping off one buffer-load to the sink at a time.  Unfortunately, unless a rangefeed reaches a new checkpoint, we will end up duplicating its output the next time it is started. 

To ensure that the overall changefeed makes progress, the feed manager needs to prioritize starting rangefeeds for ranges which are the *furthest behind* in the overall changefeed, and needs to carefully limit the number of rangefeeds initially started to maximize the chance of at least one range making checkpointed progress.

**Comment by mrtracy** [comment]
### Work Tracking

- [ ] changefeedccl: Prevent slow consumers from blocking rangefeed Processor #32945
- [ ] changefeedccl: Correct ordering of events from a single rangefeed #32946
- [ ] changefeedccl: Implement ChangeAggregator buffer + rangefeed manager #32947

**Comment by danhhz** [comment]
This is a meta issue and the sub-work it represents is done. Closing
