### ISSUE TITLE
ui: roadmap

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#3326]
_This list doesn't include the existing UI features, but is just a list of planed features_

**For beta:**
- [ ] Cluster level stats (as listed below)
- [ ] Node level stats (as listed below)
- [ ] Store level stats (as listed below)
- [x] Explanatory tooltips for attributes
- [x] Bring graphs into overview page
- [ ] Ability to view data across different time scales
- [ ] Ability to change graph timescales
- [ ] Rich log view (by node/store)
- [x] Register your version of Cockroach prompt
- [ ] Support/report issue button
- [ ] Database level stats (as discussed)
- [ ] Table level stats (as discussed)
- [ ] Rich log view (searchable by table/db)
- [x] Table schemas
- [x] Table/database permissions
- [ ] Audit trail (when and which user)
  - [ ] Table/Database - created, changed, deleted
  - [ ] Permissions changes
  - [ ] Zone config changes
- [ ] Ability to view node/zone config in the UI
- [ ] Ability to modify node/zone config in the UI
- [ ] Prebaked SQL Queries from the UI (click a table to see rows, click “see more” to show more, etc)

**Stats List**

Primary (empty)
- [x] Status - healthy (green), unhealthy (yellow), dead (red) - ( counts/status): 20(g) / 4(y) / 1(r)
- [x] Node name (# nodes)
- [x] Stores (total stores)
- [x] Ranges (total ranges)

Storage
- [x] total count/bytes - 180 (54 KiB)
- [x] Live count/bytes - (live count / live value bytes + key bytes) 
- [x] intent count/bytes
- [x] sys count/bytes - metadata, trans records

Gateway Traffic - these are totals, and need ability to view by 1hr/10min/1min/10s

_SQL CRUD stats_
- [x] TRANSACTIONS (count)
- [x] SELECTS (count, bytes out)
- [x] UPDATES (count, bytes in)
- [x] INSERTS (count, bytes in)
- [x] DELETES (count)
- [x] CREATES (count)
- [x] DROPS (count)

_pgwire stats_
- [x] pgwire connections (count, bytes in/out)

Internal traffic - these are totals, and need ability to view by 1hr/10min/1min/10s
- [x] Total reqs count/bytes in /bytes out
- [x] Req Reads count/ bytes out
- [x] Req Writes count / bytes in

Range Activity 
- [x] Leaders (count)
- [x] Splits
- [ ] Merges
- [x] Rebalances
- [ ] Availability (%)

**Comment by maxlang** [comment]
I'm currently working on the first 5 items here.

**Comment by marcuswestin** [comment]
@maxlang: Nice! :+1:

**Comment by mrtracy** [comment]
Most of this was completed. This list does have several ideas which are unimplemented (mostly around zone configuration management), but this issue itself no longer serves as a roadmap for UI work. It hasn't been updated in over a year. Closing.
