### ISSUE TITLE
Change Data Capture: 2.2 Feature Set

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#33279]
_Meta-issue tracking the work we are targeting for [Change Data Capture](https://www.cockroachlabs.com/docs/stable/change-data-capture.html) in CockroachDB 2.2._

## General
- [x] Ability to create a changefeed on a table, to deliver per-row change messages to a configurable data sink
  - Apache Kafka is currently the only supported sink; also targeting a cloud storage sink
- [x] Option to include updated timestamps on messages
- [x] Option to interleaved "resolved timestamp" messages in a changefeed, indicating that all changes up to the specified cluster timestamp have been emitted to the changefeed
- [x] Expose changefeed metrics through CockroachDB Prometheus metrics endpoint
- [x] Re-plumb internals of changefeeds to use CockroachDB _rangefeeds_ to improve reliability and decrease latency (#31206)

## Kafka/Confluent Sink
- [x] Ability to create a changefeed that delivers per-row change messages for a table to an Apache Kafka topic
- [x] JSON output format
- [x] Avro output format (following Confluent's [encoding convention](https://docs.confluent.io/current/schema-registry/docs/serializer-formatter.html#wire-format)) (#28637)
  - Currently experimental; remaining work includes creating a stable and complete mapping of all CockroachDB types to Avro types (#32472, #34417, #34420, #34421)
  - [x] Fix Confluent schema registry compatibility issues with CockroachDB schema changes
- [x] Registration of Avro schemas in a Confluent [schema registry](https://docs.confluent.io/current/schema-registry/docs/index.html) instance (#28637)
- [x] Support TLS encryption when communicating with Kafka (#30834)

## Cloud Storage Sink
- [x] Ability to create a changefeed that delivers per-row change messages for a table in bulk to a cloud storage provider like AWS S3 or Google Cloud Storage (#28675)
- [x] Time based partitioning in cloud storage sink (#34473)

**Comment by glerchundi** [comment]
@rolandcrosby i don't know if you can answer these questions but anyway here it is:
* Protobuf: Based on a predefined schema.
* Google Cloud Pub/Sub: In architectures were we don't care (that much) about the ordering -preferring high availability-, this would be a fantastic addition. In case you're not going to work on this, would you be open to contributions?
* I saw that you have an idea of freeing CDC to the core version. Do you have a timeline? What parts of it do you plan to make it into the core?

WDYT?

**Comment by rolandcrosby** [comment]
Hi @glerchundi, thanks for your interest in our CDC functionality. In order --

* Protobuf output format: We haven't prioritized this yet, but it's something we could consider building if there's enough demand for it. Can you tell us more about your use case for a predefined schema, rather than one generated by CockroachDB based on the table schema?
* Google Cloud pub/sub: We haven't looked at this sink specifically, but we have seen some interest in general around emitting changefeeds to other data pipeline systems that don't have the same order/consistency guarantees as Kafka. We're a little hesitant to prioritize these kinds of sinks, since message ordering really is quite important in most CDC use cases we've looked at so far, but this is definitely something we can re-evaluate as we plan future releases.
* Core version of CDC: This remains an important item on our roadmap, but it has been moved out of scope for the 2.2 release (so we probably won't start working on it again until the end of Q2 2019). As currently planned and prototyped, the core CDC implementation won't include support for the Kafka or cloud storage data sinks. Instead, core changefeeds will stream their results over the Postgres protocol. #26707 has more detail on what this will look like.

I hope this answers your questions -- let me know if there's anything else I can help with. Thanks!

**Comment by glerchundi** [comment]
> * Protobuf output format: We haven't prioritized this yet, but it's something we could consider building if there's enough demand for it. Can you tell us more about your use case for a predefined schema, rather than one generated by CockroachDB based on the table schema?

I don't have a requirement yet so i'm not able to told you what would be the best for us. Without any data on the table I would opt for custom protobuf definition per table schema.

> * Google Cloud pub/sub: We haven't looked at this sink specifically, but we have seen some interest in general around emitting changefeeds to other data pipeline systems that don't have the same order/consistency guarantees as Kafka. We're a little hesitant to prioritize these kinds of sinks, since message ordering really is quite important in most CDC use cases we've looked at so far, but this is definitely something we can re-evaluate as we plan future releases.

Ok, our idea for these sinks is to decouple business tasks from the hot path. Most of the times we don't require ordering as we only want to guarantee that a fact has occurred.




> * Core version of CDC: This remains an important item on our roadmap, but it has been moved out of scope for the 2.2 release (so we probably won't start working on it again until the end of Q2 2019). As currently planned and prototyped, the core CDC implementation won't include support for the Kafka or cloud storage data sinks. Instead, core changefeeds will stream their results over the Postgres protocol. #26707 has more detail on what this will look like.

Cool, thanks for the pointers. Any umbrella/meta issue you can point me to so that I could get some updates?

Thanks

**Comment by rolandcrosby** [comment]
@glerchundi #30723 has more detail on the work that needs to happen to get core changefeeds ready for use in production.

**Comment by danhhz** [comment]
@rolandcrosby I think everything in this in done. I'll leave it to you to close once you're happy.
