### ISSUE TITLE
sql: Ecto compatibility

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#33441]
This is a list of issues found with Ecto (Exlixir). 
Note that most of these are not required to get Ecto working, but each of these can be a potential roadblock when migrating an existing app to cockroach.

* [ ] Defaults where arrays are set must be annotated, solving this with fragment on default definition
* [ ] Can't do any operation on a column or table where the operation is in the same migration as that objects creation
* [ ] #32917 Must do foreign keys in three separate migrations (add column, add an index on that column, add the constraint)
* [ ] Doesn't support Compound Data Types
  * [ ] #8318
  * [ ] #25123
* [ ] Doesn't support ENUM data Types
  * [ ] #24873
  * [ ] #25123
* [ ] #9683 Doesn't support unique index with where clauses
* [ ] #17511 Doesn't support stored procedures or functions
* [ ] Not possible to change stored query on a view, must drop the view and recreate
* [ ] #10735 named SAVEPOINTs

**Comment by DavidOliver** [comment]
I believe [support for the timestamp precision has been reverted](https://github.com/cockroachdb/cockroach/pull/42286).

Discussion at https://github.com/cockroachdb/cockroach/issues/32098#issuecomment-594545673.

**Comment by awoods187** [comment]
@DavidOliver this will be in 20.1 and you can see it in this beta (https://www.cockroachlabs.com/docs/releases/v20.1.0-beta.2.html)

**Comment by fire** [comment]
Note that #24897 is resolved.

> Not possible to change stored query on a view, must drop the view and recreate #24897

**Comment by fire** [comment]
> #32917 Must do foreign keys in three separate migrations (add column, add an index on that column, add the constraint)

#32917 in a pr stage.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[5257](https://cockroachdb.zendesk.com/agent/tickets/5257) has been linked to this issue.

**Comment by DavidOliver** [comment]
#32917 is resolved.

**Comment by rafiss** [comment]
note that named SAVEPOINT support will also be included in 20.1

**Comment by tlvenn** [comment]
It should be noted that with CDB 20.1 all the major issues have been fixed but [one](https://github.com/cockroachdb/cockroach/issues/50858) as soon as you are running tests. This is fixed on master but it has yet to be released.

Additionally:
- Support for arrays is broken since 19.2 (https://github.com/cockroachdb/cockroach/issues/51360)
- Support for `if_not_exists / if_exists` is missing for now (https://github.com/elixir-ecto/ecto_sql/issues/247)

**Comment by rafiss** [comment]
#50858 is closed and the fix will also be included in the next 20.1 release.

Thanks for filing those two new issues!

**Comment by escobera** [comment]
I found a problem when creating schemas with Ecto.Migration.

This code just hangs after the execution and the next migration never runs. I'm testing on 20.2

```
defmodule ProcessosApi.Repo.Migrations.CreateMySchema do
  use Ecto.Migration

  def change do
    execute "CREATE schema myschema;"
  end
end
```

I don't know if this is the correct place to report this. If not just lemme know and I'll move to the correct place.

Thanks in advance!

**Comment by lessless** [comment]
In light of the upcoming webinar - what are the plans for getting proper compatibility with Ecto?

**Comment by bryanhuntesl** [comment]
> In light of the upcoming webinar - what are the plans for getting proper compatibility with Ecto?

We’ve been running in production for a number of clients for a while (+ 6 months) now (erlang solutions). Using the Postgres driver and can’t think of any issues. 

Might be time to close this issue out unless there’s something we’ve been missing. Migrations issues etc are gone now.

**Comment by lessless** [comment]
Thanks for feedback @bryanhuntesl

**Comment by lessless** [comment]
Thanks for all your hard work, folks! I'm going to try it now and hope never to look back. 
The replication feature that you built into CockroachDB and backwards compatibility with PG means a word for indie devs such as myself.

**Comment by lessless** [comment]
@escobera won't you mind sharing your connection settings, please? I have few problems:

The first one is with SSL -  I’m running into an  `{:tls_alert, {:handshake_failure, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:1990 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}}`  with
```
ssl_opts: [
  verify: :verify_peer,
  cacertfile: '/Users/lessless/.postgresql/root.crt',
]
```

The second one with  specifying a cluster name? If I disable an SSL I’m getting following error `FATAL 08004 (sqlserver_rejected_establishment_of_sqlconnection) codeParamsRoutingFailed: missing cluster name in connection string`

I took connection params from “Connection parameters” tab and database value there seems to be a combination from cluster name and a database name `database = superfun-superfun-448.defaultdb` but that doesn't work.

**Comment by lessless** [comment]
@bryanhuntesl given that I ignore SSL host validation and create a database by hand I'm encountering a problem when running migrations: 


```
no match of right hand side value: {:error, %Postgrex.Error{connection_id: 0, message: nil, postgres: %{code: :syntax_error, detail: "source SQL:\nLOCK TABLE \"schema_migrations\" IN SHARE UPDATE EXCLUSIVE MODE\n^", file: "lexer.go", line: "215", message: "at or near \"lock\": syntax error", pg_code: "42601", routine: "Error", severity: "ERROR"}, query: "LOCK TABLE \"schema_migrations\" IN SHARE UPDATE EXCLUSIVE MODE"}}
```

**Comment by timothyvanderaerden** [comment]
@lessless to configure with SSL:

```exs
database: "superfun-superfun-448.defaultdb",
ssl: true,
ssl_opts: [
  cacertfile: "cc-ca.crt"
]
```
More info: https://hexdocs.pm/postgrex/Postgrex.html#start_link/1-ssl-client-authentication

To run migrations, `migration_lock` should be disabled since CockroachDB doesn't support table locking (as far as I know):

```exs
migration_lock: false
```
More info: https://hexdocs.pm/ecto_sql/Ecto.Migration.html#module-repo-configuration

**Comment by erszcz** [comment]
I confirm getting the error that @lessless mentioned above:

```
** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: 0, message: nil, postgres: %{code: :syntax_error, detail: "source SQL:\nLOCK TABLE \"schema_migrations\" IN SHARE UPDATE EXCLUSIVE MODE\n^", file: "lexer.go", line: "215", message: "at or near \"lock\": syntax error", pg_code: "42601", routine: "Error", severity: "ERROR"}, query: "LOCK TABLE \"schema_migrations\" IN SHARE UPDATE EXCLUSIVE MODE"}}
```

Running migrations used to work fine - this started happening after an upgrade from `ecto_sql` 3.5.4 to 3.7.1.

**Comment by benonymus** [comment]
Hey,

I am dabbling with moving to cockroachDB.

When I am running some historical migrations, this seems to not work:

```
    alter table(:session_chats) do
      modify :session_id, references(:sessions, on_delete: :delete_all),
        from: references(:sessions, on_delete: :nothing)
    end
```

The error: 
```
alter table session_chats
** (Postgrex.Error) ERROR 42710 (duplicate_object) duplicate constraint name: "session_chats_session_id_fkey"
```

Are these not supported? Or how would I need to rewrite them?
