### ISSUE TITLE
ui: surface logical plans for statement fingerprints (tracking issue)

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#34233]
## Description

Display sampled logical plans for statement fingerprints.

## Breakdown

Legend:
💯- merged
👍- on track
⚠- behind
⛑- off track

### Initial prototype to Production (#26494)

For Cutoff | On Track? / Status | PR | Issue | Description
---|---|---|---|---
Jan 7 | 💯 | #33020 || backend work to sample logical plans
Jan 7 | 💯 | #33483 || frontend work surface logical plans
~Jan 28~ Feb 4 | 💯 | #33726 || [fix] frontend bug
~Jan 28~ Feb 4 | 💯 | #33561 || [fix] sql: fix the collection of logical plan samples
~Jan 28~ Feb 4 | 💯 | #34231 || [fix] sql: use time-based sampling for logical plans

### Implement UI designs for Feb 11/18 ([Zeplin](https://app.zeplin.io/project/5c40e9dab2616abf79e3eb99/dashboard))

For Cutoff | On Track? / Status | PR | Issue | Description
---|---|---|---|---
Feb 11 | 👍merged | #34531 || ui: implement logical plan design [to 95%]
(push to March) | | | #34545 | ui: fix known design issues [the other 5%]
Feb 11 | 👍 in review | #34724 |#34595 | (sql) scrub sampled logical plan
Feb 11 | |  | #34594 | (sql) bug? “row source to node id” as last node / discrepancy between sample and explain

Misc UI:
- [ ] Related to bug fix from #34231:
  - [ ] Now that each sample has a timestamp, surface most recent plan across all nodes
- [ ] Test UI on big queries:
  - [ ] Add an `overflow: scroll` on the div containing the plan to prevent text that runs off the screen ([slack](https://cockroachlabs.slack.com/archives/C3T5LG9R8/p1548448436071100))
- [ ] #34020: Is there a better sampling strategy for how we sample logical plans?

**Comment by knz** [comment]
All issues but the last have been addressed. The last is relatively unrelated so there is no need to keep it block this tracking issue.
