### ISSUE TITLE
exec: tracking issue for TPC-H queries

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#34497]
This issue tracks missing `experimental_vectorize` features by TPC-H query.

- [x] Q2
  - [x] LIKE
  - [x] MIN
- [x] Q3	inner 1 col mergejoin
- [x] Q4	semi hashjoin
- [x] Q7
  - [x] OR expr
  - [x] ComparisonExpr on char and string (#39464)
  - [x] AND expr projection
- [x] Q8
  - [x] case expression
- [x] Q11
  - [x] float * int 
- [x] Q12
  - [x] sum on integer types (https://github.com/cockroachdb/cockroach/issues/38845)
  - [x] case
- [x] Q13
  - [x] NOT LIKE
  - [x] COUNT(col)
- [x] Q15	max
- [x] Q16
  - [x] LIKE
  - [x] anti merge join
  - [x] `p_size IN (49, 14, 23, 45, 19, 3, 36, 9)`
  - [x] ComparisonExpr on varchar/char and string (#39464)
  - [x] distinct aggregation (#39242)
- [x] Q18	semi merge join
- [x] Q19
  - [x] tuple cmp
  - [x] OR expr
  - [x] AND expr projection
- [x] Q20
  - [x] LIKE
  - [x] int/float comparison in selection (#39464)
- [ ] Q21
  - [x] ComparisonExpr on char and string (#39464)
  - [ ] LEFT ANTI merge join with ON expression (#38018)
  - [ ] LEFT SEMI hash join with ON expression (#38018)
- [x] Q22	substring

**Comment by yuzefovich** [comment]
The only remaining query is Q21, but the plan for it changed in July, and the ON conditions of joiners aren't used anymore, so I'll close this issue. cc @asubiotto @jordanlewis 🎉

**Comment by jordanlewis** [comment]
Wow, another great milestone!
