### ISSUE TITLE
19.1 release blockers list

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#35554]
Possible blockers for the 19.1 release.

- [x] #34695 (Scaledata roachtest node crashing with “unexpected non-pending txn in augmentMetaLocked”) @andreimatei 
- [x] #35424 (Consistency violation crash on fixture import) @andreimatei / @tbg 
- [x] #35559 / #33120 overlapping range descriptor after merge @bdarnell 
- [x] #34241 racy access to ObservedTimestamps causing marshalling panics @nvanbenschoten
- [x] #35803 updated marshalling panic @nvanbenschoten 
- [x] #35812 TPCC index inconsistency @nvanbenschoten 
- [x] #35988 schema change crash @vivekmenezes 
- [x] #36022 missing row during consistency check @nvanbenschoten 
- [x] https://github.com/cockroachdb/cockroach/issues/12768#issuecomment-475964523 slow downreplication @bdarnell 
- [x] #36025 poor replication decisions @ajwerner 
- [x] #36679 Corruption: external file have non zero sequence number @dt 
- [x] #36385 Creating an index produced disk stall error @dt  
- [x] #36381 creating an index, user experienced OOM @dt 
- [x] #36430 add a knob to control the speed of schema changes @lucy-zhang (we added a knob but it didn't slow things down @awoods187 )
- [x] #36044 table name cache is not populated after misses
- [x] #36574 distsql backward compatibility fail
- [x] https://github.com/cockroachdb/cockroach/issues/35986#issuecomment-479986933 check 3.3.2.4 fails in tpcc-1000 @bdarnell  
- [x] https://github.com/cockroachdb/cockroach/pull/36714 crash migrating from 19.1-beta to 19.1 @tbg 
- [x] #35142 closedts stalls resulting in changefeed stalls @danhhz 
- [x] #36381 OOM with CREATE INDEX @vivekmenezes 
- [x] #36861  consistency check failure during import @tbg, @andreimatei (fix is in, linked issue is still open pending more testing)
- [x] #36937 schema change (mvcc stats) replica corruption
- [x] #37056 hung CREATE DATABASE due to replica with invalid term failing to catch up @ajwerner

**Comment by petermattis** [comment]
@tbg Does https://github.com/cockroachdb/cockroach/issues/34241 also warrant being on this list? It doesn't look like it is causing corruption, yet it is super suspicious.

**Comment by awoods187** [comment]
We need to add https://github.com/cockroachdb/cockroach/issues/35559 to this list (either addressing it or turning off range merging)

**Comment by tbg** [comment]
@petermattis yes, definitely.

**Comment by knz** [comment]
We need to also look at all the tests currently skipped:

- some are related to key features (import CSV) - the skipped test may be hiding a bug
- some were designed to exercise stability - the skipped test may be hiding unstability

**Comment by tbg** [comment]
I updated the list with the merge bug and the marshaling panic.

**Comment by gigatexal** [comment]
All of the possible blockers seem to have been closed/fixed. So does that mean the release is imminent?

**Comment by petermattis** [comment]
All of the release blockers were fixed, and 19.1 has been released.
