### ISSUE TITLE
build: Upgrade to Go 1.12

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#35637]
Open standing issues:

- [x] darwin / jemalloc #35620
- [x] homebrew linker segfault  Homebrew/homebrew-core#37788 + #35657.
- [x] SQL/kv encoding problems  #35636
- [x] innocuous `TestCrashReportingPacket` failure #35792
- [x] make lint also fails if you're using go 1.12

**Comment by bdarnell** [comment]
When built in the homebrew CI environment, the go 1.12 linker segfaults: https://github.com/Homebrew/homebrew-core/pull/37788. We haven't seen that elsewhere so I don't know what, if anything, we can do about that.

This issue also makes the homebrew-core cockroach package unbuildable (since brew insists on using the latest version of everything). We'll need to either fix the go 1.12 issues or go back to our own tap for 19.1: #35657.

**Comment by benesch** [comment]
Linker bug appears to be known upstream: https://github.com/golang/go/issues/30908

**Comment by bdarnell** [comment]
`make lint` also fails if you're using go 1.12:

```
    --- FAIL: TestLint/TestVet (0.04s)
        lint_test.go:1357: 
            vet: flag "-shadow" not defined
        lint_test.go:1357: 
            Run "go help vet" for more information
```

**Comment by dt** [comment]
What's the difference between this and #35197?

**Comment by knz** [comment]
The other issue was a *plan* to do things with an attempt to identify problem areas *ahead of time*.

This issue here is the list of *actual problems*  that fell out of having some folk trying go 1.12 "by accident".

I agree that given where we are we can probably combine them. Will close the other issue.

**Comment by dt** [comment]
I think `lint` is happy now with #36486 and #36527

**Comment by chenrui333** [comment]
It looks like there is some issue with homebrew 2.1.7 upgrade: https://github.com/Homebrew/homebrew-core/pull/40048

```
13:24:41 tar xof /Users/brew/Library/Caches/Homebrew/downloads/af0196d886dbaae1bb8c23b91f4cc38ef4dabdee0ede47364776c6f4094859ca--cockroach-v2.1.7.src.tgz -C /private/tmp/d20190519-47502-nel76u
13:24:41 cp -pR /private/tmp/d20190519-47502-nel76u/cockroach-v2.1.7/. /private/tmp/cockroach-20190519-47502-12kwzdy/cockroach-v2.1.7
13:24:41 chmod -Rf +w /private/tmp/d20190519-47502-nel76u
13:24:41 ==> make buildoss
13:24:41 make -C src/github.com/cockroachdb/cockroach buildoss
13:24:41 make[1]: Entering directory '/private/tmp/cockroach-20190519-47502-12kwzdy/cockroach-v2.1.7/src/github.com/cockroachdb/cockroach'
13:24:41 GOPATH set to /private/tmp/cockroach-20190519-47502-12kwzdy/cockroach-v2.1.7
13:24:41 go 1.12+ is known to produce invalid crdb builds, see https://github.com/cockroachdb/cockroach/issues/35637
13:24:41 Disable this check with IGNORE_GOVERS=1.
13:24:41 make[1]: *** [Makefile:660: build/defs.mk] Error 1
13:24:41 make[1]: Leaving directory '/private/tmp/cockroach-20190519-47502-12kwzdy/cockroach-v2.1.7/src/github.com/cockroachdb/cockroach'
13:24:41 make: *** [Makefile:6: buildoss] Error 2
13:24:41 
13:24:41 ==> Formula
13:24:41 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cockroach.rb
```

**Comment by zbeekman** [comment]
Can someone please explain your versioning system? Chronologically 2.1.7 is the most recent release, but 19.... is the version you're shipping on your website.

For packagers this is not easy to find or well documented info.

Cheers 🍻

**Comment by knz** [comment]
The most recent version is 19.1. However we also provide bug fixes in the previous releases 2.1 and security fixes in 2.0.
This is akin to how Postgres still provides bug fixes to version 10.8 and 9.6 etc. even though version 11.3 is the latest one.

**Comment by knz** [comment]
@zbeekman @chenrui333 
Please also read the linked issue: https://github.com/cockroachdb/cockroach/issues/35657
We do not support nor recommend building CockroachDB with any other version of Go than the one specifically allowed by our Makefile.
Thanks

**Comment by zbeekman** [comment]
> This is akin to how Postgres still provides bug fixes to version 10.8 and 9.6 etc. even though version 11.3 is the latest one.

Sure, I'm familiar with supporting maintenance branches and backporting. The skip from 2 to 19 was the source of my confusion combined with it being somewhat unclear which versions are currently supported, and which is the newest, and where the major version numbers are coming from.

As far as building against older `go`s goes, I'm not sure if this will be possible in core, and what the best way to handle it is... You can always recommend (in your own documentation and site) that users install from your own tap if they want the most up-to-date version. In that case, we will probably continue to ship versions that we can, when they can be built against the latest go, and for newer releases that require older gos, we will probably just end up lagging behind the most recent release.

It would be really great if we could find a way to build the latest releases with the latest go for homebrew. I do understand, that it can be hard to keep up with the latest compilers and tooling though. Hopefully we can get to a place that is good for everyone.

:beers:

**Comment by bdarnell** [comment]
Another go 1.12 issue: If cockroach is built with 1.12, it will fail to start on systems where the file descriptor hard limit is below our recommended amount (previously it would log a warning and continue). See #37685 and golang/go#30401
