### ISSUE TITLE
exec: tracking issue for vectorized engine

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#36507]
This issue is an "epic" to track work in the `pkg/sql/exec` vectorized engine.

__Features__:

P0
- [x] serialization to Apache Arrow
  - [x] encoder and decoder that takes coldata.Batch/Vec to Arrow data structures and back
  - [x] ~(not absolutely necessary) transparent use of Apache Arrow data structures as coldata.Batch/Vec~
  - [ ] decimal encoding #37044
  - [x] Use uint8 null bitmaps #37045
- [x] distribution - distributed flows must be plannable. Needs serialization.
  - [x] stream encoder and decoders that operate on columnar batches instead of encdatumrows.
  - [x] unordered synchronizer -  some async component to eagerly decode. Either reuse rowchannel or write columnar batch equivalents.
  - [x] ordered synchronizer
  - [x] outbox/inbox
  - [x] hash router
    - 2 weeks: PR out (#36173)
- [x] metadata propagation. Make sure to not introduce metadata into operators. Metadata should forward to the end of flows. (#36039)

P1
- [x] memory monitoring #37301
- [x] disk spilling - computation that hits a memory limit must fall back to disk containers. Needs serialization.
  - [x] spilling a queue - first in first out
  - [x] spilling for sort computations - external sort
  - [x] spilling for hash joins
    - [x] ordinary hash lookup - how to make this fast? "grace" hash join?
    - [x] marked rows for outer joins
  - [ ] spilling window computations

P2
- [x] tracing / stats: understand quantity of rows/batches flowing through operators. selection vector selectivity, maybe?
- [x] explain (shows flow of exec operators)

__Relational operators__:

- [x] index / lookup join (accomplished with plan wrapping)
- [x] offset
- [x] finish hash aggregate
- [x] sort chunks
- [x] other unhandled operators - plan wrapping
- [x] top k sort
- [x] merge join
- [x] unordered / partially ordered distinct
- [x] add null support to ordered distinct
- [x] add null support to sorter
- [x] planning for projections which use comparison operators (`SELECT x > 5 FROM ...`)
- [x] COUNT agg func (needed for distributed TPCH queries) #38063
Next:
- [ ] window functions

**Scalar operators**:
- [x] LIKE, ILIKE, etc. (needed for several TPCH queries)
- [x] min and max support
- [x] random builtins like string matching (needed for TPCH queries)

**Comment by tim-o** [comment]
Zendesk ticket #[3223](https://cockroachdb.zendesk.com/agent/tickets/3223) has been linked to this issue.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3528](https://cockroachdb.zendesk.com/agent/tickets/3528) has been linked to this issue.

**Comment by yuzefovich** [comment]
Closing in favor of #34497
