### ISSUE TITLE
sqlsmith: meta TODO list

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#36944]
SQL features to teach sqlsmith:

- [ ] correlated subqueries
- [ ] sequences
- [ ] views
- [ ] interleaved tables
- [ ] foreign keys
- [x] index hinting
- [ ] favor inserts over drops and deletes, or something else where medium-large tables are tested more. as is drop and delete happens enough that tables are empty quite a lot.
- [ ] various `ON CONFLICT DO UPDATE` assignments
- [ ] `USING DEFAULTS`

Tweak sqlsmith internals:

- [x] improve the random type picking to be aware of the available columns in the FROM tables of a SELECT so we can avoid needing to generate constants as often
- [ ] make complexity a configurable option. useful for generating memo or comparison queries that are smaller and run faster.

Other areas to apply sqlsmith to:

- [ ] postgres differential comparison testing for correctness
- [ ] datum round tripping (https://github.com/mjibson/cockroach/tree/rsg-datum)

Other improvements:
- [x] createRandDatum needs a list of special values it sometimes picks from for each datum type
- [x] the crasher mechanism in the RSG sqlsmith test prints the table structure at the end of the test. it should instead be snapshotted at the time of the crasher because sqlsmith has alters now.
- [x] run tests on a multi-node, disk-backed cluster
- [ ] index hint tests (#21215)
- [ ] use the optimizer testing knob that can disable norm rules and do comparison tests. for example disable a random 50% of the rules and compare some sqlsmith queries. any differences are probably bugs.

**Comment by mjibson** [comment]
cc @jordanlewis @awoods187

**Comment by mjibson** [comment]
cc @justinj

**Comment by justinj** [comment]
Another idea we talked about: using the optimizer's ability to register a callback that fires when a rule is used to see if SQLSmith is hitting every rule. Search for uses of `NotifyOnMatchedRule`.
