### ISSUE TITLE
exec: implement window functions in vectorized engine

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#37040]
- [x] #37034 add sorting partitioner
- [x] #37035 support all window functions (i.e. not aggregates)
- [x] #37036 support all aggregates as window functions
- [x] #37037 support window frames
- [x] #37039 add optimized versions of aggregates/window functions in some cases
- [ ] #37228 add hashing partitioner

**Comment by jordanlewis** [comment]
Should we just close this in favor of #37228 since that's the only remaining task?

**Comment by yuzefovich** [comment]
Yeah, I think it's ok to close this. We're still missing the support of some aggregate functions used as window functions (required for full parity with the row-by-row engine) - those that are supported via the "default agg fn" in the vectorized engine as well as the support for `FILTER` clause. I'll open up separate issues for those. #37228 is an optimization that will allow the vectorized engine to not sort the input data set when `ORDER BY` clause is omitted by `PARTITION BY` clause is present.
