### ISSUE TITLE
perf: optimize locking on hlc.Clock

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#37276]
Currently we observe large amounts of contention on the hlc.Clock mutex. Some of the worst offenders can be optimized. This is a meta issue to track those optimizations.

- [ ] #37277 `storage.Store.Send()` interacts with the clock twice when it could do it once.
- [x] #37279 `kv.DistSender.sendSingleRange()` calls Update which returns a value that isn't used, preventing a fast path optimization.
- [ ] #37278 `Replica.tick()` reads the current time twice while holding the raftMu and could get away with not calling it at all.

**Comment by erikgrinaker** [comment]
I've been looking at some mutex profiles with a 5-node 8-core cluster running various `kv`, `tpcc`, and `ycsb` workloads with `COCKROACH_MUTEX_PROFILE_RATE=1`. HLC mutex contention hovers around 1% of overall contention, always on `NowAsClockTimestamp()`. Here's an example profile during YCSB/B: [mutex.pprof.gz](https://github.com/cockroachdb/cockroach/files/7532238/mutex.pprof.gz).

This contention appears negligible, and the main contention is in other code paths than those outlined above (`Replica.maybeQuiesceLocked` and `connExecutor.txnStateTransitionsApplyWrapper`). I'm therefore going to close this issue and the linked issues and PRs, as it appears the previous work on HLC mutex contention has alleviated most of the problems.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-4441](https://cockroachlabs.atlassian.net/browse/CRDB-4441) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-37276` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-4441](https://cockroachlabs.atlassian.net/browse/CRDB-4441) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-37276` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-4441](https://cockroachlabs.atlassian.net/browse/CRDB-4441) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-37276` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-4441](https://cockroachlabs.atlassian.net/browse/CRDB-4441) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-37276` :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-4441](https://cockroachlabs.atlassian.net/browse/CRDB-4441) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-37276`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
