### ISSUE TITLE
exec: add external storage

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#37303]
The work that needs to be done here is dependent on #37301 in that memory monitoring needs to provide feedback to an execution flow as to when a spill should happen, but the majority of this work can be completed in parallel. This issue is intended as a tracking issue and a description of the surrounding infrastructure for external storage, as well as a quick overview of the algorithmic options.

__Use Case__
External storage needs to be added so that queries that consume a large amount of memory have a chance to complete by spilling data to disk. There are four main use cases we need to support external storage for:
- [x] spilling a queue - first in first out (e.g. `hashRouter` buffering output)
- [x] spilling for sort computations - external sort
    - Use an external merge sort. This requires spilling a large amount of batches and the ability to read at a fine granularity from each batch (we need to keep the first n rows from each batch in memory to perform a merge, there is also the possibility of a recursive merge). The design of the ordered synchronizer will probably further inform the design of this merge cc @solongordon. Note that we might also have to sort variable length data types.
- [x] spilling for hash joins
    - The first option is to use a naive external hash join by buffering the whole left + right input, reading a batch at a time from the right input into memory, reading the whole left input, emitting the join, discarding the current right batch and repeating with the next right batch.
    - The GRACE hash join is an improvement on this algorithm by avoiding re-reading the left input but is more complicated (see #24582)
- [ ] spilling window computations
    - I am not familiar with what would be needed for this cc @yuzefovich 

__Infrastructure__
What makes most sense to me is to reuse the `SortedDiskMap` infrastructure that already exists for row-based external storage. This would use RocksDB under the hood and has the advantage of implementing temp storage management features (e.g. cleaning up orphaned temp storage files, throttling disk IO). The alternative is to simply flush serialized batches to files which will avoid unnecessary RocksDB features (e.g. compactions) but will require the implementation of temp storage management features. Each key could hold a batch or less (e.g. for the sorter where we want to do partial batch reads as we can't paginate values) and just be a sequence number, @ajkr recommends keeping values at 32kb, which is the size of the block cache. The serialization format will be the standard Arrow IPC format, as used for remote communication.

**Comment by asubiotto** [comment]
Considering this done since sorts and joins spill to disk in the vectorized execution engine. Create #45880 to track disk spilling for window functions we support.
