### ISSUE TITLE
unsupported TPC-DS queries tracking issue

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#37464]
This issue tracks features that are unimplemented but needed for TPC-DS queries (also some of the queries that didn't finish within 10 minutes or so on scale factor 1 - 1GB - dataset on my laptop).

- [ ] Q1, Q4, Q11, Q14, Q23, Q24, Q30, Q31 - multiple use of CTE clause #21084
- [ ] Q2 - `pq: no data source matches prefix: wswscs` - multiple CTEs or a CTE used in another CTE?
- [ ] Q5, Q18, Q22 - `unknown function: rollup()`
- [ ] Q7, Q13, Q19, Q25, Q26, Q29, Q45 - didn't complete in 10 minutes or so
- [ ] Q17, Q35, Q39 - `pq: unknown function: stddev_samp()`
- [ ] Q27, Q36, Q70, Q86 - skipped due to parsing errors (queries need modifications)

Note: I ran only first 45 (out of 99) queries so far, so the list will likely be updated.

**Comment by yuzefovich** [comment]
Updating the issue since
- we no longer hit memory limit on Q4, Q39, Q78
- we now can run Q7, Q13, Q17, Q19, Q25, Q26, Q29, Q45, Q46, Q48, Q50, Q61, Q66, Q68, Q84, Q85 within 5 minutes

**Comment by yuzefovich** [comment]
Recent runs [have shown](https://docs.google.com/spreadsheets/d/1HFfV7jfn2rC4kEVONcnc0a_3hnOU7M5bcVw-e5Doot0/edit?usp=sharing) that we have regressed between 9ba1a810352e0caf715cc9940cc and b32bbb59bbed8a0afa47e4b on the following queries:
- Q1: no longer completes in 5 minutes
- Q68: 19x slowdown
- Q6: 4.5x slowdown
- Q37, Q61: about 2x slowdown (still extremely fast)
- Q81: 1.6x slowdown
- Q28, Q30, Q51, Q63, Q72, Q87, Q97, Q98: 1.2-1.5x slowdown

**Comment by DrewKimball** [comment]
For Q6, disabling the vectorized hash aggregator causes a significant speedup. Nearly all the time for the vectorized hash aggregator is spent in `hashBasedPartitioner.partitionBatch`, specifically when the tuples are enqueued into the partitioned disk queues. So, the slowdown is because the external hash aggregator has to load all tuples onto disk, whereas the row-wise aggregator maintains as many buckets as are required for the entire input.

**Comment by DrewKimball** [comment]
A possible solution might be to have the external aggregator perform a pass with the in-memory aggregator _before_ partitioning, and then only partition the tuples that don't fit into the existing buckets.

**Comment by DrewKimball** [comment]
With regard to Q64, changing the join reorder limit to 10 joins gets the runtime down to a manageable ~17 seconds on my machine. Though, changing it to 20 brings it back up to ~1 minute - maybe because of overestimating predicate selectivity?

I'm not sure it's a good idea to increase the default join reorder limit, but it might be worth exploring left-deep trees for some number of joins beyond the limit, maybe proportional to the ratio between the number of bushy and the number of left-deep trees.

**Comment by yuzefovich** [comment]
Updated the numbers using 23.1.0-alpha.7.

Notable (at least 33%) speedups since the last update:
```
- Q1:	before: 2074.44s after: 98.21s	 -95.27%
- Q4:	before: 75.39s	after: 48.08s	 -36.22%
- Q6:	before: 20.44s	after: 8.29s	 -59.44%
- Q16:	before: 5.15s	after: 3.18s	 -38.25%
- Q24:	before: 0.04s	after: 0.02s	 -50.00%
- Q30:	before: 3.73s	after: 2.02s	 -45.84%
- Q31:	before: 12.47s	after: 8.29s	 -33.52%
- Q37:	before: 0.15s	after: 0.02s	 -86.67%
- Q39:	before: 97.26s	after: 53.34s	 -45.16%
- Q40:	before: 1.12s	after: 0.61s	 -45.54%
- Q41:	before: 0.07s	after: 0.04s	 -42.86%
- Q45:	before: 2.01s	after: 1.17s	 -41.79%
- Q49:	before: 0.46s	after: 0.30s	 -34.78%
- Q60:	before: 11.75s	after: 7.52s	 -36.00%
- Q61:	before: 0.24s	after: 0.10s	 -58.33%
- Q75:	before: 5.76s	after: 2.38s	 -58.68%
- Q81:	before: 15.51s	after: 7.04s	 -54.61%
```

Notable (at least 33%) slowdowns:
```
- Q17:	before: 1.53s	after: 2.36s	 54.25%
- Q25:	before: 1.10s	after: 1.54s	 40.00%
- Q28:	before: 7.14s	after: 18.92s	 164.99%
- Q32:	before: 0.06s	after: 0.08s	 33.33%
- Q34:	before: 2.04s	after: 2.79s	 36.76%
- Q44:	before: 6.35s	after: 11.73s	 84.72%
- Q56:	before: 1.18s	after: 1.82s	 54.24%
- Q73:	before: 1.95s	after: 2.61s	 33.85%
- Q88:	before: 7.28s	after: 10.08s	 38.46%
- Q92:	before: 0.04s	after: 0.07s	 75.00%
- Q96:	before: 1.60s	after: 2.22s	 38.75%
```
