### ISSUE TITLE
sql: Add Data Type Formatting Functions

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#3781]
Eventually we are going to want to add support for converting various data types to formatted strings, and from formatted strings back again. Postgres handles this well and provides a lot of detail on the specifics of its implementation [here](http://www.postgresql.org/docs/8.1/static/functions-formatting.html).

- [ ] to_char(timestamp, text)
- [ ] to_char(interval, text)
- [ ] to_char(int, text)
- [ ] to_char(double precision, text)
- [ ] to_char(numeric, text)
- [ ] to_date(text, text)
- [ ] to_timestamp(text, text)
- [ ] to_timestamp(double precision)
- [ ] to_number(text, text)

**Comment by JackKrupansky** [comment]
PG also has the concept of a pair of I/O Functions for each datatype, one function to parse and one to format. The pg_type table names that pair of I/O functions, as well as a pair of binary send/receive functions.

Ultimately, there are any number of format/parse or serialize/deserialize function pairs. For example, encoding of datum values for storage in the KV store (like the decimal type.)

**Comment by jkozlowski** [comment]
- [ ] to_char(timestamp, text)
- [ ] to_char(interval, text)
- [ ] to_char(int, text)
- [ ] to_char(double precision, text)
- [ ] to_char(numeric, text)
- [ ] to_date(text, text)
- [ ] to_timestamp(text, text)
- [ ] to_timestamp(double precision)
- [ ] to_number(text, text)

**Comment by vaskinyy** [comment]
I think I'll give it a try

**Comment by spencerkimball** [comment]
@mjibson could you prioritize this issue?

**Comment by tomholub** [comment]
These are useful. Is there currently any way to convert a timestamp to a string?

Legacy sql snippet: `to_char(timestamp, 'YYYY-MM') as month`
>  unknown function: to_char()

**Comment by mjibson** [comment]
We have a `experimental_strftime` function that can do that: https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#date-and-time-functions

**Comment by tomholub** [comment]
Perfect, thanks! Works great. Thanks for the swift response.
```sql
select experimental_strftime(now(), '%Y-%m');
```

**Comment by awoods187** [comment]
This is commonly use with INTERVAL (http://www.postgresqltutorial.com/postgresql-interval/)

**Comment by jordanlewis** [comment]
This is so unspecific as to be unactionable.

**Comment by rafiss** [comment]
Re-opening, because we still could add these functions. I added a checklist in the original issue description.

**Comment by awoods187** [comment]
I ran into this today when doing a recursive demo:

```SQL

WITH RECURSIVE rec AS (
        SELECT id, 0 AS degree
        FROM employees
        WHERE id = 1 -- John, the CEO
    UNION ALL
        SELECT e.id, rec.degree + 1 AS degree
        FROM employees e
        JOIN rec ON e.manager_id = rec.id
)
SELECT
    'John and ' || employees.name || ' are separated by ' ||
    TO_CHAR(rec.degree, '9') ||
    ' degrees of separation'
FROM employees
JOIN rec
    ON (employees.id = rec.id)
    WHERE employees.name = 'George';
```

**Comment by MEschenbacher** [comment]
I came across the unavailability of postgres' `to_timestamp` while moving applications from postgresql to cockroachdb.

Is there a statement which replaces `to_timestamp` and is supported by both postgresql and cockroachdb?
```sql
select to_timestamp(1586233649);
select to_timestamp('1586233649');
```

**Comment by insaner** [comment]
Just ran into this as well. Shame that #7976 and #9018 were abandoned (4 years ago?). The needed function in my case was `to_char()`. 

I worked around it by using `SELECT *, my_timestamp_col::TIMESTAMP::DATE as date_fmt FROM  mytable`.

As well, neither of `experimental_strftime(my_timestamp_col, 'YYYY-MM-DD')`  or `extract('date', my_timestamp_col)` worked.

**Comment by rafiss** [comment]
CockroachDB does support int->timestamp cast, though it is an experimental feature. See https://www.cockroachlabs.com/docs/stable/int.html#supported-casting-and-conversion (Postgres does not support this, so it doesn't address the question of finding something that works for both DBs.)

**Comment by bangeneticalgorithms** [comment]
I was trying to get a cockroach based backend working with Apache Superset (a very popular visualization framework). But it fails to work on CockroachDB because to_timestamp() has not yet been implemented. It would be nice if this issue is addressed.

**Comment by LeviticusMB** [comment]
Add `format()` to the list.

**Comment by lucacri** [comment]
The `to_char` function is used in Laravel Nova in the aggregate queries. It generates the following

```sql
select to_char("users"."created_at" - interval '4 HOUR', 'YYYY-MM-DD') as date_result, count("users"."id") as aggregate from "users" where "users"."created_at" between 2021-06-22 00:00:00 and 2021-06-28 19:56:46 group by to_char("users"."created_at" - interval '4 HOUR', 'YYYY-MM-DD') order by "date_result" asc)
```

Implementing the time functions will definitely improve the compatibility with PostgreSQL, and make adoption easier

**Comment by korpa** [comment]
> I was trying to get a cockroach based backend working with Apache Superset (a very popular visualization framework). But it fails to work on CockroachDB because to_timestamp() has not yet been implemented. It would be nice if this issue is addressed.

@bangeneticalgorithms Superset 1.0 works fine with CockroachDB. After Upgrading to v1.2 following issue appears: https://github.com/apache/superset/issues/15825

**Comment by altanozlu** [comment]
any news ?

**Comment by korpa** [comment]
to_timestamp was developed: https://github.com/cockroachdb/cockroach/pull/82523
But will not released in 22.1.x https://github.com/cockroachdb/cockroach/pull/82523#issuecomment-1150742165

**Comment by intern7777** [comment]
I think `to_char` seems to be documented as if it is supported already. Am I reading it wrong?
 ![Screenshot](https://user-images.githubusercontent.com/110012353/183770870-ed551209-0ea4-4fc0-a16e-674850dfc95e.png)
https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#date-and-time-functions

**Comment by otan** [comment]
> I think to_char seems to be documented as if it is supported already.

the one org version works, yes.
----

`to_char(timestamp[tz], string)` is needed by AWS DMS during "validation" mode.

**Comment by rafiss** [comment]
Update: `to_char(timestamp, text)` and `to_char(interval, text)` (https://github.com/cockroachdb/cockroach/issues/91156) will be available in v22.2.1, coming out in December.
