### ISSUE TITLE
sql: partitioning & zone config enhancements 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#38877]
**Show Partitions in SQL**
- [x] `SHOW PARTITIONS FOR <table>` #38436 @rohany 
- [x] `SHOW PARTITIONS FOR <index>` #38436 @rohany
- [x] `SHOW PARTITIONS FOR <database>` #38436 @rohany
- [x] `SHOW CREATE TABLE` shows constraints as described in #39076 @rohany
- [ ] [docs team] Document internal tables ([#2957](https://github.com/cockroachdb/docs/issues/2957)) as well as these scripts in associated partitioning guides ([#4978](https://github.com/cockroachdb/docs/issues/4978)) @rmloveland 
----

**Improve partitioning user experience**

- [x] By default, forbid users from creating non-partitioned secondary indexes on partitioned tables as described in #38475
- [x] Allow for the same name on table and index as discussed in #20880
- [x] Facilitate applying zone configs to same-named partitions #39357
----

**Improve setting of zone configs via SQL** 

- [x] Return errors for conflicting zone configuration constraints as described in #35336
- [x] In SQL, `SHOW LOCALITY` #38438 (also in the CLI via Cockroach Node Status)
- [x] In SQL, add locality to `SHOW EXPERIMENTAL RANGES` #38603
- [x] Remove `EXPERIMENTAL` from `SHOW EXPERIMENTAL_RANGES` #39127
- [x] In the CLI, Cockroach node returns locality #38438
----

**Make it easy to focus queries onto partitioned data** (SQL Planning)

- [x] [planning team] Use partition values to use/constrain indexes as described in #38031 @ridwanmsharif 
----
**Improve Cockroach Demo** 
- [x] Add nodes to cockroach demo #39088
- [x] Add locality to cockroach demo #39450

**Comment by awoods187** [comment]
@ericharmeling this is the master list of stuff for documentation

**Comment by ericharmeling** [comment]
Perfect. Thank you!

**Comment by awoods187** [comment]
I'm going to close this issue since there is only the docs issue tracked in another repo left
