### ISSUE TITLE
exec: tracking issue for turning on "auto" by default

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#38920]
- [x] [exec: tracking issue for unit test failures ](https://github.com/cockroachdb/cockroach/issues/38935)

- [x] unordered synchronizer is blocked forever #39092

This is an incomplete list of failing logic tests when attempting to turn streaming operators through vectorized engine by default.

- [x] #38995

Failures on `local` config:
- [x] #38807
- [x] #38858
- [x] #38775

Failures on `fakedist` config:
- [x] `EXISTS` hanging #38919 (on `fakedist-opt` this problem occurs on `explain_analyze` logic test)
- [x] #38651
- [x] a crash due to incorrect type conversion #38918
- [x] mismatched batch width and schema length (I, @asubiotto can take this one) #38970
- [x] no output
  **Update: I haven't seen this issue after #38992, so I'm marking it as resolved here.**
  - `alter_table:742: SELECT * from default_err_test ORDER BY foo`
  - `distinct_on:132: SELECT DISTINCT ON (c, a) b, c, a FROM abc ORDER BY c, a, b DESC`
  - **`optimizer:30: SELECT * FROM test.t ORDER BY 1-t.k`**
  - `order_by:22: SELECT c FROM t ORDER BY c`
  - `ordinal_references:35: SELECT b, a FROM foo ORDER BY @1`
  - `suboperators:86: SELECT * FROM abc WHERE a = ANY(ARRAY[1,3]) ORDER BY a`
  - *this also occured on `5node-dist` config on `distsql_agg:419: SELECT c, count(*) FROM nullables GROUP BY c;`*
  - (an example failure):
```
                    testdata/logic_test/alter_table:742: SELECT * from default_err_test ORDER BY foo
                    expected:
                        bar
                        baz
                        foo
                        
                    but found (query options: "") :
                        
```
- [x] probably a problem with some nodes running vectorized while others running row execution
  **Update: I haven't seen this issue after #38992, so I'm marking it as resolved here. I believe the hypothesis about some nodes running vectorized while others running row execution was correct.**
  - **`join:12: SELECT * FROM onecolumn AS a(x) CROSS JOIN onecolumn AS b(y)`**
  - **`srfs:210: SELECT t.*, u.*, generate_series(1,2), generate_series(3, 4) FROM t, u`**
  - **`union:264: SELECT a FROM (SELECT a FROM a UNION ALL SELECT a FROM c) ORDER BY a`**
  - **`window:53: SELECT avg(k) OVER () FROM kv ORDER BY 1`**
  - *this also occurred on `5node-dist` config on `explain_analyze_plans:91: SELECT url FROM [EXPLAIN ANALYZE (DISTSQL) SELECT avg(k) OVER () FROM kv]`*
  - (an example failure):
```
                testdata/logic_test/join:12: SELECT * FROM onecolumn AS a(x) CROSS JOIN onecolumn AS b(y)
                expected success, but found
                (XXUUU) [n2] decoding error: received data before header and/or typing info
                stream_decoder.go:79: in AddMessage()
```
 - [x] partial output
  **Update: I haven't seen this issue after #38992, so I'm marking it as resolved here (although I observed a similar issue in #38994).**
```
                    testdata/logic_test/upsert:77: SELECT * from no_unique ORDER BY a, b
                    expected:
                        a  b
                        1  2
                        1  2
                        1  2
                        1  3
                        3  2
                        
                    but found (query options: "colnames") :
                        a  b
                        
```
 - [x] slice out of bounds
  **Update: I haven't seen this issue after #38992, so I'm marking it as resolved here.**
  - `views:117: SELECT * FROM v1 AS v1 INNER JOIN v2 AS v2 ON v1.a = v2.x`
  - `optimizer:54: SELECT * FROM t WHERE EXISTS(SELECT * FROM xy WHERE x=t.k)`
```
                testdata/logic_test/with:12: WITH t AS (SELECT a FROM y WHERE a < 3)
                  SELECT * FROM x NATURAL JOIN t
                expected success, but found
                (XXUUU) unexpected error from the vectorized runtime: unexpected error from the vectorized runtime: runtime error: slice bounds out of range
                error.go:56: in func1()
```

Interestingly, adding `5node-dist-vec` config to some of these logic tests and running them on master doesn't trigger the same issues (some succeed, some fail on a different query).

**Comment by awoods187** [comment]
This is great to see in one place as we track it moving forward!

**Comment by awoods187** [comment]
We also have this too https://github.com/cockroachdb/cockroach/issues/38935 which I added to the checklist
