### ISSUE TITLE
exec: tracking issue for unit test failures

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#38935]
This is a list of non-logic unit test failures when streaming vectorized execution is enabled.

pkg/ccl/backupccl
- [x] TestConcurrentBackupRestores (seems to be fixed by #38992)

pkg/sql
- [x] TestSessionFinishRollsBackTxn (#38858, fixed by #39007)
- [x] TestDistSQLRangeCachesIntegrationTest (#39033, fixed by #39038)
- [x] TestTxnObeysTableModificationTime (#39030, fixed by #39038)
- [x] TestSecondaryIndexWithOldStoringEncoding (fixed by #38971)
- [x] TestTrace (fixed by #39031)
- [x] TestTraceFieldDecomposition (fixed by #39027 and #39082)
- [x] TestKVTraceDistSQL (fixed by #38971)
- [x] TestNonRetryableError (fixed by #38990)
- [x] TestDistSQLRetryableError (#38943, will be fixed by #38990)

pkg/sql/distsqlplan
- [x] TestSpanResolverUsesCaches (#39039, fixed by #39038)

pkg/sql/distsqlrun
- [x] TestDrainingProcessorSwallowsUncertaintyError (#39029, fixed by #39080)

pkg/sql/tests
- [x] TestMonotonicInserts (fixed by #38990 + #38992)

**Comment by rohany** [comment]
TestKVTraceDistSQL passes once #38971 lands.

**Comment by solongordon** [comment]
All unit tests are now passing, pending #39080 and #39082 getting merged.

**Comment by jordanlewis** [comment]
Can we close this now?
