### ISSUE TITLE
exec: tracking issue for known logic tests failures for vectorize "experimental_on"

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#38994]
I ran logic tests on top of #38992 with vectorized set to "on." Here are the failures:
 - [x] #38919 (`explain_analyze`, `optimizer`, `subquery` files were skipped due to this issue)
 - [x] `aggregate` (#38858)
 - [x] `order_by`, `window`, `float`, `distinct_on`, `lookup_join`, `distsql_join`, `create_as` (#36880)
 - [x] `join` (#40371)
 - [x] `aggregate` (~#39240~)
 - [x] `select_index` (#38807)
 - [x] `ordinality` (#38995)
 - [x] `edge` (#38775)
 - [x] `postgresjoin`, `cascade`, and `cascade_opt` (#42670)
 - [x] #43269
 - [x] #43656

**Comment by rafiss** [comment]
Regarding #36880 -- that refers to global sort, which requires disk spilling, so should it not be part of this release? (so it should not be used if `experimental_vectorized=on`?) I'm wondering if the correct fix here is (1) to resolve that issue, or (2) to make sure global sort isn't used in vectorized yet. cc @jordanlewis who I believe indicated to me elsewhere that we want to take approach (2).

**Comment by yuzefovich** [comment]
Yeah, it is not a part of this release - the presence of global sort will fail the vectorized setup with "streaming" setting. I was just curious to see what failures do occur on the logic tests with things we have implemented so far (even if it's not going to be used by default in this release), so this tracking issue is more forward-looking.

**Comment by rohany** [comment]
After #39375 landed, a large number of the remaining logic tests now succeed -- order_by, window, float, distinct_on, lookup_join, distsql_join, and create_as. Updating the tracking issue with the remaining tests.

**Comment by asubiotto** [comment]
Can we close this?

**Comment by yuzefovich** [comment]
Not yet - rerunning it again, we now have failures on `postgresjoin`, `cascade`, and `cascade_opt` (from the first glance, it seems as a single bug, might be related to flat bytes). I added them above.

I also think that once we fix the known issues, we should add `local-vec` and `fakedist-vec` to default configurations.

**Comment by yuzefovich** [comment]
Added #43269 to the list which we need to fix before we can add `local-vec` and `fakedist-vec` to default logic tests configs.
