### ISSUE TITLE
demo: tracking issue for demo enhancements in 19.2

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#39940]
Demo Enhancements

**Usability**
- [x] Improve error message #39624
- [x] Silence error and warning logs #39939
- [ ] webui: cockroach demo shows 0 B for all tables #39155
- [x] demo: add enterprise license for cockroach demo #40222
- [ ] enhance error message #40434 

**Functionality**
- [x] Add nodes to cockroach demo #39088 
- [x] Add locality to cockroach demo #39450
- [x] Add topology patterns to Demo #39945
- [x] Add default locality settings for multi-node demos #39938
- [x] Add WebUI Map data for default multi-region zones #39937
- [ ] Persist data #39505
- [x] Add with-load switch for background workload for loaded dataset #39944

**Comment by asubiotto** [comment]
@awoods187 what should we do with this issue?

**Comment by awoods187** [comment]
we can close it
