### ISSUE TITLE
19.2 release blockers list

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#40447]
# Backport patrol

- [x] https://github.com/cockroachdb/cockroach/issues/41629 @tbg

Possible blockers for the 19.2 release:
# Build State
- [x] #40876  Go dependency updates @bdarnell 
- [x] #41291 JS dependency updates @nathanstilwell 

# KV
- [x] **BETA BLOCKER** #40213 (Non-zero HardState.Commit on uninitialized replica) @nvanbenschoten
- [x] #12768 (Rebalances must be atomic) @tbg
- [x] #40207 (Learner snap can fail when interacting with raft snap) @danhhz 
- [x] #40328 (teamcity: failed test: TestParallel invalid retryable err) @nvanbenschoten
- [x] #39460 (roachtest: tpcc/mixed-headroom/n5cpu16 failed) @tbg
- [x] [Slack link](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1567987255175600) (intents ignored when in a read's uncertainty interval, can cause stale reads) @nvanbenschoten 
- [x] #38785 (roachtest: acceptance/bank/cluster-recovery failed) @irfansharif 
- [x] #41206 performance regression (logging memory leak + stats collection inefficiency) @nvanbenschoten 
- [x] #41415 bug in poller causes it to emit a resolved timestamp before emitting row updates at that timestamp @aayushshah15. Update: PR for this is in now (#41665). Pending backport. 
- [x] #41694 bug in table history/poller when fetching old table descriptor versions after a restart @aayushshah15.
- [x] #41328 Under-replicated ranges when performing sequence of node removes/adds -- @darinpp 
- [x] #41446 system.replication_stats shows faux overreplication @andreimatei 
- [x] #41609 replication reports generation takes 20% of a node's CPU for 200k ranges @andreimatei 

- **BETA BLOCKERS** The "old replicaID state reuse" fallout cluster:
  - [x] #40367 (must never reuse snapshots from old replicaIDs) @ajwerner @tbg
  - [x] https://github.com/cockroachdb/cockroach/issues/38772#issuecomment-527721688 (merge missing RHS during clearrange)
  - [x] #39796 (Avoid fatal error from splitPostApply) @tbg 
  - [x] https://github.com/cockroachdb/cockroach/issues/40470 (splitPostApply sees tombstone for RHS which should be impossible) @tbg
  - [x] #40257 #40934 (Crash with snapshot widens existing replica, but no replica exists for subsumed key) @ajwerner

- [x] **BETA BLOCKER** https://github.com/cockroachdb/cockroach/issues/38772 (roachtest: clearrange/checks=false failed) @nvanbenschoten
- [x] #41096 (had non-voter replicas assertion fired) @danhhz 
- [x] **BETA BLOCKER** https://github.com/cockroachdb/cockroach/issues/41364 Jepsen/monotonic failures
- [x] #42068 leases can be transferred to replicas which are being removed @ajwerner 

### Probably not blockers, but here for visibility and discussion:
- [x] #38368 cloud storage cdc sinks are marked as experimental but there's a known correctness problem (that we know how to fix) -- @danhhz @aayushshah15 
- [x] #40412 Sentry events do not file github issues any more -- @knz
- [ ] https://github.com/cockroachdb/cockroach/issues/38720#issuecomment-538997993 node crashed during roachtest due to consistency checker -- @tbg 
- [ ] https://github.com/cockroachdb/cockroach/pull/41266 unsafe-remove-replicas needs to work in 19.2 with learners -- @darinpp 
- [ ] https://github.com/cockroachdb/cockroach/issues/40935 schemachange/mixed/tpcc reports a FK violation @lucy-zhang

#### [CRDB on Windows has severe issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+label%3AB-os-windows+milestone%3A19.2+is%3Aopen)
  - [x] #38789 "Failed to link" error creating index on windows -- @darinpp
  - [x] #37427 fatal error running on Windows -- @darinpp
  - [x] #37819 sentry: windows: io error failed to remove dir -- @darinpp
  - [x] #40936 Appveyor hangs during shutdown of CRDB on Windows -- @darinpp
  - [x] https://github.com/cockroachdb/cockroach/issues/40918 (unable to commit Raft entry batch: Corruption: Out-of-order key insertion into table)  @ajkr

Note, #32415 is a lower priority than the above

# BulkIO
- [x] https://github.com/cockroachdb/cockroach/issues/40504#issuecomment-528612842 (schema change transactions taking >30s will fail in 19.1+) @ajwerner 
- [x] https://github.com/cockroachdb/cockroach/issues/39072 `descriptor changed` (during IMPORT) @pbardea 
- [x] https://github.com/cockroachdb/cockroach/issues/40670 Failed to restore a registration cluster.  @pbardea 
- [x] ~#39726 roachtest: import/tpcc/warehouses=1000/nodes=4 failed @lucy-zhang~ (not a release blocker) 
- [x] #38720 roachtest: clearrange/checks=true failed @dt 
- [x] https://github.com/cockroachdb/cockroach/issues/41009 OOM when importing TPCC 10k @pbardea 

# SQL
- [x] **Combined SQL/KV issue** kv: scan doesn't return row added in the same txn) #40487 @andreimatei
- [x] **Combined SQL/KV issue** jepsen-monotonic failure when using RootTxn on the gateway #41424 @andreimatei 
- [x] **Combined SQL/KV issue** write skew in distributed DistSQL flows #41173 @andreimatei 
- [x] Malformed planNode tree generated for TPCH variant #40562
- [x] Insufficient privilege checking for ALTER CONFIGURE ZONE #40693
- [x] **BETA BLOCKER** Incorrect span creation for plans with column families #40890
- [x] **BETA BLOCKER** panic in TPCCBench due to something about getRangesInfo #39013
- [x] Index/lookup join has correctness problem in the face of column families #41007
- [x] issues with AND and OR expressions with vectorized #40913
- [ ] Timestamps are truncated to precision 0 after upgrading to 19.2 https://github.com/cockroachdb/cockroach/issues/42283

# Storage
- [x] https://github.com/cockroachdb/rocksdb/pull/64 Fix concurrent full purge and WAL recycling -- @ajkr 
- [x] Intra-LO compaction+ingestion bug https://github.com/facebook/rocksdb/pull/5958

# Other Discussion
- Should we add new stability period criteria: change allowed if it's going to be back-ported to previous release, and there's at least 1-2 weeks left for testing?

**Comment by andy-kimball** [comment]
We'll need to add Isaac as an Assignee once he's in the system.

**Comment by irfansharif** [comment]
Can we have a tracking issue for this:
> Slack link (intents ignored when in a read's uncertainty interval, can cause stale reads) @nvanbenschoten

**Comment by nvanbenschoten** [comment]
> Can we have a tracking issue for this:

We never opened an issue for it. It was fixed by https://github.com/cockroachdb/cockroach/pull/40600.

**Comment by andreimatei** [comment]
Heads up that I have a new horse in the race: #41173

**Comment by mjibson** [comment]
I'm adding #41206 to the list.

**Comment by knz** [comment]
added #41222 from andrei pending further assessment

**Comment by lucy-zhang** [comment]
I added https://github.com/cockroachdb/cockroach/issues/38720#issuecomment-538997993 from @dt (a node crashed during the `clearrange` roachtest due to a consistency checker failure) to the KV section. (Note that this is a new failure.)

**Comment by bdarnell** [comment]
Added jepsen failure #41364, and marked it and #38720 as beta blockers.

**Comment by aayushshah15** [comment]
Added #41415 to the list (changefeed poller bug).

**Comment by aayushshah15** [comment]
Added #41694 to the list (bug in table history/poller when fetching old table descriptor versions after a job restart).

**Comment by solongordon** [comment]
Added #42068 (leases can be transferred to replicas which are being removed)

**Comment by lucy-zhang** [comment]
Added https://github.com/cockroachdb/cockroach/issues/42283.

**Comment by andreimatei** [comment]
Long live 19.2
