### ISSUE TITLE
release: backport patrol for 19.2

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#41629]
We don't have a good process around making sure everything that needs to be backported is actually backported. As a stand-in, I'm doing this manually for now. Below is a list of PRs that were not backported into 19.2; please check off any line that has been "acted upon" (i.e. it was decided that no backport is needed, or a backport PR opened). Reminder: we're being very conservative at this point.

Instead of pulling in all of the original authors, I'm asking the TLs to do a pass, which I assume will take care of most items (pretty sure that the majority below won't need backports).

- [x] ~chriskseto 	sql: Add support for JOIN LATERAL syntax 	#40945~
- [x] knz 	sql: use errors.Is instead of direct error compares 	#41474 			
- [x] rogaps 	sql/parser: support string constant as element in EXTRACT arguments 	#41429 		 		

Created via

```
cat backport.txt  | grep -vE '(✓|◷)$' | grep -vE '(roachtest:)|(sqlsmith:)|(roachprod:)' | cut -c33- | sort | sed -E 's/^/- [ ] /' | pbcopy
```

where `backport.txt` was copy-pasted from backboard (pedestrian, I know, but it works fine, and the data isn't readily available as a SQL query, I checked) as of last refresh timestamp `2019-10-16 08:17`.
