### ISSUE TITLE
release: v19.2.0-rc.2

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#41787]
Candidate SHA: [918d925bcb7d3b42e3f201d2e0f534a9d0d26684](https://github.com/cockroachdb/cockroach/commit/918d925bcb7d3b42e3f201d2e0f534a9d0d26684)
Deployment status: `yahor-release-v1920-rc1-239513` and `yahor-release-v1920-rc2-918d92`
Nightly Suite: https://teamcity.cockroachdb.com/viewLog.html?buildId=1555680&
 
[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: `10/23`
- [x] [Pick a SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-PickingaSHA), fill in `Candidate SHA` above, notify #release-process of SHA.
- [x] [Tag the provisional SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA)
- [x] [Publish provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)
- [x] [Check binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkbinaries)
- [x] [Deploy to test clusters](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [x] [Verify node crash reports](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io)
- [x] [Start release qualification suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] fill in `Deployment status` above with clusters and `Nightly Suite` with the link to Nightly TeamCity Job
 
- Keep an eye on clusters until release date. Do not proceed below until the release date.
 
Release date: `10/28`
- [x] [Check cluster status](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkclusterstatus)
- [x] [Tag release](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Tagtherelease)
- [x] [Bless provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
 
- ~For production or stable releases in the latest major release series~
  - ~[ ] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)~
  - ~[ ] Update the image tag in our [Orchestrator configurations]~(https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)
  - ~[ ] Announce version to the [registration cluster]~(https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - ~[ ] Upgrade the registration cluster (reg runs latest stable version)~
 
- [x] Update docs
- [ ] External communications for release

**Comment by yuzefovich** [comment]
There were 7 failures during the nightly suite.
- [ ] Lint URLs. `TestLint/TestStaticCheck` failed with some `could not analyze dependency` and `... is unused (U1001)`. Previously, it was run against the master branch, so we didn't encounter this before. I don't think it is important, but cc @jordanlewis for sign off.
- [x] pgjdbc. #41886. The roachtest was not updated properly which was fixed by #41906.
- [x] ycsb/D/nodes=3. An infra flake #41885.
- [ ] cancel/tpcc/distsql/w=10,nodes=3. #38417 cc @asubiotto, @jordanlewis for sign off.
- [ ] hibernate. #41751 cc @rafiss for sign off. 
- [ ] kv50/rangelookups/relocate/nodes=8. #41491
- [ ] TestRandomSyntaxSQLSmith. Nothing stands out to me here. cc @mjibson for sign off.

**Comment by rafiss** [comment]
Signing off on Hibernate. There was a new Hibernate release that added new tests, so we have to update the blacklist.

**Comment by asubiotto** [comment]
Signing off on cancel (can't seem to check the checkbox on my phone though)
