### ISSUE TITLE
release: v19.2.0-rc.3

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#42029]
Candidate SHA: 62801ce77d9055c00b0e30010f5998ea2cd86686
Deployment status:
  - rc2: http://solon-release-v1920-rc2-918d925b-0001.roachprod.crdb.io:26258
  - rc3: http://solon-release-v1920-rc3-62801ce7-0001.roachprod.crdb.io:26258

Nightly Suite: https://teamcity.cockroachdb.com/viewLog.html?buildId=1571212
 
[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: `2019-10-31`
- [x] [Pick a SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-PickingaSHA), fill in `Candidate SHA` above, notify #release-process of SHA.
- [x] [Tag the provisional SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA)
- [x] [Publish provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)
https://teamcity.cockroachdb.com/viewLog.html?buildId=1568206
- [x] [Check binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkbinaries)
https://github.com/cockroachdb/bincheck/pull/151
- [x] [Deploy to test clusters](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [x] [Verify node crash reports](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io)
- [x] [Start release qualification suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
https://teamcity.cockroachdb.com/viewLog.html?buildId=1568237
- [x] [Start nightly suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] fill in `Deployment status` above with clusters and `Nightly Suite` with the link to Nightly TeamCity Job
 
- Keep an eye on clusters until release date. Do not proceed below until the release date.
 
Release date: `Monday 2019-11-04`
- [x] [Check cluster status](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkclusterstatus)
- [ ] [Tag release](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Tagtherelease)
- [ ] [Bless provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
 
- For production or stable releases in the latest major release series
  - [ ] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [ ] Update the image tag in our [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)
  - [ ] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - [ ] Upgrade the registration cluster (reg runs latest stable version)
 
- [ ] Update docs
- [ ] External communications for release

**Comment by solongordon** [comment]
Nightly roachtest failures:
- [x] cancel/tpcc/distsql/w=10,nodes=3 #38417, also failed in rc2
- [ ] clearrange/checks=true #38720, cc @tbg for sign-off
- [ ] hibernate #41751, cc @rafiss for sign-off
- [ ] import/tpch/nodes=8 #39113 
- [x] kv50/rangelookups/relocate/nodes=8 #41491, also failed in rc2
- [x] scaledata/filesystem_simulator/nodes=3 #36981, Looks consistent with historical flakiness
- [ ] tpccbench/nodes=9/cpu=4/multi-region #41876, cc @ajwerner for sign-off

**Comment by tbg** [comment]
Can't sign off on #38720, the error logs set off my alarms. https://github.com/cockroachdb/cockroach/issues/38720#issuecomment-548390887

Asking someone else from the team to dig in.

**Comment by lucy-zhang** [comment]
I'm signing off on #39113 because the import failure due to a test timeout looks similar to the import slowness we're already aware of and that @dt has been investigating. More details here: https://github.com/cockroachdb/cockroach/issues/39113#issuecomment-548596283

**Comment by solongordon** [comment]
Release process has been restarted with a new SHA to pick up #42068, which addresses the `clearrange/checks=true` roachtest failure above.

**Comment by solongordon** [comment]
Nightly roachtest failures:
- [x] cancel/tpcc/distsql/w=10,nodes=3 #38417, also failed in rc2
- [ ] hibernate #41751, cc @rafiss for sign-off
- [x] kv50/rangelookups/relocate/nodes=8 #41491, also failed in rc2
- [ ] overload/tpcc_olap/nodes=3/cpu=8/w=50/c=96 #40774, cc @ajwerner for sign-off
- [x] schemachange/mixed/tpcc #40935, cc @lucy-zhang. This issue is called out in #40447 as "probably not a blocker" so I'm assuming this is acceptable.
- [x] tpccbench/nodes=9/cpu=4/multi-region #41876, likely an infra flake like in the previous run
