### ISSUE TITLE
opt: 20.1 release checklist

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#42180]
This issue captures a series of tests and steps that we need to run when 20.1 is getting close to being finalized.
 - [x] check bug fixes that may need backport
 - [x] check and update private opt tests repository
 - [x] check regressions in microbenchmarks
 - [x] run all tests with FastIntSet cutoff to 2
 - [x] check that any new session settings have a cluster setting for the default (or a good justification for why not)
 - [x] consider adding session+cluster settings for all new features
 - [x] check TODOs in opt code (especially those added since the last release)

Please clone an instance of this issue for the next release before closing.

**Comment by RaduBerinde** [comment]
This checklist resulted in finding at least these issues:
 - https://github.com/cockroachdb/cockroach/issues/46600
 - https://github.com/cockroachdb/cockroach/issues/47283
