### ISSUE TITLE
storage/engine: Pebble test failure tracking issue

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#42355]
This is a tracking issue for the test failures when running on top of Pebble via `COCKROACH_STORAGE_ENGINE=pebble make test`.

- [x] https://github.com/cockroachdb/cockroach/issues/42348: ccl/backupccl
- [x] https://github.com/cockroachdb/cockroach/issues/42349: ccl/changefeedccl
- [x] https://github.com/cockroachdb/cockroach/issues/42350: ccl/storageccl
- [x] https://github.com/cockroachdb/cockroach/issues/42351: cli
- [x] https://github.com/cockroachdb/cockroach/issues/42352: sql/logictest
- [x] https://github.com/cockroachdb/cockroach/issues/42353: storage
- [x] https://github.com/cockroachdb/cockroach/issues/42354: storage/batcheval
