### ISSUE TITLE
release: v19.2.1

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#42557]
Candidate SHA: 53eef0857d14cc3af720e136ddaff4eeab026fd0
Deployment status: http://lucy-release-v1920-338deb2-0001.roachprod.crdb.io:26258/, http://lucy-release-v1921-53eef08-0001.roachprod.crdb.io:26258/
Nightly Suite: https://teamcity.cockroachdb.com/viewLog.html?buildId=1599082&buildTypeId=Cockroach_Nightlies_NightlySuite
 
[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: 2019-11-18
- [x] [Pick a SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-PickingaSHA), fill in `Candidate SHA` above, notify #release-announce of SHA.
- [x] [Tag the provisional SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA)
- [x] [Publish provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)
- [x] [Check binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkbinaries)
- [x] [Deploy to test clusters](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [x] [Verify node crash reports](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io)
- [x] [Start release qualification suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] fill in `Deployment status` above with clusters and `Nightly Suite` with the link to Nightly TeamCity Job
 
- Keep an eye on clusters until release date. Do not proceed below until the release date.
 
Release date: 2019-11-25
- [x] [Check cluster status](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkclusterstatus)
- [x] [Tag release](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Tagtherelease)
- [x] [Bless provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
 
- For production or stable releases in the latest major release series
  - [x] Update the [Homebrew Formula](https://github.com/cockroachdb/homebrew-tap/blob/master/Formula/cockroach.rb)
  - [x] Update the image tag in our [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)
  - [x] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - [ ] Upgrade the registration cluster (reg runs latest stable version)
 
- [x] Update docs
- [x] External communications for release

**Comment by lucy-zhang** [comment]
Failed nightlies:

- [ ] cdc/bank #41177
- [ ] overload/tpcc_olap/nodes=3/cpu=8/w=50/c=96 #40774
- [ ] sqlsmith/setup=empty/setting=no-ddl #42101
- [ ] sqlsmith/setup=empty/setting=no-mutations #42096
- [ ] sqlsmith/setup=seed/setting=no-ddl #42105
- [ ] sqlsmith/setup=seed/setting=no-mutations #42106
- [ ] sqlsmith/setup=tpcc/setting=no-ddl #42472
- [ ] sqlsmith/setup=tpcc/setting=no-mutations #42096
- [ ] sqlsmith/setup=tpch-sf1/setting=default #42107
- [ ] sqlsmith/setup=tpch-sf1/setting=no-ddl #42218
- [ ] sqlsmith/setup=tpch-sf1/setting=no-mutations #42212
- [ ] tpccbench/nodes=9/cpu=4/multi-region #41876

**Comment by andreimatei** [comment]
is this issue done?

**Comment by lucy-zhang** [comment]
I'm upgrading the reg cluster right now.

**Comment by lucy-zhang** [comment]
I restarted the reg cluster with 19.2.1 binaries. The reg cluster used to be on 19.1.5, so I'm leaving it with auto-finalization for the 19.2 upgrade turned off for a week. I'd like to keep this issue open to remember to finalize the upgrade.

**Comment by lucy-zhang** [comment]
The reg cluster upgrade is done.
