### ISSUE TITLE
bulkio, sql: schema changes should be jobs

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#42554]
[This meta-issue is still somewhat in progress. I haven't spun off any individual issues yet.]

Currently, schema changes are managed by the schema changer framework, which is a system within the SQL codebase that predates our job infrastructure and exists independently of it. The schema changer executes schema changes as job-like tasks whose metadata and state are stored entirely on the table descriptor itself, in the `Mutations` field. Typically, schema changes run immediately after the transaction that initiated the schema change commits, and the `connExecutor` blocks on the completion of the schema change before returning to the client. Each node also has a `SchemaChangeManager` that listens for gossip updates and executes outstanding schema changes, and a schema change lease field on the table descriptor ensures that no more than one node can run a schema change at any given time.

The problem with the schema change framework is that it makes the state of a schema change largely unobservable and difficult to control. Every schema change does have an associated job, but the job status is updated by the schema changer and largely exists for visibility to the user, and there have been bugs related to the job and the schema change getting out of sync (e.g., #38617, #40563). It's also difficult to monitor and debug schema changes because of a lack of information about which node is running a schema change (if outside the original session). If a schema change is taking a long time, we can't easily see whether a schema change is waiting on the release of older table leases, waiting to be picked up by a node, or doing something else.

We're also overburdening the table descriptor by storing state in the `Mutations` list that's only relevant to the process of running of the schema change, when ideally the table descriptor should only contain information about its schema elements that's necessary for SQL execution.

The plan is to port schema changes to the jobs infrastructure and get rid of the existing schema change framework. This lets us use the existing means of visibility and control provided by the jobs infra, solves the problem of the schema change job currently being an unreliable and out-of-date reflection of the true state, and allows taking advantage of upcoming improvements to the job infrastructure (e.g., the ability to pause jobs reliably).

Here's the plan in more detail:

- [ ] MVP: Add a new "schema change" job that simply reads the table descriptor and calls `SchemaChanger.exec()` as a black-box implementation of the schema change, and get rid of the `SchemaChangeManager`.
    - This can be done incrementally: First implement a job resumer and have the existing `SchemaChangeManager` create and start the job, and then have the `ALTER TABLE` implementation create the job instead and remove the need for the `SchemaChangeManager`.
    - Fully replicating the existing functionality, where schema changes are run immediately after the transaction that started the schema change, requires expanding the job API and adding `connExecutor` support (see below). Without this, we'd just have schema change jobs that run asynchronously.
- [ ] Support the ability to create/"schedule" jobs in a transaction and queue them in (e.g.)`connExecutor.extraTxnState`, start them after the transaction commits, and block on the completion of the job before returning to the user. (This is tracked somewhat in #37691, and more detailed issues will come soon, after we do more planning.) This is needed for running schema changes immediately after the transaction that initiated them.
- [ ] Implement and test the 19.2 -> 20.1 upgrade path. Presumably we'll need to keep the `SchemaChangeManager` around for mixed-version clusters, and create jobs for schema changes that were started without proper jobs.
- [ ] Clean up `Mutations` on the table descriptor, and move all the state that's only used for running schema changes to the job proto itself. This could involve separating different types of schema changes into different job resumers.
- [ ] Consider splitting multi-step schema changes into multiple jobs (e.g., "column backfill" or "validation") with dependencies between them, or otherwise break up the current monolithic state machine + backfiller process. This would be useful for more complex schema changes that don't fit into a single run of the schema change state machine, e.g., the current prototype for a primary key change (#42462).
