### ISSUE TITLE
roachtest: improve tracking and triage for release qualification

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#43920]
Roachtests are the primary way we run larger, complex integration tests -- those that require many nodes, hours or days of execution, etc.

These tests are very valuable in finding bugs or emergent behaviors that only manifest over size or time scales impractical for unit tests, and as such are an important and growing part of our release qualification process (indeed, we expect to utilize them even more as we automate more of the release process, in particular qualification).

Unfortunately, such bugs can be rare or intermittent. Simply running all the roachtests once as part of qualifying a release might catch some things, but if the same test on the same code failed the night before, or a week before, that is also really important signal that there may be a problem lurking and should be investigated before we bless that release.

This is currently challenging for two reasons:
1. Tracking which tests have failed on which branches leading up to a release is currently difficult.
2. Figuring out who needs to investigate is difficult, manual and time-consuming.

In the interest of improving the overall state of testing, but in particular the release qualification process, we should fix both of these.

**Tracking failures by branch / Treat every failure as a release-blocker**
For the first, we should 1) split the automated issues by branch, and 2) automatically apply a `release-blocker` label as well as 3) a per-branch label. Doing this will allowing easy querying the set of open blockers by branch. From the point of view of the release-qualification process, this significantly simplifies things -- we can simply link to a query of blockers for a branch, and we know we can bless a release when it is empty.

**Tracking ownership of failures and other blockers**
The above simplifies the identification of and tracking of release blockers, but another significant task is actually resolving them. Individual teams which own each test or issue need to triage failures or reported problems flagged as potential blockers to figure out if they require a fix, can be dismissed as flakes/should be skipped, can be untagged as blockers, etc. Currently this is a highly manual, labor-intensive process that falls on the release-engineering team to coordinate. 

Encoding the "owner team" for every test in that test's metadata could be then used in the automatic issue filing to additionally tag the issue with the team responsible. This in turn could streamline the identification of who needs to investigate, while also allowing automatic grouping by team, giving individual teams an easy query to summarize their open blockers and allow them to *proactively* address them, even before a specific release candidate begins qualification (and indeed we likely would want to automate some form of notification/nag for teams with open blockers).

Doing these two thing -- improving tracking and mapping of ownership -- would *significantly* improve the release process (and the overall state of our integration test maintainability and stability). 

**Action Items**
 - [x] Change roachtest issue-filer to file/update separate issues for each branch.
     - [x] Change roachtest issue-file to apply per-branch labels to issues for querying by branch.
 - [x] Change roachtest issue-filer to apply the `release-blocker` label to created or updated issues.
 - [x] Add "owner" field to roachtest metadata
    - [ ] include it in filed issues text+label issues with owner labels.
 - [x] Audit all existing roachtests to fill in owner fields.

**Comment by andreimatei** [comment]
> Tracking failures by branch

A lot of failures are common across branches. I think we should aim to have different issues for different failure messages (as opposed to a single issue per test today), but if one failure is common across branches, I think a single issue is better than several. The first time a particular failure is seen on a release branch, that issue could be marked as release blocker.

cc @tbg

**Comment by tbg** [comment]
I strongly support (today) having the roachtest issues disambiguated by release branch for the reasons David mentioned. But I'm with you in spirit Andrei, though to get there we need some better concept of a "message" that is more discrete than what we have today. I think the first step here should be to disambiguate infra failures from "real" failures, but this ought not to hold up the suggestions David made.

I don't know how well the owner team will work because the owner often depends on what failed, which we can't classify well today (for example, everyone and their mother runs an import at the beginning, so if that fails, it's bulk's problem usually, and perhaps actually KV's). I think we can get some relatively quick mileage out of having these common steps behind a helper that, if the test fails within, assigns to the owner responsible for that helper (example: an import helper that will result in failures assigned to bulkio). This roughly ties back in with Andrei's comment and I'll chat with him more on what we can do there.

**Comment by dt** [comment]
> if one failure is common across branches, I think a single issue is better than several

I originally thought that but I've changed my mind. 

Even when the failure is common, we still need to apply a fix _to each branch_ to resolve it. Sometimes that might be backporting the same fix master got to other branches, other times it might be coming up with something version-specific, etc. Having separate issues gives us the ability to discuss the fixes separately _if needed_ but we can also just link to the prior issue if we don't, but more importantly, it gives us the ability to track when the issue is fixed _on that branch_.

**Comment by danhhz** [comment]
Have we thought about the `release-blocker` tag plays with something that blocks a beta/rc/final but shouldn't block an alpha? (This has been common enough historically that I think it's worth considering)

**Comment by dt** [comment]
IMO that's enough of an edge case that i'm tentitively okay resolving it case-by-case (e.g. telling the release-team they can ignore that issue) or, if that doesn't scale, a `release-unstable-only` that blesses something with the `release-blocker` tag to for inclusion in an unstable release (while leaving the blocker status intact where a stable release would find it).

**Comment by dt** [comment]
This is all done now -- nightly roachtests file issues, we've made the dashboards for teams to monitor and the release team has switch to exclusively looking at `release-blocker` tagged issues by branch for the past several months, and kicking any that are still open over to eng to figure out before the release goes out. We have the manually  "ga-blocker" for something that blocks a final release but does not block an alpha or beta. For "maybe okay in an unstable alpha", that call would need a human to make, and I think would look like removing "release-blocker" (for the `master` branch copy of the issue) and potentially adding ga-blocker as a reminder to revisit before release. The major release stabilization/RC process counts and tracks ga-blockers so it'd get caught then.
