### ISSUE TITLE
CRDB compatibility with Postgres LTREE data type

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#44657]
Feature requested in [forum](https://forum.cockroachlabs.com/t/ltree-support-in-cockroachdb/3463). CRDB compatibility with Postgres LTREE data type as described [here](https://www.postgresql.org/docs/current/ltree.html)

MVP Implementation:
- [x] LTREE datatype and datum integration
- [x] LTREE containment operators
- [x] LTREE `subpath()`, `nlevel()`, `subltree()`, `lca()`, `index()` functions
- [x] Support index acceleration for LTREE comparison operators and containment operators

Additional Feature Implementation:
- [ ] LTREE matching with LQUERY
- [ ] LTREE matching with LTXTQUERY

Epic CRDB-65889

**Comment by jlgerber** [comment]
Ltree has proven to be a really good way of materializing hierarchies for us.

For example, we are in M&E, and have a number of asset management systems that utilize ltree to associate assets with a project level (show.sequence.shot). Using the ltree extension, we are able to efficiently look up all the assets in a particular show, or sequence in the show, or shot,etc, without resorting to recursive joins, or the more cumbersome solutions (found for instance in Joe Celko's Trees and Hierarchies bool)

**Comment by chickahoona** [comment]
I myself would be interested to see this too. With Psono I'd like to explore alternative databases that allow a georedundant setup more easily and CockroachDB is sadly not possible as ltree doesn't work :(

**Comment by cbollerud** [comment]
Is Ltree still under consideration?  It has been a useful feature with several companies to quickly select on a subset of a hierarchy.

**Comment by alen-z** [comment]
Bumping this as a deciding factor to move to CRDB.

**Comment by koudelka** [comment]
Also interested in this!

**Comment by alen-z** [comment]
Bump as it’s a critical feature for us to consider CRDB. We love it and would like to use it. Any plans here?
