### ISSUE TITLE
Add anonymized feature tracking for RBAC

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#45022]
Please add anonymized usage tracking for RBAC. This will help the Product team answer questions like “What % of clusters are using RBAC?” and improve feature usability and documentation.

- [ ] CREATE ROLE -> `iam.roles.create`
- [ ] CREATE ROLE with NOLOGIN set (new in 20.1) -> `iam.roles.create.nologin`
- [ ] ALTER ROLE (new in 20.1) -> `iam.roles.alter`
- [ ] ALTER ROLE  with NOLOGIN set (new in 20.1) -> `iam.roles.alter.nologin`
- [ ] GRANT <roles> -> `iam.roles.grant{.with_admin}`
- [ ] GRANT <priviliges> -> `iam.roles.privileges.granted.on_{table|database}`
- [ ] SHOW ROLES -> `iam.roles.show`
- [ ] SHOW GRANTS -> `iam.grants.show`
- [ ] DROP ROLE -> `iam.roles.drop`
- [ ] REVOKE <roles> -> `iam.roles.revoke{.with_admin}`
- [ ] REVOKE <priviliges> -> `iam.roles.privileges.revoked`
