### ISSUE TITLE
ui: style updates to overview page cluster health module 

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#45475]
Style updates to [overview page cluster health module](https://www.figma.com/file/OzoUuhNk05nFuaZB6UNVBx/obsrv_admin-ui-node-list?node-id=39%3A841):

- [x] Update labels from `#B8BBBC` to `#7E89A9`  (ie. `USED CAPACITY` `LIVE NODES` `TOTAL RANGES`
- [x] When counts are `0` update color to `#7E89A9`
- [x] Update capacity counts from blue `#0788FF` to `#394455`  (ie. 284.9 MiB)

![Screen Shot 2020-02-26 at 4 42 35 PM](https://user-images.githubusercontent.com/51920721/75391802-c7f26600-58b8-11ea-8bc3-a3d37c6d51d0.png)
