### ISSUE TITLE
20.1 release blockers list

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#45599]
PSA: The 20.1 release branch is now cut. The lucky winner SHA is 1225203862ef2e2ca552415c2b7f131deee09e16.

As we entering an important stabilization period, do not backport anything into the release-20.1 branch unless it is part of the release blockers list. _Please also add a comment if it blocks the beta releases._

# Possible blockers for the 20.1 release.

### General
- [x] Mint the 20.1 cluster version before picking 20.1 SHA [rel-eng / @dt ]

### Bulk IO
- [x] sql: nodelocal upload and export need to require admin user #46222 [@dt]
- [x] importccl,gcjob: failed and canceled imports don't seem to clean up their data #46684 [@pbardea]
- [x] telemetry counters on new features (_very_ low risk, high impact) [#46518, #46520, #46521]
- [x] (possible, still investigating) incremental full cluster backup sometimes flakes? release blocker, not beta blocker. https://github.com/cockroachdb/cockroach/issues/47050
- [x] backupccl: 2.1 (and prior) backups of tables with columns of a certain type had corrupted column types when restored into 20.1. [#44453]

### Admin UI (Observability)
- [x] ui: statement diagnostics should allow downloading of bundle #46331 
- [x] ui: statements page columns only sort per page #46173 (bug)
- [x] ui: time dropdown on metrics page reverts to 6h randomly #46145 (bug)
- [x] ui: truncate job description tooltip #46078 (visual bug)
- [x] ui: Remove statements summary from table details page #47079 (broken feature; replaces prior bug: #46584)
- [x] ui: statements page default sort by time column not visible #46427 (bug)
- [x] ui: refactor usage of `latency-parse` class name in non-latency settings #46445 (poorly worded but this is a regression)
- [x] ui: Fix over view page scrolling #46516 (bug)
- [x] ui: update existing storage tooltips as specified in docs #46726 (misleading tooltips need fixing)
- [x] ui: fix the insecure cluster indicator #46844 (regression; thanks @knz!)
- [x] ui: (fix) Tooltip component styling and props #46854 (regression)
- Telemetry (this is for metrics in Segment for us to measure feature usage)
	- [x] ui: add telemetry to statements list page #45506
	- [x] ui: add telemetry to statement details page #45625
	- [x] ui: add telemetry to Jobs page #45628
	- [x] ui: add telemetry for pagination clicks on databases page #45629
	- [x] ui: add telemetry to network latency matrix #45627
	- [x] ui: add time picker telemetry #45632

### Server / UI
- [x] ui,server: enable pain-free test-on-own-laptop user journey #46420 [knz]
- [x] sql,server: crash when connecting to a running cluster with `version not initialized` #46410 [ajwerner]

### KV
- [x] `TxnCoordMeta` refactor broke retry/savepoint logic #45477 
- [x] sql: rollback to savepoint after schema change can lead to deadlock #24885 [andrei]
- [x] sql: ROLLBACK TO SAVEPOINT after SFU must either release locks or fail #46075
- [x] kv: follower read that hits intent may get stuck in endless loop #46148 [nathan]
- [x] kv: we should collapse the refresh spans when exceeding the memory budget #46095 [andrei]
- [x] kv: caller violated contract of OnLockAcquired #46290 [nathan]
- [x] kv: idempotency failure across implicit commit breaks refreshing a parallel commit request #46341 [andrei]
- [x] kvserver: v20.1.0-beta.3: received ... results, limit was ... #46652 [tbg]
- [x] kv: don't bump ReadTimestamp on EndTxn batch with bounded read latches #46625 [nathan] [beta 5 blocker]
- [x] kv: clearrange/checks=true fails due to existing lock cannot be acquired by different transaction assertion #46460 [nathan] [beta 5 blocker]
- [x] kv: WriteTooOldError below write timestamp assertion #43273 [irfan] [beta 5 blocker]
- [x] kv: ranged intent resolution is not batched, regresses performance on TPC-C #46752 [nathan]
- [x] roachtest: cdc/tpcc-1000/rangefeed=true failed #46526 [nathan]
- [x] kv: invalid Raft truncation decision panic in cli unittests #43605 [irfan]
- [x] kv: READ_UNCOMMITTED scan observes WriteIntentError, hits assertion #47219 [nathan]
- [x] "kv: avoid excessively wide range tombstones during Raft snapshot reception" deemed unsafe https://github.com/cockroachdb/cockroach/issues/44048#issuecomment-610071732 [nathan]
- [x] kv: semi-syncronous intent resolution can deadlock in loaded cluster #47187 [nathan]
- [x] kv: txn recovery false positive #47337 [andrei]
- [x] kv: ranged intent resolution does not respect key limit, causes assertion failure #47471 [nathan]

### SQL Schema
- [x] gcjob: fix race in gc job test #46792
- [x] gcjob: ensure GC job timer fires appropriately when tables are expired #46715
- [x] ~~alter primary key roachtest failure #45812~~ High priority bug, but not a release blocker per [yahor & jordan]
- [x] 19.2 to 20.1 migration for schema change jobs #46152 [lucy/paul] [beta 5 blocker]
- [x] sqlmigrations: create jobs to GC leftover failed import/restore jobs from 19.2 #46818 @lucy-zhang 
- [x] bug in reverting schema changes after restarting #46018 [paul/lucy]
- [x]  sql: DROP DATABASE issue with TEMP tables #46393 
- [x] sql: recent regression in stopper quiescence time #47011 [knz]
- [x] ~~sql: WITH HASH hash column is not null but formula can return NULL #47055~~Removing from blockers list per @ajwerner (feature gated by flag)
- [x]  sql: upgrade from 19.x to 20.x eliminates all computed columns #47263 
- [x] sql: errors during schema change rollback are getting swallowed #47324
- [x] gcjob: tables are being refreshed on every system config gossip update, not just zone config updates #47312
- [x] sql: TestMigrateSchemaChanges/drop-table-blocked-at-after-reversing-mutations-canceled is flaky #47532

### SQL Execution
- [x] rowexec: memory accounting for row operators seems to be incorrect #45975
- [x] sql: CREATEROLE is inconsistently implemented #45857
- [x] Temporary tables aren't always GC'd #45669 
- [x] **[VEC]** Possible deadlock scenario #45602 
- [x] **[VEC]** Disk monitoring to avoid disk usage blowup #45169 
- [x] **[VEC]** Incorrect results of some timestamp operations. #44770
    - The issue is still present but these operations are now delegated to the row execution engine.
- [x] **[VEC]** UNION ALL incorrect results. #44188 
- [x] **[VEC]** TPCH Q5 incorrect output with low work memory limit #46106 
- [x] **[VEC]** nil pointer in hash router shutdown #46256 
- [x] sql: rollback to savepoint broken in mixed-version (19.2/20.1) clusters #46372 [andrei/knz]
- [x] rowexec: misuse of memory accounts by aggregate builtins #46664
- [x] **[VEC]** vector type mismatch in certain scenarios #46646
- [x] **[VEC]** move disk spilling operators behind feature flag #46925 
- [x] **[VEC]** register new package with panic catcher #47165
- [x] system.namespace unreadable from SQL from 19.2 nodes in mixed-version state #47167
- [x] running workload/schemachange causes 19.2 node in mixed version cluster to crash #47156
- [x] backport #47365 (sql: ignore soft limits on scan nodes for distsql planning)
- [x] https://github.com/cockroachdb/cockroach/pull/47425 (sql: prevent time-related precision during upgrade from 19.2 -> 20.1)

### SQL Planning
- [x] sql: Move RBAC into the BSL license. #46042  [richard/knz]
- [x] fix handling of write-only columns during update #42459 [andyk]
- [x] sql telemetry fixes (issues #43765, #46188, #43794; PR #46749) [radu]
- [x] bundles triggered via SQL don't show up in the UI #46330 [radu]
- [x] hard scan limit removed incorrectly #47283 [radu]

### Storage
- [x] pebble: duo of WAL issues affecting compatibility with RocksDB and recovery from crashes #47350 [peter]
- [x] pebble: fix bloom filter incompatibility with RocksDB: #47406, https://github.com/cockroachdb/pebble/pull/629 [peter]

### Performance Regressions
- [x] microbenchmark regression investigation and sign-off #46502

**Comment by lucy-zhang** [comment]
I'm adding https://github.com/cockroachdb/cockroach/issues/46018, which is a correctness bug in schema change rollbacks, to the list. I think it should be considered blocking for the beta since it also affects the correctness of #46152.

**Comment by andreimatei** [comment]
Added kv: idempotency failure across implicit commit breaks refreshing a parallel commit request #46341

**Comment by andreimatei** [comment]
Added sql: rollback to savepoint broken in mixed-version (19.2/20.1) clusters #46372

**Comment by ajwerner** [comment]
Added importccl,gcjob: failed and canceled imports don't seem to clean up their data https://github.com/cockroachdb/cockroach/issues/46684

**Comment by andreimatei** [comment]
Added kvserver: v20.1.0-beta.3: received ... results, limit was ... #46652

**Comment by tbg** [comment]
I am mitigating #46652 by turning it into a sentry-reported error instead of a crash (https://github.com/cockroachdb/cockroach/pull/46720/files). This may not be enough to remove it from the release blocker list, though.

**Comment by tbg** [comment]
@andreimatei looks like you didn't actually add that issue to the list? Done now, though.

**Comment by nvanbenschoten** [comment]
Added the following three blockers:
- don't bump ReadTimestamp on EndTxn batch with bounded read latches #46625
 - clearrange/checks=true fails due to existing lock cannot be acquired by different transaction assertion #46460
 - WriteTooOldError below write timestamp assertion #43273

**Comment by yuzefovich** [comment]
Added two release blockers (#46664 and #46646).

**Comment by lucy-zhang** [comment]
Adding #46715 (PR to fix bug where table/index GC could be delayed indefinitely)

**Comment by RaduBerinde** [comment]
Added sql telemetry fixes as a "soft" blocker.

**Comment by dhartunian** [comment]
Added Admin UI/Observability blockers.

**Comment by RaduBerinde** [comment]
@dhartunian none of the diagnostics-related ones are on there.. Most importantly #46331. Are we not planning to finish those?

**Comment by dhartunian** [comment]
Added statement diagnostics bundle download to Admin UI release blockers as per @RaduBerinde's comment above.

**Comment by lucy-zhang** [comment]
Adding #46792 which is a test-only change that fixes a flake.

**Comment by lucy-zhang** [comment]
Adding #46818.

**Comment by dhartunian** [comment]
Adding two more regressions on our end. Both have PRs already up for review.

- ui: fix the insecure cluster indicator #46844 (regression; thanks @knz!)
- ui: (fix) Tooltip component styling and props #46854 (regression)

**Comment by nvanbenschoten** [comment]
Adding https://github.com/cockroachdb/cockroach/issues/46752 to the list.

**Comment by andreimatei** [comment]
I've added "sql: recent regression in stopper quiescence time #47011 [knz]". Depending on what ends up being the problem, it might turn out to not be a release blocker, but also perhaps it will be.

**Comment by andreimatei** [comment]
I've added "[ ] kvserver/closedts: setting kv.closed_timestamp.target_duration to 0 does not disable #47010 [ajwerner]"

**Comment by ajwerner** [comment]
Added sql: WITH HASH hash column is not null but formula can return NULL #47055

**Comment by irfansharif** [comment]
Added "kv: invalid Raft truncation decision panic in cli unittests #43605", which I think can cause panics out in the wild.

**Comment by miretskiy** [comment]
Will you be able to get  #43605
<https://github.com/cockroachdb/cockroach/issues/43605> fix in in a day or
two?

**Comment by irfansharif** [comment]
> Will you be able to get  #43605 fix in in a day or two?

I think so, I'm typing it up today. I was just going to downgrade the panic.

**Comment by tbg** [comment]
Checking off: kvserver: v20.1.0-beta.3: received ... results, limit was ... #46652 [tbg]

@nvanbenschoten will give this bug another look to see if he can spot a bug but either way we don't want to block the release on it. Previous code inspection plus randomized testing was not able to reproduce it. Not satisfying but better than not releasing.

**Comment by lucy-zhang** [comment]
I checked off #46152 (19.2 to 20.1 migration for schema change jobs) earlier. The fix for #46818 (sqlmigrations: create GC jobs for failed import/restore jobs from 19.2) is being merged right now; the backport PR is #47144.

**Comment by miretskiy** [comment]
We are all clear on the release blockers list; starting rc1

**Comment by yuzefovich** [comment]
Added the need to backport #47165 as a release blocker (it doesn't need to go into rc1 though).

**Comment by jordanlewis** [comment]
Added: system.namespace unreadable from SQL from 19.2 nodes in mixed-version state #47167

This issue causes problems for 19.2 nodes in a mixed-version cluster. The nodes will not be able to read from `crdb_internal.zones`, which causes problems for debug zip, some parts of the admin ui, and a few other related areas.

**Comment by otan** [comment]
adding https://github.com/cockroachdb/cockroach/pull/47156 - not important for RC.

**Comment by dt** [comment]
#47167 is a hard blocker -- it probably doesn't block a beta, but it _does_ block release, so that means any sha we start qualifying right now would be considered a beta, not an RC.

**Comment by dt** [comment]
cc @miretskiy re above w.r.t. #47167 and RC.1

**Comment by nvanbenschoten** [comment]
Adding https://github.com/cockroachdb/cockroach/issues/47219 - which is an old bug responsible for a new assertion failing.

**Comment by miretskiy** [comment]
@nvanbenschoten  is 47219 rc1 blocker as well?

**Comment by pbardea** [comment]
Adding #44453.

**Comment by nvanbenschoten** [comment]
> @nvanbenschoten is 47219 rc1 blocker as well?

I don't know exactly how that's being defined. It is a hard release blocker, so it should block the final release. But I don't think it should stop any intermediate release. Whether this means we should consider a currently qualifying release as a beta instead of an RC is up for discussion (https://github.com/cockroachdb/cockroach/issues/45599#issuecomment-610713912)

**Comment by nvanbenschoten** [comment]
Also, adding _"kv: avoid excessively wide range tombstones during Raft snapshot reception" deemed unsafe_ https://github.com/cockroachdb/cockroach/issues/44048#issuecomment-610071732 as a hard release blocker. We need to back that change out of the release, as it's too risky to do anything more with it at this point in the release cycle and it hypothetically risks replica inconsistencies.

**Comment by knz** [comment]
Adding:

sql: upgrade from 19.x to 20.x eliminates all computed columns #47263

**Comment by RaduBerinde** [comment]
Added sql: hard scan limit removed incorrectly #47283. ETA for a fix is today

**Comment by lucy-zhang** [comment]
Adding #47324 as a possible blocker.

**Comment by yuzefovich** [comment]
Adding the need to backport #47365 (sql: ignore soft limits on scan nodes for distsql planning) as a release blocker.

**Comment by petermattis** [comment]
Adding the need to backport #47350. I think we could technically release without this backport as it only affects Pebble, but we'd have to recommend against using Pebble and it would set back our rollout plans for Pebble. These fixes should only affect Pebble.

**Comment by otan** [comment]
Adding https://github.com/cockroachdb/cockroach/pull/47425 for release blocker - not important for RC.

**Comment by nvanbenschoten** [comment]
Adding https://github.com/cockroachdb/cockroach/issues/47187 as a hard release blocker.

**Comment by andreimatei** [comment]
Added "kv: txn recovery false positive #47337 [andrei]". It's a bug causing transactions to be wrongfully committed, so it's quite bad I think.

**Comment by nvanbenschoten** [comment]
Adding https://github.com/cockroachdb/cockroach/issues/47471 as a soft release blocker. It's an old bug, but it's worse now that we perform significantly more ranged intent resolution. The fix is targetted and should be up today.

**Comment by lucy-zhang** [comment]
Adding #47312 as a soft release blocker.

**Comment by lucy-zhang** [comment]
Adding #47532 as a potential "soft" release blocker.

For context, this is a regression I introduced as part of fixing #47324, and it'll take a one-line change to fix.

**Comment by petermattis** [comment]
Added https://github.com/cockroachdb/cockroach/issues/47406 which is fixed by https://github.com/cockroachdb/pebble/pull/629. There is a subtle incompatibility between RocksDB and Pebble bloom filters which was causing the failures in #47406. While we've only seen problems in a test which switches back and forth between RocksDB and Pebble, I'm very anxious this could be causing other rare problems as Pebble is used to create sstables used for ingestion (e.g. during rebalancing, import, and restore) even with RocksDB is the storage engine in use.

**Comment by otan** [comment]
considering 20.1 released.
