### ISSUE TITLE
sql: meta issue for transitioning virtual tables to generators

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#47941]
The following tables need to be transitioned to generators. They currently eagerly generate all of their rows.

- [ ] crdb_internal.backward_dependencies
- [ ] crdb_internal.builtin_functions
- [ ] crdb_internal.cluster_queries
- [ ] crdb_internal.cluster_sessions
- [ ] crdb_internal.cluster_settings
- [ ] crdb_internal.cluster_transactions
- [ ] crdb_internal.create_statements
- [ ] crdb_internal.feature_usage
- [ ] crdb_internal.forward_dependencies
- [ ] crdb_internal.gossip_alerts
- [ ] crdb_internal.gossip_liveness
- [ ] crdb_internal.gossip_network
- [ ] crdb_internal.gossip_nodes
- [ ] crdb_internal.index_columns
- [x] crdb_internal.jobs
- [ ] crdb_internal.kv_node_status
- [ ] crdb_internal.kv_store_status
- [ ] crdb_internal.leases
- [ ] crdb_internal.node_build_info
- [ ] crdb_internal.node_metrics
- [ ] crdb_internal.node_queries
- [ ] crdb_internal.node_runtime_info
- [ ] crdb_internal.node_sessions
- [ ] crdb_internal.node_statement_statistics
- [ ] crdb_internal.node_transactions
- [ ] crdb_internal.node_txn_stats
- [x] crdb_internal.partitions
- [ ] crdb_internal.predefined_comments
- [ ] crdb_internal.ranges
- [ ] crdb_internal.ranges_no_leases
- [ ] crdb_internal.schema_changes
- [ ] crdb_internal.session_trace
- [ ] crdb_internal.session_variables
- [x] crdb_internal.table_columns
- [x] crdb_internal.table_indexes
- [x] crdb_internal.tables
- [ ] crdb_internal.zones
- [ ] information_schema.administrable_role_authorizations
- [ ] information_schema.applicable_roles
- [ ] information_schema.check_constraints
- [ ] information_schema.column_privileges
- [ ] information_schema.columns
- [ ] information_schema.constraint_column_usage
- [ ] information_schema.enabled_roles
- [ ] information_schema.key_column_usage
- [ ] information_schema.parameters
- [ ] information_schema.referential_constraints
- [ ] information_schema.role_table_grants
- [ ] information_schema.routines
- [ ] information_schema.schema_privileges
- [ ] information_schema.schemata
- [ ] information_schema.sequences
- [ ] information_schema.statistics
- [ ] information_schema.table_constraints
- [ ] information_schema.table_privileges
- [ ] information_schema.tables
- [ ] information_schema.user_privileges
- [ ] information_schema.views
- [ ] pg_catalog.pg_am
- [ ] pg_catalog.pg_attrdef
- [ ] pg_catalog.pg_attribute
- [ ] pg_catalog.pg_auth_members
- [ ] pg_catalog.pg_authid
- [ ] pg_catalog.pg_available_extensions
- [ ] pg_catalog.pg_cast
- [ ] pg_catalog.pg_class
- [ ] pg_catalog.pg_collation
- [ ] pg_catalog.pg_constraint
- [ ] pg_catalog.pg_conversion
- [ ] pg_catalog.pg_database
- [ ] pg_catalog.pg_default_acl
- [ ] pg_catalog.pg_depend
- [ ] pg_catalog.pg_description
- [ ] pg_catalog.pg_enum
- [ ] pg_catalog.pg_extension
- [ ] pg_catalog.pg_foreign_data_wrapper
- [ ] pg_catalog.pg_foreign_server
- [ ] pg_catalog.pg_foreign_table
- [ ] pg_catalog.pg_index
- [ ] pg_catalog.pg_indexes
- [ ] pg_catalog.pg_inherits
- [ ] pg_catalog.pg_language
- [ ] pg_catalog.pg_locks
- [ ] pg_catalog.pg_matviews
- [ ] pg_catalog.pg_namespace
- [ ] pg_catalog.pg_operator
- [ ] pg_catalog.pg_prepared_statements
- [ ] pg_catalog.pg_prepared_xacts
- [ ] pg_catalog.pg_proc
- [ ] pg_catalog.pg_range
- [ ] pg_catalog.pg_rewrite
- [ ] pg_catalog.pg_roles
- [ ] pg_catalog.pg_seclabel
- [ ] pg_catalog.pg_seclabels
- [ ] pg_catalog.pg_sequence
- [ ] pg_catalog.pg_settings
- [ ] pg_catalog.pg_shdepend
- [ ] pg_catalog.pg_shdescription
- [ ] pg_catalog.pg_shseclabel
- [ ] pg_catalog.pg_stat_activity
- [ ] pg_catalog.pg_tables
- [ ] pg_catalog.pg_tablespace
- [ ] pg_catalog.pg_trigger
- [ ] pg_catalog.pg_type
- [ ] pg_catalog.pg_user
- [ ] pg_catalog.pg_user_mapping
- [ ] pg_catalog.pg_views

**Comment by rohany** [comment]
cc @jordanlewis
