### ISSUE TITLE
sql/kv: remove all uses of keyutils.TestingSQLCodec (previously keys.TODOSQLCodec)

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#48123]
We want to remove uses of `keysutils.TestingSQLCodec` (previously `keys.TODOSQLCodec`) then remove that codec altogether.

Dependencies:

- Feature work:
  - [x] table/db details in admin server HTTP API  #82879
  - [x] `cockroach debug backup export` #82878 
  - [ ] KV replication reports #82881 - use renamed to `FIXMEIDONTKNOWWHICHCODECTOUSE` in #99774

- Test code:
  - [x] backup TestPublicIndexTableSpans, check two keyspaces #82882   
  - [x] tenant streaming TestRandomClientGeneration, plumb proper codec #82883  
  - [x] columnar execution, TestSpanAssembler, check two keyspaces #82884 
  - [x] row / jobs, TestJobBackedSeqChunkProvider, plumb proper codec #82886  
  - [ ] keysutils/pretty_scanner (used by replication reports), plumb proper codec #100004 / #82881  

Jira issue: CRDB-4356
Epic: CRDB-26091

**Comment by nvanbenschoten** [comment]
The following paragraph in https://github.com/cockroachdb/cockroach/commit/695318206ddc56bfe2542e8e3d19672ccde6ad1b was unintentionally interpreted as closing this issue:

> All of this works towards a good cause - we eliminate the remaining uses
of `keys.TODOSQLCodec` from `pkg/sql/...` and `pkg/config/...`, bringing
us a big step closer towards being able to remove the placeholder and
close #48123.

Unfortunately, we have not yet completed it.

**Comment by tbg** [comment]
What's left here?

**Comment by nvanbenschoten** [comment]
There are no critical remaining uses of `keys.TODOSQLCodec`, but there are still a number of uses in BACKUP, RESTORE, IMPORT, and CDC. All of these are locked down for the initial launch, so we can keep this open, but it's not a blocker.

**Comment by knz** [comment]
I'll file sub-issues accordingly and close this.

**Comment by knz** [comment]
updated issue description with finer-grain dependencies. Let's keep this issue open to actually remove the codec at the end.

**Comment by knz** [comment]
Renamed `TODOSQLCodec` to `TestinSQLCodec` in #99774.
