### ISSUE TITLE
Gopkg.lock => go.mod checklist

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#50148]
Generated from: https://github.com/otan-cockroach/otan-scripts/blob/master/gomodupdate/diff.py
PR: #49447

- [x] item in Gopkg.lock but not in go.sum: [github.com/Azure/go-autorest](https://github.com/Azure/go-autorest)
- [x] mismatching version: [github.com/DataDog/zstd](https://github.com/DataDog/zstd) - go.sum v1.4.4 vs Gopkg.lock v1.3.5
- [x] item in Gopkg.lock but not in go.sum: [github.com/Masterminds/semver](https://github.com/Masterminds/semver)
- [x] item in Gopkg.lock but not in go.sum: [github.com/Masterminds/vcs](https://github.com/Masterminds/vcs)
- [x] mismatching version: [github.com/Microsoft/go-winio](https://github.com/Microsoft/go-winio) - go.sum v0.4.14 vs Gopkg.lock v0.4.11
- [x] mismatching SHA for [github.com/Shopify/sarama](https://github.com/Shopify/sarama) - [go.sum cd910a68 vs Gopkg.lock 03a43f93](https://github.com/Shopify/sarama/compare/03a43f93...cd910a68)
- [x] item in Gopkg.lock but not in go.sum: [github.com/apache/arrow](https://github.com/apache/arrow)
- [x] item in Gopkg.lock but not in go.sum: [github.com/armon/go-radix](https://github.com/armon/go-radix)
- [x] version in go.mod, but SHA in Gopkg.lock: [github.com/beorn7/perks](https://github.com/beorn7/perks) - go.sum v1.0.1 vs Gopkg.lock SHA 3a771d99
- [x] item in Gopkg.lock but not in go.sum: [github.com/boltdb/bolt](https://github.com/boltdb/bolt)
- [x] item in Gopkg.lock but not in go.sum: [github.com/cockroachdb/apd](https://github.com/cockroachdb/apd)
- [x] mismatching version: [github.com/cockroachdb/sentry-go](https://github.com/cockroachdb/sentry-go) - go.sum v0.6.1-cockroachdb.2 vs Gopkg.lock v0.6.1-cockroachdb - **oops** see https://github.com/cockroachdb/cockroach/pull/49447#issuecomment-643740918
- [x] mismatching version: [github.com/cpuguy83/go-md2man](https://github.com/cpuguy83/go-md2man) - go.sum v1.0.10 vs Gopkg.lock v1.0.8
- [x] version in go.mod, but SHA in Gopkg.lock: [github.com/dave/dst](https://github.com/dave/dst) - go.sum v0.24.0 vs Gopkg.lock SHA ce1c8af3
- [x] mismatching version: [github.com/docker/go-units](https://github.com/docker/go-units) - go.sum v0.4.0 vs Gopkg.lock v0.3.3
- [x] mismatching version: [github.com/eapache/go-resiliency](https://github.com/eapache/go-resiliency) - go.sum v1.2.0 vs Gopkg.lock v1.1.0
- [x] version in go.mod, but SHA in Gopkg.lock: [github.com/ghodss/yaml](https://github.com/ghodss/yaml) - go.sum v1.0.0 vs Gopkg.lock SHA 0ca9ea5d
- [x] item in Gopkg.lock but not in go.sum: [github.com/golang/dep](https://github.com/golang/dep)
- [x] mismatching SHA for [github.com/golang/snappy](https://github.com/golang/snappy) - [go.sum ff6b7dc8 vs Gopkg.lock 2e65f852](https://github.com/golang/snappy/compare/2e65f852...ff6b7dc8)
- [x] version in go.mod, but SHA in Gopkg.lock: [github.com/google/btree](https://github.com/google/btree) - go.sum v1.0.0 vs Gopkg.lock SHA 4030bb1f
- [x] mismatching version: [github.com/google/flatbuffers](https://github.com/google/flatbuffers) - go.sum v1.11.0 vs Gopkg.lock v1.10.0
- [x] mismatching version: [github.com/google/go-cmp](https://github.com/google/go-cmp) - go.sum v0.4.0 vs Gopkg.lock v0.3.0
- [x] mismatching version: [github.com/google/go-github](https://github.com/google/go-github) - go.sum v17.0.0 vs Gopkg.lock v21.0.0
- [x] mismatching version: [github.com/googleapis/gax-go](https://github.com/googleapis/gax-go) - go.sum v2.0.2 vs Gopkg.lock v2.0.3
- [x] mismatching version: [github.com/inconshreveable/mousetrap](https://github.com/inconshreveable/mousetrap) - go.sum v1.0.0 vs Gopkg.lock v1.0
- [x] item in Gopkg.lock but not in go.sum: [github.com/jmank88/nuts](https://github.com/jmank88/nuts)
- [x] mismatching version: [github.com/kisielk/errcheck](https://github.com/kisielk/errcheck) - go.sum v1.2.0 vs Gopkg.lock v1.1.0
- [x] mismatching version: [github.com/konsorten/go-windows-terminal-sequences](https://github.com/konsorten/go-windows-terminal-sequences) - go.sum v1.0.2 vs Gopkg.lock v1.0.1
- [x] mismatching version: [github.com/kr/pretty](https://github.com/kr/pretty) - go.sum v0.2.0 vs Gopkg.lock v0.1.0
- [x] mismatching version: [github.com/kr/text](https://github.com/kr/text) - go.sum v0.2.0 vs Gopkg.lock v0.1.0
- [x] item in Gopkg.lock but not in go.sum: [github.com/linkedin/goavro](https://github.com/linkedin/goavro)
- [x] version in go.mod, but SHA in Gopkg.lock: [github.com/lufia/iostat](https://github.com/lufia/iostat) - go.sum v1.0.0 vs Gopkg.lock SHA 9f7362b7
- [x] mismatching version: [github.com/mattn/go-isatty](https://github.com/mattn/go-isatty) - go.sum v0.0.9 vs Gopkg.lock v0.0.4
- [x] mismatching version: [github.com/mattn/go-runewidth](https://github.com/mattn/go-runewidth) - go.sum v0.0.7 vs Gopkg.lock v0.0.4
- [x] item in Gopkg.lock but not in go.sum: [github.com/nightlyone/lockfile](https://github.com/nightlyone/lockfile)
- [x] mismatching version: [github.com/opentracing/opentracing-go](https://github.com/opentracing/opentracing-go) - go.sum v1.1.0 vs Gopkg.lock v1.0.2
- [x] item in Gopkg.lock but not in go.sum: [github.com/pelletier/go-toml](https://github.com/pelletier/go-toml)
- [x] item in Gopkg.lock but not in go.sum: [github.com/petar/GoLLRB](https://github.com/petar/GoLLRB)
- [x] mismatching version: [github.com/pierrec/lz4](https://github.com/pierrec/lz4) - go.sum v2.4.1 vs Gopkg.lock v2.0.7
- [x] mismatching version: [github.com/pkg/errors](https://github.com/pkg/errors) - go.sum v0.9.1 vs Gopkg.lock v0.8.1
- [x] mismatching version: [github.com/prometheus/client_golang](https://github.com/prometheus/client_golang) - go.sum v1.1.0 vs Gopkg.lock v0.9.2
- [x] version in go.mod, but SHA in Gopkg.lock: [github.com/prometheus/client_model](https://github.com/prometheus/client_model) - go.sum v0.2.0 vs Gopkg.lock SHA 56726106
- [x] version in go.mod, but SHA in Gopkg.lock: [github.com/prometheus/common](https://github.com/prometheus/common) - go.sum v0.9.1 vs Gopkg.lock SHA 2998b132
- [x] version in go.mod, but SHA in Gopkg.lock: [github.com/prometheus/procfs](https://github.com/prometheus/procfs) - go.sum v0.0.10 vs Gopkg.lock SHA b1a0a9a3
- [x] mismatching SHA for [github.com/rcrowley/go-metrics](https://github.com/rcrowley/go-metrics) - [go.sum cac0b30c vs Gopkg.lock 3113b840](https://github.com/rcrowley/go-metrics/compare/3113b840...cac0b30c)
- [x] item in Gopkg.lock but not in go.sum: [github.com/sdboyer/constext](https://github.com/sdboyer/constext)
- [x] mismatching version: [github.com/sirupsen/logrus](https://github.com/sirupsen/logrus) - go.sum v1.4.2 vs Gopkg.lock v1.3.0
- [x] mismatching version: [github.com/spf13/cobra](https://github.com/spf13/cobra) - go.sum v0.0.5 vs Gopkg.lock v0.0.3
- [x] mismatching version: [github.com/spf13/pflag](https://github.com/spf13/pflag) - go.sum v1.0.5 vs Gopkg.lock v1.0.3
- [x] mismatching version: [github.com/stretchr/testify](https://github.com/stretchr/testify) - go.sum v1.5.1 vs Gopkg.lock v1.4.0
~- [x] mismatching SHA for [go.etcd.io/etcd](https://go.etcd.io/etcd) - [go.sum bbe86b06 vs Gopkg.lock 4a2b4c8f](https://go.etcd.io/etcd/compare/4a2b4c8f...bbe86b06)~
- [x] mismatching SHA for [golang.org/x/crypto](https://golang.org/x/crypto) - [go.sum 0ec3e997 vs Gopkg.lock ff983b9c](https://golang.org/x/crypto/compare/ff983b9c...0ec3e997)
- [x] mismatching SHA for [golang.org/x/exp](https://golang.org/x/exp) - [go.sum 00229845 vs Gopkg.lock 01c40f57](https://golang.org/x/exp/compare/01c40f57...00229845)
- [x] mismatching SHA for [golang.org/x/lint](https://golang.org/x/lint) - [go.sum 910be7a9 vs Gopkg.lock 959b441a](https://golang.org/x/lint/compare/959b441a...910be7a9)
~- [ ] mismatching SHA for [golang.org/x/net](https://golang.org/x/net) - [go.sum 0de0cce0 vs Gopkg.lock a8b05e91](https://golang.org/x/net/compare/a8b05e91...0de0cce0)~
- [x] mismatching SHA for [golang.org/x/sync](https://golang.org/x/sync) - [go.sum cd5d95a4 vs Gopkg.lock 37e7f081](https://golang.org/x/sync/compare/37e7f081...cd5d95a4)
- [x] mismatching SHA for [golang.org/x/sys](https://golang.org/x/sys) - [go.sum fe76b779 vs Gopkg.lock a457fd03](https://golang.org/x/sys/compare/a457fd03...fe76b779)
- [x] version in go.mod, but SHA in Gopkg.lock: [golang.org/x/text](https://golang.org/x/text) - go.sum v0.3.2 vs Gopkg.lock SHA 470f45bf
- [x] mismatching SHA for [golang.org/x/time](https://golang.org/x/time) - [go.sum 9d24e822 vs Gopkg.lock 85acf8d2](https://golang.org/x/time/compare/85acf8d2...9d24e822)
- [x] mismatching SHA for [golang.org/x/tools](https://golang.org/x/tools) - [go.sum 2212a7e1 vs Gopkg.lock 63859f38](https://golang.org/x/tools/compare/63859f38...2212a7e1)
- [x] mismatching SHA for [google.golang.org/genproto](https://google.golang.org/genproto) - [go.sum dad8c97a vs Gopkg.lock db91494d](https://google.golang.org/genproto/compare/db91494d...dad8c97a)
- [x] version in go.mod, but SHA in Gopkg.lock: [honnef.co/go/tools](https://honnef.co/go/tools) - go.sum v0.0.1-2019.2.3 vs Gopkg.lock SHA 1f0868a6
- [x] item in go.sum but not in Gopkg.lock: [github.com/Azure/go-autorest/autorest](https://github.com/Azure/go-autorest/autorest)
- [x] item in go.sum but not in Gopkg.lock: [github.com/Azure/go-autorest/autorest/adal](https://github.com/Azure/go-autorest/autorest/adal)
- [x] item in go.sum but not in Gopkg.lock: [github.com/Azure/go-autorest/autorest/azure/auth](https://github.com/Azure/go-autorest/autorest/azure/auth)
- [x] item in go.sum but not in Gopkg.lock: [github.com/Azure/go-autorest/autorest/azure/cli](https://github.com/Azure/go-autorest/autorest/azure/cli)
- [x] item in go.sum but not in Gopkg.lock: [github.com/Azure/go-autorest/autorest/date](https://github.com/Azure/go-autorest/autorest/date)
- [x] item in go.sum but not in Gopkg.lock: [github.com/Azure/go-autorest/autorest/to](https://github.com/Azure/go-autorest/autorest/to)
- [x] item in go.sum but not in Gopkg.lock: [github.com/Azure/go-autorest/autorest/validation](https://github.com/Azure/go-autorest/autorest/validation)
- [x] item in go.sum but not in Gopkg.lock: [github.com/Azure/go-autorest/logger](https://github.com/Azure/go-autorest/logger)
- [x] item in go.sum but not in Gopkg.lock: [github.com/Azure/go-autorest/tracing](https://github.com/Azure/go-autorest/tracing)
- [x] item in go.sum but not in Gopkg.lock: [github.com/apache/arrow/go/arrow](https://github.com/apache/arrow/go/arrow)
- [x] item in go.sum but not in Gopkg.lock: [github.com/cockroachdb/apd/v2](https://github.com/cockroachdb/apd/v2)
- [x] item in go.sum but not in Gopkg.lock: [github.com/cockroachdb/go-test-teamcity](https://github.com/cockroachdb/go-test-teamcity)
- [x] item in go.sum but not in Gopkg.lock: [github.com/goware/modvendor](https://github.com/goware/modvendor)
- [x] item in go.sum but not in Gopkg.lock: [github.com/hashicorp/go-uuid](https://github.com/hashicorp/go-uuid)
- [x] item in go.sum but not in Gopkg.lock: [github.com/jcmturner/gofork](https://github.com/jcmturner/gofork)
- [x] item in go.sum but not in Gopkg.lock: [github.com/linkedin/goavro/v2](https://github.com/linkedin/goavro/v2)
- [x] item in go.sum but not in Gopkg.lock: [github.com/mattn/go-zglob](https://github.com/mattn/go-zglob)
- [x] item in go.sum but not in Gopkg.lock: [gopkg.in/jcmturner/aescts.v1](https://gopkg.in/jcmturner/aescts.v1)
- [x] item in go.sum but not in Gopkg.lock: [gopkg.in/jcmturner/dnsutils.v1](https://gopkg.in/jcmturner/dnsutils.v1)
- [x] item in go.sum but not in Gopkg.lock: [gopkg.in/jcmturner/gokrb5.v7](https://gopkg.in/jcmturner/gokrb5.v7)
- [x] item in go.sum but not in Gopkg.lock: [gopkg.in/jcmturner/rpc.v1](https://gopkg.in/jcmturner/rpc.v1)

-----

new to  pick up sentry-go / errors update

- [x] google.golang.org/grpc v1.29.1 (vs old version v1.27.1)
- [x] gopkg.in/yaml.v2 v2.3.0 (vs old version v2.2.8)

----

etcd change

- [x] golang.org/x/net a8b05e91 => 627f9648deb9
- [x] etcd becomes github.com/cockroachdb/etcd v0.4.7-0.20200615211340-a17df30d5955

**Comment by otan** [comment]
ticking off apd and modvendor changes because they were upgraded deliberately.

**Comment by jordanlewis** [comment]
Checked `errcheck`, `go-test-teamcity` neither of which are runtime deps.

**Comment by otan** [comment]
ticking `linkedin/goavro` because that was manually fixed to be go.mod compatible
ticking `testify` as test only.

**Comment by knz** [comment]
Checking off on:

- sentry-go
- pkg/errors
- go-uuid
- pflag
- cobra
- go-isatty
- go-runewidth
- kr/pretty, kr/text

**Comment by knz** [comment]
We also need to double check exactly where this repo is used: github.com/jcmturner/gofork

It contains "modified Go standard library packages for use as work arounds until issues are addressed in the official distribution" however the package is 3 years old so the issues may have been addressed since.

Also it forks crypto-related content, so this is suspicious.

cc @bdarnell @aaron-crl

**Comment by knz** [comment]
@otan I retract my comment on sentry-go. The anchor on 0.3.999 is incorrect. We absolutely need to anchor on tag **v0.6.1-cockroachdb**

**Comment by knz** [comment]
I think there's a go mod brokenness in the sentry-go and cockroachdb/errors packages. looking into it

**Comment by knz** [comment]
Ok I have bumped the go.mod in cockroachdb/errors and sentry-go.
This should get  v0.6.1-cockroachdb.2 for sentry properly.

**Comment by bdarnell** [comment]
`gofork` (and other `jcmturner` repos including `gokrb5`) appear to be brought in by the update to sarama, the kafka client we use, which gained kerberos support since the last time we updated it. It's not clear to me what exactly has changed in that fork, but apparently it is still needed since sarama tried to take it out [but just put it back in](https://github.com/Shopify/sarama/blob/b5764af1c47d0f6718dba3be6a3d75e8c97b351a/gssapi_kerberos.go). 

If sarama is the only use of the `jcmturner` repos, I'm OK with the additions (but someone from CDC should sign off on the update to sarama itself). What repo/branch would I need to check out to be able to grep for this?

**Comment by otan** [comment]
@bdarnell #49447 is the PR

**Comment by bdarnell** [comment]
The etcd changes look good to me; they're picking up some relevant changes from @tbg (and nothing else in the raft package). @tbg, is there any reason your changes like https://github.com/etcd-io/etcd/commit/9018b3dc4dff90cff8b9eca291b67a401f96d189 haven't been picked up in CRDB yet?

**Comment by tbg** [comment]
Wait, we hadn't picked that up yet? That's an omission if it's true, I
thought we had a flaky test because of this.

**Comment by otan** [comment]
mmm, i may have rolled back etcd instead of going forward because of this when using the same version:

```
go: finding go.etcd.io/etcd 4a2b4c8f
go get: go.etcd.io/etcd@v0.5.0-alpha.5.0.20190816082442-4a2b4c8f7e0a requires
	golang.org/x/net@v0.0.0-20190813000000-74dc4d7220e7: invalid pseudo-version: does not match version-control timestamp (2019-08-13T14:13:03Z)
```

**Comment by otan** [comment]
fixed it up, etcd shoudl match now.

**Comment by otan** [comment]
it looks like they never pulled `4a2b4c8f7e0a3754fdd5a3341a27c2431c2a5385` to any of their release branches...

**Comment by tbg** [comment]
Can you just use a newer commit from their latest release branch? Usually there are not many changes in raft.

**Comment by otan** [comment]
the release branch requires a heavy refactor; i've cherry picked a go.mod fix and added it to our fork of etcd.

**Comment by otan** [comment]
ticking zglob as it is part of modvendor; ticking all azure ones as they affect roachprod only.

**Comment by otan** [comment]
* mismatching version: github.com/kisielk/errcheck - go.sum v1.2.0 vs Gopkg.lock v1.1.0
* mismatching version: github.com/konsorten/go-windows-terminal-sequences - go.sum v1.0.2 vs Gopkg.lock v1.0.1

both look good as they upgrade to use go.mod

**Comment by otan** [comment]
>  mismatching version: github.com/Microsoft/go-winio - go.sum v0.4.14 vs Gopkg.lock v0.4.11

lgtm - go mod support and only needed for go-geom indirectly.

**Comment by otan** [comment]
[sarama](https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1592839229257400) et all looks good.

**Comment by otan** [comment]
iostat same SHA, different version tag

**Comment by otan** [comment]
logrus / docker/go-units is a docker related upgrade, so checking

**Comment by nvanbenschoten** [comment]
btree same SHA, different version tag

**Comment by tbg** [comment]
Signed off on https://github.com/opentracing/opentracing-go/compare/v1.0.2...v1.1.0

**Comment by tbg** [comment]
Signed off on https://github.com/golang/text/compare/470f45bf...v0.3.2

There are a ton of commits, I scanned the titles only and nothing stood out. I vaguely remember something about how the collation tables must never change or CRDB will break, however I wasn't able to find a reference to that in the code. Nevertheless, I searched for `collate` and `table` through the commit history of x/test and found nothing.

**Comment by tbg** [comment]
https://github.com/golang/lint/compare/959b441a...910be7a9?tab=doc is fine, nothing changed

**Comment by tbg** [comment]
https://github.com/golang/exp/compare/01c40f57...00229845?tab=doc looks ok too (not saying this with any scientific precision, but I did look through the commit titles)

**Comment by tbg** [comment]
https://github.com/golang/crypto/compare/ff983b9c...0ec3e997?tab=doc as well. A number of bug fixes and test improvements, along with some new features, though none that I expect would affect existing behavior in the small subset of the package we're using.

**Comment by tbg** [comment]
https://github.com/golang/sync/compare/37e7f081...cd5d95a4?tab=doc is fine, almost a noop

**Comment by tbg** [comment]
Jeez, https://github.com/golang/sys/compare/a457fd03...fe76b779?tab=doc has 325 commits, no way I can review that. But reasonably if something regresses here we will have to find out the hard way anyway, it's not like anyone could tell looking at the commits. Signing off.

**Comment by tbg** [comment]
https://github.com/golang/time/compare/85acf8d2...9d24e822?tab=doc is noop

http://github.com/golang/tools/compare/63859f38...2212a7e1?tab=doc has >1000 commits. Signing off blindly. We'll find out if something breaks.

**Comment by tbg** [comment]
https://github.com/googleapis/go-genproto/compare/db91494d...dad8c97a?tab=doc is fine

**Comment by tbg** [comment]
https://github.com/dominikh/go-tools/compare/1f0868a6...v0.0.1-2019.2.3 has >100 updates, but nothing sticks out. If anything it'll probably work better (if it passes lints, which is where we use this mostly)

**Comment by tbg** [comment]
Also checking off prometheus and flatbuffers.

**Comment by tbg** [comment]
Also checking off `arrow`. Usually I would ask Dan to do it but he's out, and I strongly suspect that if there's any problem with this update, we should have been seeing it in our testing where the arrow format is exercised.

**Comment by tbg** [comment]
https://github.com/beorn7/perks/compare/3a771d99...v1.0.1 is basically noop
https://github.com/golang/snappy/compare/2e65f852...ff6b7dc8 ditto
https://github.com/golang/net/compare/a8b05e91...627f9648deb9 is fine, mostly fixing builds on exotic archs

https://github.com/grpc/grpc-go/compare/v1.27.1...v1.29.1 is ok too. I found it interesting that they added some built-in profiling helpers but then had to revert them again because of a perf regression:
https://github.com/grpc/grpc-go/pull/3378

**Comment by tbg** [comment]
https://github.com/go-yaml/yaml/compare/v2.2.8...v2.3.0 is a single commit which looks fine, too.

I think we've got them all!

**Comment by tbg** [comment]
> the master branch requires a heavy refactor on CRDB; i've cherry picked a go.mod fix ([cockroachdb/etcd@a17df30](https://github.com/cockroachdb/etcd/commit/a17df30d59552d296f9ac570b3f72a3683e82a47)) and added it to our fork of etcd.

if you still remember, what was the heavy refactor? That seems unlikely
Either way I signed off on the cherry-pick ref change, that's fine for now

**Comment by otan** [comment]
> if you still remember, what was the heavy refactor? That seems unlikely

oops, i mean heavy rebase*.

**Comment by otan** [comment]
thanks @tbg !
