### ISSUE TITLE
sql: ownership meta issue

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#52021]
Pr for ownership:
- [x] https://github.com/cockroachdb/cockroach/pull/51856

ALTER OWNER:
- [x] https://github.com/cockroachdb/cockroach/issues/52019
- [x] https://github.com/cockroachdb/cockroach/issues/52020
- [x] https://github.com/cockroachdb/cockroach/issues/50882
- [x] https://github.com/cockroachdb/cockroach/issues/48700
- [ ] https://github.com/cockroachdb/cockroach/issues/52022

Inheritance:
- [x] https://github.com/cockroachdb/cockroach/issues/51931

Validation:
- [x] https://github.com/cockroachdb/cockroach/issues/52716

Other:
- [x] https://github.com/cockroachdb/cockroach/issues/51930
- [ ] https://github.com/cockroachdb/cockroach/issues/52513

Jira issue: CRDB-3987
