### ISSUE TITLE
ogr2ogr: support meta-issue

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#52382]
* For v20.2, direct SQL invocations will not work as we cannot insert into spatial_ref_sys directly.
* Workaround is available by importing to PGDUMP and then using IMPORT PGDUMP 

- [ ] https://github.com/cockroachdb/cockroach/issues/52501 (blocker if not using `IMPORT PGDUMP`)

# Blockers for direct SQL
Example invocation: `ogr2ogr -f PostgreSQL "PG:dbname=defaultdb port=26257 user=root host=localhost" census2016_uaim_nsw_short.gpkg -lco LAUNDER=NO`:

- [ ] psql-compatible typmod information
- [x] pg_get_serial_sequence
- [ ] ability to insert into spatial_ref_sys directly
# Blockers for `IMPORT PGDUMP` using INSERT INTO output
Example invocation: `ogr2ogr -f PGDUMP $GOPATH/src/github.com/cockroachdb/cockroach/cockroach-data/extern/oprvrs.sql oprvrs_gb.gpkg -lco LAUNDER=NO`

- [x] Proper support for sequences, e.g.
```
SELECT setval(pg_get_serial_sequence('"public"."WatercourseLink"', 'fid'), MAX("fid")) FROM "public"."WatercourseLink";
```
- [x] INSERT INTO does not work for columns which are "altered" in after CREATE TABLE:
```
CREATE TABLE "public"."HydroNode" (    "fid" SERIAL,    CONSTRAINT "HydroNode_pk" PRIMARY KEY ("fid") );
SELECT AddGeometryColumn('public','HydroNode','geom',27700,'POINT',2);
--ALTER TABLE "HydroNode" ALTER COLUMN "geom" SET NOT NULL;
CREATE INDEX "HydroNode_geom_geom_idx" ON "public"."HydroNode" USING GIST ("geom");
ALTER TABLE "public"."HydroNode" ADD COLUMN "id" VARCHAR(38) NOT NULL;
ALTER TABLE "public"."HydroNode" ADD COLUMN "hydroNodeCategory" VARCHAR(20) NOT NULL;
INSERT INTO "public"."HydroNode" ("geom" , "fid" , "id", "hydroNodeCategory") VALUES ('0101000020346C0000B81E85EB735B1C41333333F31D8F3241', 1, 'id41F90EF5-E9DE-48D0-977F-7599CDA3B5BA', 'source');
INSERT INTO "public"."HydroNode" ("geom" , "fid" , "id", "hydroNodeCategory") VALUES ('0101000020346C0000A4703D0AE35B1C41333333B36C863241', 2, 'idBBD7A2F7-CD52-4925-94B9-3E2070D1FB22', 'junction');
```

result:
```
ERROR: nodelocal://0/oprvrs.sql: targeted column "\"hydroNodeCategory\"" not found
```
- [x] ALTER TABLE ... SET NOT NULL unsupported
```
root@:26257/defaultdb> import pgdump 'nodelocal://0/oprvrs_copy.sql';
ERROR: unsupported statement: ALTER TABLE "HydroNode" ALTER COLUMN geom SET NOT NULL
```

# Blockers for `IMPORT PGDUMP` using COPY option in ogr2ogr
Example invocation: `ogr2ogr --config PG_USE_COPY YES  -f PGDUMP $GOPATH/src/github.com/cockroachdb/cockroach/cockroach-data/extern/oprvrs.sql oprvrs_gb.gpkg -lco LAUNDER=NO`

- [x] COPY has to match the number of columns entered, but in ogr2ogr, PK column is not part of the copy:
```
SET standard_conforming_strings = OFF;
DROP TABLE IF EXISTS "public"."HydroNode" CASCADE;
BEGIN;
CREATE TABLE "public"."HydroNode" (    "fid" SERIAL,    CONSTRAINT "HydroNode_pk" PRIMARY KEY ("fid") );
SELECT AddGeometryColumn('public','HydroNode','geom',27700,'POINT',2);
ALTER TABLE "HydroNode" ALTER COLUMN "geom" SET NOT NULL;
CREATE INDEX "HydroNode_geom_geom_idx" ON "public"."HydroNode" USING GIST ("geom");
ALTER TABLE "public"."HydroNode" ADD COLUMN "id" VARCHAR(38) NOT NULL;
ALTER TABLE "public"."HydroNode" ADD COLUMN "hydroNodeCategory" VARCHAR(20) NOT NULL;
COPY "public"."HydroNode" ("geom", "fid", "id", "hydroNodeCategory") FROM STDIN;
0101000020346C0000B81E85EB735B1C41333333F31D8F3241      1       id41F90EF5-E9DE-48D0-977F-7599CDA3B5BA  source
```

result:
```
ERROR: nodelocal://0/oprvrs_copy.sql: COPY columns do not match table columns for table HydroNode
```
- [x] ALTER TABLE ... SET NOT NULL unsupported
```
root@:26257/defaultdb> import pgdump 'nodelocal://0/oprvrs_copy.sql';
ERROR: unsupported statement: ALTER TABLE "HydroNode" ALTER COLUMN geom SET NOT NULL
```
