### ISSUE TITLE
sql: meta issue for finer-grained role options

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#52575]
This is a meta issue for tracking enhancements related to the [finer-grained role options RFC](https://github.com/cockroachdb/cockroach/pull/51646).

- [x] #52576  add CREATEDB role option
- [x] #52577 add CONTROLJOB role option
- [x] #52578 add CANCELQUERY role option
- [x] #52579 add CANCELSESSION role option
- [x] add VIEWQUERIES role option
- [x] add VIEWQUERYSTATS role option
- [x] #52580 add CONTROLCHANGEFEED role option
- [x] #52581 allow non-admin users to RESTORE
- [x] #52582 disallow non-admin users from dropping admins
- [x] #53554 allow non-admins to modify some cluster settings
