### ISSUE TITLE
sql, bulkio: RESTORE improvements w/r/t types, schemas, leased descriptors

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#53378]
Some of these still need separate issues.

- [x] #53338 backupccl: failed restores need to remove backreferences from existing types
- [x] #53375 sql, backupccl: make type, schema, database descriptors offline during RESTORE
    - A canceled/failed restore job can leave behind orphaned objects that were added to restored schemas in the meantime. This would be fixed by #53375, but if we don't do that, then we should at least drop the child objects or not drop the schema.
- [x] #51417 sql,lease: `Publish`/`PublishMultiple` are bad APIs which can cause bugs
    - We need to both replace the existing usage of `PublishMultiple` in `publishDescriptors` and have all descriptor writes go through the new interface. The current thinking is that the underlying `descs.Collection` will also handle validation.
- [ ] #54403 If a job fails and enters `OnFailOrCancel` after descriptors have been made public, we need to queue drop jobs for all the descriptors instead of simply deleting them. Deleting descriptors without passing through the dropped state first can cause prior leased descriptors to not be released until expiration.

**Comment by ajwerner** [comment]
>We should validate all descriptors before making them public. (This might mostly be a SQL problem, in that our validation methods are incomplete.)

If we do everything right and read and write all descriptors through a `desc.Collection` it feels like we ought to be able to stick a `Validate` method on the thing which can validate not just the structure of each newly written descriptor but also all of its references and back-references without doing any reads from the `kv`.

**Comment by lucy-zhang** [comment]
That's true. I actually had an unrelated concern while writing that, which is that we have yet to implement a schema validation method, but that's easily fixable.

**Comment by lucy-zhang** [comment]
> If we do everything right and read and write all descriptors through a `desc.Collection` it feels like we ought to be able to stick a `Validate` method on the thing which can validate not just the structure of each newly written descriptor but also all of its references and back-references without doing any reads from the `kv`.

Returning to this. (Possibly this discussion should be split off into a separate issue since it affects all users of `descs.Collection`, but maybe RESTORE-specific considerations will come up). I think we decided that we'll have to start caching non-leased descriptors that were fetched in the transaction but never modified (and stored in `uncommittedDescriptors`). Basically, the plan is to have a cache parallel to `uncommittedDescriptors`, or to just reuse that for unmodified descriptors as well. Ultimately we'll never have to fetch a mutable descriptor from disk more than once in the same transaction.

In general, though, it's not the case that we'll resolve all of a descriptor's references and backreferences when resolving the descriptor mutably, and we can't use leased descriptors for the remaining referenced descriptors that haven't been fetched in the transaction already. So calling `Validate()` to perform all the checks will require extra reads from KV in general (or in the worst case as many as we're doing now, since we do already call `Validate()` on schema changes, but outside the `Collection`). Am I missing something here?

**Comment by lucy-zhang** [comment]
Removing the release blocker tags now that we've finished all the release-blocking issues. #54403 remains and will be backported when we get to it.

**Comment by ajwerner** [comment]
Closing as  #54403 tracks the remaining work.
