### ISSUE TITLE
sql: permit user-defined hidden columns

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#53428]
SQL supports hidden columns: columns that are only included in a projection if explicitly requested. An example of this is the `rowid` column that is created on tables without explicitly primary keys.

Currently, there is no way to get a hidden column on a user-defined table: it's only possible if you manually set the hidden boolean in the table descriptor, by editing the CockroachDB source code.

It could conceivably be useful for users to define hidden columns on their own tables. This issue tracks adding that functionality. It should be pretty straightforward, and reasonably suitable for a new contributor.

- [x] Add an NOT VISIBLE keyword to `pkg/sql/parser/sql.y` as an optional modifier to columns for creation and modification. e.g. `CREATE TABLE a (a INT NOT VISIBLE)`, `ALTER TABLE a ALTER COLUMN a SET [NOT] VISIBLE` #58923
- [x] Add a NOT VISIBLE attribute to `ColumnTableDef` in `pkg/sql/sem/tree/create.go` #58923
- [x] Update `MakeColumnDefDescs` in `pkg/sql/catalog/tabledesc/table.go` to set `Hidden` on the column descriptor if the attribute above is set #58923
- [ ] Add `AlterTableSetHidden` AST nodes to `pkg/sql/sem/tree/alter_table.go`
- [ ] Add cases for those AST nodes in `pkg/sql/alter_table.go`
- [x] Add logic tests that verify that hidden columns work as expected. A good place for these would be in `pkg/sql/logictest/testdata/logic_test/hidden`. #58923

**Comment by jasobrown** [comment]
I'd like to take a stab at implementing this, if that's cool.

**Comment by jordanlewis** [comment]
You're more than welcome to, Jason! Thanks.

**Comment by rohany** [comment]
There might be some gotchas that we'll find out along the way. I think there might be some assertions lurking around that `rowid` is the only hidden column.

**Comment by jordanlewis** [comment]
I don't think that's true - didn't you just add the `crdb_internal_mvcc_timestamp` column to every table that's marked hidden too? :)

**Comment by rohany** [comment]
No, that was only within the optimizer's representation of tables.

**Comment by jordanlewis** [comment]
Hmm, ok. I think the hash sharded index columns are also marked hidden though, unless I'm missing something there too (`makeShardColumnDesc`)

**Comment by knz** [comment]
There was a draft implementation here: https://github.com/cockroachdb/cockroach/pull/26644

**Comment by knz** [comment]
That PR incidentally makes the case that it's needed to implement certain pg_catalog tables that also have hidden columns.

Also the approach at the top of this issue is flawed. Look at the linked PR:

> Note: the choice for the syntax "NOT VISIBLE" as opposed to "HIDDEN"
is mandated by the fact that the first word of an attribute must be a
reserved keyword, and adding reserved keywords is disruptive. This
way, the patch is properly backward-compatible.

**Comment by Heoric** [comment]
Which method should be used ?

ALTER TABLE a ALTER COLUMN a [SET|DROP] NOT  VISIBLE
or
 ALTER TABLE a ALTER COLUMN a SET [NOT]  VISIBLE

**Comment by knz** [comment]
I changed the description of the issue to explain that the syntax must use "NOT VISIBLE".
We cannot use a keyword "HIDDEN" in the proposed way, because of grammar restrictions (see #26644 for details).

**Comment by knz** [comment]
> ` ALTER TABLE a ALTER COLUMN a SET [NOT] VISIBLE`

This is the correct one.

**Comment by knz** [comment]
Note: this feature is now discussed as well in this RFC: #58440

**Comment by knz** [comment]
PR #58923 is implementing the CREATE part of this, but does not implement ALTER SET [NOT] VISIBLE. @lucy-zhang requested that we delay the ALTER changes until after the schema change work has moved forward.

**Comment by lucy-zhang** [comment]
I don't think we should necessarily wait for the schema change work to proceed. I just thought it would be easier to review in a separate commit. Do we need ALTER SET VISIBLE for the multiregion work? I have no objections to implementing it.

**Comment by rafiss** [comment]
PR https://github.com/cockroachdb/cockroach/pull/63052 implements `ALTER SET [NOT] VISIBLE`
