### ISSUE TITLE
backupccl: handle schema/type privileges

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#53548]
There are several aspects of privileges on schemas/types that need to be addressed with respect to types/schemas:

- [x] #54183 - Backup should check that the user has sufficient privs on the schemas/types it backups up
- [x] #54182 - SHOW BACKUP should correctly display the privs for the types/schemas included in the backup
- [x] #54328 - For non-cluster restores, privs should be reset as we do for table descriptors since the users/roles that had privs on these descriptors may not exist in the restoring cluster.
    - [x] Ensure OWNERs are properly revoked on non-cluster restore, and are maintained in cluster restore.

**Comment by pbardea** [comment]
Point 3, was addressed and backported in #54854. Closing.
