### ISSUE TITLE
20.2 Release Backports Request List

### ISSUE THREAD

**Issue by isaactwong** [cockroachdb/cockroach#53662]
# Possible backports for the 20.2 release.

Please include a backport requests in this ticket for discussion by the release triage team. If you have an issue that is a release blocker please add the "release-blocker" label and it will be surfaced to the release triage team.

### AppDev

- [x] sql: include partial index predicates in pg_catalog and pg builtins #54076

### BulkIO
- [x] cli: add deprecation notice to dump CLI command #54061
- [ ] parser: fix drop schedule help message #54375
- [ ] backupccl: change CREATE SCHEDULE output `name` column to `label` #54397
- [ ] backupccl: add more backup telemetry #54863
- [ ] backupccl: add scheduled backup telemetry #54864

### Spatial

- [x] geoindex,invertedidx...: add bounding box to inverted column #54128 
- [ ] release-20.2: backport ST_S2Covering #54433
- [ ] release-20.2: backport various standalone geospatial builtins #54436
- [ ] invertedidx: don't do *types.T pointer comparison (bug fix) #54540

### Server / UI

- [x] support opt-in non-TLS SQL client conns in secure clusters #54198
- [x] release-20.2: keys: avoid creating invalid utf-8 sequences in logs #54272

### KV

- [x] server: always create a liveness record before starting up #54212

### SQL Features 

- [ ] make `statement_timeout` respect implicit transactions (#53968)
- [x] make Copy slurp extra bytes #54187
- [x] search_path can be set to something invalid and error message is inaccurate #54192
- [x] release-20.2: sql: support UPDATE ONLY syntax #54426
- [x] release-20.2: sql: allow CONNECTION LIMIT syntax for CREATE DATABASE #54421

### SQL Schema

- [x] sql: non-public schema tables can have zone cfgs #54849
- [ ] schema: meta issue for missing metrics #52078
- [ ] sql/catalog: SchemaDescriptor should have a Validate method #53439
- [ ] sql/catalog: implement log redaction on sqlbase types #51239
- [ ] sql: gate potentially unsafe schema changes behind sql_safe_updates #51863
- [ ] sqlbase: TableDescriptor.Validate is incomplete #50854
- [ ] sql: writing new descriptors to `system.descriptor` from SQL is not possible #50948
- [x] sql: fix DROP COLUMN bug which ignores containing indexes #54262
- [x] sql: fix adding constraints in same transaction as table #54287

### SQL Execution

- [x] release-20.2: sql: make multi-tenancy errors report to telemetry #54341
- [x] multitenancy: implement SHOW/CANCEL QUERIES/SESSIONS for tenants #54336 
- [x] sql: disable interleaved joins by default #54162
- [x] colflow: catch expected panics in an edge case #54404
- [ ] ui: s/"query"/"statement"/ in sessions page #54850

### SQL Optimizer

- [x] opt: add transformation rule to convert left join to inner join #54110
- [x] opt: add transformation rule to convert anti join to left join #54471
- [x] sql: emit more tracing events from the stats cache #54190 - very low risk change, may help debugging; backported to 20.1.x as well
- [x] sql: add placeholder values to the statement diagnostics bundle #54220 - backported to 20.1.x as well
- [x] sql: add telemetry for partial indexes #54474
- [x] opt: generate lookup joins on partial indexes #54362
- [x] unwrap explain.Node in ConstructScanBuffer #54419 - fixes a regression that results in an internal error
- [x] opt: fix st_distance -> st_dwithin rule to cast distance param as float #54366 - fixes a panic/internal error in new functionality

### Performance Regressions

**Comment by ajwerner** [comment]
@JuanLeon1 @isaactwong is this still useful?

**Comment by celiala** [comment]
Closing, as we've released 20.2, and currently have a different process for reviewing/approving backport requests
