### ISSUE TITLE
opt: 21.1 release checklist

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#53912]
This issue captures a series of tests and steps that we need to run when 20.2 is getting close to being finalized.
 - [x] check bug fixes that may need backport
 - [x] check and update private opt tests repository
 - [ ] check regressions in microbenchmarks
 - [x] run all tests with `TAGS=fast_int_set_small` and `TAGS=fast_int_set_large`
 - [x] check that any new session settings have a cluster setting for the default (or a good justification for why not)
 - [x] consider adding session+cluster settings for all new features
 - [x] check TODOs in opt code (especially those added since the last release)
 - [x] clone an instance of this issue for the next release

Jira issue: CRDB-3821
