### ISSUE TITLE
auth: OIDC user experience improvements

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#54619]
This issue collects quality of life improvements to the OIDC feature being completed here #41856

* [x] ~Better error message when state fails to validate~ errors have been standardized
See: https://github.com/cockroachdb/cockroach/blob/dd97761d2fc2d8a9da1f110e327c92263df9e03e/pkg/ccl/oidcccl/authentication_oidc.go#L244
* [x] Autologin OIDC when password login is disabled and OIDC is enabled #55552 
* [x] ~Disable password login cluster setting~ this is captured by the item above
* [x] Query param to force password login prompt (or a separate pwd login page) when password login is disabled #55552 
* [x] Telemetry on feature #55623
* [x] ~Metrics on state cache size~ (not needed if hmac change is merged)
* [ ] e2e integration test with token validation
* [X] follow up on HMAC-based stateless flow so we can take out all the state management from the authn transaction #55556
