### ISSUE TITLE
workload/schemachange: improve error classification, random schema generation, and observability

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#56118]
This is the parent issue to track progress on the schemachange workload project. The goals and motivation of the project are discussed in detail in this [doc](https://docs.google.com/document/d/1vVE10kP_JxUwkHTI8vmu6IYRax4giOY8MEOtpxpNTlg/edit?usp=sharing).

**Error Classification** 
- [x] Add knob to control the frequency of errors (https://github.com/cockroachdb/cockroach/pull/55521)
- [x] Classify and handle errors (https://github.com/cockroachdb/cockroach/issues/56119)

**Complex Schema Generation**
- [x] Support user defined schemas (https://github.com/cockroachdb/cockroach/pull/54889)
- [x] Create views/tables that depend on other views/tables (https://github.com/cockroachdb/cockroach/pull/55521)
- [x] Unique constraints (https://github.com/cockroachdb/cockroach/pull/58065)
- [x] Single FK constraints (https://github.com/cockroachdb/cockroach/issues/57472)
- [ ] Composite FK constraints
- [ ] Check constraints
- [ ] Serial column types that are backed by sequences
- [ ] Use DEFAULTs in insertRow op. This will require small updates in unique/fk constraint checking where we will have to look up column defaults and sub them in. 

**Observability**
- [x] Improve logging and add backups https://github.com/cockroachdb/cockroach/issues/57471

**Automation**
- [ ] Improve github issues created by roachtest failures https://github.com/cockroachdb/cockroach/issues/58245

**Other Improvements**
- [x] Handle aborted transactions / update nested function calls to use nested transactions (https://github.com/cockroachdb/cockroach/issues/56120)
- [ ] Use better knobs https://github.com/cockroachdb/cockroach/issues/57300
- [ ] Have a way to debug errors in the workload https://github.com/cockroachdb/cockroach/issues/57949

Jira issue: CRDB-3577

**Comment by postamar** [comment]
We've either done a lot of these things or have other issues tracking them, so I'll close.
