### ISSUE TITLE
logging: database access management (DAM)

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#56156]
Here's a list of tasks to get us fully compliant with Audit Logging requirements.

- [x] #56148 logging: create new debugging log `cockroach.debug.log`
- [x] #56149 logging: restrict `cockroach-sql-exec.log` to **users** SQL statements that have been so GRANTed
- [x] #56151 logging: log all Events into a new `cockroach.events.log` file
- [x] #56153 logging: log Jobs into separate log file
- [x] #56154 logging: enhance cockroach auth logging -  #56154 

The goal is to ensure that for no meaningful event it is required to enable the "debug" log. Currently, DCL and user password changes are only logged to `cockroach-sql-exec.log`.

**ZenDesk:** [6513](https://cockroachdb.zendesk.com/agent/tickets/6513)

**Comment by thtruo** [comment]
Thanks @fabiog1901 - good fit for what your RFC is solving for @knz https://github.com/cockroachdb/cockroach/pull/51990

**Comment by knz** [comment]
Thanks fabio for filing these discrete issues. Most of the requests can probably be satisfied.

Some of the specifics raise security questions though, and so the phrasing of the issues as-is in github is insufficient to translate this into action items. However I hope that @piyush-singh and @aaron-crl can sit together and hash out how to get a satisfying UX outcome without authorization problems. 

(Example issue: when a table is marked for auditing, and a user without privilege attempts to use that table, should the SQL error be logged to that table's audit log? Including the text of the statement and possible sensitive strings? Arguably, that statement is not "within" the authorization realm for that table, so it looks like unauthorized information disclosure to report too much details about it to the log.

Generally this is the reason why error messages should not be detailed in audit logs.)

**Comment by knz** [comment]
Most of the issues have been addressed by the recent logging work.
Closing this in favor of the last remaining issue #56154 which will be addressed by #56154
