### ISSUE TITLE
import: Issue tracking PGDUMP improvements

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#56659]
**High Priority**
- [x] Support user defined schema / Schema manipulation statements
           https://github.com/cockroachdb/cockroach/issues/29471
   Fix: #57183
- [x] PARTIAL INDEXES
          https://github.com/cockroachdb/cockroach/issues/50225
- [ ] CREATE SEQUENCE AS integer: failed since we do not support AS
          https://github.com/cockroachdb/cockroach/issues/29046
   Fix: #57339
- [x] Array data
          https://github.com/cockroachdb/cockroach/issues/29043 
   Fix: #58244
- [x] Views
          https://github.com/cockroachdb/cockroach/issues/29039

**Medium Priority**
- [x] DROP TABLE [IF EXISTS] https://github.com/cockroachdb/cockroach/issues/53112
        Fix: #56920
- [ ] CREATE and ALTER SEQUENCE
          https://github.com/cockroachdb/cockroach/issues/53958
          https://github.com/cockroachdb/cockroach/issues/55469
          https://github.com/cockroachdb/cockroach/issues/56767

**Low Priority**
- [ ] Citext columns

**To Triage**
- [ ] DROP DATABASE [IF EXISTS]. No issue created yet. TLDR: pgdump `--clean` and `--create` flags allow users to prepend `DROP DATABASE IF EXISTS` and `CREATE DATABASE ` to the dump file. 

Not solving - other workaround
- [ ] Stored procedures
- [ ] Auto Vacuum https://github.com/cockroachdb/cockroach/issues/56364
- [ ] GRANT ALL ON SCHEMA
          https://github.com/cockroachdb/cockroach/issues/30647
          https://github.com/cockroachdb/cockroach/issues/56369
- [ ] Deferred FK
- [ ] ALTER DEFAULT PRIVILEGES

Jira issue: CRDB-2917

**Comment by mokaixu** [comment]
NB: Work for `CREATE VIEW` #29039 has been put on on hold due to design limitations. `CREATE VIEW` needs to be able to support arbitrary SQL queries and therefore the code at import should be able to understand all of SQL (this logic exists in the sql optbuilder).

Can circle back on this when discussions related to separating sql logic for ddls and import logic for the ingestion of data is addressed.

**Comment by mwang1026** [comment]
Any thoughts on `varchar_pattern_ops`? From what I can tell it allows creation of indexes that allow `LIKE` or `POSIX` string comparisons. Is this something where we would just skip the creation of that index?

**Comment by adityamaru** [comment]
nextval support added in - https://github.com/cockroachdb/cockroach/pull/56473

**Comment by adityamaru** [comment]
Work is also being done to improve the ignore semantics of unsupported statements during an IMPORT PGDUMP.
The current approach is to introduce an option `ignore_unsupported` which will ignore all unparseable and unsupported SQL statements seen during an IMPORT PGDUMP. We also plan to expose a `ignored_stmt_log_destination` (name subject to change) which will allow the user to point to where they would like us to write the ignored constructs.

**Comment by adityamaru** [comment]
TODO: go through all our example customer pgdump files and add ignore rules for unsupported statements.

**Comment by adityamaru** [comment]
IMPORT has moved over to @cockroachdb/sql-foundations, considering most items on this list were completed I'm inclined to close this. Future improvements can be tracked more granularly.
