### ISSUE TITLE
roachtest/schemachange/random-load: failures and bugs

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#57470]
This is a parent issue which tracks bugs found by the schemachange/random-load roachtest. TeamCity creates these issues and comments bugs to investigate. 
- https://github.com/cockroachdb/cockroach/issues/56235
- https://github.com/cockroachdb/cockroach/issues/56230
- https://github.com/cockroachdb/cockroach/issues/56081
- https://github.com/cockroachdb/cockroach/issues/56425

Comments aren't particularly organized between the separate issues, so they should be **hidden** and **triaged** into correctly into the child issue categories below.

**Workload Issues**
Any bugs in the workload itself that have caused errors
- [ ] check for missing primary key https://github.com/cockroachdb/cockroach/issues/57493
- [x] fix primitive type resolution https://github.com/cockroachdb/cockroach/issues/57993
- [x] improve interactions between savepoints and txn retry errors https://github.com/cockroachdb/cockroach/issues/58068
- [ ] update DDL after write error logic https://github.com/cockroachdb/cockroach/issues/58141

**Database Issues**
Any bugs in database code which result in unexpected errors occurring 
- [x] schema change after write is allowed https://github.com/cockroachdb/cockroach/issues/57476
- [x] descriptor is being dropped error https://github.com/cockroachdb/cockroach/issues/57487
- [x] index in the middle of being added error https://github.com/cockroachdb/cockroach/issues/42844
- [x] table remains visible in transaction after being dropped/renamed https://github.com/cockroachdb/cockroach/issues/57494
- [x] column remains visible in transaction after being dropped/renamed https://github.com/cockroachdb/cockroach/issues/58067
- [x] deadlock/timeout https://github.com/cockroachdb/cockroach/issues/56425

Jira issue: CRDB-3528

**Comment by ajwerner** [comment]
@fqazi I'm going to let you decide to close this after you decide if there's any value to it.

**Comment by rafiss** [comment]
Closing due to staleness
