### ISSUE TITLE
logging: standardize the event log and bring structured details to external logs

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57629]
Today we have an `EventLog` mechanism inside the SQL package that writes JSON blobs to `system.eventlog`. These use structured payloads that are undocumented, unstable and irregular/inconsistent.

Then, separately, we also have the logging infrastructure that writes unstructured strings to external files.

We want instead to have structured payloads that are documented, stable and consistent, and have them into external files (or network collector when that is supported - see #57170  ), on a dedicated logging channel (see #57171 ).

Steps:

- [x] finish converting the calls throughout the SQL package #57737
- [x] find some workable approach for the node events #57737 
- [x] fix the generated names for grant/revoke events  #57737 
- [x] add a doc generator  #57737 
- [x] tweak the files in `pkg/ui/src/util` accordingly  #57737 
- [x] add an assertion in `sql.planner` that everything that touches descriptor has at least 1 event logged - NOT DONE, instead filed #57823 for SQL Schema team
- [x] add a "category" field for cluster-level vs sql-level, use that in doc generator   #57737 
- [x] recognize the events in `util/log` and treat them separately   #57737 
- [x] make writes to system.eventlog conditional #57879
- [x] include the sql tenant ID in log file headers alongside cluster ID #57888 #57890
- [x] update PR #57171 to assign cluster events to the OPS channel 
- [x] rework PR #51987 to assign DDL and privilege events to their appropriate channels
- [x] ensure that individual fields inside JSON notable events are redacted (or marked as redactable) separately  #57990 
- [x] add the application name to all structured sql events #58130 
- [x] insert JSON formats #58126 
- [x] treat event types specially and insert their JSON representation inline #58126 
- [x] transform the single-string "Tags" payload of log events into separate JSON fields #58126 
- [x] modify the JSON output to inject the node ID and tenant ID and sql instance ID as separate discrete fields #57890   #58128 
- [x] pgwire: migrate auth/conn logs to notable events #57839
- [x] update the RFC in #51990 
- [x] new RFC to explain notable events #58374 
- [x] sql: ensure event log entries for ALTER/DROP TYPE are fully qualified #58257 
- [x] add placeholder values alongside the SQL statement #59108
- [x] add more structure for the events for accesses to audited tables (SENSITIVE_ACCESS) and SQL query logs #59105  #59110
- [x] server: file operational notable events for TLS cert rotations #57889  #59345
- [x] add a new sort of SQL query logging, for all statements performed by admin users  #58334 #59356

**Comment by knz** [comment]
cc @thtruo

**Comment by knz** [comment]
Finding during the investigation:

- SQL-level log events (e.g. "drop database") operate within the context of a SQL tenant server, which only have a "SQL instance ID". These do not typically have access to a Node ID, which is a KV concept.

- Cluster-level log events (e.g. "node join") do have node IDs, but they don't typically have access to a SQL instance ID.

So we will need different metadata for them.

**Comment by knz** [comment]
Updated todo list:

- [x] finish converting the calls throughout the SQL package #57737
- [x] find some workable approach for the node events #57737 
- [x] fix the generated names for grant/revoke events  #57737 
- [x] add a doc generator  #57737 
- [x] tweak the files in `pkg/ui/src/util` accordingly  #57737 
- [ ] add an assertion in `sql.planner` that everything that touches descriptor has at least 1 event logged
- [ ] add a "category" field for cluster-level vs sql-level, use that in doc generator
- [ ] recognize the events in `util/log` and treat them separately
- [ ] modify #57170 to treat event types specially and insert their JSON representation inline

**Comment by knz** [comment]
lifting the remaining to-do list to the top of the issue.

**Comment by knz** [comment]
All the items have been addressed.
