### ISSUE TITLE
opt: inverted index improvements

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#59331]
This issue tracks improvements that could be made to inverted indexes.

- [ ] use inverted indexes to satisfy filters with comparison operators: `<`, `<=`, `>`, `>=` #35154
- [ ] partitioned inverted indexes #43643 #48100
- [ ] create several alternative plans when inverted index spans are intersected #56868
- [ ] enable histogram statistics for JSON and ARRAY inverted index scans #56870
- [ ] use paired joins for left joins with non-covering indices #55452
- [ ] improve cardinality estimate for lookup join that follows an inverted join #55448
- [ ] calculate statistics for the JSON fetch val and equality operator #55319
- [ ] generate inverted index scans for chained JSON fetch value operators with equality expression #55317
- [ ] generate inverted index scans for JSON fetch value and containment operators #55318
- [ ] enable usage of inverted index with OR clauses #47340
- [ ] support INVERTED INDEX range scans #24960
- [ ] support indexed key-contains queries in JSON inverted indexes #23905
- [ ] index accelerate the `&&` overlap operator
- [ ] plan inverted joins when filters have a `->` JSON fetch value operator
- [ ] use "optional" filters (CHECK constraints and computed column expressions)
- [ ] use computed column expressions to constrain
- [ ] sqlsmith should generate random inverted indexes
- [ ] sqlsmith should generate random multi-column inverted indexes
- [ ] index accelerate the `->` JSON fetch value operator when the index (right side of the `->`) is an integer
- [ ] index accelerate the `->` JSON fetch value operator when the result is equal to an object or array, e.g. `j->'a' = {"a": "b"}`
- [ ] plan inverted zig zag joins on multi-column inverted indexes
- [ ] consider indexed computed column expressions when planning inverted joins (see [TODO](https://github.com/cockroachdb/cockroach/pull/59266/files#diff-e89121c658a6a042f344e9170ece05a0003449b6baa68727d849715132801803R62))
