### ISSUE TITLE
kvprober: implement a prober that sends queries to KV in order to generate signal on the healthiness of KV client & below

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#61074]
https://docs.google.com/document/d/1NqsIgizseyMxUBimpE10m6sSnbebQ25VyJRUwxdmJyM/edit

**Is your feature request related to a problem? Please describe.**
The problem to solve it provide operators & others better signals of the healthiness of kvclient & below.

Operators & others can alert on these signals. CRL can use them to think about how "big" outages are & to understand where in CRDB stack (is KV broken or not?) & keyspace the impact is.

**Describe the solution you'd like**
Implement a prober that sends queries to KV in order to generate signal on the healthiness of KV client & below. For a POC that does reads only, see https://github.com/cockroachdb/cockroach/pull/58124.

**Describe alternatives you've considered**
More discussion in design doc linked above about alternatives.

By 21.2:
- [x] Implement a basic prober that does reads the whole "rangespace" by sending `Gets` to the start key of a randomly selected ranges in loop: https://github.com/cockroachdb/cockroach/pull/58124
- [x] Protect CRDB against repeated plan failures: https://github.com/cockroachdb/cockroach/issues/61255
- [x] Probe start key + some suffix to avoid contention as per comments from Tobias here: https://github.com/cockroachdb/cockroach/pull/58124
- [x] Move to `timeutil.NewTimer` per comments from Tobias here: https://github.com/cockroachdb/cockroach/pull/61275
- [X] Address meta2 in more idiomatic way as per comments from Tobias here: https://github.com/cockroachdb/cockroach/pull/58124
- [x] Design v1 write prober (prob custom command to send NOP operation thru raft): https://github.com/cockroachdb/cockroach/issues/67112
- [x] Implement v1 write prober: https://github.com/cockroachdb/cockroach/issues/67112

Later:
- [x] Log out successful probes but without adding so much noise to logs, e.g. by having a dedicated log file for `kvprober`
- [ ] Design v1 scan prober (scan at historical timestamp)
- [ ] Implement v1 scan prober
- [ ] Break metrics down by leaseholder
- [ ] Trace all probes made by kvprober: https://github.com/cockroachdb/cockroach/issues/69427
- [ ] Do structured logging via `pkg/util/log/eventpb` 
- [ ] Test panic recovery
- [ ] Test timeout logic
- [ ] Build a probe whole keyspace fast mode: https://github.com/cockroachdb/cockroach/issues/61695
- [ ] Build repeatedly probe unavailable ranges once found logic

Epic CC-5241

**Comment by joshimhoff** [comment]
I opened some follow up issues. I am closing this one as the main work is DONE!
