### ISSUE TITLE
sql: connection pooling meta issue

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#62393]
General connection questions:
- [x] How many idle/active connections are supported. 
  - Ans: hard to quantify, better to write in terms of memory overhead.
- [x] Idle / Active connection overhead https://github.com/cockroachdb/cockroach/issues/62525
  - https://github.com/cockroachdb/cockroach/issues/62525#issuecomment-809737358 answer here
- [x] Performance impacts of connections on TPCC https://github.com/cockroachdb/cockroach/issues/62526
  - Ans: With some limited testing, idle connections of up to 10000 on 3 node roachprod clusters made no noticeable difference.
- [x] memory overhead of prepared statements https://github.com/cockroachdb/cockroach/issues/63248

Other:
- [ ] How does my connection pool interact with load balancing as nodes come up and down?  https://github.com/cockroachdb/cockroach/issues/62530
- [x] Can I use PGBouncer to handle hundreds of thousands of connections from my microservices and multiplex them to a smaller number of connections to CRDB? https://github.com/cockroachdb/cockroach/issues/62529
  - Summary: CockroachDB is compatible with PGBouncer. Unsure of performance benefits as preliminary TPCC testing with up to 10000 idle connections showed no benefit. Users can test performance to deem if necessary or feel free to use if there is application side benefits.
- [x] Add connection latencies to roachperf https://github.com/cockroachdb/roachperf/pull/56

**Comment by RichardJCai** [comment]
Did some very informal testing for this just preparing a hundred thousand statements.

It seems like memory overhead can grow arbitrarily but overall the memory usage is very low (likely just the string).

ie.
```
PREPARE y30 AS SELECT 123::string;
PREPARE y31 AS SELECT 123::string;
PREPARE y32 AS SELECT 123::string;
PREPARE y33 AS SELECT 123::string;
PREPARE y34 AS SELECT 123::string;
PREPARE y35 AS SELECT 123::string;
PREPARE y36 AS SELECT 123::string;
PREPARE y37 AS SELECT 123::string;
PREPARE y38 AS SELECT 123::string;
PREPARE y39 AS SELECT 123::string;
```
