### ISSUE TITLE
sql: extend sql smith testing for user defined types

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#62894]
**Describe the problem**

We taught SQL Smith some things about user defined types as part of https://github.com/cockroachdb/cockroach/issues/49916, but the coverage there is very basic. It only supports creating user defined types with <= 7 enum members. There's a fair bit of scope to extend it and this meta issue captures that. 

- [ ] Add support for `ALTER TYPE ... DROP VALUE` https://github.com/cockroachdb/cockroach/issues/62812 
- [ ] Add support for `ALTER TYPE ... ADD VALUE` https://github.com/cockroachdb/cockroach/issues/62895
- [ ] Add support for `ALTER TYPE .... RENAME VALUE ... TO` https://github.com/cockroachdb/cockroach/issues/62897
- [ ] Add support for `ALTER TYPE ... RENAME TO` https://github.com/cockroachdb/cockroach/issues/62896
