### ISSUE TITLE
ruby-pg: meta issue for failing tests

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#63642]
Running the ruby-pg test suite against CRDB results in many failing tests currently. Too many to create individual issues.

- [ ] PG::TypeMapByColumn will deny copy queries with different column count
- [ ] PG::TypeMapByColumn should gracefully handle not initialized state
- [ ] PG::TypeMapByColumn forwards get_copy_data conversions to another TypeMapByColumn as #default_type_map
- [ ] PG::TypeMapByOid should build a TypeMapByColumn when assigned and the number of rows is high enough
- [ ] PG::TypeMapByOid should allow mixed type conversions in binary format
- [ ] PG::TypeMapByOid should allow mixed type conversions in text format
- [ ] PG::TypeMapByOid should allow building new TypeMapByColumn for a given result
- [ ] running with sync_* methods PG::Connection calls the block supplied to wait_for_notify with the notify payload if it accepts three arguments
- [ ] running with sync_* methods PG::Connection calls a block for NOTIFY events if one is given
- [ ] running with sync_* methods PG::Connection sends nil as the payload if the notification wasn't given one
- [ ] running with sync_* methods PG::Connection described_class#block shouldn't block a second thread
- [ ] running with sync_* methods PG::Connection gracefully handle SQL statements while in #copy_data for output
- [ ] running with sync_* methods PG::Connection calls the block supplied to wait_for_notify with the notify payload if it accepts two arguments
- [ ] running with sync_* methods PG::Connection not read past the end of a large object
- [ ] running with sync_* methods PG::Connection automatically rolls back a transaction started with Connection#transaction if an exception is raised
- [ ] running with sync_* methods PG::Connection doesn't leave stale server connections after finish
- [ ] running with sync_* methods PG::Connection can handle server errors in #copy_data for input
- [ ] running with sync_* methods PG::Connection can process #copy_data output queries
- [ ] running with sync_* methods PG::Connection gracefully handle SQL statements while in #copy_data for input
- [ ] running with sync_* methods PG::Connection doesn't collapse sequential notifications
- [ ] running with sync_* methods PG::Connection can process #copy_data input queries
- [ ] running with sync_* methods PG::Connection can handle client errors in #copy_data for output
- [ ] running with sync_* methods PG::Connection correctly finishes COPY queries passed to #async_exec
- [ ] running with sync_* methods PG::Connection calls the block supplied to wait_for_notify with the notify payload if it doesn't accept arguments
- [ ] running with sync_* methods PG::Connection can handle client errors in #copy_data for input
- [ ] running with sync_* methods PG::Connection can handle server errors in #copy_data for output
- [ ] running with sync_* methods PG::Connection returns notifications which are already in the queue before wait_for_notify is called without waiting for the socket to become readable
- [ ] running with sync_* methods PG::Connection calls the block supplied to wait_for_notify with the notify payload if it accepts any number of arguments
- [ ] running with sync_* methods PG::Connection allows a query to be cancelled
- [ ] running with sync_* methods PG::Connection accepts nil as the timeout in #wait_for_notify
- [ ] running with sync_* methods PG::Connection can handle incomplete #copy_data output queries
- [ ] running with sync_* methods PG::Connection can receive notices while waiting for NOTIFY without exceeding the timeout
- [ ] running with sync_* methods PG::Connection trace and untrace client-server communication
- [ ] running with sync_* methods PG::Connection returns the block result from Connection#transaction
- [ ] running with sync_* methods PG::Connection can wait for NOTIFY events
- [ ] running with sync_* methods PG::Connection set_single_row_mode should receive rows before entire query is finished
- [ ] running with sync_* methods PG::Connection set_single_row_mode should receive rows before entire query fails
- [ ] running with sync_* methods PG::Connection deprecated forms of methods should forward send_query to send_query_params
- [ ] running with sync_* methods PG::Connection deprecated forms of methods should forward exec to exec_params
- [ ] running with sync_* methods PG::Connection multinationalization support returns properly encoded text from notifies
- [ ] running with sync_* methods PG::Connection multinationalization support receives properly encoded text from wait_for_notify
- [ ] running with sync_* methods PG::Connection multinationalization support receives properly encoded messages in the notice callbacks
- [ ] running with sync_* methods PG::Connection multinationalization support encodes exception messages with the connection's encoding (#96)
- [ ] running with sync_* methods PG::Connection multinationalization support handles clearing result in or after set_notice_receiver
- [ ] running with sync_* methods PG::Connection multinationalization support respect and convert character encoding of input strings should convert strings to #send_describe_portal
- [ ] running with sync_* methods PG::Connection multinationalization support respect and convert character encoding of input strings should convert strings and parameters to #prepare and #exec_prepared
- [ ] running with sync_* methods PG::Connection multinationalization support respect and convert character encoding of input strings should convert query string and parameters to #send_query_params
- [ ] running with sync_* methods PG::Connection multinationalization support respect and convert character encoding of input strings should convert strings and parameters to #send_prepare and #send_query_prepared
- [ ] running with sync_* methods PG::Connection multinationalization support respect and convert character encoding of input strings should convert strings to #describe_portal
- [ ] running with sync_* methods PG::Connection multinationalization support respect and convert character encoding of input strings should convert query string and parameters to #exec_params
- [ ] running with sync_* methods PG::Connection multinationalization support respect and convert character encoding of input strings should convert error string to #put_copy_end
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support uses the client encoding for escaped literal
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support should return results in the same encoding as the client (EUC-JP)
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support the connection should use JOHAB dummy encoding when it's set to JOHAB
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support should return results in the same encoding as the client (iso-8859-1)
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support can use an encoding with high index for client encoding
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support uses the client encoding for escaped string
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support uses the previous string encoding for escaped string
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support uses the previous string encoding for quote_ident
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support uses the client encoding for quote_ident
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support the connection should return ASCII-8BIT when it's set to SQL_ASCII
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support uses the client encoding for escaped identifier
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support returns the results in the correct encoding even if the client_encoding has changed since the results were fetched
- [ ] running with sync_* methods PG::Connection multinationalization support rubyforge #22925: m17n support raises appropriate error if set_client_encoding is called with invalid arguments
- [ ] running with sync_* methods PG::Connection multinationalization support Ruby 1.9.x default_internal encoding allows users of the async interface to set the client_encoding to the default_internal
- [ ] running with sync_* methods PG::Connection multinationalization support Ruby 1.9.x default_internal encoding honors the Encoding.default_internal if it's set and the synchronous interface is used
- [ ] running with sync_* methods PG::Connection type casting shouldn't type map params unless requested
- [ ] running with sync_* methods PG::Connection type casting can type cast parameters to put_copy_data with explicit encoder
- [ ] running with sync_* methods PG::Connection type casting with default query type map can process #copy_data input queries with row encoder and respects character encoding
- [ ] running with sync_* methods PG::Connection type casting with default result type map should work with arbitrary number of params in conjunction with type casting
- [ ] running with sync_* methods PG::Connection type casting with default result type map can process #copy_data output with row decoder and respects character encoding
- [ ] running with sync_* methods PG::Connection type casting with default result type map should respect a type mapping for result
- [ ] running with sync_* methods PG::Connection type casting with default result type map can type cast #copy_data output with explicit decoder
- [ ] PG::Result raises a proper exception for a nonexistant schema
- [ ] PG::Result encapsulates errors in a PG::Error object
- [ ] PG::Result encapsulates database object names for integrity constraint violations
- [ ] Basic type mapping PG::BasicTypeMapForResults with usage of result oids for copy decoder selection can type cast #copy_data output with explicit decoder
- [ ] Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 0 timestamps per TimestampLocal
- [ ] Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 1 timestamps per TimestampUtc
- [ ] Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should do float type conversions
- [ ] Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should do cidr type conversions
- [ ] Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should do text datetime without time zone type conversions
- [ ] Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 0 timestamps per TimestampUtc
- [ ] Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 1 timestamps per TimestampUtcToLocal
- [ ] Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 0 timestamps per TimestampUtcToLocal
- [ ] Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should do array type conversions
- [ ] Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 1 timestamps with time zone
- [ ] Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 0 timestamps with time zone
- [ ] Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 1 timestamps per TimestampLocal
- [ ] Basic type mapping PG::BasicTypeMapBasedOnResult with usage of result oids for copy encoder selection can type cast #copy_data input with explicit encoder
- [ ] Basic type mapping PG::BasicTypeMapBasedOnResult with usage of result oids for bind params encoder selection can do JSON conversions
- [ ] Basic type mapping PG::BasicTypeMapForQueries should do IPAddr param encoding
- [ ] Basic type mapping PG::BasicTypeMapForQueries should do bigdecimal param encoding
- [ ] Basic type mapping PG::BasicTypeMapForQueries should do hash-as-json encoding
- [ ] Basic type mapping PG::BasicTypeMapForQueries should do array of string encoding on unknown classes
- [ ] Basic type mapping PG::BasicTypeMapForQueries should do default array-as-array param encoding with Time objects
- [ ] Basic type mapping PG::BasicTypeMapForQueries should do default array-as-array param encoding
- [ ] Basic type mapping PG::BasicTypeMapForQueries should do basic param encoding
- [ ] Basic type mapping PG::BasicTypeMapForQueries should do basic Time encoding
- [ ] Basic type mapping PG::BasicTypeMapForQueries should do basic param encoding of various float values
- [ ] Basic type mapping PG::BasicTypeMapForQueries should do array-as-json encoding
- [ ] Basic type mapping PG::BasicTypeMapForQueries Record encoding should do array-as-record encoding
- [ ] PG::TypeMapByClass should expire the cache after changes to the coders
- [ ] PG::Connection doesn't leave stale server connections after finish
- [ ] PG::Connection sends nil as the payload if the notification wasn't given one
- [ ] PG::Connection can handle client errors in #copy_data for input
- [ ] PG::Connection automatically rolls back a transaction started with Connection#transaction if an exception is raised
- [ ] PG::Connection returns the block result from Connection#transaction
- [ ] PG::Connection can handle server errors in #copy_data for output
- [ ] PG::Connection calls the block supplied to wait_for_notify with the notify payload if it doesn't accept arguments
- [ ] PG::Connection allows a query to be cancelled
- [ ] PG::Connection can process #copy_data output queries
- [ ] PG::Connection can handle client errors in #copy_data for output
- [ ] PG::Connection returns notifications which are already in the queue before wait_for_notify is called without waiting for the socket to become readable
- [ ] PG::Connection can process #copy_data input queries
- [ ] PG::Connection not read past the end of a large object
- [ ] PG::Connection doesn't collapse sequential notifications
- [ ] PG::Connection gracefully handle SQL statements while in #copy_data for output
- [ ] PG::Connection calls a block for NOTIFY events if one is given
- [ ] PG::Connection can wait for NOTIFY events
- [ ] PG::Connection can handle incomplete #copy_data output queries
- [ ] PG::Connection calls the block supplied to wait_for_notify with the notify payload if it accepts any number of arguments
- [ ] PG::Connection gracefully handle SQL statements while in #copy_data for input
- [ ] PG::Connection can handle server errors in #copy_data for input
- [ ] PG::Connection can receive notices while waiting for NOTIFY without exceeding the timeout
- [ ] PG::Connection correctly finishes COPY queries passed to #async_exec
- [ ] PG::Connection trace and untrace client-server communication
- [ ] PG::Connection accepts nil as the timeout in #wait_for_notify
- [ ] PG::Connection calls the block supplied to wait_for_notify with the notify payload if it accepts three arguments
- [ ] PG::Connection described_class#block shouldn't block a second thread
- [ ] PG::Connection calls the block supplied to wait_for_notify with the notify payload if it accepts two arguments
- [ ] PG::Connection multinationalization support handles clearing result in or after set_notice_receiver
- [ ] PG::Connection multinationalization support receives properly encoded messages in the notice callbacks
- [ ] PG::Connection multinationalization support encodes exception messages with the connection's encoding (#96)
- [ ] PG::Connection multinationalization support returns properly encoded text from notifies
- [ ] PG::Connection multinationalization support receives properly encoded text from wait_for_notify
- [ ] PG::Connection multinationalization support Ruby 1.9.x default_internal encoding allows users of the async interface to set the client_encoding to the default_internal
- [ ] PG::Connection multinationalization support Ruby 1.9.x default_internal encoding honors the Encoding.default_internal if it's set and the synchronous interface is used
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support uses the previous string encoding for quote_ident
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support raises appropriate error if set_client_encoding is called with invalid arguments
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support can use an encoding with high index for client encoding
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support uses the client encoding for escaped string
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support uses the client encoding for escaped literal
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support returns the results in the correct encoding even if the client_encoding has changed since the results were fetched
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support uses the previous string encoding for escaped string
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support the connection should use JOHAB dummy encoding when it's set to JOHAB
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support uses the client encoding for escaped identifier
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support uses the client encoding for quote_ident
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support should return results in the same encoding as the client (iso-8859-1)
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support the connection should return ASCII-8BIT when it's set to SQL_ASCII
- [ ] PG::Connection multinationalization support rubyforge #22925: m17n support should return results in the same encoding as the client (EUC-JP)
- [ ] PG::Connection multinationalization support respect and convert character encoding of input strings should convert query string and parameters to #send_query_params
- [ ] PG::Connection multinationalization support respect and convert character encoding of input strings should convert strings and parameters to #send_prepare and #send_query_prepared
- [ ] PG::Connection multinationalization support respect and convert character encoding of input strings should convert query string and parameters to #exec_params
- [ ] PG::Connection multinationalization support respect and convert character encoding of input strings should convert strings to #describe_portal
- [ ] PG::Connection multinationalization support respect and convert character encoding of input strings should convert strings and parameters to #prepare and #exec_prepared
- [ ] PG::Connection multinationalization support respect and convert character encoding of input strings should convert strings to #send_describe_portal
- [ ] PG::Connection multinationalization support respect and convert character encoding of input strings should convert error string to #put_copy_end
- [ ] PG::Connection type casting can type cast parameters to put_copy_data with explicit encoder
- [ ] PG::Connection type casting shouldn't type map params unless requested
- [ ] PG::Connection type casting with default query type map can process #copy_data input queries with row encoder and respects character encoding
- [ ] PG::Connection type casting with default result type map can type cast #copy_data output with explicit decoder
- [ ] PG::Connection type casting with default result type map can process #copy_data output with row decoder and respects character encoding
- [ ] PG::Connection type casting with default result type map should respect a type mapping for result
- [ ] PG::Connection type casting with default result type map should work with arbitrary number of params in conjunction with type casting
- [ ] PG::Connection set_single_row_mode should receive rows before entire query is finished
- [ ] PG::Connection set_single_row_mode should receive rows before entire query fails
- [ ] PG::Connection deprecated forms of methods should forward send_query to send_query_params
- [ ] PG::Connection deprecated forms of methods should forward exec to exec_params
