### ISSUE TITLE
sql: persistent SQL Stats main tracking issue

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#64743]
This is the main tracking issue for all persisted SQL Stats related work:

## Infrastructure:

* [x] [system table schema](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20210330_sql_stats_persistence.md#system-table-schema): 
  * #65374 
  * #67331
  * #69320
  * #69502
* [x] JSON encoding for stats objects: 
  * #67805
* [x] [flush mechanism](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20210330_sql_stats_persistence.md#writing-in-memory-stats-to-system-tables): 
  * #67090
* [x] a feature flag + version gate : 
  * #67090 
  * #69592
* [x] Clean up old stats using job 
  * #68434
* [x] Runs the clean up job on a schedule 
  * #68401 
  * #69346
* [ ] Running benchmark with new persisted SQL stats turned on to measure the performance impact.
   * [x] Initial [benchmark](https://github.com/cockroachdb/cockroach/pull/67090#issuecomment-887089444) shows ~2ms increase in average latency
   * [x] More [benchmark](https://github.com/cockroachdb/cockroach/pull/67090#issuecomment-891866786) on SQL Stats flush with different configurations.
   * [ ] testing flushing behaviour with injected errors in an overloaded cluster. (chaos testing)

## Minimum Requirement to enable it by default by 21.2

* [x] [Serve both cluster-wide in-memory stats with persisted SQL stats through a virtual table](#68193) 
  * #68555 
  * #68620 
  * #68675
  * #68715
  * #69022
  * #69049
  * #69441
* [x] Update status RPC/HTTP endpoint to be able to be queried by aggregation interval. 
  * #69238 
  * #69591
* [x] Update the [DB Console Statement/Transaction Page](https://github.com/cockroachdb/cockroach/issues/68089) to include a [time picker](#69474) to select aggregation interval.
  * #68831
* [x] Extend Reset SQL Stats to support resetting on-disk stats.
  * #69273

## Further Enhancement 

* [x] #69302
* [x] #69303
* [x] #67867
* [x] #69032
* [x] #69321
* [x] #69429
* [x] #67500
  * Depends on #63885

## Clean Up

* [ ] #69326
* [x] #59205 
* [x] #66047

RFC PR: #63752 

Epic: CRDB-9866

Jira issue: CRDB-7226
