### ISSUE TITLE
restore: investigation of performance bottlenecks

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#64937]
This is a tracking issue to summarize the ongoing performance investigation work to identify and remove bottlenecks in RESTORE performance.

# Bottlenecks Identified

- [x] Many requests not handled locally
    - Fix bug in split and scattering mapping (https://github.com/cockroachdb/cockroach/pull/63875)
- [x] Nodes completing their assigned work with a large variance (this could still be improved, but the variance was reduced significantly)
    - Adjust chunk size based on cluster size (https://github.com/cockroachdb/cockroach/pull/64067)
- [x] Split-and-scatter was scattering was inefficiently chunking entries
    - Rework split and scattering mechanism (https://github.com/cockroachdb/cockroach/pull/63471)
- [ ] Large nodes not saturated with AddSSTable requests
   - [x] Parallelize RESTORE (https://github.com/cockroachdb/cockroach/pull/61942)
   - [ ] Memory monitoring (https://github.com/cockroachdb/cockroach/issues/64936)
- [ ] Restore on large nodes is waiting for split and scatter to finish

# Ongoing Investigations
- [x] Performance testing with incremental layers + revision history
- [ ] Performance testing on geo-distributed clusters to identify latency bottlenecks

# Milestones

As a means to keep track of the goals. The next milestone will be defined when the previous one is reached.

- [x] **Milestone 1**
    - [x] Restore 2TB (replicated) dataset from a full-backup on a 6 node cluster with plenty of memory (e.g. n2-standard-16s) at 200(replicated) MB/s/node. (Testing vertical scaling) 
    - [x] Restore 2TB (replicated) dataset from a full-backup on a 32 node cluster should be at most 10% slower per node than a 10 node cluster. (Testing horizontal scaling)

**Comment by pbardea** [comment]
Closing out this investigation issue as we've identified a good set of things to work on and will assign myself to the relevant tickets created as a result of this investigation.
