### ISSUE TITLE
jobs: job lease expiration query is long-running, holds locks, runs frequently [meta-issue]

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#65081]
**Describe the problem**

The query used to make remove claims due to expired sessions can be slow and lays down locks as it goes.

https://github.com/cockroachdb/cockroach/blob/88754f2866fde1f37620b04c6a708eefc0b5be54/pkg/jobs/registry.go#L671-L675

This is problematic as this query can hold off readers. Holding off readers is bad UX. This can happen if the jobs table has a large number of jobs in an adoptable state and there is high latency between nodes. The jobs table doesn't even need to be in a bad state like in https://github.com/cockroachdb/cockroach/issues/62666.

Part of the problem is that, in order to decide whether a row should be updated, we need to perform an index join. A second part of the problem is there is no bound on the number of rows we'll attempt to update. Another problem is that the operation happens on all nodes in the cluster at a pretty high frequency; the contention can lead to restarts.

Restarts on this query are not themselves fundamentally problematic; deadlock detection eventually should pick a winner. The problem is that while this is happening, readers will be blocked.

**Proposed solution[s]**

Short term work:
1) [x] (backport) In order to not starve readers, we should run this update at low priority. This will largely mitigate the UX considerations. (https://github.com/cockroachdb/cockroach/issues/65077).
1) [x] (backport) We currently do not limit the number of jobs rows which we mark as unassigned, meaning if one node had many claims, we'll potentially need to update many rows. Having a bound on the number of rows updated at a time in the cancellation loop will help bound the duration of the transaction and, hopefully, avoid livelock issues. (https://github.com/cockroachdb/cockroach/issues/65075).
1) [x] (maybe backport) The fact that this query runs on each node, once every 10s seems pretty crazy given the amount of work it has to do, at least on large, global clusters. The intervals should be cluster settings. (https://github.com/cockroachdb/cockroach/issues/65079)
1) [x] (definitely can't backport) The query, in the common case, should be much cheaper than it is. If we had the right index, we could scan tighter spans and completely avoid an index-join. Creating a better index can mitigate these problems. (https://github.com/cockroachdb/cockroach/issues/65080)

Future work:

4) [ ] The cancellation task could be coordinated using leases and only run on one node to eliminate the contention on the table. 

Epic: CRDB-7912

**Comment by awoods187** [comment]
Nice analysis here!

**Comment by RaduBerinde** [comment]
@shermanCRL we need someone to take ownership of these jobs issues and carve out time to work on the backportable fixes.

**Comment by dt** [comment]
@RaduBerinde sql-schema has ownership of the general jobs infrastructure, while specific teams own their own jobs and how they behave. Is there something about one of bulk-io's job you wanted me to look at here?

**Comment by RaduBerinde** [comment]
No, I thought BulkIO has ownership of the general jobs infrastructure. Assigning @jordanlewis and @ajwerner instead.

**Comment by ajwerner** [comment]
All of the proposed changes here have been implemented 🎉 .
