### ISSUE TITLE
admission control: default cluster settings are set to enabled 

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#65955]
The admission.kv.enabled and admission.sql_kv_response.enabled cluster settings have a default value of false. There will be more cluster settings when we integrate {SQLSQLResponseWork, SQLStatementLeafStartWork, SQLStatementRootStartWork} which will also be false.
This tracking bug is to set the defaults to enabled for 21.2. Work items:

- [x] Investigate drop in cpu utilization when admission control is enabled.
- [x] Integrate for SQL=>SQL response admission
- [x] Store overload only affects write requests to the relevant store (#65957)
- [x] Benchmarks (tpccbench etc.) show no slowdown. Results: no slowdown for tpccbench. kv benchmarks that do not overload the store also show no slowdown.
- [x] Multi-store roachtest with single store overloaded.
- [x] Investigate behavior when tpcc is overloaded to figure out interaction between locking and admission control (the graphs show a significant drop in throughput 5+ min into the run, that recovers after 1min)
- [x] Investigate kv0 throughput drop to 0 when store is overloaded (the tokens for the 60s time interval should be non-zero)
- [x] Add trace statements for admission queue wait times (#68595)
- [x] Fixes from tpcc and kv investigation
- [x] Make `l0FileCountOverloadThreshold`, `l0SubLevelCountOverloadThreshold` configurable via cluster setting.
- [x] Add admission control metrics to overload page in the DB console (#68595)
- [x] Reduce frequency of goschedstats polling when node is mostly idle (#66881)
- [ ] Roachtest for multi-tenant environments (#65954)
- [x] Ensure sane interaction between admission control and rebalancing. Resolved based on internal discussion with KV folks

**Comment by sumeerbhola** [comment]
The investigation of drop in cpu utilization was done in https://github.com/cockroachdb/cockroach/pull/66891

**Comment by sumeerbhola** [comment]
Manually running tpccbench and kv benchmarks as a precursor to adding them to roachperf.
- tpcc on aws with 2999 warehouses (close to the limit) does not show any slowdown. The cpu utilization was ~85%, and only  0.23% of cpu is in the admission package, and 1.68% of mutex contention. Admission control is mostly not restricting admission as the cpu and storage are not overloaded.
- kv0/enc=false/nodes=3/cpu=32 also shows no slowdown for the same reason.
- kv0/enc=false/nodes=3/cpu=32/size=64kb results in an unhealthy store in the absence of admission control -- the L0 sublevels count keeps rising, and we've probably not noticed/cared for the short duration these run for. With admission control on, we see the system switch back and forth between not restricting work and restricting work, and this happens at the granularity of 1min. At the low point there are ~100 files and ~7 sub-levels, which suggests that the granularity of switching at 1min is acceptable (we did not get to a low point where L0 was fully healthy). See attached graphs.
<img width="678" alt="Screen Shot 2021-08-05 at 1 06 13 PM" src="https://user-images.githubusercontent.com/54990988/128393367-6620702f-a9f1-4fd1-a064-d686ace6e1b1.png">
<img width="1034" alt="Screen Shot 2021-08-05 at 1 05 28 PM" src="https://user-images.githubusercontent.com/54990988/128393392-f55ddc1f-6095-437a-9c4a-a13a8c39fb38.png">

**Comment by sumeerbhola** [comment]
**tpccbench investigation** ("significant drop in throughput 5+ min into the run, that recovers after 1min"):
- This is rare IO overload that currently causes tokens to be restricted for a 1min interval. tpcc sometimes crosses the 10 sublevel count threshold with only 100 files in L0.
- Possible solution is to increase threshold to 20 and decrease the restriction time from 1min

**kv throughput drop to 0 during store write overload**
- This was unexpected since there are a positive number of tokens even when store is overloaded.
- There is no locking in this work: write is an upsert of a single row, and locktable metrics stay at 0 when throughput drops to 0. So it can't be explained by txns holding locks being slow to get admitted and thereby blocking others that are ahead.
- During overload node 1 is receiving HeartbeatTxnRequests that bypass admission control, and use up all the write slots. So nothing else gets through. Interestingly, nodes 2, 3 are not receiving such requests (perhaps node 1 is the leaseholder for all ranges?). When not overloaded, the write requests that bypass admission control are primarily TruncateLogRequests and these are going to all nodes equally.
- HeartbeatTxnRequests are occurring due to admission control throttling. Since we know these are tiny, perhaps they should not consume an admission token.
