### ISSUE TITLE
sql/kv: bounded staleness reads

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#67562]
Tracking issue for bounded staleness reads, as outlined in #66020.

The tracking issue is split into [three stages](https://github.com/cockroachdb/cockroach/blob/025c53decd8eb00cb70a1d410692026c9f8614dc/docs/RFCS/20210519_bounded_staleness_reads.md#limitations):
> - **Stage 1 - single-scan, single-range queries**
> - **Stage 2 - single-scan, multi-range queries**
> - **Stage 3 - multi-scan, multi-range queries**

#### Stage 1:
- [ ] https://github.com/cockroachdb/cockroach/issues/67549
- [ ] https://github.com/cockroachdb/cockroach/issues/67551
- [ ] https://github.com/cockroachdb/cockroach/issues/67552
- [ ] https://github.com/cockroachdb/cockroach/issues/67553
- [ ] https://github.com/cockroachdb/cockroach/issues/67555
- [ ] https://github.com/cockroachdb/cockroach/issues/67556
- [ ] https://github.com/cockroachdb/cockroach/issues/67558

#### Stage 2:
- [ ] https://github.com/cockroachdb/cockroach/issues/67554

#### Stage 3:
- [ ] https://github.com/cockroachdb/cockroach/issues/67559
