### ISSUE TITLE
*: rework zone configurations to support tenants

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#67679]
This is the tracking issue for #66348. We've been prototyping the what's described in the RFC over at [`multi-tenant-zcfgs`](https://github.com/cockroachdb/cockroach/tree/multi-tenant-zcfgs) (see all the recent PRs prefixed with `[prototype]` and the project board [here](https://github.com/cockroachdb/cockroach/projects/63)). This is the tracking issue to merge the prototype branch back into master, adding more rigorous testing for it as we do. We expect the work to ~ break down into the following major and minor PRs:

Major:
- [x] #68522; introduce the span config manager and the reconciliation job
- [x] #69047; expose new span config related RPCs on KV, introduce the backing system table on the host tenant, and grant access to KV RPCs through the tenant `Connector`
- [x] #69172; abstract away the use of the system config span in KV
- [x] #70287; implement an in-memory data structure to store spans and their corresponding configs
- [x] #71359; translate sql descriptors and corresponding zone configs into constituent spans and span configs
- [x] #69614; introduce a per-store listener over `system.span_configurations`, using it to maintain a `spanconfig.Store` to replace `config.SystemConfig`
- [x] #71968; introduce watchers over system.{descriptor,zones} in SQL to learn about zone config changes
- [x] #71994; make use of SQL{Watcher,Translator} and spanconfig.Store to issue RPCs to KV

Minor:
- [x] #69169; introduce `system.zones` for secondary tenants + enable secondary tenants to commit zone configs
- [x] #69275; validate locality constraints/regions in zone configs for secondary tenants
- [x] #69658; gate the creation of reconciliation job behind a cluster setting for secondary tenants, and env var for host tenant
- [x] #71256 + #71225; introduce a thin buffer on top of a rangefeed to batch + flush timestamp sorted events
- [x] #71795; add datadriven tests for the KVAccessor
- [x] #73086; expose "frontier timestamp precedes the GC threshold" rangefeed errors
- [x] #73150; support atomic batch update for spanconfig store
- [ ] Add limits to request sizes for `{Get,Update}SpanConfigs`
- [ ] Overload `RANGE TENANT` to seed default zone config for new tenants
- [ ] De-deplicate config proto messages between zonepb and roachpb
- [ ] Expose the number of KVSubscriber restarts due to internal errors as a metric
- [ ] Write datadriven tests for spanconfig.SQLWatcher
- [ ] Add checkpointing to the reconciliation job

Epic CRDB-2515.

Epic CRDB-10563

**Comment by irfansharif** [comment]
With the spanconfig.Reconciler (#71994) we've finished the feature work phase of this project, shifting now into hardening mode -- tracked in #73874 (listing important outstanding TODOs).
