### ISSUE TITLE
CockroachDB CI does not properly cache dependencies

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#69334]
- [ ]  cdc/bank roachtest pull 260MB off a 3rd party vendor upon every CI run, and fails if upstream unavailable #51543 
- [ ]  Example-ORMs pulls files from 3rd party vendors on every CI run, and fails if upstream is unavailable #52342 
- [ ]  roachtest: jepsen tests pull code from github upon every run #62023 
- [ ] roachtest: jepsen tests pull code from clojar upon every run #62066
- [ ]  acceptance: all acceptance tests that use docker download images from docker-io upon every use #62024 
- [ ]  CI pulls from npmjs registry upon every run and fails if npmjs reg is not available #69333 

Previously tracked here: https://github.com/cockroachdb/dev-inf/issues/39
Unsure where this is tracked now.

**Comment by knz** [comment]
still relevant
