### ISSUE TITLE
storage: non-atomic renames with encryption-at-rest

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#69861]
Extracting this into its own issue from https://github.com/cockroachdb/cockroach/issues/55967#issuecomment-889527891.

This Pebble comment has a good summary of current state of the world and discussion of potential solutions:
https://github.com/cockroachdb/pebble/pull/1227#issuecomment-909436699

All the potential solutions for this issue require backwards incompatible changes.

All the tasks below are release blockers, except for those marked with [GA], which are general availability blockers:
- [x] Introduce format major version into Pebble, and replace the `CURRENT` file with an atomic marker. cockroachdb/pebble#1227
- [x] Bump Pebble on master.  #69967
- [x] Bump Pebble on release-21.2. #69969
- [x] Add call to RatchetFormatMajorVersion via an internal cluster version. #70025
- [x] Backport PR to add call to RatchetFormatMajorVersion via an internal cluster version. #70055
- [x] Update file registry to use an atomic marker file. #69941.
- [x] Backport PR to update file registry to use an atomic marker file. #70042
- [x] Update data keys registry to use an atomic marker file. [GA] #70156
- [x] Backport PR to update data keys registry to use an atomic marker file. [GA] #70335

**Comment by jbowens** [comment]
> Update data keys registry to use an atomic marker file. [GA]

@sumeerbhola Do you still think we should try to migrate the data keys registry to a record-based file format at the same time? I'm a little wary of rushing it out the door, but if we don't need to until GA that does give us some time.

**Comment by jbowens** [comment]
The beta release blocker elements have been fixed and merged.

There's still the remaining issue that a crash during a rotation of the data keys registry may corrupt the store. This only applies to stores using encryption-at-rest. It's also an issue that has existed in all prior releases of encryption-at-rest. We would still like to fix it before GA, through a new migration.

**Comment by jbowens** [comment]
All known instances are resolved on 21.2 and master.
