### ISSUE TITLE
opt: 22.1 release checklist

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#73254]
This issue captures a series of tests and steps that we need to run when 22.1 is getting close to being finalized.
 - [x] check bug fixes that may need backport
 - [x] check and update private opt tests repository
 - [x] check regressions in microbenchmarks
 - [x] run all tests with `TAGS=fast_int_set_small` and `TAGS=fast_int_set_large`
 - [x] check that any new session settings have a cluster setting for the default (or a good justification for why not)
 - [x] consider adding session+cluster settings for all new features
 - [x] check TODOs in opt code (especially those added since the last release): #79137
 - [x] clone an instance of this issue for the next release
 - [x] check the SQL Queries high likelihood bucket for issues that we'd really like to get into the release

Jira issue: CRDB-11497

**Comment by mgartner** [comment]
SQL Queries session settings that were added without cluster default settings include:

* `disable_plan_gists`
* `index_recommendations_enabled`
* `null_ordered_last`
* `cost_scans_with_default_col_size`
* `default_transaction_quality_of_service`
* `opt_split_scan_limit`

**Comment by mgartner** [comment]
As of 22.1, users can set default session settings for all roles (or a particular role) with `ALTER ROLE ...`. For example: `ALTER ROLE ALL SET index_recommendations_enabled = false`. So cluster settings aren't necessary.
