### ISSUE TITLE
settings: multi-tenant cluster settings tracking issue

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#73857]
This issue tracks the implementation of multi-tenant cluster settings, as described in the [RFC](https://github.com/cockroachdb/cockroach/pull/73349):
 - [x] introduce the new setting classes (#73937)
 - [x] add support for overrides in the SettingsWatcher (#73774)
 - [x] disallow any uses of system-only settings from tenant code (#74253)
 - [x] design API for listening to tenant overrides from the host cluster (for use by the tenant connector) (#74268)
 - [x] add the new `system.tenant_settings` table (#76313)
 - [x] implement the host side of the API above using a range feed on the tenant settings table (similar to `SettingsWatcher`) (#76445)
 - [x] implement `TenantReadOnly` semantics (#76680)
   - [ ] change appropriate settings to `TenantReadOnly` (partially done)
 - [x] implement the tenant side code that uses the API (#75711)
 - [x] delete tenant settings when deleting tenant (#76716)
 - [x] add tenant setting overrides to tenant backups (#76758)
 - [x] implement the new statements in the RFC #76929 #77218 #77471 

Nice to haves:
 - [x] fail SET CLUSTER SETTING in the tenant if there is an override (in progress)
 - [ ] add infrastructure for consistently retrieving the current value along with the information whether this is an override (one idea in [this comment](https://github.com/cockroachdb/cockroach/pull/73774#pullrequestreview-831053053)); make `SHOW CLUSTER SETTING` (on the tenant) show when the setting is an override
 - [x] audit all non-system-only settings and find the set that needs to be moved to system (e.g. most `kv.*` settings are not SystemOnly) #77472 
 - [x] implement "system visible" class where the tenant sees the system value by default (?) (see https://github.com/cockroachdb/cockroach/pull/73349#issuecomment-1041959046)

  Epic: CRDB-6671

Jira issue: CRDB-11785

**Comment by vy-ton** [comment]
- [ ] audit all non-system-only settings and find the set that needs to be moved to system (e.g. most kv.* settings are not SystemOnly)

FYI this should be done in consultation with various product areas/eng teams so that they understand how to classify settings going forward

**Comment by knz** [comment]
Regarding the remaining identified steps, what skills/expertise are required:

> add the new system.tenant_settings table and implement the host side of the API above using a range feed on the tenant settings table (similar to SettingsWatcher)

This is probably SQL schema

> implement the tenant side code that uses the API

SQL experience

> implement the new statements in the RFC

SQL experience

> audit all non-system-only settings and find the set that needs to be moved to system (e.g. most kv.* settings are not SystemOnly)
add tenant setting overrides to tenant backups

Server

> add infrastructure for consistently retrieving the current value along with the information whether this is an override (one idea in this comment); make SHOW CLUSTER SETTING (on the tenant) show when the setting is an override; also disallow SET CLUSTER SETTING while an override is in effect.

SQL experience

cc @ajstorm

**Comment by knz** [comment]
We have completed the work on this, especially through
- [ ] #77472
- [ ] #110758
