### ISSUE TITLE
sql,bulk: index backfiller cross-version compatibility tracking issue

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#74147]
Rewriting the index backfiller to account for the removal on non-MVCC operations requires that we correctly handle schema change jobs generated from past versions.  Because we restore schema change jobs during a `RESTORE`, this includes being able to handle (in some way) schema change jobs from arbitrarily far in the past.  This issues tracks the work we think is required to make that work:

- [ ] New Index Backfiller should only write new-style backfill jobs once a given cluster version `DoubleIndexBackfills` is active.
- [ ] BatchEval should reject non-MVCC operations once a given cluster version (`DisallowNonMVCCOps`) is active
- [ ] [Reverting Schema changes should not attempt to rebuild indexes](https://github.com/cockroachdb/cockroach/issues/74146)
- [ ] (nice-to-have) [Schema change jobs should carry the cluster version they were created on. This will make it a bit cleaner to early-exit old schema changes after `DisallowNonMVCCOps` has passed.](https://github.com/cockroachdb/cockroach/issues/74151)
- [ ] (nice to have) A migration that waits for all in-flight schema changes to enter a terminal state.

Epic CRDB-10258

Jira issue: CRDB-11941

**Comment by stevendanna** [comment]
cc @ajwerner @dt this is s stub tracking ticket for the work we discussed with respect to handling cross-version compatibility.
