### ISSUE TITLE
sql: contention event store main tracking issue

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#74485]
This is the meta tracking issue for the new Contention Event Registry described in the [Contention Even Store RFC](https://github.com/cockroachdb/cockroach/pull/71965)

---

# In scope for 22.1

# Infrastructure
* [x] [KV Layer start tracking Gateway Node ID](https://github.com/Azhng/cockroach/blob/rfc-ces/docs/RFCS/20211013_contentions.md#option-2-kv-team-embeds-nodeid-into-contention-event) 
  * #73500
* [x] #74486
  * #74114
  * #74115
  * #74687
* [x] #74487
  * #75177
  * #75176
  * #75763
  * #75835
  * #76549
  * #76719
* [x] TPCC/TPCE/KV95 benchmark to measure performance impact
  * #77514
* [x] #75110
  * #77607
* [x] #76329 
  * #76523
* [x] #75998
* [x] Stability:
  * #77673
  * #77623
  * #77514

# Performance

* [x] #76013 
  * #76244
  * #76350
  * #76418
* [x] #76738
  * #77220
* [x] #77447

# Interface
* [x] #75904
  * #76917

---

# Post 22.1

# Data Persistence

* [ ] System table for persisting contention event
* [ ] Periodic flush process 
* [ ] Periodic cleanup job for deleting old data
* [ ] Virtual table that exposes combined in-memory and persisted contention events (Require Data Persistence)

# UX
* [x] New Contention Tab under SQL Activity Page

# Optimization: 
* [ ] [Self Throttling](https://github.com/Azhng/cockroach/blob/rfc-ces/docs/RFCS/20211013_contentions.md#performance-consideration) (possibly using low pass filter option)
* [x] Implement ConcurrentWriteBuffer Sharing between `connExecutor`s
* [ ] Resolver outbound RPC rate limiter
