### ISSUE TITLE
dev,bazel: miscellaneous paper cuts

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#75453]
**Describe the problem**

Here's an assorted list of paper cuts we should address. They're grouped by size and should ease the transition away from `make` as a daily driver. Collecting them here for the Bazel CS team + volunteers.

Small:
- [x] --rewrite should probably imply --ignore-cache
- [x] list all [supported build targets](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/dev/build.go#L70-L96) as part of 'dev build -h'
- [x] stop munging ccache paths through dev to reduce build thrashing when switching between bazel/dev
- [x] introduce a top-level --test-arg to pass arguments directly to the go test binary (see 'go help testflags' for all you can do); get rid of --rewrite-arg while here.
- [x] when running test/benchmark with '-{cpu,mem}profile' passed to the underlying go test binary, it's not clear where the pprof output is placed
- [x] support --stress{,-args}, --count for 'dev testlogic' (maybe unify the code paths with 'dev test'?)
- [x] support --show-sql for 'dev testlogic'
- [x] disable test sharding (--test_sharding_strategy=disabled) when --filter is specified; for sharded (like pkg/kv/kvserver) packages when filtering for a specific test, there's a lot of additional test runner output for spawns that don't do anything.
- [x] symlink 'cockroach' to the 'cockroach-short' binary for 'dev build short'
- [x] ~maybe stream 'dev test' output by default (i.e. use --test_output streamed instead), or provide a flag for it~ [serializes test runs](https://docs.bazel.build/versions/main/command-line-reference.html#flag--test_output) which may be undesirable
- [x] https://github.com/cockroachdb/cockroach/issues/76513
- [ ] `dev test pkg/kv/kvserver -f TestNonExistent` succeeds without any warnings; we could be peeking at the generated test.xml and spit out something: 
```
$ cat _bazel/testlogs/pkg/kv/kvserver/kvserver_test/test.xml
```
- [ ] pprof profiles expects generated files to be found under `bazel-out`, but we stash them under `_bazel/`
  - Adding `build --symlink_prefix=bazel-` to `.bazelrc.user` is a temporary workaround. Alternatively commenting out `build --symlink_prefix=_bazel/` in .bazelrc. See #81748
  - To repro:
```
dev bench pkg/sql/colexec/colexecjoin -f=MergeJoiner/rows=32768 --count=5 --cpus=1 --test-args="-test.cpuprofile=cpu.out" --bench-mem
go tool pprof -http localhost:8081 cpu.out # navigate to "Source" view and see that listings for .eg.go files aren't resolvable
```
- [ ] pass '-no_warning_for_no_symbols' to libtool/ar on macs (gets rid of benign "has no symbols" warnings, [hint](https://github.com/bazelbuild/bazel/blob/master/site/docs/cc-toolchain-config-reference.md))
- [ ] top-level `dev clean` (aliasing `bazel clean {--expunge}` and re-parenting `dev ui clean --all` to come underneath it
- [ ] `dev gen bazel --short` to only run gazelle

Medium:
- [x] https://github.com/cockroachdb/cockroach/issues/76527
- [ ] https://github.com/cockroachdb/cockroach/issues/79785
  - [ ] evaluate speedups if using a memory-mounted sandbox base; by-passing all IO.
- [ ] with vanilla go, when a test test hangs, you can ctrl-/ which a sigquit to Go and dumps all goroutines; with bazel the signal goes to bazelisk instead
- [ ] https://github.com/cockroachdb/cockroach/issues/74906
- [x] https://github.com/cockroachdb/cockroach/issues/73944
- [x] #74457; add ability to build test targets without linking the test binaries (can noticeably slow things down)
- [x] #76276; add ability to hoist any and all generated code back into the workspace
- [x] #71854; don't generate gomock code through bazel
- [x] #72233; add ability to hoist generated protos without needing a full build (you often want to protoc code gen to get your code to be compilable, say when changing a proto interface)
- [x] provide an easy way to run a [remote build cache](https://github.com/buchgr/bazel-remote) locally, bazel's out-of-the-box cache busting is painful
- [x] improve the testing story for dev (the mocks/recordings are being maintained by hand at the moment)

Epic CRDB-17171

Jira issue: CRDB-12679

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-12679](https://cockroachlabs.atlassian.net/browse/CRDB-12679) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-75453`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rickystewart** [comment]
I'm closing this. Most of the remaining paper cuts either already have GitHub issues set up, or they're tasks which I'm uncertain we'll actually implement.
