### ISSUE TITLE
distsql: processor implementation checklist

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#7587]
This issue tracks implementation of various processor "core" types:
- [X] Table Reader
- [X] Join Reader
- [x] Sort
  - [x] Basic implementation
  - [x] Implementation that takes advantage of partial orderings
  - [x] Speed-ups for limits
- [x] Aggregation (GROUP BY)
  - [x] Local stage
  - [x] Final stage
- [x] Evaluator
  - [ ] Support function calls that need the `EvalCtx` (#13821)
- [x] Distinct
- [x] Join
  - [x] Merge Join
  - [x] Hash Join
- [x] Set operations
- [x] Limit

**Comment by irfansharif** [comment]
taking on Sort.

**Comment by irfansharif** [comment]
taking on Aggregation.

**Comment by RaduBerinde** [comment]
I have some partial work done on a merge-join processor, I will continue work on that when the work around tracing stuff dies down.

**Comment by irfansharif** [comment]
taking on `Evaluator` (see `PROGRAM` in the RFC). 
> `PROGRAM` is a fully programmable no-grouping aggregator. It runs a "program"
  on each individual row. The program can drop the row, or modify it
  arbitrarily.

**Comment by irfansharif** [comment]
taking on `Distinct`.

**Comment by irfansharif** [comment]
taking on Join next, taking over from #10054.

**Comment by RaduBerinde** [comment]
Added Limit to the list.

**Comment by irfansharif** [comment]
@RaduBerinde: how about `Final`?

**Comment by RaduBerinde** [comment]
It's there, as a "no-op" processor (NoopCoreSpec).
