### ISSUE TITLE
sql, ccl/sqlproxyccl: connection migration tracking issue

### ISSUE THREAD

**Issue by jaylim-crl** [cockroachdb/cockroach#76000]
This issue tracks the implementation of the connection migration mechanism, as described in this RFC: https://github.com/cockroachdb/cockroach/pull/75707.

- [x] add postgres interceptor for message forwarding (#76006)
  - [x] update PeekMsg to return message size instead of body size. See comment [here](https://github.com/cockroachdb/cockroach/pull/76006#pullrequestreview-881620994). (#76562)
- [x] add `SHOW TRANSFER STATE [ WITH <transfer_key> ]` observer statement (#76127)
- [x] refactor connection establishment logic into a connector component  (#76417)
- [x] add basic forwarder component with ConnectionCopy logic (#76167)
- [x] update ConnectionCopy logic to use interceptors (#76560)
- [x] add token-based auth into connector component (#76417)
- [x] add migration logic to forwarder (#76805)
  - [x] cleanup interceptor API (#76613). It was difficult to update the destination of interceptors without this.
- [x] observability: metrics and logging (See #76805)
  - "There should be metrics tracking the number of failed transfers and the number of connections closed mid-transfer. The metrics should be visible on the sqlproxy grafana page."
  - The grafana updates will be part of CC, and will be omitted here.
- [x] Attempt to refactor expectNextServerMessage again. The approach of us checking the message size can be confusing as-is here. (#77109)
- [x] Add metrics to measure DataRow size. This will allow us to figure out what's the right size. (#77700)
- [ ] clean up interceptor benchmarks (#76429)
- [x] clean up TenantResolver interface (#78276)

Related Epics:
- https://cockroachlabs.atlassian.net/browse/CC-5385
- https://cockroachlabs.atlassian.net/browse/CC-5387

Jira issue: CRDB-12912

**Comment by rafiss** [comment]
Can this be closed?

**Comment by jaylim-crl** [comment]
The connection migration work has been completed, and has been running in production for over a year now. Closing this issue.
