### ISSUE TITLE
multitenant: Investigate tests which fail when run using the default test tenant

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#76378]
A change was made with #76582  to enable all tests which leverage `testServer`/`testCluster` to run with some probability in multi-tenant mode.  In doing so, several tests were found to fail or hang when run under multi-tenant mode.  This tracking issue enumerates all of the problematic test cases so that they can be investigated in the future.

Jira issue: CRDB-13093

## Remaining tests that specify the parameter `TODOTestTenantDisabled`

By product area:

**Disaster recovery**

- [ ]  49 pkg/ccl/backupccl
- [ ]  14 pkg/ccl/streamingccl
- [x]   2 pkg/ccl/jobsccl

**KV**

- [x]   9 pkg/ccl/spanconfigccl
- [x]   5 pkg/kv/kvserver
- [x]   2 pkg/spanconfig/spanconfigkvaccessor
- [x]   1 pkg/kv/kvclient/rangefeed/rangefeedcache

**Mixed bag: Obs Inf - DB Server - Multi-tenant**

- [ ]  pkg/server - SQL inspection APIs
- [x]  pkg/server - debug API tests
- [x]  pkg/server - server controller tests
- [x]  32 pkg/ccl/serverccl
- [x]   1 pkg/ts
- [x]   1 pkg/upgrade/upgrademanager
- [x]   1 pkg/util/tracing
- [x]   1 pkg/server/systemconfigwatcher
- [x]   1 pkg/server/structlogging

**Multi-tenant**

- [x]   9 pkg/ccl/multitenantccl
- [x]   4 pkg/kv/kvclient/kvtenant
- [x]   2 pkg/configprofiles
- [x]   2 pkg/base
- [x]   1 pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl
- [x]   1 pkg/multitenant/tenantcapabilities
- [x]   1 pkg/ccl/testutilsccl

**SQL / Migrations**

- [ ]  18 pkg/sql/importer
- [ ]   5 pkg/sql
- [ ]   5 pkg/ccl/partitionccl
- [ ]   5 pkg/ccl/multiregionccl
- [x]   4 pkg/ccl/testccl
- [ ]   4 pkg/sql/schemachanger
- [x]   4 pkg/bench
- [ ]   3 pkg/cli/democluster
- [ ]   2 pkg/ccl/workloadccl
- [ ]   2 pkg/ccl/importerccl
- [ ]   1 pkg/sql/ttl
- [ ]   1 pkg/sql/tests
- [ ]   1 pkg/sql/sqltestutils
- [ ]   1 pkg/sql/sqlinstance
- [x]   1 pkg/sql/copy
- [x]   1 pkg/sql/colenc
- [ ]   1 pkg/sql/catalog

**CDC**

- [ ]  10 pkg/ccl/changefeedccl
- [ ] 9 pkg/ccl/changefeedccl that are disabled via `feedTestNoTenants` option

**Serverless**

- [x]  11 pkg/ccl/sqlproxyccl

## Remaining tests that were hidden due to the CCL import (#108761)

**Disaster recovery / KV**

- [ ] 34 kv/bulk

**Disaster recovery**

- [ ] 61 jobs

**CDC**

- [x] 8  ccl/changefeedccl/cdceval
- [x] 7  ccl/changefeedccl/cdcevent
- [x] 3  kv/kvclient/rangefeed
- [x] 1  kv/kvclient/rangefeed/rangefeedcache

**KV**

- [ ] 81 kv/kvserver
- [ ] 27 kv/kvclient/kvcoord
- [ ] 22 kv
- [x] 8  util/rangedesc
- [x] 8  spanconfig/spanconfigkvsubscriber
- [x] 7  spanconfig/spanconfigkvaccessor
- [x] 3  kv/kvnemesis
- [x] 2  spanconfig/spanconfigmanager
- [x] 2  kv/kvserver/batcheval
- [x] 2  kv/kvserver/intentresolver
- [x] 1  spanconfig/spanconfigsqlwatcher
- [x] 1  kv/kvclient
- [x] 1  kv/kvserver/loqrecovery
- [x] 1  kv/kvserver/reports

**SQL Queries**

- [x] 9  kv/kvclient/kvstreamer
- [x] 8  ccl/multitenantccl/tenantcostserver
- [x] 7  sql/row
- [x] 3  sql/stmtdiagnostics
- [x] 3  sql/physicalplan
- [x] 2  sql/sqlliveness/slstorage
- [x] 2  sql/sqlinstance/instancestorage
- [x] 1  sql/stats
- [x] 1  sql/scheduledlogging
- [ ] 1  sql/rowexec
- [x] 1  sql/colflow
- [x] 1  sql/colexec/colbuilder

**SQL Foundations**

- [ ] 81 sql
- [x] 10 sql/catalog/descs
- [x] 9  sql/catalog/resolver
- [x] 4  workload/insights
- [x] 4  workload/bank
- [x] 2  sql/ttl/ttljob
- [ ] 2  sql/sem/builtins
- [x] 2  sql/catalog/lease
- [x] 1  sql/catalog/tabledesc
- [x] 1  sql/catalog/schematelemetry
- [ ] 1  sql/gcjob_test

**SQL (mixed)**

- [ ] 8  sql/logictest/tests/local-vec-off
- [ ] 8  sql/logictest/tests/local-legacy-schema-changer
- [ ] 7  sql/logictest/tests/fakedist
- [ ] 7  sql/logictest/tests/fakedist-disk
- [ ] 5  sql/logictest/tests/fakedist-vec-off
- [ ] 5  sql/logictest/tests/5node-disk
- [ ] 4  sql/logictest/tests/local-mixed-22.2-23.1
- [ ] 4  sql/logictest

**Multi-tenant**

- [x] 4  multitenant/tenantcapabilities/tenantcapabilitieswatcher
- [x] 2  server/settingswatcher
- [x] 2  server/tenantsettingswatcher
- [x] 1  server/systemconfigwatcher
- [x] 1  server/autoconfig

**Obs Infra**

- [ ] 24 server
- [x] 3  obsservice/obslib/ingest
- [x] 2  util/log/logcrash

**Clust Obs**

- [x] 10 server/application_api
- [x] 1  server/storage_api

**Misc**

- [ ] 40 upgrade/upgrades
- [x] 1  security

**Comment by ajwerner** [comment]
As far as I can tell, one source of problems with the randomized tenant testing is that we clobber/don't use the testing knobs provided to the server.

**Comment by ajstorm** [comment]
>As far as I can tell, one source of problems with the randomized tenant testing is that we clobber/don't use the testing knobs provided to the server.

Good catch @ajwerner.  Addressed with #86877.

**Comment by rafiss** [comment]
There are ~300 tests that use `tests.CreateTestServerParams()`, and it seems that this function always disables testing with tenants: https://github.com/cockroachdb/cockroach/blob/1137aee0089fc2fe161bab0f1c899d2ddc997c90/pkg/sql/tests/server_params.go#L26-L39

It seems like we are unintentionally missing a lot of test coverage.

**Comment by knz** [comment]
Next actions:

- [ ] review and merge #106768 
- [ ] list all tests still using TODODisableTestTenant
- [ ] divide that list and distribute for review across the team
- [ ] for each test using that value, pick one of the other values that more clearly identifies the situation. When relevant, identify which github issue is most related or create one.

**Comment by knz** [comment]
Next actions:

- [ ] review and merge #106768 
- [ ] list all tests still using TODODisableTestTenant
- [ ] divide that list and distribute for review across the team
- [ ] for each test using that value, pick one of the other values that more clearly identifies the situation. When relevant, identify which github issue is most related or create one.

cc @stevendanna @yuzefovich

**Comment by knz** [comment]
Areas that are suspicious:

- flow of conditionals at the beginning of `serverutils.StartServer()`
- conditional setting of `defaultTestTenant` in (*logictest.logicTest).newCluster()` (pkg/sql/logictest)
- conditional setting of repl mode in the same function
- conditional creation of tenant servers in same function
- cluster settings in same function
- creation of 'test' database in same function

**Comment by knz** [comment]
Here is the list of packages that still use `TODOTestTenantDisabled` after #106772:

```
  46 pkg/ccl/backupccl
  33 pkg/server
  30 pkg/ccl/serverccl
  18 pkg/sql/importer
  10 pkg/ccl/sqlproxyccl
   9 pkg/ccl/changefeedccl
   8 pkg/ccl/multitenantccl/tenantcostclient
   6 pkg/ccl/streamingccl/streamproducer
   6 pkg/ccl/streamingccl/streamingest
   5 pkg/sql
   5 pkg/ccl/spanconfigccl/spanconfigsqlwatcherccl
   5 pkg/ccl/partitionccl
   4 pkg/kv/kvserver
   4 pkg/kv/kvclient/kvtenant
   4 pkg/ccl/multiregionccl
   4 pkg/ccl/kvccl/kvfollowerreadsccl
   4 pkg/bench
   3 pkg/cli/democluster
   3 pkg/ccl/testccl/sqlccl
   2 pkg/sql/schemachanger/sctest
   2 pkg/spanconfig/spanconfigkvaccessor
   2 pkg/configprofiles
   2 pkg/ccl/workloadccl/allccl
   2 pkg/ccl/kvccl/kvtenantccl/upgradeccl
   2 pkg/ccl/jobsccl/jobsprotectedtsccl
   2 pkg/ccl/importerccl
   2 pkg/ccl/backupccl/backuptestutils
   2 pkg/base
   1 pkg/util/tracing/collector
   1 pkg/upgrade/upgrademanager
   1 pkg/ts
   1 pkg/sql/ttl/ttljob
   1 pkg/sql/tests
   1 pkg/sql/sqltestutils
   1 pkg/sql/sqlinstance/instancestorage
   1 pkg/sql/schemachanger/scdecomp
   1 pkg/sql/schemachanger/scbuild
   1 pkg/sql/copy
   1 pkg/sql/colenc
   1 pkg/sql/catalog/internal/catkv
   1 pkg/server/systemconfigwatcher/systemconfigwatchertest
   1 pkg/server/structlogging
   1 pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher
   1 pkg/kv/kvserver/gc
   1 pkg/kv/kvclient/rangefeed/rangefeedcache
   1 pkg/ccl/testutilsccl
   1 pkg/ccl/testccl/sqlstatsccl
   1 pkg/ccl/streamingccl/streamclient
   1 pkg/ccl/streamingccl/replicationtestutils
   1 pkg/ccl/sqlproxyccl/tenant
   1 pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl
   1 pkg/ccl/spanconfigccl/spanconfigsplitterccl
   1 pkg/ccl/spanconfigccl/spanconfigreconcilerccl
   1 pkg/ccl/spanconfigccl/spanconfigkvaccessorccl
   1 pkg/ccl/serverccl/statusccl
   1 pkg/ccl/serverccl/diagnosticsccl
   1 pkg/ccl/multitenantccl/tenantcapabilitiesccl
   1 pkg/ccl/multiregionccl/multiregionccltestutils
   1 pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl
   1 pkg/ccl/changefeedccl/schemafeed
   1 pkg/ccl/backupccl/backuprand
```

**Comment by knz** [comment]
Here's a more aggregated list, by top-level packages:
```
  49 pkg/ccl/backupccl
  33 pkg/server
  32 pkg/ccl/serverccl
  18 pkg/sql/importer
  14 pkg/ccl/streamingccl
  11 pkg/ccl/sqlproxyccl
  10 pkg/ccl/changefeedccl
   9 pkg/ccl/spanconfigccl
   9 pkg/ccl/multitenantccl
   7 pkg/ccl/kvccl
   5 pkg/sql
   5 pkg/kv/kvserver
   5 pkg/kv/kvclient
   5 pkg/ccl/partitionccl
   5 pkg/ccl/multiregionccl
   4 pkg/sql/schemachanger
   4 pkg/ccl/testccl
   4 pkg/bench
   3 pkg/cli/democluster
   2 pkg/spanconfig/spanconfigkvaccessor
   2 pkg/configprofiles
   2 pkg/ccl/workloadccl
   2 pkg/ccl/jobsccl
   2 pkg/ccl/importerccl
   2 pkg/base
   1 pkg/util/tracing
   1 pkg/upgrade/upgrademanager
   1 pkg/ts
   1 pkg/sql/ttl
   1 pkg/sql/tests
   1 pkg/sql/sqltestutils
   1 pkg/sql/sqlinstance
   1 pkg/sql/copy
   1 pkg/sql/colenc
   1 pkg/sql/catalog
   1 pkg/server/systemconfigwatcher
   1 pkg/server/structlogging
   1 pkg/multitenant/tenantcapabilities
   1 pkg/ccl/testutilsccl
```

**Comment by knz** [comment]
For further reference, here are the shell commands I've used:
```
git grep TODOTestTenantDisabled|cut -d: -f1|sed -e 's,/[^/]*$,,g'|sort|uniq -c|sort -rn

git grep TODOTestTenantDisabled|cut -d: -f1|sed -Ee 's,^(.*pkg/[^/]*(/[^/]*)?).*/[^/]*$,\1,g'|sort|uniq -c|sort -rn
```

**Comment by yuzefovich** [comment]
@knz FYI I updated the issue description to have the list of packages that still need attention and hid the comment.

**Comment by yuzefovich** [comment]
I still have a handful of commits in flight, but I've now repurposed this issue to be a meta issue about investigating the remaining packages / tests. The issue description has been updated to resemble the current state. This issue should not be referenced directly in the codebase anymore (shortly).
