### ISSUE TITLE
sql: audit all tests where `SET use_declarative_schema_changer = 'off'`

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#77150]
Recently, we disabled the declarative schema changer in a variety of tests, in the interest of turning on this new feature. This issue tracks re-enabling the declarative schema changer in tests.

In 22.1:
- [x] https://github.com/cockroachdb/cockroach/issues/78027
- [x] https://github.com/cockroachdb/cockroach/issues/78029
- [x] https://github.com/cockroachdb/cockroach/issues/78030

In 22.2 at some point:
- [x] https://github.com/cockroachdb/cockroach/issues/78028

Jira issue: CRDB-13435

Epic CRDB-18987
