### ISSUE TITLE
sql: meta issue for SQL Queries testing

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#77439]
This issue will serve as the meta-issue for our upcoming testing sprint. Please add ideas or links to other relevant issues.

- [ ] https://github.com/cockroachdb/cockroach/issues/73632
- [ ] https://github.com/cockroachdb/cockroach/issues/73920
- [ ] https://github.com/cockroachdb/cockroach/issues/73970
- [ ] https://github.com/cockroachdb/cockroach/issues/73971
- [ ] https://github.com/cockroachdb/cockroach/issues/73633
- [ ] https://github.com/cockroachdb/cockroach/issues/62901
- [ ] https://github.com/cockroachdb/cockroach/issues/77311
