### ISSUE TITLE
schemachanger: DROP DATABASE CASCADE on a db with 1000+ tables is slow

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#77601]
It has recently come to our attention that the declarative schema changer was exceedingly slow in these types of scenarios which, in my opinion, are not extreme.

We already have some PRs up to partly remedy this:
- [x] https://github.com/cockroachdb/cockroach/pull/77560
- [x] https://github.com/cockroachdb/cockroach/pull/77534

Outstanding work still remains:
- [x] We need to add a test case that exercises this scenario. Tracked by https://github.com/cockroachdb/cockroach/issues/73796
- [ ] @ajwerner noticed that the btree implementation which the schema change planner heavily relies on is inefficient and replacing it with something more suitable could cut planning time by a factor of ~5: https://github.com/cockroachdb/cockroach/issues/77603

Epic: CRDB-2356

Jira issue: CRDB-13689

**Comment by ajwerner** [comment]
I'm leaving this in the current release until we decide it is good enough for now.

**Comment by rafiss** [comment]
I can't figure out why exalate removed the release-blocker label, so just confirming that was intentional?

It might be because the Jira issue type was changed from task to bug?

**Comment by postamar** [comment]
No clue! That's rather concerning. I'll report this to dev-inf.

**Comment by postamar** [comment]
We're probably going to leave it at that in this release and won't replace the btree implementation, it turns out that the expected perf gains are less than originally anticipated.

**Comment by rafiss** [comment]
@postamar not sure if you saw, but we thought the slowness here was causing the test regressions in https://github.com/cockroachdb/cockroach/issues/78155, https://github.com/cockroachdb/cockroach/issues/77999, https://github.com/cockroachdb/cockroach/issues/78073.

Is your team able to confirm if those failures are related to this issue? If so, I think we still do need to do something here. 

Tests aside, it still seems quite likely that a user would run into this (especially if they test their app by spinning up/tearing down an environment),  and that to me feels like a regression, no?)

**Comment by ajwerner** [comment]
That's good intel. I'll look at those specifically. I have a branch that makes the regression far less severe. The btree is more or less irrelevant, but the algorithmic runtime matters. I'll take a deeper look at some of those.

**Comment by postamar** [comment]
I was not aware @rafiss , reopening.

**Comment by rafiss** [comment]
Sorry, that might have been a false alarm. https://github.com/cockroachdb/cockroach/issues/78073 and https://github.com/cockroachdb/cockroach/issues/78155 seem to have improved, so one of the other fixes that went in might have helped. 

https://github.com/cockroachdb/cockroach/issues/77999 is failing because of a memory accounting thing, not slowness.

So don't keep this issue open on my account -- i'm fine if you want to go with your earlier preference of stopping further work on this for now.

**Comment by postamar** [comment]
Thanks Rafi, still, I'll err on the side of prudence on this one and keep it open for a few more days before declaring victory on the performance front.

**Comment by rafiss** [comment]
Well, I might have jinxed it -- https://github.com/cockroachdb/cockroach/issues/78487 failed again due to a timeout when dropping objects.
