### ISSUE TITLE
security, sql: User IDs For Internal User Information

### ISSUE THREAD

**Issue by Fenil-P** [cockroachdb/cockroach#78963]
**Is your feature request related to a problem? Please describe.**
Currently, all internal per-user information is keyed by the username. This is not ideal because it makes it difficult to rename a user without breaking things. It's also not ideal because usernames can be considered personal data, but we need to use them in many places in logging.

**Describe the solution you'd like**

- [x] Add user_id columns in system tables with role, member or username columns.
- [x] Fix `RESTORE` from backups as `system.users` table is missing a column when trying to backup from a previous version.
- [ ] Update Authorization functions to use IDs when possible (they receive a user info struct containing both ID and username). The ID lookups will need to be version-gated.
- [ ] Update user privileges and their lookups based on IDs instead of usernames (also version gated).
- [x] A long-running migration to give existing users IDs (using a sequence of type OID silimar to postgres).
- [x] Re-enable membership cache which was disabled during changes to authorization functions.
- [x]  Fix systems sequences issue where options like min, start and max aren't being respected and the default settings are used.

**Additional context**
RFC: https://github.com/cockroachdb/cockroach/pull/77453

relates to https://github.com/cockroachdb/cockroach/issues/50821

Jira issue: CRDB-14465

Epic CRDB-14475

**Comment by rafiss** [comment]
@RichardJCai will create new issues to track the remaining work

**Comment by ajwerner** [comment]
Ref https://github.com/cockroachdb/cockroach/issues/87079
