### ISSUE TITLE
Active Executions - V2

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#79130]
Builds on: https://github.com/cockroachdb/cockroach/issues/66217 (live queries V1)

Figma: https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=6152%3A136586

Tasks:

- [x] [Surface missing live query stats](79124)
- [x] [surface blocked txns/query information via sql over http](https://github.com/cockroachdb/cockroach/issues/79127)
- [x] [ui changes to add blocking information](https://github.com/cockroachdb/cockroach/issues/79131)
- [x] [Surface EXPLAIN plan for active query details page](https://github.com/cockroachdb/cockroach/issues/79128)

Jira issue: CRDB-14589

**Comment by maryliag** [comment]
yes, that sounds good!
