### ISSUE TITLE
sql-queries: 22.2 release checklist

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#79610]
This issue captures a series of tests and steps that we need to run when 22.2 is getting close to being finalized.
 - [x] check bug fixes that may need backport
 - [x] check and update private opt tests repository
 - [x] check regressions in microbenchmarks
 - [x] run all tests with `TAGS=fast_int_set_small` and `TAGS=fast_int_set_large`
 - [x] consider adding session settings for all new features
 - [x] check TODOs in opt code (especially those added since the last release)
 - [x] clone an instance of this issue for the next release
 - [x] check the SQL Queries "Active", "Up Next", and "Release XX.X" buckets for issues that we'd really like to get into the release
 - [x] upgrade https://github.com/sqlancer/sqlancer to the latest version of CRDB
   - https://github.com/sqlancer/sqlancer/pull/587

Jira issue: CRDB-14942
