### ISSUE TITLE
release: new major version checklist, 22.1

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#80555]
GA-blockers:
- [x] 1. Update the license files in the license/ directory to reflect all the currently used licenses (master, release-22.1.0). https://github.com/cockroachdb/cockroach/pull/80612
	- Timing: this can be done before the branch cut. **This must be done before the last rc** (to be included in the .0)
- [x] 2. clusterversion: mint 22.1 cluster version (master, release-22.1.0). https://github.com/cockroachdb/cockroach/pull/80502
	- Timing: **This should be the FINAL GA-blocker that gets backported** (see "Minting" below)
	- [x] https://github.com/cockroachdb/cockroach/pull/80606 contains a fix needed for minting PR to pass tests

Fast-follows (not GA blockers):

- [x] 1. introduce 22.2 development versions. **Depends on GA-blocker 2** (on master). https://github.com/cockroachdb/cockroach/pull/80665
- [x] 2. roachtest: update version map and test fixtures for 22.2 (master only) https://github.com/cockroachdb/cockroach/pull/80753
- [x] 3. Configure roachtest block and ignore lists for 22.2 (master only) https://github.com/cockroachdb/cockroach/pull/80756
- [x] 4. Push v22.2.0-alpha.00000000 onto master. **Depends on Fast-follows 2 and 3 (on master) and GA-blocker 2 (on release-22.1.0)**. https://github.com/cockroachdb/cockroach/releases/tag/v22.2.0-alpha.00000000
- [x] 5. licenses: Update BSL change date for master/22.2 (on master). **Depends on GA-blocker 1** (on master). https://github.com/cockroachdb/cockroach/pull/81078

Fast-follows (v22.1.1 blockers, on release-22.1):

- [x] merge temporary "dot zero" branch into release-22.1 (ideally should be a no-op), (on release-22.1). **Depends on publishing v22.1.0, blocks selection of v22.1.1 candidate**. https://github.com/cockroachdb/cockroach/pull/81919

Slow-follows:
- [ ] bump binaryMinSupportedVersion to Start_22_1. Tracking issue: https://github.com/cockroachdb/cockroach/issues/80663

### Minting: what is it and when to do it?

- Minting a cluster version indicates the end of one release and the beginning of the next. 
- Minting closes the door on any future version gates or migrations being backported to 21.1; i.e. once we mint the version, we cannot add new migrations/version gates under it without requiring a wipe of any clusters that ran a build including the mint. Because of this, we should only merge this onto the 22.1 release branch once we’re sure we won’t need any more cluster versions. 
- In terms of timing, the release team plans for this to be the last commit backported onto 22.1 immediately before choosing the SHA for an rc.1.

Jira issue: CRDB-15344

**Comment by celiala** [comment]
All GA-blockers have cleared - removing labels

**Comment by celiala** [comment]
Pushing https://github.com/cockroachdb/cockroach/releases/tag/v22.2.0-alpha.00000000 onto master triggered bincheck (which we don't want to run for these special `-alpha.00000000` tags). PR to update bincheck rule: https://github.com/cockroachdb/cockroach/pull/81587

**Comment by rafiss** [comment]
@celiala i think pushing the tag caused the following failures:

heads up, i think this PR caused the following failures:

 https://github.com/cockroachdb/cockroach/issues/81626
 https://github.com/cockroachdb/cockroach/issues/81625
 https://github.com/cockroachdb/cockroach/issues/81624
 https://github.com/cockroachdb/cockroach/issues/81623
 https://github.com/cockroachdb/cockroach/issues/81623
 https://github.com/cockroachdb/cockroach/issues/81622
 https://github.com/cockroachdb/cockroach/issues/81621
 https://github.com/cockroachdb/cockroach/issues/81620
 https://github.com/cockroachdb/cockroach/issues/81619
 https://github.com/cockroachdb/cockroach/issues/81617
 https://github.com/cockroachdb/cockroach/issues/81616
 https://github.com/cockroachdb/cockroach/issues/81615
 https://github.com/cockroachdb/cockroach/issues/81613
 https://github.com/cockroachdb/cockroach/issues/81612
 https://github.com/cockroachdb/cockroach/issues/81611
 https://github.com/cockroachdb/cockroach/issues/81608
 https://github.com/cockroachdb/cockroach/issues/81607

Perhaps the checklist should be updated so the change in https://github.com/cockroachdb/cockroach/pull/80756 happens before pushing the tag

**Comment by celiala** [comment]
Ah, sorry for the mess of test failures!

> Perhaps the checklist should be updated so the change in https://github.com/cockroachdb/cockroach/pull/80756 happens before pushing the tag

Fixed above - thank you!
