### ISSUE TITLE
storage: manual compaction improvements meta issue

### ISSUE THREAD

**Issue by bananabrick** [cockroachdb/cockroach#81585]
Creating this issue to track pending improvements to both offline and online manual compactions.

Recently, we've had some cool speed improvements to offline manual compactions which were achieved through improved concurrency, and better algorithms. Some of these improvements are discussed here: https://github.com/cockroachdb/pebble/issues/1533

Offline manual compactions require taking a node down, and https://github.com/cockroachdb/pebble/issues/1533#issuecomment-1091003279 describes the motivation to perform these forced compactions online.

Currently, we have a method to perform online manual compactions by writing a sql command: https://github.com/cockroachdb/cockroach/blob/cf7c8aaeb3156cac4fe9e31b490a0734416a2bca/pkg/sql/sem/builtins/builtins.go#L6128-L6163. However, these compactions can be problematic as they schedule one large compaction out of L0. This large compaction can conflict with ongoing automatic compactions, and delay the manual compaction.

https://github.com/cockroachdb/pebble/issues/1533#issuecomment-1091003279, also describes a method to perform online manual compactions out of L0 using the existing L0 compaction mechanisms. 

**Todos in no particular order:**
- [x] allow compaction concurrency to be modified using a sql command to prevent node restarts.

- [x] Prototype concurrent online manual compactions out of L0(issue pending).

- [x] Benchmark concurrent online manual compactions out of L0(issue pending).

- [x] Briefly talk to sre/support teams to determine the UX for these compactions

- [ ] https://github.com/cockroachdb/pebble/issues/1644. It's important to create benchmarks for the current offline manual compactions so that we can make informed decisions during various on-call scenarios. These benchmarks will also tell us whether we actually need to have concurrent compactions out of L0. It might be okay to have one large online manual compaction out of L0 if we can prevent it from conflicting with automatic compactions.

- [ ] https://github.com/cockroachdb/pebble/issues/1622. It's useful to restrict the depth of manual compactions. Often, we only want to clear out L0.

Jira issue: CRDB-15088

Epic CRDB-13159

**Comment by bananabrick** [comment]
> I'd love to review the proposed UX.

I was being lazy. Describing the current plan for online manual compaction UX:

It would be similar to this: https://github.com/cockroachdb/cockroach/commit/40029d161a803b0ee7d105ec737c0a205571a0b9. A sql command which will cause Pebble to try and clear out the LSM. Issuing it when the node is online does imply that the lsm level may not be empty at the end of the online manual compaction. The goal of the online manual compaction would be to clear out the number of bytes in, say, L0 at the time when the online manual compaction was issued. 

So, if L0 has 200GB, and we issue an online manual compaction, but we write an additional 100GB to L0 while the online manual compaction is happening, then there will be 100GB left in L0 at the end of the compaction.

> Mitigations like offline compaction take many hours to take effect. 

Hopefully, this is going to be faster now onwards.

> As a result of ^^, I think the absolute most important thing with online compaction is to enable operators, TSEs, & devs to test theories of the outage at a much faster speed. We should be able to compact some piece of the key-space, see a change in LSM structure / metric, & see it regress post online compaction finishing assuming the combination of workload + bug (e.g. a gap in AC) that caused the inversion is still present. If we can iterate fast, we will resolve these outages quicker.

Online manual compactions will perform smaller, and more compactions out of L0, which will allow us to see the change in the lsm shape and metrics even when the manual compactions are on going. Although, I'm not sure if that would tell us whether the mitigation is working or not.

--

Note that online manual compactions don't guarantee that the lsm will become healthy. I see an online manual compaction as a way to prioritize compactions out of L0, without taking the node down. If a workload is hitting a store hard, and we can't compact fast enough out of L0, even with online manual compactions, then the lsm will stay unhealthy.

**Comment by joshimhoff** [comment]
> It would be similar to this: https://github.com/cockroachdb/cockroach/commit/40029d161a803b0ee7d105ec737c0a205571a0b9.

I'll review later! Thanks for link.

> Although, I'm not sure if that would tell us whether the mitigation is working or not.
>
> Note that online manual compactions don't guarantee that the lsm will become healthy. I see an online manual compaction as a way to prioritize compactions out of L0, without taking the node down. If a workload is hitting a store hard, and we can't compact fast enough out of L0, even with online manual compactions, then the lsm will stay unhealthy.

Ya makes sense. So long as it takes us less time to realize we still have a problem, I think we'll observe a surprising reduction in time to fix.

**Comment by bananabrick** [comment]
> I'll review later! Thanks for link.

That's an old PR with the current online manual compaction steps.

**Comment by joshimhoff** [comment]
Would it benefit us to have some SQL commands that allow **understanding** the state of the LSM? I can imagine getting paged for LSM inversion & then running a SQL command that determines what slices of the keyspace (including MVCC timestamps) are "disproportionally present" in L0, leading to significant read application. I can imagine that being useful in of itself, for example if a particular backfill job targeting a specific slice of the keyspace is the problem workload. I'm not sure how useful tho, but I have felt that in past incidents we didn't get to an understanding of why the LSM inverted quickly enough, and we need that understanding to actually fix the cluster in a way that avoids reoccurrence.

**Comment by mwang1026** [comment]
> but I have felt that in past incidents we didn't get to an understanding of why the LSM inverted quickly enough, and we need that understanding to actually "fix" the cluster in a way that avoids reoccurrence

My ask is that we keep that discussion to a different ticket, if that's ok josh

**Comment by mwang1026** [comment]
Separately, I think we should provide actual mock syntax here for folks to review if possible @bananabrick so that we can bikeshed that as you're working on the guts of the functionality. I'm happy to figure out time to just mock that out -- just let me know.

**Comment by joshimhoff** [comment]
Sure, I can do that. I'll first try to understand the tools we have such as `cockroach debug pebble`.

**Comment by joshimhoff** [comment]
Discussion re: understanding cause of LSM inversion added to https://github.com/cockroachdb/cockroach/issues/79101.

**Comment by ricardocrdb** [comment]
Apologies for the delayed response, COVID decided to roll up 😢 

In regards to UX asks, a progress bar (percentage based) with an estimated time of completion would be ideal, something akin to a `wget` progress bar. This should be applicable whether performing an offline compaction or initiating an online compaction. A user is usually performing a manual compaction in the event that the LSM is already inverted as a mitigation factor, and to reiterate what @joshimhoff had mentioned, its usually an unknown amount of time that the cluster is impacted. Having the time until completion, even if a rough estimate, would ultimately help assuage any immediate customer concerns. I understand the implications may be more difficult, as its hard to determine overlapping keys, etc. and so may be more difficult to implement, but the ideal scenario would be to have an idea of progress.

An additional improvement would be to target specific parts of the entire keyspace, and initiate a manual compaction only where files that have that particular set of data would be marked for immediate compaction. In recent memory, a lot of inverted LSM issues have revolved around either a specific schema change with a backfill impacting a single table/index, or workload impacting a particular table. Given that we know that most keys in the keyspace for a table start with something like `/Table/N/1`, we should be able to apply a particular tool that targets that keyspace for manual compaction. Something like `cockroach debug compact cockroach-data --targeted-compaction=/Table/N/1`

Let me know if further clarification is required. Appreciate the oppurtunity to chime in on this thread.

**Comment by mwang1026** [comment]
re: Status, is say a countdown of # compactions remaining or number of SSTs remaining to compact useful? I'm wary of time based signals and their accuracy -- yes people ask for it but then they complain it's not accurate. The # of X remaining is factual, and we could use metrics / benchmarking to get a sense of how that might translate (but parallelization, CPU, disk thruput, all might impact time -- and if you have time elapsed and "compactions complete and/or sst's compacted" you could back into the rate)

re: targeting a keyspace, is that more valuable than just saying "compact files currently in L0"? Said another way, would you want to compact it from all levels all the way down to L6? Or are you just trying to get the inversion out of the way?

**Comment by bananabrick** [comment]
> Separately, I think we should provide actual mock syntax here for folks to review if possible

I was going to re-use the current, `SELECT crdb_internal.compact_engine`, or have something similar.

> In regards to UX asks, a progress bar (percentage based) with an estimated time of completion would be ideal, something akin to a wget progress bar. This should be applicable whether performing an offline compaction or initiating an online compaction.

A progress bar will be difficult. I think focussing on benchmarking so we have some rough numbers for some scenarios(https://github.com/cockroachdb/pebble/issues/1644) will help with estimated time.

For the current offline compaction, and the planned online compaction, there should be a way to tell progress using the lsm metrics. Previously, we weren't able to figure out how the one large L0 offline compaction was progressing. But I realized that looking at the "in progress bytes", in the lsm metrics, gives a rough estimate of the progress of an L0 offline manual compaction.

For concurrent compactions during an offline manual compaciton out of levels other than L0, level size in the lsm metrics is a good indicator of progress.


>  In recent memory, a lot of inverted LSM issues have revolved around either a specific schema change with a backfill impacting a single table/index, or workload impacting a particular table. Given that we know that most keys in the keyspace for a table start with something like /Table/N/1, we should be able to apply a particular tool that targets that keyspace for manual compaction. Something like cockroach debug compact cockroach-data --targeted-compaction=/Table/N/1

It's a good point, but it's more complicated and gives me less freedom while implementing this. Given that, I'm wondering if it's worthwhile to target a keyspace. Don't we just want to clear the majority L0 ASAP?

**Comment by mwang1026** [comment]
>  I was going to re-use the current, SELECT crdb_internal.compact_engine, or have something similar.

We can bike shed this some more maybe. But I think it'd be user friendly to have the syntax match what the thing is doing and have it be "descriptive" of what's going to happen. It also matters if say we want to eventually extend it to be more descriptive / functional in choosing say how or what you want to compact. So if say, iteration one is there is one type of manual compaction, and it compacts away current files in L0, then the syntax should make reference to that, IMO

**Comment by joshimhoff** [comment]
> It's a good point, but it's more complicated and gives me less freedom while implementing this. Given that, I'm wondering if it's worthwhile to target a keyspace. Don't we just want to clear the majority L0 ASAP?

I initially thought this would be useful, but the more I learn about pebble, I'm not sure it actually is?

IMO, it's very important to *know what keys are in L0*, as this provides clues on what workload caused the LSM inversion (given AC gaps, etc.). It's important to know that, since the workload must be stopped, or the issue will reoccur. But this is an observability need which is independent from the idea of compacting a specific key span.

Does the amount of read amp depend on where in the keyspace a read is happening? Or do all reads regardless of what keys they target experience roughly the same read amp, e.g. since all reads need to query all L0 sublevels?

If the former, I guess I see why a targeted compaction might be useful. It reduces time to fix assuming the big problem is that reads to a very specific key span are slow.

OTOH, if the latter, I see no benefit to a targeted compaction. The key thing is to reduce the number of L0 sublevels as fast as possible.

**Comment by mwang1026** [comment]
> It's important to know that, since the workload must be stopped, or the issue will reoccur.

I agree, but my point above is that this is a separate topic and I'd rather not distract from the "mitigation" part of the equation and prefer a separate tracking issue for the "prevention" or "o11y" portion of it the issue. Mind creating one?

**Comment by joshimhoff** [comment]
Hey, @mwang1026, I agree with that. I was giving input on the Q of whether we need to target specific slices of the key span, not making the point again.

Re: new ticket, I think this one already covers it, and I've posted some thoughts there: https://github.com/cockroachdb/cockroach/issues/79101

**Comment by mwang1026** [comment]
sg thanks. broken record sorry :)

**Comment by mwang1026** [comment]
>  rough estimation could then be calculated based on that historical info, which should be pretty accurate.

I think the point is that from past experience it's not, especially if you're doing something under duress (which you are for a manual compaction). And my point is that I feel like a progress bar should be a goal eventually, but would cause more confusion than benefit in the current scope.

> was under the impression that it would be easier to just extract all SSTs

Let's just do what simpler, because I think it'll have value regardless. re: single table schema results in high file count, we should solve that one at the source, IMO

**Comment by bananabrick** [comment]
> We can bike shed this some more maybe. But I think it'd be user friendly to have the syntax match what the thing is doing and have it be "descriptive" of what's going to happen

Sure. I'll think up something and post here.

> Here's a Q about pebble: Does the amount of read amp depend on where in the keyspace a read is happening? Or do all reads regardless of what keys they target experience roughly the same read amp, e.g. since all reads need to query all L0 sublevels?
If a key has no overlap in a level, then the level can be skipped.

If we're compacting a keyspace, then we have to pick a keyspace to compact. Let's say a workload is inverting the lsm and we determine a given key range which is being written into L0. If the majority of keys written into L0 belong to the key range we picked, then we might as well compact the entire lsm. Since, it's also much simpler to not pick a key range for compactions out of L0, I'd rather stick to that for now.

> Additionally, in further consideration, even in the event a single table schema change backfill results in high L0 file count, that would assume the vast majority of files in L0 are most likely associated with said table anywho.

Yea, this is why I think it's better to compact the entire L0.

> Re: progress bar, we log the time taken for various compactions from various levels in the Pebble log. Would it not be conducive then to track this info as historical timeseries data, which can then be used as a sort of barometer for the particular node performing the compactions? A rough estimation could then be calculated based on that historical info, which should be pretty accurate. I understand this could add significant complexity to the compactions, but I am just speaking from an ideal perspective :)

The compaction picking mechanism is heuristic based. It's difficult to assume how many compactions will be picked/how large those compactions will be.

**Comment by nicktrav** [comment]
@bananabrick - we can probably close this one out now, yeah? The two remaining issues are being tracked separately.
