### ISSUE TITLE
asim: allocation simulator

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#82627]
This is a tracking issue for the allocation simulator.

## Why do we need a simulator?
> There is an agreement that unit tests and roachtests are useful but not enough to verify allocation changes, and that a fast (not using real time) and repeatable simulation can be useful to reproduce rare bugs in the allocator. In addition to verifying correctness, optimizing the allocation and rebalancing algorithm is an area that is costly to verify and necessitates slow feedback loops (see [QPS Accounting - Experiments internal](https://docs.google.com/document/d/1fAzcpoqWvLFSHM7OvsLb1xj2pwUewKMGL9ROD1RWbm8/edit#)); this may be addressed by a deterministic simulator.

[design doc internal](https://docs.google.com/document/d/1FEEktM7dfYlfLCIuj2D4kjXIOT4OjLfZxipo5oczXkc/edit#heading=h.ruyplo376p8u)

## Tracking

- [x] set up skeleton https://github.com/cockroachdb/cockroach/pull/78272
- [x] random load generator https://github.com/cockroachdb/cockroach/pull/79773
- [x] static config loader https://github.com/cockroachdb/cockroach/pull/79961
- [x] apply workload to state https://github.com/cockroachdb/cockroach/pull/80127
  - [x] load adapter https://github.com/cockroachdb/cockroach/pull/81004
- [x] simulate store scanner https://github.com/cockroachdb/cockroach/pull/81770
- [x] simulate gossip https://github.com/cockroachdb/cockroach/pull/81710
- [x] simulate state changes https://github.com/cockroachdb/cockroach/pull/82089
- [x] simulate replicate queue consider rebalance https://github.com/cockroachdb/cockroach/pull/82089
- [x] generate a score, cost and statistics of a simulation run https://github.com/cockroachdb/cockroach/issues/82628
- [x] simulate load based splitting https://github.com/cockroachdb/cockroach/issues/82630
- [x] simulate size based splitting https://github.com/cockroachdb/cockroach/issues/82660
- [x] simulate store rebalancer https://github.com/cockroachdb/cockroach/issues/82631
- [x] validate the simulator against the a crdb cluster with equivalent configuration 
  - [x] validate range count rebalancing https://github.com/cockroachdb/cockroach/issues/83989
  - [x] validate rebalancing https://github.com/cockroachdb/cockroach/issues/83990

Jira issue: CRDB-16618
