### ISSUE TITLE
logictest: create a new test directive to assert the creation of structured logging events

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#84991]
Currently several unit tests assert that structured events get created by reading from `system.eventlog`. However, we are going to remove this feature altogether. (#84983)

So we will want to rewrite the tests to assert the creation of a structured event on a logging channel.

For this, we should use a common mechanism in the logic test runner, probably a new directive. (Maybe the same kind that was used in the pgwire authentication tests already?).

Issues that would benefit from this new feature:
- [ ] multiregion: properly assert the emission of structured logging events in tests #84984
- [ ] sql: properly assert the emission of structured logging events in create stats test #84985 
- [ ] sql: properly assert the emission of structured logging events in event log SQL tests #84986
- [ ] opt/execbuilder: use a different table than system.eventlog for the trace test #84989 
- [ ] sql: properly assert the emission of structured logging events in the SQL schema tests #84990 

Jira issue: CRDB-17991

**Comment by rafiss** [comment]
I think Obs-inf are best suited to think about using structured logging channels in tests.

**Comment by knz** [comment]
We've done this differently: #86174

in logic tests there's a new directive `# knob-opt: sync-event-log`
