### ISSUE TITLE
server: sql server cold start [meta issue]

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#85612]
**Is your feature request related to a problem? Please describe.**
This issue is a placeholder to track issues related to WAN round-trips required during the SQL server startup protocol. The goal is to get the number of WAN RPCs to zero. This issue will track work items required to reach that goal. 

* [x] https://github.com/cockroachdb/cockroach/issues/85736 partition `sqlliveness` table for more efficient cold-start
* [x] https://github.com/cockroachdb/cockroach/issues/85737 optimize `sql_instances`
* [x] https://github.com/cockroachdb/cockroach/issues/85738 optimize reading of cluster settings
* [x] https://github.com/cockroachdb/cockroach/issues/85740 ensure `Connector` methods don't leave the local region
* [x] https://github.com/cockroachdb/cockroach/issues/85741 optimize descriptor leasing protocol
	* Note that this ends up also containing the work to make user metadata and role membership access local
* [x] https://github.com/cockroachdb/cockroach/issues/76305 improve the speed of startup migrations
	* The issue above is strangely named, but is related to the speed of startup migrations when creating and first activating a tenant.  Note that this isn't directly related to cold start latency, but is related to the first start after tenant creation, which is also important to optimize.

Jira issue: CRDB-18341

Epic: CRDB-18596

**Comment by ajwerner** [comment]
This will rely to a great extent on doing something about https://github.com/cockroachdb/cockroach/issues/63365.
