### ISSUE TITLE
storage: review 22.2 microbenchmark regressions

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#88723]
See #87685.

The following are benchmarks showing regressions of greater than 5% ([source data](https://docs.google.com/spreadsheets/d/1XW2e2AambrbTIv4Otg6bMHLlISizPk5L7LQNZslo5OE/edit?pli=1#gid=5)):

- [x] `CheckSSTConflicts` #88702
- [x] `EncodeMVCCKey` https://github.com/cockroachdb/cockroach/issues/88818
- [x] `IntentInterleavingIterPrev` resolved, see https://github.com/cockroachdb/cockroach/issues/88723#issuecomment-1265927709
- [x] `IntentInterleavingSeekGEAndIter` resolved, see https://github.com/cockroachdb/cockroach/issues/88723#issuecomment-1265945247
- [x] `IntentRangeResolution` #89153
- [x] `IntentResolution` #89153
- [x] `IntentScan` #89153
- [x] `MVCCBatchPut_Pebble` #88819
- [x] `MVCCBlindConditionalPut_Pebble` #90360
- [x] `MVCCBlindInitPut_Pebble` #90360
- [x] `MVCCBlindPut_Pebble` #90360
- [x] `MVCCFindSplitKey_Pebble` #89171
- [x] `MVCCKeyCompare` https://github.com/cockroachdb/cockroach/issues/89006
- [x] `MVCCPutDelete_Pebble` https://github.com/cockroachdb/cockroach/issues/89253
- [x] `MVCCScanTransactionalData` in line with `MVCCScan` regression
- [x] `ScanAllIntentsResolved`
- [x] `ScanOneAllIntentsResolved`
- [x] `UpdateSSTTimestamps` inconsequential, see https://github.com/cockroachdb/cockroach/issues/88723#issuecomment-1265298655

NB: used the following to generate the above list `cat $FILE | cut -d '/' -f1 | sort | uniq`.

Jira issue: CRDB-19852

Epic CRDB-2624

**Comment by jbowens** [comment]
**BenchmarkIntentScan/versions=400/percent-flushed=0**

Diffing release-22.1 and release-22.2 cpu profiles:
```
      flat  flat%   sum%        cum   cum%
   114.07s  8.46%  8.46%    111.52s  8.27%  github.com/cockroachdb/pebble/internal/arenaskl.(*Iterator).decodeKey (inline)
    12.79s  0.95%  9.40%     26.29s  1.95%  github.com/cockroachdb/cockroach/pkg/storage.EngineKeyEqual
     8.29s  0.61% 10.02%     14.85s  1.10%  github.com/cockroachdb/pebble/internal/arenaskl.(*Skiplist).findSpliceForLevel
     6.22s  0.46% 10.48%    105.48s  7.82%  github.com/cockroachdb/pebble.(*Iterator).nextUserKey
    -4.57s  0.34% 10.14%     89.02s  6.60%  github.com/cockroachdb/pebble.(*mergingIter).nextEntry
    
         .          .    235:func (it *Iterator) decodeKey() {
    52.12s     49.57s    236:	b := it.list.arena.getBytes(it.nd.keyOffset, it.nd.keySize)
         .          .    237:	// This is a manual inline of base.DecodeInternalKey, because the Go compiler
         .          .    238:	// seems to refuse to automatically inline it currently.
    -230ms     -230ms    239:	l := len(b) - 8
    -110ms     -110ms    240:	if l >= 0 {
    62.11s     62.11s    241:		it.key.Trailer = binary.LittleEndian.Uint64(b[l:])
     180ms      180ms    242:		it.key.UserKey = b[:l:l]
         .          .    243:	} else {
         .          .    244:		it.key.Trailer = uint64(base.InternalKeyKindInvalid)
         .          .    245:		it.key.UserKey = nil
         .          .    246:	}
         .          .    247:}
```
I've seen similar cpu profile deltas with slowdowns in `internal/arenaskl` in other regressed benchmarks. I think there must be:
a) more keys in the memtable
b) or, we're iterating over the memtable skiplist more frequently (eg, through lost TrySeekUsingNext optimizations or the like)

**Comment by erikgrinaker** [comment]
I'm seeing the same arenaskl-related regression in `BenchmarkIntentRangeResolution` when comparing `release-22.1` with `master`. For example, `BenchmarkIntentRangeResolution/versions=400/sparseness=100/other-txn-intents=false/percent-flushed=0` had a 35% regression. I expect that most of the intent resolution regressions have the same root cause.

Opened #89153 for this and marked it as a release blocker, since the regressions are as much as 50%.

**Comment by erikgrinaker** [comment]
`UpdateSSTTimestamps`

The regression here only affects the slow path (unused by default), which uses a naïve read/write loop. This only appears to affect small SSTs, likely due to increased iterator setup costs (in particular, the additional range key seek). This is inconsequential.

```
UpdateSSTTimestamps/numKeys=1/concurrency=0-24         84.9µs ± 2%   131.5µs ± 1%  +54.91%  (p=0.008 n=5+5)
UpdateSSTTimestamps/numKeys=1/concurrency=1-24          287µs ± 1%     291µs ± 2%     ~     (p=0.421 n=5+5)
UpdateSSTTimestamps/numKeys=1/concurrency=2-24          265µs ± 3%     274µs ± 1%   +3.34%  (p=0.008 n=5+5)
UpdateSSTTimestamps/numKeys=1/concurrency=4-24          305µs ± 1%     313µs ± 1%   +2.69%  (p=0.008 n=5+5)
UpdateSSTTimestamps/numKeys=1/concurrency=8-24          322µs ± 2%     327µs ± 2%     ~     (p=0.095 n=5+5)
UpdateSSTTimestamps/numKeys=10/concurrency=0-24        86.5µs ± 1%   138.0µs ± 2%  +59.52%  (p=0.008 n=5+5)
UpdateSSTTimestamps/numKeys=10/concurrency=1-24         292µs ± 1%     295µs ± 1%     ~     (p=0.095 n=5+5)
UpdateSSTTimestamps/numKeys=10/concurrency=2-24         270µs ± 1%     267µs ± 2%     ~     (p=0.222 n=5+5)
UpdateSSTTimestamps/numKeys=10/concurrency=4-24         318µs ± 1%     319µs ± 1%     ~     (p=0.421 n=5+5)
UpdateSSTTimestamps/numKeys=10/concurrency=8-24         334µs ± 1%     337µs ± 2%     ~     (p=0.421 n=5+5)
UpdateSSTTimestamps/numKeys=100/concurrency=0-24        128µs ± 1%     174µs ± 4%  +35.92%  (p=0.008 n=5+5)
UpdateSSTTimestamps/numKeys=100/concurrency=1-24        373µs ± 0%     378µs ± 1%   +1.22%  (p=0.008 n=5+5)
UpdateSSTTimestamps/numKeys=100/concurrency=2-24        371µs ± 1%     372µs ± 2%     ~     (p=0.548 n=5+5)
UpdateSSTTimestamps/numKeys=100/concurrency=4-24        383µs ± 1%     383µs ± 1%     ~     (p=0.690 n=5+5)
UpdateSSTTimestamps/numKeys=100/concurrency=8-24        391µs ± 1%     392µs ± 1%     ~     (p=0.690 n=5+5)
UpdateSSTTimestamps/numKeys=1000/concurrency=0-24       469µs ± 0%     467µs ± 1%     ~     (p=0.222 n=5+5)
UpdateSSTTimestamps/numKeys=1000/concurrency=1-24      1.01ms ± 1%    1.01ms ± 2%     ~     (p=0.690 n=5+5)
UpdateSSTTimestamps/numKeys=1000/concurrency=2-24      1.16ms ± 1%    1.14ms ± 2%   -2.35%  (p=0.008 n=5+5)
UpdateSSTTimestamps/numKeys=1000/concurrency=4-24       875µs ± 2%     868µs ± 2%     ~     (p=0.548 n=5+5)
UpdateSSTTimestamps/numKeys=1000/concurrency=8-24       875µs ± 1%     877µs ± 1%     ~     (p=1.000 n=5+5)
UpdateSSTTimestamps/numKeys=10000/concurrency=0-24     3.50ms ± 2%    3.38ms ± 0%   -3.22%  (p=0.008 n=5+5)
UpdateSSTTimestamps/numKeys=10000/concurrency=1-24     2.37ms ± 1%    2.37ms ± 3%     ~     (p=0.841 n=5+5)
UpdateSSTTimestamps/numKeys=10000/concurrency=2-24     2.43ms ± 2%    2.41ms ± 1%     ~     (p=0.151 n=5+5)
UpdateSSTTimestamps/numKeys=10000/concurrency=4-24     2.32ms ± 2%    2.30ms ± 1%     ~     (p=0.690 n=5+5)
UpdateSSTTimestamps/numKeys=10000/concurrency=8-24     2.42ms ± 1%    2.45ms ± 1%     ~     (p=0.056 n=5+5)
UpdateSSTTimestamps/numKeys=100000/concurrency=0-24    33.3ms ± 0%    32.6ms ± 1%   -2.12%  (p=0.008 n=5+5)
UpdateSSTTimestamps/numKeys=100000/concurrency=1-24    15.9ms ± 1%    15.9ms ± 1%     ~     (p=1.000 n=5+5)
UpdateSSTTimestamps/numKeys=100000/concurrency=2-24    10.3ms ± 2%    10.1ms ± 3%     ~     (p=0.151 n=5+5)
UpdateSSTTimestamps/numKeys=100000/concurrency=4-24    7.11ms ± 3%    7.23ms ± 3%     ~     (p=0.151 n=5+5)
UpdateSSTTimestamps/numKeys=100000/concurrency=8-24    6.00ms ± 5%    5.86ms ± 5%     ~     (p=0.548 n=5+5)
```

**Comment by erikgrinaker** [comment]
`MVCCScanTransactionalData`

Ran another set of benchmarks. The results are in line with the overall, known `MVCCScan` regression seen in #82559, so this is expected.

```
name                                 old time/op    new time/op    delta
MVCCScanTransactionalData_Pebble-24    3.18ms ± 2%    3.36ms ± 1%  +5.80%  (p=0.000 n=10+10)
```

**Comment by erikgrinaker** [comment]
`IntentInterleavingIterPrev`

This appears to have been resolved on `master`, which has significantly better performance than `release-22.1`:

```
name                                                                                     old time/op  new time/op  delta
IntentInterleavingIterPrev/separated=false/version=1/intentStride=1/keyLen=10-24         95.5ns ± 7%  85.7ns ± 1%  -10.25%  (p=0.001 n=10+5)
IntentInterleavingIterPrev/separated=false/version=1/intentStride=1/keyLen=100-24         106ns ± 3%    94ns ± 1%  -11.73%  (p=0.001 n=10+5)
IntentInterleavingIterPrev/separated=false/version=1/intentStride=100/keyLen=10-24       94.7ns ± 3%  89.3ns ± 1%   -5.68%  (p=0.001 n=10+5)
IntentInterleavingIterPrev/separated=false/version=1/intentStride=100/keyLen=100-24       110ns ± 6%   102ns ± 2%   -6.82%  (p=0.001 n=10+5)
IntentInterleavingIterPrev/separated=false/version=1/intentStride=1000000/keyLen=10-24   94.4ns ± 3%  88.9ns ± 1%   -5.80%  (p=0.001 n=10+5)
IntentInterleavingIterPrev/separated=false/version=1/intentStride=1000000/keyLen=100-24   107ns ± 2%   101ns ± 1%   -6.05%  (p=0.001 n=9+5)
IntentInterleavingIterPrev/separated=false/version=5/intentStride=1/keyLen=10-24         97.6ns ± 3%  94.3ns ± 3%   -3.40%  (p=0.013 n=10+5)
IntentInterleavingIterPrev/separated=false/version=5/intentStride=1/keyLen=100-24         116ns ± 2%   106ns ± 2%   -8.29%  (p=0.000 n=10+5)
IntentInterleavingIterPrev/separated=false/version=5/intentStride=100/keyLen=10-24       99.2ns ± 2%  92.9ns ± 2%   -6.32%  (p=0.001 n=9+5)
IntentInterleavingIterPrev/separated=false/version=5/intentStride=100/keyLen=100-24       117ns ± 2%   109ns ± 2%   -6.88%  (p=0.002 n=8+5)
IntentInterleavingIterPrev/separated=false/version=5/intentStride=1000000/keyLen=10-24   97.1ns ± 1%  94.2ns ± 3%   -2.92%  (p=0.001 n=9+5)
IntentInterleavingIterPrev/separated=false/version=5/intentStride=1000000/keyLen=100-24   116ns ± 2%   107ns ± 3%   -7.04%  (p=0.001 n=9+5)
IntentInterleavingIterPrev/separated=true/version=1/intentStride=1/keyLen=10-24           162ns ± 1%   163ns ± 4%     ~     (p=1.000 n=10+5)
IntentInterleavingIterPrev/separated=true/version=1/intentStride=1/keyLen=100-24          191ns ± 2%   186ns ± 2%   -2.38%  (p=0.011 n=10+5)
IntentInterleavingIterPrev/separated=true/version=1/intentStride=100/keyLen=10-24         172ns ± 2%   172ns ± 1%     ~     (p=0.882 n=10+5)
IntentInterleavingIterPrev/separated=true/version=1/intentStride=100/keyLen=100-24        201ns ± 2%   192ns ± 1%   -4.51%  (p=0.001 n=10+5)
IntentInterleavingIterPrev/separated=true/version=1/intentStride=1000000/keyLen=10-24     174ns ± 3%   170ns ± 1%   -2.27%  (p=0.008 n=10+5)
IntentInterleavingIterPrev/separated=true/version=1/intentStride=1000000/keyLen=100-24    197ns ± 2%   190ns ± 1%   -3.79%  (p=0.001 n=10+5)
IntentInterleavingIterPrev/separated=true/version=5/intentStride=1/keyLen=10-24           144ns ± 1%   145ns ± 2%     ~     (p=0.771 n=9+5)
IntentInterleavingIterPrev/separated=true/version=5/intentStride=1/keyLen=100-24          207ns ± 3%   203ns ± 1%   -1.96%  (p=0.012 n=9+5)
IntentInterleavingIterPrev/separated=true/version=5/intentStride=100/keyLen=10-24         175ns ± 1%   174ns ± 1%     ~     (p=0.539 n=9+5)
IntentInterleavingIterPrev/separated=true/version=5/intentStride=100/keyLen=100-24        204ns ± 1%   200ns ± 2%   -2.26%  (p=0.002 n=8+5)
IntentInterleavingIterPrev/separated=true/version=5/intentStride=1000000/keyLen=10-24     176ns ± 2%   174ns ± 1%     ~     (p=0.416 n=10+5)
IntentInterleavingIterPrev/separated=true/version=5/intentStride=1000000/keyLen=100-24    205ns ± 2%   201ns ± 2%   -2.17%  (p=0.007 n=10+5)
```

**Comment by erikgrinaker** [comment]
`IntentInterleavingSeekGEAndIter`

Same as above, this has mostly been resolved on `master`. There are a few significant exceptions that may be worth looking into, but I'm going to mark this as resolved overall.

```
name                                                                                                        old time/op  new time/op   delta
IntentInterleavingSeekGEAndIter/separated=false/version=1/intentStride=1/keyLen=10/seekStride=1-24           969ns ± 1%    865ns ± 1%  -10.73%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=1/intentStride=1/keyLen=10/seekStride=10-24         2.79µs ± 0%   2.68µs ± 1%   -4.06%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=1/intentStride=1/keyLen=100/seekStride=1-24         1.17µs ± 1%   1.04µs ± 1%  -11.56%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=1/intentStride=1/keyLen=100/seekStride=10-24        3.05µs ± 5%   2.97µs ± 1%   -2.41%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=1/intentStride=100/keyLen=10/seekStride=1-24         776ns ± 0%    695ns ± 7%  -10.38%  (p=0.016 n=4+5)
IntentInterleavingSeekGEAndIter/separated=false/version=1/intentStride=100/keyLen=10/seekStride=10-24       1.70µs ± 1%   1.58µs ± 2%   -6.90%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=1/intentStride=100/keyLen=100/seekStride=1-24        941ns ± 1%    876ns ± 0%   -6.86%  (p=0.016 n=5+4)
IntentInterleavingSeekGEAndIter/separated=false/version=1/intentStride=100/keyLen=100/seekStride=10-24      1.90µs ± 2%   1.84µs ± 2%   -3.57%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=1/intentStride=1000000/keyLen=10/seekStride=1-24     757ns ± 1%    788ns ± 2%   +4.12%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=1/intentStride=1000000/keyLen=10/seekStride=10-24   1.66µs ± 1%   1.66µs ± 1%     ~     (p=0.802 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=1/intentStride=1000000/keyLen=100/seekStride=1-24    950ns ± 1%    839ns ± 1%  -11.62%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=1/intentStride=1000000/keyLen=100/seekStride=10-24  1.90µs ± 2%   1.80µs ± 1%   -5.33%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=5/intentStride=1/keyLen=10/seekStride=1-24          1.44µs ± 1%   1.37µs ± 1%   -4.86%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=5/intentStride=1/keyLen=10/seekStride=10-24         6.54µs ± 1%   6.30µs ± 2%   -3.67%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=5/intentStride=1/keyLen=100/seekStride=1-24         1.79µs ± 1%   1.65µs ± 1%   -7.88%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=5/intentStride=1/keyLen=100/seekStride=10-24        7.36µs ± 1%   7.25µs ± 4%     ~     (p=0.151 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=5/intentStride=100/keyLen=10/seekStride=1-24        1.30µs ± 0%   1.22µs ± 0%   -5.85%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=5/intentStride=100/keyLen=10/seekStride=10-24       5.39µs ± 1%   5.30µs ± 1%   -1.73%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=5/intentStride=100/keyLen=100/seekStride=1-24       1.61µs ± 1%   1.51µs ± 1%   -6.05%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=5/intentStride=100/keyLen=100/seekStride=10-24      6.22µs ± 1%   6.10µs ± 3%     ~     (p=0.095 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=5/intentStride=1000000/keyLen=10/seekStride=1-24    1.32µs ± 1%   1.27µs ± 1%   -3.54%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=5/intentStride=1000000/keyLen=10/seekStride=10-24   5.54µs ± 5%   5.36µs ± 0%   -3.25%  (p=0.016 n=5+4)
IntentInterleavingSeekGEAndIter/separated=false/version=5/intentStride=1000000/keyLen=100/seekStride=1-24   1.62µs ± 4%   1.48µs ± 1%   -8.81%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=false/version=5/intentStride=1000000/keyLen=100/seekStride=10-24  6.25µs ± 2%   6.02µs ± 1%   -3.58%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=1/keyLen=10/seekStride=1-24           1.94µs ± 0%   1.81µs ± 1%   -6.72%  (p=0.016 n=4+5)
IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=1/keyLen=10/seekStride=10-24          5.21µs ± 6%   5.01µs ± 1%   -3.93%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=1/keyLen=100/seekStride=1-24          2.44µs ± 0%   2.17µs ± 0%  -11.28%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=1/keyLen=100/seekStride=10-24         6.08µs ± 1%   5.85µs ± 3%   -3.68%  (p=0.032 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=100/keyLen=10/seekStride=1-24         1.44µs ± 1%   1.31µs ± 1%   -9.16%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=100/keyLen=10/seekStride=10-24        2.57µs ± 1%   2.85µs ± 1%  +10.54%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=100/keyLen=100/seekStride=1-24        1.77µs ± 0%   1.65µs ± 0%   -6.67%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=100/keyLen=100/seekStride=10-24       2.97µs ± 1%   3.30µs ± 0%  +11.04%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=1000000/keyLen=10/seekStride=1-24     1.42µs ± 1%   0.90µs ± 2%  -36.38%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=1000000/keyLen=10/seekStride=10-24    2.53µs ± 1%   1.92µs ± 0%  -24.04%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=1000000/keyLen=100/seekStride=1-24    1.71µs ± 1%   1.02µs ± 1%  -40.65%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=1000000/keyLen=100/seekStride=10-24   2.88µs ± 1%   2.13µs ± 2%  -25.91%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=5/intentStride=1/keyLen=10/seekStride=1-24           2.66µs ± 1%   2.72µs ± 2%   +2.32%  (p=0.016 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=5/intentStride=1/keyLen=10/seekStride=10-24          12.1µs ± 1%   11.9µs ± 2%   -1.92%  (p=0.032 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=5/intentStride=1/keyLen=100/seekStride=1-24          3.35µs ± 0%   3.20µs ± 1%   -4.50%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=5/intentStride=1/keyLen=100/seekStride=10-24         14.3µs ± 1%   13.9µs ± 2%   -2.48%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=5/intentStride=100/keyLen=10/seekStride=1-24         2.21µs ± 1%   2.24µs ± 1%   +1.29%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=5/intentStride=100/keyLen=10/seekStride=10-24        7.43µs ± 1%   9.52µs ± 2%  +28.03%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=5/intentStride=100/keyLen=100/seekStride=1-24        2.74µs ± 1%   2.55µs ± 2%   -6.72%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=5/intentStride=100/keyLen=100/seekStride=10-24       8.43µs ± 1%  10.71µs ± 2%  +27.16%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=5/intentStride=1000000/keyLen=10/seekStride=1-24     2.17µs ± 1%   1.50µs ± 1%  -30.63%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=5/intentStride=1000000/keyLen=10/seekStride=10-24    7.37µs ± 1%   6.34µs ± 1%  -14.05%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=5/intentStride=1000000/keyLen=100/seekStride=1-24    2.57µs ± 0%   1.77µs ± 1%  -31.14%  (p=0.008 n=5+5)
IntentInterleavingSeekGEAndIter/separated=true/version=5/intentStride=1000000/keyLen=100/seekStride=10-24   8.23µs ± 1%   7.09µs ± 2%  -13.82%  (p=0.008 n=5+5)
```

**Comment by erikgrinaker** [comment]
@nicktrav Is storage looking into the remaining blind put regressions?

**Comment by nicktrav** [comment]
We aren't actively looking. It's on our list, but other stuff has come up. If you're able to take a peek that would be much appreciated.

**Comment by erikgrinaker** [comment]
Will do.

**Comment by nicktrav** [comment]
All tasks done. Closing.
