### ISSUE TITLE
sql: implement mechanisms to limit resource consumption

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#8879]
This is a meta-issue to track progress on the issue of resource usage.

Memory usage:
- [x] track dynamic memory usage (where the amount is dependent on user queries and/or current db state) #8691 
- [ ]  sql+kv: monitor memory usage by KV batches and write intents #10320 
- [x] bound memory usage to prevent large queries from crashing server #7657
  - e.g #7572 
- [x] stream results from executor through pgwire instead of collecting them first in RAM #7775
- [x] automatically drop idle client connections
- [x] whatever mechanism is introduced for throttling the start of new queries could also be a good place to prevent starting new queries in a server that is being drained
- [x] restrict REPEAT #10545

Time usage:
- [x] sql: actively cancel queries when client connection drops #16262
- [x] prevent queries from consuming 100% cpu time 
  - e.g. #8633 
- [x] prevent queries from running forever unless there are actually results communicated to the client cc #7657
- [x] allow clients to set a custom transaction timeout #5924

File descriptors:
- [ ] ensure the db doesn't run out of file descriptors #6210
  - [ ] limit the number of concurrent connections
- [ ] ensure that KV txns are cleaned up when clients go away without closing their SQL connection

**Comment by a6802739** [comment]
@knz, I wonder if I could offer some help here? :)

**Comment by jordanlewis** [comment]
@knz I feel that this issue has been sufficiently tackled and broken down into other issues, so I'll close it. Thanks for starting this initiative back in the day! :) If you feel like there are missing pieces still, let me know and we can create / link to new issues.

**Comment by knz** [comment]
All the check list at the top is crossed off so clearly the work is completed in my book
