### ISSUE TITLE
sql-queries: 23.1 release checklist

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#88869]
This issue captures a series of tests and steps that we need to run when 23.1 is getting close to being finalized.
 - [x] check bug fixes that may need backport
 - [x] check and update private opt tests repository
 - [x] check regressions in microbenchmarks
 - [x] run all tests with `fast_int_set_small` tag: `./dev test -- --define gotags=bazel,gss,fast_int_set_small`
 - [x] run all tests with `fast_int_set_large` tag: `./dev test -- --define gotags=bazel,gss,fast_int_set_large`
 - [x] consider adding session settings for all new features
 - [x] check TODOs in opt code (especially those added since the last release)
 - [x] clone an instance of this issue for the next release
 - [x] check the SQL Queries "Active" and "Release XX.X" buckets for issues that we'd really like to get into the release
 - [x] upgrade https://github.com/sqlancer/sqlancer to the latest version of CRDB

Jira issue: CRDB-20021

**Comment by rharding6373** [comment]
Opened https://github.com/sqlancer/sqlancer/pull/779 to upgrade the CRDB version in SQLancer.

**Comment by rharding6373** [comment]
The SQLancer change is merged.

**Comment by mgartner** [comment]
The TODOs have been double-checked.
