### ISSUE TITLE
storage: improve tooling for decrypting files in situ

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#89095]
**Is your feature request related to a problem? Please describe.**

We've had a few scenarios where files we've needed access to (namely Pebble manifest files) have been encrypted. This hampers our ability to debug. Decrypting the file is an involved process that relies on access to both the store key, but also the data keys and the file encryption registry - files that shouldn't leave a deployment environment.

**Describe the solution you'd like**

- [X] Improve tooling that would allow an operator to decrypt one or more files from a node using the store key. #89668
- [x] Tool for dumping out a registry. #89873
- [x] Remove the existing `pkg/ccl/cmdccl/enc_utils` - no longer works with new registry format. #89874

Jira issue: CRDB-20113

Epic CRDB-20293

**Comment by nicktrav** [comment]
While I was spelunking Cockroach code, I found [`enc_utils`](https://github.com/cockroachdb/cockroach/tree/master/pkg/ccl/cmdccl/enc_utils), which gives a good starting point for the tool outlined above. However, it no longer seems to work - issues unmarshalling the file registry back into its proto form. We've had that issue elsewhere, so I assume it should be a similar fix.

**Comment by nicktrav** [comment]
Going to close this out as we now have the decryption and listing sub-commands.
