### ISSUE TITLE
decommission: pre-flight checks

### ISSUE THREAD

**Issue by AlexTalks** [cockroachdb/cockroach#90752]
This is a tracking issue for decommission pre-flight checks, relating to #70486.

## Design
- [x] Create initial design doc
- [x] Create test plan
- [x] Create initial tests

## Implementation

- [x] Create & implement new request APIs: #91568
- [x] Implement replica / span config lookup & evaluation: #91571
- [x] Implement support for allocator dry run: #91570 
- [x] Collect and summarize errors/traces
- [x] Implement CLI flags: #91893

Jira issue: CRDB-20923

Epic: CRDB-20924

**Comment by data-matt** [comment]
Hi Alex, 

Will disk space be considered? thanks

Reference:
https://github.com/cockroachdb/cockroach/issues/70486

**Comment by AlexTalks** [comment]
@data-matt as an FYI, disk space is not considered in this initial version of Decommission Pre-Checks, though we do have #71757 open and there is infrastructure now to implement this in the future.
