### ISSUE TITLE
keyvisualizer: Tracking issue for various improvements

### ISSUE THREAD

**Issue by zachlite** [cockroachdb/cockroach#96737]
Tracking Issue for Key Visualizer Improvements, Post 23.1
In no particular order

- [x] https://github.com/cockroachdb/cockroach/issues/96740
- [ ] https://github.com/cockroachdb/cockroach/issues/96197
- [ ] https://github.com/cockroachdb/cockroach/issues/96742
- [ ] https://github.com/cockroachdb/cockroach/issues/96744
- [x] https://github.com/cockroachdb/cockroach/issues/97523
- [x] https://github.com/cockroachdb/cockroach/issues/97525

Jira issue: CRDB-24301
Epic: CRDB-30635

**Comment by maryliag** [comment]
No longer a priority
